/* ###################################################################
 *      This component module is generated by Processor Expert. Do not modify it.
 *      Filename    : KW40_UART.c
 *      Project     : HEXIWEAR_MK64
 *      Processor   : MK64FN1M0VDC12
 *      Component   : fsl_uart
 *      Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
 *      Repository  : KSDK 1.2.0
 *      Compiler    : GNU C Compiler
 *      Date/Time   : 2016-03-04, 12:30, # CodeGen: 0
 *      Abstract    :
 *
 *
 *      Copyright : 1997 - 2015 NXP Semiconductor, Inc.
 *      All Rights Reserved.
 *
 *      Redistribution and use in source and binary forms, with or without modification,
 *      are permitted provided that the following conditions are met:
 *
 *      o Redistributions of source code must retain the above copyright notice, this list
 *        of conditions and the following disclaimer.
 *
 *      o Redistributions in binary form must reproduce the above copyright notice, this
 *        list of conditions and the following disclaimer in the documentation and/or
 *        other materials provided with the distribution.
 *
 *      o Neither the name of NXP Semiconductor, Inc. nor the names of its
 *        contributors may be used to endorse or promote products derived from this
 *        software without specific prior written permission.
 *
 *      THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *      ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *      WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *      DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 *      ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *      (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *      LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 *      ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *      (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *      SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *      http: www.nxp.com
 *      mail: support@nxp.com
 *  ###################################################################*/
/*!
 *  @file KW40_UART.c
 *  @version 01.00
 *  @brief
 *
 */
/*!
 *   @addtogroup KW40_UART_module KW40_UART module documentation
 *   @{
 */

 /** MODULE KW40_UART. */

#include "KW40_UART.h"

#include "power_driver.h"

/*! KW40_UART configuration structure */
const uart_user_config_t KW40_UART_InitConfig0 = {
  .baudRate = 230400U,
  .parityMode = kUartParityDisabled,
  .stopBitCount = kUartTwoStopBit,
  .bitCountPerChar = kUart8BitsPerChar,
};


/*! Driver state structure without DMA */
uart_state_t KW40_UART_State;

 /** Implementation of UART4 handler named in startup code. */
extern void UART_DRV_IRQHandler(uint32_t instance);
void UART4_RX_TX_IRQHandler(void)
{
    if ( (UART_BRD_C2_RIE( UART4_BASE_PTR )) && (UART_BRD_S2_RXEDGIF( UART4_BASE_PTR )) )
    {
        // clear the active edge interrupt flag
        UART_BWR_S2_RXEDGIF( UART4_BASE_PTR , 1 );

		switch ( power_GetCurrentMode() )
		{
			case POWER_CURRENT_MODE_NORMAL:
			{
				// regular work mode, do nothing
				break;
			}

			// if we were in shallow sleep mode, just turn the OLED ON
			case POWER_CURRENT_MODE_SLEEP_SHALLOW:
			{
				HostInterface_SetWakingTouch();
				power_SetCurrentMode( POWER_CURRENT_MODE_NORMAL );
				break;
			}

			case POWER_CURRENT_MODE_SLEEP_TOTAL:
			{
				HostInterface_SetWakingTouch();
				power_SetCurrentMode( POWER_CURRENT_MODE_NORMAL );

				if ( POWER_STATUS_SUCCESS != power_SetWakeSource( POWER_WAKE_SRC_USER ) )
				{
					asm("nop");
				}
				break;
			}

			/**
			 * special consideration is also required for the sensor tag sleep mode,
			 * since we might not be actually sleeping when UART interrupt occurs
			 */

			case POWER_CURRENT_MODE_SLEEP_SENSOR_TAG:
			{
				HostInterface_SetWakingTouch();
				power_SetCurrentMode( POWER_CURRENT_MODE_NORMAL );

				if ( POWER_STATUS_SUCCESS == power_SetWakeSource( POWER_WAKE_SRC_USER ) )
				{
				}
				else
				{
					asm("nop");
				}
				break;
			}
		}
    }

    UART_DRV_IRQHandler(FSL_KW40_UART);
}

 /** END KW40_UART. */
/*!
 *  @}
 */
/*
 *  ###################################################################
 *
 *      This file was created by Processor Expert 10.5 [05.21]
 *      for the NXP Kinetis series of microcontrollers.
 *
 *  ###################################################################
 */
