/* ###################################################################
 *      This component module is generated by Processor Expert. Do not modify it.
 *      Filename    : PWR_Manager.c
 *      Project     : HEXIWEAR_MK64
 *      Processor   : MK64FN1M0VDC12
 *      Component   : fsl_power_manager
 *      Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
 *      Repository  : KSDK 1.2.0
 *      Compiler    : GNU C Compiler
 *      Date/Time   : 2016-03-04, 12:30, # CodeGen: 0
 *
 *      Copyright : 1997 - 2015 NXP Semiconductor, Inc.
 *      All Rights Reserved.
 *
 *      Redistribution and use in source and binary forms, with or without modification,
 *      are permitted provided that the following conditions are met:
 *
 *      o Redistributions of source code must retain the above copyright notice, this list
 *        of conditions and the following disclaimer.
 *
 *      o Redistributions in binary form must reproduce the above copyright notice, this
 *        list of conditions and the following disclaimer in the documentation and/or
 *        other materials provided with the distribution.
 *
 *      o Neither the name of NXP Semiconductor, Inc. nor the names of its
 *        contributors may be used to endorse or promote products derived from this
 *        software without specific prior written permission.
 *
 *      THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *      ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *      WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *      DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 *      ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *      (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *      LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 *      ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *      (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *      SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *      http: www.nxp.com
 *      mail: support@nxp.com
 *  ###################################################################*/
/*!
 *  @file PWR_Manager.c
 *  @version 01.00
 */
/*!
 *   @addtogroup PWR_Manager_module PWR_Manager module documentation
 *   @{
 */
 /** PWR_Manager. */
#include "Events.h"
#include "PWR_Manager.h"
const power_manager_user_config_t PWR_CFG_Run = {
  .mode = kPowerManagerRun,
  .sleepOnExitValue = false,
  .lowPowerWakeUpOnInterruptValue = kSmcLpwuiDisabled,
  .powerOnResetDetectionValue = kSmcPorEnabled,
};

const power_manager_user_config_t PWR_CFG_Sleep = {
  .mode = kPowerManagerVlps,
  .sleepOnExitValue = false,
  .lowPowerWakeUpOnInterruptValue = kSmcLpwuiEnabled,
  .powerOnResetDetectionValue = kSmcPorEnabled,
};

const power_manager_callback_user_config_t
    PWR_manager_CallbackBefore =
    {
            .callback     = power_CallBeforeSleep,        /*!< Entry of callback function.     */
            .callbackType = kPowerManagerCallbackBefore,  /*!< Callback type.                  */
            .callbackData = NULL                          /*!< Parameter of callback function. */
    },

	PWR_manager_CallbackAfter =
    {
            .callback     = power_CallAfterSleep,        /*!< Entry of callback function.     */
            .callbackType = kPowerManagerCallbackAfter,  /*!< Callback type.                  */
            .callbackData = NULL                         /*!< Parameter of callback function. */
    };

/*! @brief Array of pointers to User configuration structures */
power_manager_user_config_t const * powerConfigsArr[] =
{
    &PWR_CFG_Run,
    &PWR_CFG_Sleep
};

/*! @brief Array of pointers to User defined Callbacks configuration structures */
power_manager_callback_user_config_t * powerStaticCallbacksConfigsArr[] =
{
	&PWR_manager_CallbackBefore,
	&PWR_manager_CallbackAfter
};

 /** END PWR_Manager. */
/*!
 *  @}
 */
/*
 *  ###################################################################
 *
 *      This file was created by Processor Expert 10.5 [05.21]
 *      for the NXP Kinetis series of microcontrollers.
 *
 *  ###################################################################
 */
