HEXIWEAR MK64 Firmware Reference Manual: HEXIWEAR/src/HEXIWEAR_driver.c File Reference
HEXIWEAR_driver.c File Reference
this file contains global HEXIWEAR functionality
#include "HEXIWEAR_driver.h"
#include "HEXIWEAR_defs.h"
#include "HEXIWEAR_info.h"
#include "flash_boot_kinetis.h"
#include "sensor_driver.h"
#include "sensor_defs.h"
#include "timer_driver.h"
#include "power_driver.h"
#include "notifications.h"
#include "flashlight.h"
#include "host_mcu_interface.h"
#include "gui_driver.h"
#include "FLASH_driver.h"
#include "CLOCK.h"
#include "PWR_Manager.h"
#include "error.h"
#include "error_types.h"
#include "screens_common.h"
Functions
void HEXIWEAR_startup (task_param_t param)
hexiwear_status_t HEXIWEAR_Init ()
void HEXIWEAR_ResetMCU ()
void * HEXIWEAR_GetAppBackupList ()
packet_pushTarget_t HEXIWEAR_GetAppTarget ()
void HEXIWEAR_SetBackupList (packet_pushTarget_t *currentBackupList)
void HEXIWEAR_SetTargetApp (packet_pushTarget_t currentApp)
hexiwear_status_t HEXIWEAR_SetFlags (uint32_t flashAddress, void *flags, uint32_t flagSize)
void HEXIWEAR_CreateVersionEvent ()
void HEXIWEAR_SendVersionReq ()
osa_status_t HEXIWEAR_WaitForVersionUpdate (uint32_t timeout)
osa_status_t HEXIWEAR_UpdateVersion ()
Detailed Description
this file contains global HEXIWEAR functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.freescale.com
Project HEXIWEAR, 2015
Definition in file HEXIWEAR_driver.c.
Function Documentation
void HEXIWEAR_CreateVersionEvent ()
[HEXIWEAR_CreateVersionEvent description]
Definition at line 276 of file HEXIWEAR_driver.c.
References kEventAutoClear, and OSA_EventCreate().
Referenced by GuiDriver_Init().
void* HEXIWEAR_GetAppBackupList ()
[HEXIWEAR_GetBackupList description]
Definition at line 197 of file HEXIWEAR_driver.c.
packet_pushTarget_t HEXIWEAR_GetAppTarget ()
[HEXIWEAR_GetTargetApp description]
Definition at line 205 of file HEXIWEAR_driver.c.
hexiwear_status_t HEXIWEAR_Init ()
initialize the rest of the tasks
Returns
status flag
Definition at line 160 of file HEXIWEAR_driver.c.
References HEXIWEAR_startup(), HEXIWEAR_STARTUP_PRIO, kStatus_OSA_Success, and OSA_TaskCreate().
Referenced by main().
void HEXIWEAR_ResetMCU ()
reset the MCU
Definition at line 189 of file HEXIWEAR_driver.c.
References NVIC_SystemReset().
Referenced by bootloader_DestroyTasks(), catch(), and reset_DestroyTasks().
void HEXIWEAR_SendVersionReq ()
[HEXIWEAR_CreateVersionEvent description]
Definition at line 284 of file HEXIWEAR_driver.c.
References HEXIWEAR_VERSION_PATCH, HostInterface_TxQueueMsgPut(), kStatus_OSA_Success, and packetType_buildVersion.
Referenced by GuiDriver_Init().
void HEXIWEAR_SetBackupList (packet_pushTarget_t * currentBackupList)
[HEXIWEAR_SetBackupList description]
Definition at line 213 of file HEXIWEAR_driver.c.
Referenced by gui_motionControl_DestroyTasks(), gui_motionControl_Init(), gui_weatherStation_DestroyTasks(), and gui_weatherStation_Init().
hexiwear_status_t HEXIWEAR_SetFlags (uint32_t flashAddress, void * flags, uint32_t flagSize)
set application-specific flags
Parameters
flashAddress flash address for programming
flags data to be programmed into flash
flagSize data size, must be multiple of 8 bytes
Returns
status flag
erase the sector before programming
program flags
Definition at line 233 of file HEXIWEAR_driver.c.
References INTFLASH_EraseSector(), and INTFLASH_Program().
Referenced by gui_sensorTag_DestroyTasks(), and haptic_CheckAtStartup().
void HEXIWEAR_SetTargetApp (packet_pushTarget_t currentApp)
[HEXIWEAR_SetTargetApp description]
Definition at line 221 of file HEXIWEAR_driver.c.
Referenced by gui_motionControl_DestroyTasks(), gui_motionControl_Init(), gui_weatherStation_DestroyTasks(), and gui_weatherStation_Init().
void HEXIWEAR_startup (task_param_t param)
output GPIO configuration
input GPIO configuration
create basic tasks
set GPIO interrupt for the tap function
set charging battery interrupt
check for settings in flash at startup
Definition at line 80 of file HEXIWEAR_driver.c.
References BAT_CHG_cfg, CLOCK_SYS_Init(), DEBUG_cfg, FLASH_cfg, FLASH_Init(), FSL_CLOCK_MANAGER_CALLBACK_CNT, FSL_CLOCK_MANAGER_CONFIG_CNT, g_clockManCallbacksArr, g_clockManConfigsArr, GPIO_DRV_Init(), gui_sensorTag_CheckAtStartup(), GuiDriver_Init(), haptic_CheckAtStartup(), haptic_MutexCreate(), HEXIWEAR_CHG_IRQ_PRIO, HostInterface_Init(), INTFLASH_Init(), kPortIntEitherEdge, kPortIntFallingEdge, KW40_GPIO_cfg, Notification_Init(), NVIC_SetPriority(), OLED_cfg, OSA_TaskDestroy(), PORTC, PORTC_IRQn, power_Init(), power_ResetKW40(), POWER_SYS_Init(), powerConfigsArr, powerStaticCallbacksConfigsArr, PWR_cfg, RGB_cfg, RTC_Init(), sensor_GetPacketTargets(), sensor_Init(), sensor_InitAcc(), sensor_SetPacketTargets(), TAP_cfg, timer_Init(), and VIBRO_cfg.
Referenced by HEXIWEAR_Init().
osa_status_t HEXIWEAR_UpdateVersion ()
update KW40 version
Returns
status flag
Definition at line 327 of file HEXIWEAR_driver.c.
References kStatus_OSA_Success, and OSA_EventSet().
osa_status_t HEXIWEAR_WaitForVersionUpdate (uint32_t timeout)
[HEXIWEAR_WaitForVersionUpdate description]
Parameters
timeout [description]
Returns
[description]
Definition at line 306 of file HEXIWEAR_driver.c.
References kStatus_OSA_Error, kStatus_OSA_Success, and OSA_EventWait().
Referenced by GuiDriver_Init().