HEXIWEAR MK64 Firmware Reference Manual: sensors/HTU/src/HTU_driver.c File Reference
HTU_driver.c File Reference
this file contains sensor HTU21D implemented functionality
#include "HTU_driver.h"
#include "HTU_info.h"
#include "FS_I2C.h"
#include "generic_i2c_driver.h"
#include "HEXIWEAR_types.h"
#include "HEXIWEAR_info.h"
#include <string.h>
#include "error.h"
Functions
htu_status_t HTU_Init (handleHTU_t *htuHandle, settingsHTU_t *htuSettings)
htu_status_t HTU_Deinit ()
htu_status_t HTU_SoftReset ()
htu_status_t HTU_SetUserRegister ()
htu_status_t HTU_GetTemp (int16_t *tempData)
htu_status_t HTU_GetHum (int16_t *humData)
htu_status_t HTU_ReadRawData (int16_t *temperature, int16_t *humidity)
htu_status_t HTU_RecoverI2C ()
void hum_fmtDef2Float (const void *src, void *dst, uint32_t idx)
void hum_fmtDef2Me (const void *src, void *dst, uint32_t idx)
void hum_fmtDef2Byte (const void *src, void *dst, uint32_t idx)
void temp_fmtDef2Float (const void *src, void *dst, uint32_t idx)
void temp_fmtDef2Me (const void *src, void *dst, uint32_t idx)
void temp_fmtDef2Byte (const void *src, void *dst, uint32_t idx)
Detailed Description
this file contains sensor HTU21D implemented functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file HTU_driver.c.
Function Documentation
htu_status_t HTU_Deinit ()
initialize i2c interface to HTU21D sensor and reset the module
Returns
status flag
Definition at line 118 of file HTU_driver.c.
References I2C_Deinit(), and STATUS_I2C_SUCCESS.
htu_status_t HTU_GetHum (int16_t * humData)
retrieve humidity data
Parameters
humData data to be filled
Returns
status flag
convert to final value discard the third received byte (checksum)
Definition at line 325 of file HTU_driver.c.
References I2C_DRV_MasterReceiveDataBlocking(), I2C_DRV_MasterSendDataBlocking(), and kStatus_I2C_Success.
Referenced by HTU_ReadRawData(), and sensor_Init().
htu_status_t HTU_GetTemp (int16_t * tempData)
retrieve temperature data
Parameters
tempData data to be filled
Returns
status flag
convert to final value discard the third received byte (checksum)
Definition at line 250 of file HTU_driver.c.
References I2C_DRV_MasterReceiveDataBlocking(), I2C_DRV_MasterSendDataBlocking(), and kStatus_I2C_Success.
Referenced by HTU_ReadRawData(), and sensor_Init().
htu_status_t HTU_Init (handleHTU_t * htuHandle, settingsHTU_t * htuSettings)
intern functions visible functions initialize i2c interface to HTU21D sensor and reset the module
Returns
status flag
initialize the intern structures, which will be used from now on
Definition at line 71 of file HTU_driver.c.
References HTU_SetUserRegister(), HTU_SoftReset(), I2C_Init(), and STATUS_I2C_SUCCESS.
Referenced by sensor_InitAcc().
htu_status_t HTU_ReadRawData (int16_t * temperature, int16_t * humidity)
retrieve temperature and humidity data
Parameters
temperature address to place the temperature data to
humidity address to place the humidity data to
Returns
status flag
Definition at line 398 of file HTU_driver.c.
References HTU_GetHum(), and HTU_GetTemp().
htu_status_t HTU_RecoverI2C ()
check if I2C bus needs to be recovered
Returns
status flag
Definition at line 416 of file HTU_driver.c.
References I2C_Recover(), and STATUS_I2C_SUCCESS.
Referenced by sensor_Init().
htu_status_t HTU_SetUserRegister ()
configure the measurement resolution
Returns
status flag
set a byte to be written to user register and also set the corresponding measurement time
Definition at line 176 of file HTU_driver.c.
References I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by HTU_Init().
htu_status_t HTU_SoftReset ()
reset the sensor
Returns
status flag
Definition at line 139 of file HTU_driver.c.
References I2C_DRV_MasterSendDataBlocking(), and kStatus_I2C_Success.
Referenced by HTU_Init(), and sensor_Init().
void hum_fmtDef2Byte (const void * src, void * dst, uint32_t idx)
format raw to byte - currently unimplemented
Definition at line 502 of file HTU_driver.c.
void hum_fmtDef2Float (const void * src, void * dst, uint32_t idx)
format raw to float
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
convert data
Definition at line 438 of file HTU_driver.c.
void hum_fmtDef2Me (const void * src, void * dst, uint32_t idx)
format raw to mE format
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
convert data
Definition at line 470 of file HTU_driver.c.
References foo.
void temp_fmtDef2Byte (const void * src, void * dst, uint32_t idx)
format raw to byte - currently unimplemented
Definition at line 577 of file HTU_driver.c.
void temp_fmtDef2Float (const void * src, void * dst, uint32_t idx)
format raw to float
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
convert data
Definition at line 515 of file HTU_driver.c.
void temp_fmtDef2Me (const void * src, void * dst, uint32_t idx)
format raw to mE format
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
convert data
Definition at line 538 of file HTU_driver.c.
References foo.