HEXIWEAR MK64 Firmware Reference Manual: OLED/src/OLED_driver.c File Reference
OLED_driver.c File Reference
this file contains OLED driver functionality for drawing images and text
#include "HEXIWEAR_info.h"
#include "OLED_Driver.h"
#include "string.h"
#include <stdlib.h>
#include "error.h"
#include "generic_spi_driver.h"
#include "generic_spi_info.h"
#include "fsl_dspi_edma_master_driver.h"
#include "fsl_gpio_driver.h"
#include "OLED_Defs.h"
#include "OLED_Info.h"
#include "gui_resources.h"
#include "gui_driver.h"
#include "gui_defs.h"
#include "power_driver.h"
#include "GPIO.h"
Macros
#define OLED_REMAP_SETTINGS (REMAP_ORDER_ABC | REMAP_COM_SPLIT_ODD_EVEN_EN | REMAP_COLOR_RGB565 | REMAP_COLUMNS_LEFT_TO_RIGHT | REMAP_SCAN_UP_TO_DOWN | REMAP_HORIZONTAL_INCREMENT)
Functions
oled_status_t OLED_Init (handleOLED_t *oledHandle, settingsOLED_t *oledSettings)
oled_status_t OLED_Deinit ()
oled_status_t OLED_SendCmd (uint32_t cmd, uint8_t isFirst)
oled_status_t OLED_SendData (const uint8_t *dataToSend, uint32_t dataSize)
oled_status_t OLED_DrawBox (uint16_t xCrd, uint16_t yCrd, uint16_t width, uint16_t height, uint16_t color)
oled_status_t OLED_FillScreen (uint16_t color)
oled_status_t OLED_DrawPixel (int16_t xCrd, int16_t yCrd, uint16_t color)
oled_status_t OLED_DrawScreen (const uint8_t *image, uint8_t xCrd, uint8_t yCrd, uint8_t width, uint8_t height, oled_transition_t transition)
oled_status_t OLED_SetFont (const uint8_t *newFont, uint16_t newColor)
void OLED_SetDynamicArea (oled_dynamic_area_t *dynamic_area)
void OLED_DestroyDynamicArea ()
void OLED_SetTextProperties (oled_text_properties_t *textProperties)
uint8_t OLED_GetTextWidth (const uint8_t *text)
uint8_t OLED_CharCount (uint8_t width, const uint8_t *font, const uint8_t *text, uint8_t length)
oled_status_t OLED_AddText (const uint8_t *text)
oled_status_t OLED_DrawText (const uint8_t *text)
void OLED_GetImageDimensions (uint8_t *width, uint8_t *height, const uint8_t *image)
oled_status_t OLED_AddImage (const uint8_t *image)
oled_status_t OLED_DrawImage (const uint8_t *image)
void OLED_DimScreenON ()
void OLED_DimScreenOFF ()
void OLED_Swap (oled_pixel_t imgDst, const uint8_t *imgSrc, uint16_t imgSize)
Detailed Description
this file contains OLED driver functionality for drawing images and text
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file OLED_driver.c.
Macro Definition Documentation
#define OLED_REMAP_SETTINGS (REMAP_ORDER_ABC | REMAP_COM_SPLIT_ODD_EVEN_EN | REMAP_COLOR_RGB565 | REMAP_COLUMNS_LEFT_TO_RIGHT | REMAP_SCAN_UP_TO_DOWN | REMAP_HORIZONTAL_INCREMENT)
macros and consts
Definition at line 103 of file OLED_driver.c.
Referenced by OLED_DimScreenOFF(), and OLED_Init().
Function Documentation
oled_status_t OLED_AddImage (const uint8_t * image)
add image to the main screen buffer
Parameters
image desired image
Returns
status flag
Definition at line 1063 of file OLED_driver.c.
References oled_dynamic_area_t::areaBuffer, GuiDriver_UpdateScreen(), oled_dynamic_area_t::height, OLED_STATUS_INIT_ERROR, OLED_STATUS_SUCCESS, OLED_Swap(), oled_dynamic_area_t::width, oled_dynamic_area_t::xCrd, and oled_dynamic_area_t::yCrd.
Referenced by GuiDriver_ImageAddToScr(), and OLED_DrawImage().
oled_status_t OLED_AddText (const uint8_t * text)
add text to the main screen buffer
Parameters
text text to add
Returns
status flag
set default values, if necessary
write the characters into designated space, one by one
Definition at line 885 of file OLED_driver.c.
References oled_text_properties_t::alignParam, oled_dynamic_area_t::areaBuffer, GuiDriver_UpdateScreen(), oled_dynamic_area_t::height, OLED_GetTextWidth(), OLED_SetDynamicArea(), OLED_STATUS_ERROR, OLED_STATUS_INIT_ERROR, OLED_STATUS_SUCCESS, oled_dynamic_area_t::width, oled_dynamic_area_t::xCrd, and oled_dynamic_area_t::yCrd.
Referenced by GuiDriver_LabelAddToScr(), and OLED_DrawText().
uint8_t OLED_CharCount (uint8_t width, const uint8_t * font, const uint8_t * text, uint8_t length)
count the characters
Parameters
width text width
font text font
text given text string
length text length
Returns
character count
Definition at line 857 of file OLED_driver.c.
Referenced by GuiDriver_LabelFormatCaption().
oled_status_t OLED_Deinit ()
deinitialize OLED (not used)
Parameters
self OLED handle
Returns
status flag
Definition at line 374 of file OLED_driver.c.
References SPI_Deinit().
void OLED_DestroyDynamicArea (void)
destroy current OLED dynamic area
Definition at line 804 of file OLED_driver.c.
References oled_dynamic_area_t::areaBuffer.
Referenced by bluetooth_DestroyTasks(), bond_DestroyTasks(), bootloader_DestroyTasks(), buttonsGroup_DestroyTasks(), flashlight_DestroyTasks(), gui_heartRate_DestroyTasks(), gui_motionControl_DestroyTasks(), gui_notifications_DestroyTasks(), gui_pedometer_DestroyTasks(), gui_sensorTag_DestroyTasks(), gui_weatherStation_DestroyTasks(), haptic_DestroyTasks(), heartRate_Deinit(), info_DestroyTasks(), OLED_DimScreenOFF(), OLED_DrawBox(), OLED_SetDynamicArea(), pedometer_Deinit(), reset_DestroyTasks(), and watch_DestroyTasks().
void OLED_DimScreenOFF ()
return OLED back to full contrast
Definition at line 1162 of file OLED_driver.c.
References oled_dynamic_area_t::areaBuffer, foo, OLED_CMD_SET_REMAP, OLED_DestroyDynamicArea(), OLED_REMAP_SETTINGS, OLED_SendCmd(), OLED_SendData(), OLED_SetDynamicArea(), OLED_SetFont(), OLED_STATUS_INIT_ERROR, OLED_STATUS_PROTOCOL_ERROR, OLED_STATUS_SUCCESS, and oled_dynamic_area_t::xCrd.
void OLED_DimScreenON ()
dim OLED screen on
Definition at line 1149 of file OLED_driver.c.
References OLED_SendCmd(), and OSA_TimeDelay().
oled_status_t OLED_DrawBox (uint16_t xCrd, uint16_t yCrd, uint16_t width, uint16_t height, uint16_t color)
draw box on OLED
Parameters
xCrd x-coordinate for box's uper left corner
yCrd y-coordinate for box's uper left corner
width box's width
height box's height
color color of the box
Returns
status flag
fill the buffer with color
set the locations
Definition at line 522 of file OLED_driver.c.
References oled_dynamic_area_t::areaBuffer, oled_dynamic_area_t::height, OLED_CMD_SET_COLUMN, OLED_DestroyDynamicArea(), OLED_SendCmd(), OLED_SendData(), OLED_SetDynamicArea(), OLED_STATUS_ERROR, OLED_STATUS_INIT_ERROR, OLED_STATUS_PROTOCOL_ERROR, OLED_STATUS_SUCCESS, oled_dynamic_area_t::width, oled_dynamic_area_t::xCrd, and oled_dynamic_area_t::yCrd.
Referenced by bootloader_DestroyTasks(), buttonsGroup_ActiveUpdate(), GuiDriver_CleanAbout(), and GuiDriver_CleanMainArea().
oled_status_t OLED_DrawImage (const uint8_t * image)
draw image, i.e. send image to OLED GRAM
Parameters
image desired image
transition desired transition style for the new image
Returns
status flag
Definition at line 1091 of file OLED_driver.c.
References oled_dynamic_area_t::areaBuffer, oled_dynamic_area_t::height, OLED_AddImage(), OLED_CMD_SET_COLUMN, OLED_SendCmd(), OLED_SendData(), OLED_STATUS_PROTOCOL_ERROR, OLED_STATUS_SUCCESS, oled_dynamic_area_t::width, oled_dynamic_area_t::xCrd, and oled_dynamic_area_t::yCrd.
Referenced by GuiDriver_ImageDraw().
oled_status_t OLED_DrawPixel (int16_t xCrd, int16_t yCrd, uint16_t color)
draw a single pixel
Parameters
xCrd pixel's x coordinate
yCrd pixel's y coordinate
color pixel's color
Returns
status flag
Definition at line 649 of file OLED_driver.c.
References OLED_SendData(), OLED_STATUS_INIT_ERROR, OLED_STATUS_PROTOCOL_ERROR, OLED_STATUS_SUCCESS, and OLED_SwapMe.
oled_status_t OLED_DrawScreen (const uint8_t * image, uint8_t xCrd, uint8_t yCrd, uint8_t width, uint8_t height, oled_transition_t transition)
draw the whole screen
Parameters
image image to draw
xCrd image x-coordinate
yCrd image y-coordinate
width image width
height image height
transition transition style for the new image arrival
Returns
status flag
set the locations
Definition at line 691 of file OLED_driver.c.
References OLED_SendData(), OLED_STATUS_INIT_ERROR, OLED_STATUS_PROTOCOL_ERROR, OLED_STATUS_SUCCESS, OLED_TRANSITION_DOWN_TOP, OLED_TRANSITION_LEFT_RIGHT, OLED_TRANSITION_NONE, OLED_TRANSITION_RIGHT_LEFT, and OLED_TRANSITION_TOP_DOWN.
Referenced by GuiDriver_Navigation().
oled_status_t OLED_DrawText (const uint8_t * text)
write text on OLED to given position
Parameters
text desired text
x x-coordinate for the given text
y y-coordinate for the given text
Definition at line 1023 of file OLED_driver.c.
References oled_dynamic_area_t::areaBuffer, oled_dynamic_area_t::height, OLED_AddText(), OLED_SendData(), OLED_STATUS_ERROR, OLED_STATUS_PROTOCOL_ERROR, OLED_STATUS_SUCCESS, oled_dynamic_area_t::width, oled_dynamic_area_t::xCrd, and oled_dynamic_area_t::yCrd.
Referenced by GuiDriver_LabelDraw().
oled_status_t OLED_FillScreen (uint16_t color)
fill the entire screen
Parameters
color color to fill with
Returns
status flag
fill the screen buffer with color
set the locations
fill GRAM
Definition at line 622 of file OLED_driver.c.
References OLED_SendData(), OLED_STATUS_PROTOCOL_ERROR, and OLED_STATUS_SUCCESS.
Referenced by GuiDriver_ClearScr().
void OLED_GetImageDimensions (uint8_t * width, uint8_t * height, const uint8_t * image)
return given image dimensions
Parameters
width given image's width
height given image's height
image desired image
Definition at line 1052 of file OLED_driver.c.
Referenced by GuiDriver_ImageAddToScr(), GuiDriver_ImageDraw(), and GuiDriver_Navigation().
uint8_t OLED_GetTextWidth (const uint8_t * text)
return the width in [px] required for the given string to be displayed
Parameters
text desired string
Returns
required text width in [px]
Definition at line 832 of file OLED_driver.c.
Referenced by OLED_AddText().
oled_status_t OLED_Init (handleOLED_t * oledHandle, settingsOLED_t * oledSettings)
Public API initialize OLED screen
Parameters
self OLED handle
settings specific OLED settings
Returns
status flag
initialize intern OLED structures, which will be used from now on
set IRQ priority
power sequence
Definition at line 145 of file OLED_driver.c.
References GPIO_DRV_ClearPinOutput(), GPIO_DRV_SetPinOutput(), HEXIWEAR_OLED_SPI_IRQ_PRIO, NVIC_SetPriority(), OLED_CMD_SET_CMD_LOCK, OLED_CMD_SET_COLUMN, OLED_CMD_SET_MUX_RATIO, OLED_CMD_SET_OSC_FREQ_AND_CLOCKDIV, OLED_CMD_SET_REMAP, OLED_REMAP_SETTINGS, OLED_SendCmd(), OLED_STATUS_PROTOCOL_ERROR, OLED_STATUS_SUCCESS, OSA_MutexCreate(), OSA_TimeDelay(), power_TurnOFF(), power_TurnON(), handleOLED_t::protocol, SPI_Init(), and STATUS_SPI_SUCCESS.
Referenced by GuiDriver_Init().
oled_status_t OLED_SendCmd (uint32_t cmd, uint8_t isFirst)
send the command to OLED
Parameters
self OLED handle
cmd OLED command from the datasheet
isFirst designate if this is the first byte in the command
Returns
status flag
Definition at line 386 of file OLED_driver.c.
References GPIO_DRV_ClearPinOutput(), GPIO_DRV_SetPinOutput(), OLED_STATUS_PROTOCOL_ERROR, and OLED_STATUS_SUCCESS.
Referenced by OLED_DimScreenOFF(), OLED_DimScreenON(), OLED_DrawBox(), OLED_DrawImage(), OLED_Init(), OLED_SendData(), power_TurnScreenOFF(), and power_TurnScreenON().
oled_status_t OLED_SendData (const uint8_t * dataToSend, uint32_t dataSize)
send data to OLED
Parameters
dataToSend data to send to OLED
dataSize data-size
Returns
status flag
Definition at line 436 of file OLED_driver.c.
References GPIO_DRV_ClearPinOutput(), GPIO_DRV_SetPinOutput(), OLED_SendCmd(), OLED_SPI_CHUNK, OLED_STATUS_PROTOCOL_ERROR, and OLED_STATUS_SUCCESS.
Referenced by OLED_DimScreenOFF(), OLED_DrawBox(), OLED_DrawImage(), OLED_DrawPixel(), OLED_DrawScreen(), OLED_DrawText(), and OLED_FillScreen().
void OLED_SetDynamicArea (oled_dynamic_area_t * dynamic_area)
set OLED dynamic area
Parameters
dynamic_area data-structure with desired values
Definition at line 779 of file OLED_driver.c.
References oled_dynamic_area_t::areaBuffer, oled_dynamic_area_t::height, OLED_DestroyDynamicArea(), oled_dynamic_area_t::width, oled_dynamic_area_t::xCrd, and oled_dynamic_area_t::yCrd.
Referenced by GuiDriver_ImageAddToScr(), GuiDriver_ImageDraw(), GuiDriver_LabelAddToScr(), GuiDriver_LabelDraw(), OLED_AddText(), OLED_DimScreenOFF(), and OLED_DrawBox().
oled_status_t OLED_SetFont (const uint8_t * newFont, uint16_t newColor)
set the font to use
Parameters
newFont desired font
newColor desired color
Returns
status flag
save the new values in intern variables
Definition at line 754 of file OLED_driver.c.
References OLED_STATUS_SUCCESS, and OLED_SwapMe.
Referenced by OLED_DimScreenOFF(), and OLED_SetTextProperties().
void OLED_SetTextProperties (oled_text_properties_t * textProperties)
set OLED text properties
Parameters
textProperties data-structure with desired properties
Definition at line 817 of file OLED_driver.c.
References oled_text_properties_t::alignParam, oled_text_properties_t::background, oled_text_properties_t::font, oled_text_properties_t::fontColor, and OLED_SetFont().
Referenced by GuiDriver_LabelAddToScr(), and GuiDriver_LabelDraw().
void OLED_Swap (oled_pixel_t imgDst, const uint8_t * imgSrc, uint16_t imgSize)
spap image's bytes per pixel to obtain the correct color format
Parameters
imgDst desired image
imgSrc original image
imgSize image's size
Definition at line 1632 of file OLED_driver.c.
References oled_dynamic_area_t::areaBuffer, oled_text_properties_t::background, oled_dynamic_area_t::height, kStatus_OSA_Success, OLED_STATUS_ERROR, OLED_STATUS_INIT_ERROR, OLED_STATUS_PROTOCOL_ERROR, OLED_STATUS_SUCCESS, OSA_MemAlloc(), OSA_MemFree(), OSA_MutexLock(), OSA_MutexUnlock(), OSA_WAIT_FOREVER, oled_dynamic_area_t::width, oled_dynamic_area_t::xCrd, and oled_dynamic_area_t::yCrd.
Referenced by GuiDriver_Navigation(), and OLED_AddImage().