HEXIWEAR MK64 Firmware Reference Manual: gui/screens/4. settings/4.1 bluetooth/inc/bluetooth.h File Reference
bluetooth.h File Reference
this file contains bluetooth GUI related resources
#include "gui_driver.h"
Functions
void bluetooth_CreateAdvModeUpdateEvent (void)
void bluetooth_SendGetAdvModeReq (void)
void bluetooth_SendToggleAdvModeReq (void)
osa_status_t bluetooth_WaitForAdvModeUpdate (uint32_t timeout)
osa_status_t bluetooth_AdvModeUpdate (bluetooth_advMode_t bluetooth_advMode)
bluetooth_advMode_t bluetooth_CurrentAdvModeGet (void)
Variables
guiScreen_t bluetoothScreen
Detailed Description
this file contains bluetooth GUI related resources
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file bluetooth.h.
Function Documentation
osa_status_t bluetooth_AdvModeUpdate (bluetooth_advMode_t bluetooth_advMode)
update the advertisement mode
Parameters
bluetooth_advMode new mode
Returns
status flag
Definition at line 251 of file bluetooth_driver.c.
References bluetooth_SendGetAdvModeReq(), bluetooth_SendToggleAdvModeReq(), bluetooth_WaitForAdvModeUpdate(), GUI_CURRENT_APP_SENSOR_TAG, gui_sensorTag_IsActive(), GuiDriver_ImageDraw(), GuiDriver_NotifyKW40(), GuiDriver_QueueMsgGet(), kStatus_OSA_Success, OSA_EventSet(), OSA_TimeDelay(), OSA_WAIT_FOREVER, packetType_pressRight, and watch_LinkStateUpdate().
void bluetooth_CreateAdvModeUpdateEvent (void)
create the event for bluetooth update
Definition at line 85 of file bluetooth_driver.c.
References kEventAutoClear, and OSA_EventCreate().
Referenced by GuiDriver_Init().
bluetooth_advMode_t bluetooth_CurrentAdvModeGet (void)
get current advertisement mode
Returns
current mode
Definition at line 185 of file bluetooth_driver.c.
Referenced by bootloader_Init().
void bluetooth_SendGetAdvModeReq (void)
send request to get advertisement mode
Definition at line 193 of file bluetooth_driver.c.
References HostInterface_TxQueueMsgPut(), and kStatus_OSA_Success.
Referenced by bluetooth_AdvModeUpdate(), and GuiDriver_Init().
void bluetooth_SendToggleAdvModeReq (void)
send request to toggle advertisement mode
Definition at line 211 of file bluetooth_driver.c.
References HostInterface_TxQueueMsgPut(), and kStatus_OSA_Success.
Referenced by bluetooth_AdvModeUpdate().
osa_status_t bluetooth_WaitForAdvModeUpdate (uint32_t timeout)
wait for the mode update
Parameters
timeout time to wait in [ms]
Returns
status flag
Definition at line 231 of file bluetooth_driver.c.
References kStatus_OSA_Error, kStatus_OSA_Success, and OSA_EventWait().
Referenced by bluetooth_AdvModeUpdate(), and GuiDriver_Init().
Variable Documentation
guiScreen_t bluetoothScreen
definition of watch screen
Definition at line 44 of file bluetooth_objects.c.