HEXIWEAR MK64 Firmware Reference Manual: gui/screens/4. settings/4.3 buttons group/inc/buttons_group.h File Reference
buttons_group.h File Reference
this file contains button group objects' declarations
#include "gui_driver.h"
Functions
void buttonsGroup_CreateActiveUpdateEvent (void)
void buttonsGroup_SendGetActiveReq (void)
void buttonsGroup_SendToggleActiveReq (void)
osa_status_t buttonsGroup_WaitForActiveUpdate (uint32_t timeout)
osa_status_t buttonsGroup_ActiveUpdate (buttonsGroup_t buttonsGroupActive)
buttonsGroup_t buttonsGroup_CurrnetActiveGet (void)
Detailed Description
this file contains button group objects' declarations
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file buttons_group.h.
Function Documentation
osa_status_t buttonsGroup_ActiveUpdate (buttonsGroup_t buttonsGroupActive)
destroy the button group GUI update task
Parameters
param optional parameter
Definition at line 255 of file buttons_group_driver.c.
References buttonsGroup_SendToggleActiveReq(), buttonsGroup_WaitForActiveUpdate(), GuiDriver_DrawButtonPointers(), GuiDriver_ImageDraw(), GuiDriver_QueueMsgGet(), kStatus_OSA_Success, OLED_DrawBox(), OSA_EventSet(), OSA_WAIT_FOREVER, and packetType_pressRight.
void buttonsGroup_CreateActiveUpdateEvent (void)
create the event for updating the active button group
Definition at line 88 of file buttons_group_driver.c.
References kEventAutoClear, and OSA_EventCreate().
Referenced by GuiDriver_Init().
buttonsGroup_t buttonsGroup_CurrnetActiveGet (void)
get active button group
Returns
active button group
Definition at line 192 of file buttons_group_driver.c.
Referenced by GuiDriver_DrawButtonPointers().
void buttonsGroup_SendGetActiveReq (void)
send the request to KW40
Definition at line 200 of file buttons_group_driver.c.
References HostInterface_TxQueueMsgPut(), and kStatus_OSA_Success.
Referenced by GuiDriver_Init().
void buttonsGroup_SendToggleActiveReq (void)
send the request for toggling the active group
Definition at line 217 of file buttons_group_driver.c.
References HostInterface_TxQueueMsgPut(), and kStatus_OSA_Success.
Referenced by buttonsGroup_ActiveUpdate().
osa_status_t buttonsGroup_WaitForActiveUpdate (uint32_t timeout)
wait for the update
Parameters
timeout time to wait in [ms]
Returns
status flag
Definition at line 236 of file buttons_group_driver.c.
References kStatus_OSA_Error, kStatus_OSA_Success, and OSA_EventWait().
Referenced by buttonsGroup_ActiveUpdate(), and GuiDriver_Init().