HEXIWEAR MK64 Firmware Reference Manual: gui/screens/4. settings/4.3 buttons group/src/buttons_group_driver.c File Reference
buttons_group_driver.c File Reference
this file contains button group private objects' declarations
#include "gui_driver.h"
#include "screens_common.h"
#include "buttons_group_private.h"
#include "host_mcu_interface.h"
#include "fsl_os_abstraction.h"
Macros
#define MSEC_TO_TICK(msec)
Converts milliseconds to ticks.
Functions
void buttonsGroup_CreateActiveUpdateEvent ()
void buttonsGroup_Init (void *param)
void buttonsGroup_CreateTasks (void *param)
void buttonsGroup_DestroyTasks (void *param)
buttonsGroup_t buttonsGroup_CurrnetActiveGet ()
void buttonsGroup_SendGetActiveReq ()
void buttonsGroup_SendToggleActiveReq ()
osa_status_t buttonsGroup_WaitForActiveUpdate (uint32_t timeout)
osa_status_t buttonsGroup_ActiveUpdate (buttonsGroup_t buttonsGroupActive)
Variables
task_handler_t buttonsGroup_handler
Detailed Description
this file contains button group private objects' declarations
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file buttons_group_driver.c.
Macro Definition Documentation
#define MSEC_TO_TICK (msec)
Value:
(((uint32_t)(msec)+500uL/(uint32_t)configTICK_RATE_HZ) \
                             *(uint32_t)configTICK_RATE_HZ/1000uL)
Converts milliseconds to ticks.
include private type definitions private macros
Definition at line 52 of file buttons_group_driver.c.
Function Documentation
osa_status_t buttonsGroup_ActiveUpdate (buttonsGroup_t buttonsGroupActive)
destroy the button group GUI update task
Parameters
param optional parameter
Definition at line 255 of file buttons_group_driver.c.
References buttonsGroup_SendToggleActiveReq(), buttonsGroup_WaitForActiveUpdate(), GuiDriver_DrawButtonPointers(), GuiDriver_ImageDraw(), GuiDriver_QueueMsgGet(), kStatus_OSA_Success, OLED_DrawBox(), OSA_EventSet(), OSA_WAIT_FOREVER, and packetType_pressRight.
void buttonsGroup_CreateActiveUpdateEvent (void)
create the event for updating the active button group
Definition at line 88 of file buttons_group_driver.c.
References kEventAutoClear, and OSA_EventCreate().
Referenced by GuiDriver_Init().
void buttonsGroup_CreateTasks (void * param)
create the button group GUI task
Parameters
param optional parameter
Definition at line 121 of file buttons_group_driver.c.
References buttonsGroup_handler, kStatus_OSA_Success, and OSA_TaskCreate().
buttonsGroup_t buttonsGroup_CurrnetActiveGet (void)
get active button group
Returns
active button group
Definition at line 192 of file buttons_group_driver.c.
Referenced by GuiDriver_DrawButtonPointers().
void buttonsGroup_DestroyTasks (void * param)
destroy the button group GUI task
Parameters
param optional parameter
Definition at line 163 of file buttons_group_driver.c.
References buttonsGroup_handler, GuiDriver_UnregisterFromNavigation(), kStatus_OSA_Success, OLED_DestroyDynamicArea(), OSA_MsgQDestroy(), and OSA_TaskDestroy().
void buttonsGroup_Init (void * param)
initialize the button group screen
Parameters
param optional parameter
Definition at line 97 of file buttons_group_driver.c.
References GuiDriver_ImageAddToScr(), GuiDriver_RegisterForNavigation(), and OSA_MsgQCreate().
void buttonsGroup_SendGetActiveReq (void)
send the request to KW40
Definition at line 200 of file buttons_group_driver.c.
References HostInterface_TxQueueMsgPut(), and kStatus_OSA_Success.
Referenced by GuiDriver_Init().
void buttonsGroup_SendToggleActiveReq (void)
send the request for toggling the active group
Definition at line 217 of file buttons_group_driver.c.
References HostInterface_TxQueueMsgPut(), and kStatus_OSA_Success.
Referenced by buttonsGroup_ActiveUpdate().
osa_status_t buttonsGroup_WaitForActiveUpdate (uint32_t timeout)
wait for the update
Parameters
timeout time to wait in [ms]
Returns
status flag
Definition at line 236 of file buttons_group_driver.c.
References kStatus_OSA_Error, kStatus_OSA_Success, and OSA_EventWait().
Referenced by buttonsGroup_ActiveUpdate(), and GuiDriver_Init().
Variable Documentation
task_handler_t buttonsGroup_handler
public memory declarations
Definition at line 70 of file buttons_group_driver.c.
Referenced by buttonsGroup_CreateTasks(), and buttonsGroup_DestroyTasks().