Events module documentation
Events module documentation
Functions
void I2C0_IRQHandler (void)
void I2C1_IRQHandler (void)
void SPI1_IRQHandler (void)
void SPI2_IRQHandler (void)
void ADC0_IRQHandler (void)
void PORTC_IRQHandler (void)
Detailed Description
Function Documentation
void ADC0_IRQHandler (void)
BATTERY_ADC IRQ handler
Definition at line 80 of file Events.c.
References FSL_SENSOR_TIMER.
void I2C0_IRQHandler (void)
NFS_I2C IRQ handler
Definition at line 36 of file Events.c.
References FSL_NFS_I2C.
void I2C1_IRQHandler (void)
FS_I2C IRQ handler
Definition at line 42 of file Events.c.
References FSL_FS_I2C.
void PORTC_IRQHandler (void)
special consideration is also required for the sensor tag sleep mode, since we might not be actually sleeping when UART interrupt occurs
Definition at line 90 of file Events.c.
References GPIO_DRV_ClearPinOutput(), GPIO_DRV_SetPinOutput(), kStatus_OSA_Success, and OSA_TimeDelay().
void SPI1_IRQHandler (void)
FLASH_SPI IRQ handler
Definition at line 48 of file Events.c.
References FSL_FLASH_SPI.
void SPI2_IRQHandler (void)
OLED_SPI IRQ handler
Definition at line 59 of file Events.c.
References FSL_OLED_SPI.