HEXIWEAR MK64 Firmware Reference Manual: CMSIS Core Register Access Functions
CMSIS Core Register Access Functions
Functions and Instructions Reference
Functions
__STATIC_INLINE uint32_t __get_CONTROL (void)
Get Control Register.
__STATIC_INLINE void __set_CONTROL (uint32_t control)
Set Control Register.
__STATIC_INLINE uint32_t __get_IPSR (void)
Get IPSR Register.
__STATIC_INLINE uint32_t __get_APSR (void)
Get APSR Register.
__STATIC_INLINE uint32_t __get_xPSR (void)
Get xPSR Register.
__STATIC_INLINE uint32_t __get_PSP (void)
Get Process Stack Pointer.
__STATIC_INLINE void __set_PSP (uint32_t topOfProcStack)
Set Process Stack Pointer.
__STATIC_INLINE uint32_t __get_MSP (void)
Get Main Stack Pointer.
__STATIC_INLINE void __set_MSP (uint32_t topOfMainStack)
Set Main Stack Pointer.
__STATIC_INLINE uint32_t __get_PRIMASK (void)
Get Priority Mask.
__STATIC_INLINE void __set_PRIMASK (uint32_t priMask)
Set Priority Mask.
__attribute__ ((always_inline)) __STATIC_INLINE void __enable_irq(void)
Enable IRQ Interrupts.
Detailed Description
Copyright (c) 2009 - 2015 ARM LIMITED
All rights reserved. Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of ARM nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
Copyright (c) 2009 - 2015 ARM LIMITED
All rights reserved. Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of ARM nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDERS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
ignore some GCC warnings
Function Documentation
__attribute__ ((always_inline))
Enable IRQ Interrupts.
Set Priority Mask.
Get Priority Mask.
Set Main Stack Pointer.
Get Main Stack Pointer.
Set Process Stack Pointer.
Get Process Stack Pointer.
Get xPSR Register.
Get APSR Register.
Get IPSR Register.
Set Control Register.
Get Control Register.
Disable IRQ Interrupts.
Enables IRQ interrupts by clearing the I-bit in the CPSR. Can only be executed in Privileged modes.
Disables IRQ interrupts by setting the I-bit in the CPSR. Can only be executed in Privileged modes.
Returns the content of the Control Register.
Returns
Control Register value
Writes the given value to the Control Register.
Parameters
[in] control Control Register value to set
Returns the content of the IPSR Register.
Returns
IPSR Register value
Returns the content of the APSR Register.
Returns
APSR Register value
Returns the content of the xPSR Register.
Returns
xPSR Register value
Returns the current value of the Process Stack Pointer (PSP).
Returns
PSP Register value
Assigns the given value to the Process Stack Pointer (PSP).
Parameters
[in] topOfProcStack Process Stack Pointer value to set
Returns the current value of the Main Stack Pointer (MSP).
Returns
MSP Register value
Assigns the given value to the Main Stack Pointer (MSP).
Parameters
[in] topOfMainStack Main Stack Pointer value to set
Returns the current state of the priority mask bit from the Priority Mask Register.
Returns
Priority Mask value
Assigns the given value to the Priority Mask Register.
Parameters
[in] priMask Priority Mask
Definition at line 50 of file cmsis_armcc_V6.h.
References __get_APSR(), __get_CONTROL(), __get_IPSR(), __get_MSP(), __get_PRIMASK(), __get_PSP(), __get_xPSR(), __set_CONTROL(), __set_MSP(), __set_PRIMASK(), and __set_PSP().
__STATIC_INLINE uint32_t __get_APSR (void)
Get APSR Register.
Returns the content of the APSR Register.
Returns
APSR Register value
Definition at line 93 of file cmsis_armcc.h.
Referenced by __attribute__().
__STATIC_INLINE uint32_t __get_CONTROL (void)
Get Control Register.
intrinsic void __enable_irq(); intrinsic void __disable_irq();
Returns the content of the Control Register.
Returns
Control Register value
Definition at line 57 of file cmsis_armcc.h.
Referenced by __attribute__().
__STATIC_INLINE uint32_t __get_IPSR (void)
Get IPSR Register.
Returns the content of the IPSR Register.
Returns
IPSR Register value
Definition at line 81 of file cmsis_armcc.h.
Referenced by __attribute__().
__STATIC_INLINE uint32_t __get_MSP (void)
Get Main Stack Pointer.
Returns the current value of the Main Stack Pointer (MSP).
Returns
MSP Register value
Definition at line 141 of file cmsis_armcc.h.
Referenced by __attribute__().
__STATIC_INLINE uint32_t __get_PRIMASK (void)
Get Priority Mask.
Returns the current state of the priority mask bit from the Priority Mask Register.
Returns
Priority Mask value
Definition at line 165 of file cmsis_armcc.h.
Referenced by __attribute__().
__STATIC_INLINE uint32_t __get_PSP (void)
Get Process Stack Pointer.
Returns the current value of the Process Stack Pointer (PSP).
Returns
PSP Register value
Definition at line 117 of file cmsis_armcc.h.
Referenced by __attribute__().
__STATIC_INLINE uint32_t __get_xPSR (void)
Get xPSR Register.
Returns the content of the xPSR Register.
Returns
xPSR Register value
Definition at line 105 of file cmsis_armcc.h.
Referenced by __attribute__().
__STATIC_INLINE void __set_CONTROL (uint32_t control)
Set Control Register.
Writes the given value to the Control Register.
Parameters
[in] control Control Register value to set
Definition at line 69 of file cmsis_armcc.h.
Referenced by __attribute__().
__STATIC_INLINE void __set_MSP (uint32_t topOfMainStack)
Set Main Stack Pointer.
Assigns the given value to the Main Stack Pointer (MSP).
Parameters
[in] topOfMainStack Main Stack Pointer value to set
Definition at line 153 of file cmsis_armcc.h.
Referenced by __attribute__().
__STATIC_INLINE void __set_PRIMASK (uint32_t priMask)
Set Priority Mask.
Assigns the given value to the Priority Mask Register.
Parameters
[in] priMask Priority Mask
Definition at line 177 of file cmsis_armcc.h.
Referenced by __attribute__().
__STATIC_INLINE void __set_PSP (uint32_t topOfProcStack)
Set Process Stack Pointer.
Assigns the given value to the Process Stack Pointer (PSP).
Parameters
[in] topOfProcStack Process Stack Pointer value to set
Definition at line 129 of file cmsis_armcc.h.
Referenced by __attribute__().