HEXIWEAR MK64 Firmware Reference Manual: DCT Type IV Functions
DCT Type IV Functions
Transform Functions
Functions
void arm_dct4_f32 (const arm_dct4_instance_f32 *S, float32_t *pState, float32_t *pInlineBuffer)
Processing function for the floating-point DCT4/IDCT4.
arm_status arm_dct4_init_f32 (arm_dct4_instance_f32 *S, arm_rfft_instance_f32 *S_RFFT, arm_cfft_radix4_instance_f32 *S_CFFT, uint16_t N, uint16_t Nby2, float32_t normalize)
Initialization function for the floating-point DCT4/IDCT4.
arm_status arm_dct4_init_q15 (arm_dct4_instance_q15 *S, arm_rfft_instance_q15 *S_RFFT, arm_cfft_radix4_instance_q15 *S_CFFT, uint16_t N, uint16_t Nby2, q15_t normalize)
Initialization function for the Q15 DCT4/IDCT4.
arm_status arm_dct4_init_q31 (arm_dct4_instance_q31 *S, arm_rfft_instance_q31 *S_RFFT, arm_cfft_radix4_instance_q31 *S_CFFT, uint16_t N, uint16_t Nby2, q31_t normalize)
Initialization function for the Q31 DCT4/IDCT4.
void arm_dct4_q15 (const arm_dct4_instance_q15 *S, q15_t *pState, q15_t *pInlineBuffer)
Processing function for the Q15 DCT4/IDCT4.
void arm_dct4_q31 (const arm_dct4_instance_q31 *S, q31_t *pState, q31_t *pInlineBuffer)
Processing function for the Q31 DCT4/IDCT4.
Detailed Description
Representation of signals by minimum number of values is important for storage and transmission. The possibility of large discontinuity between the beginning and end of a period of a signal in DFT can be avoided by extending the signal so that it is even-symmetric. Discrete Cosine Transform (DCT) is constructed such that its energy is heavily concentrated in the lower part of the spectrum and is very widely used in signal and image coding applications. The family of DCTs (DCT type- 1,2,3,4) is the outcome of different combinations of homogeneous boundary conditions. DCT has an excellent energy-packing capability, hence has many applications and in data compression in particular.
DCT is essentially the Discrete Fourier Transform(DFT) of an even-extended real signal. Reordering of the input data makes the computation of DCT just a problem of computing the DFT of a real signal with a few additional operations. This approach provides regular, simple, and very efficient DCT algorithms for practical hardware and software implementations.
DCT type-II can be implemented using Fast fourier transform (FFT) internally, as the transform is applied on real values, Real FFT can be used. DCT4 is implemented using DCT2 as their implementations are similar except with some added pre-processing and post-processing. DCT2 implementation can be described in the following steps:
Re-ordering input
Calculating Real FFT
Multiplication of weights and Real FFT output and getting real part from the product.
This process is explained by the block diagram below:
Discrete Cosine Transform - type-IV
Algorithm:
The N-point type-IV DCT is defined as a real, linear transformation by the formula:
where k = 0,1,2,.....N-1
Its inverse is defined as follows:
where n = 0,1,2,.....N-1
The DCT4 matrices become involutory (i.e. they are self-inverse) by multiplying with an overall scale factor of sqrt(2/N). The symmetry of the transform matrix indicates that the fast algorithms for the forward and inverse transform computation are identical. Note that the implementation of Inverse DCT4 and DCT4 is same, hence same process function can be used for both.
Lengths supported by the transform:
As DCT4 internally uses Real FFT, it supports all the lengths supported by arm_rfft_f32(). The library provides separate functions for Q15, Q31, and floating-point data types.
Instance Structure
The instances for Real FFT and FFT, cosine values table and twiddle factor table are stored in an instance data structure. A separate instance structure must be defined for each transform. There are separate instance structure declarations for each of the 3 supported data types.
Initialization Functions
There is also an associated initialization function for each data type. The initialization function performs the following operations:
Sets the values of the internal structure fields.
Initializes Real FFT as its process function is used internally in DCT4, by calling arm_rfft_init_f32().
Use of the initialization function is optional. However, if the initialization function is used, then the instance structure cannot be placed into a const data section. To place an instance structure into a const data section, the instance structure must be manually initialized. Manually initialize the instance structure as follows:
*arm_dct4_instance_f32 S = {N, Nby2, normalize, pTwiddle, pCosFactor, pRfft, pCfft};
*arm_dct4_instance_q31 S = {N, Nby2, normalize, pTwiddle, pCosFactor, pRfft, pCfft};
*arm_dct4_instance_q15 S = {N, Nby2, normalize, pTwiddle, pCosFactor, pRfft, pCfft};
where N is the length of the DCT4; Nby2 is half of the length of the DCT4; normalize is normalizing factor used and is equal to sqrt(2/N); pTwiddle points to the twiddle factor table; pCosFactor points to the cosFactor table; pRfft points to the real FFT instance; pCfft points to the complex FFT instance; The CFFT and RFFT structures also needs to be initialized, refer to arm_cfft_radix4_f32() and arm_rfft_f32() respectively for details regarding static initialization.
Fixed-Point Behavior
Care must be taken when using the fixed-point versions of the DCT4 transform functions. In particular, the overflow and saturation behavior of the accumulator used in each function must be considered. Refer to the function specific documentation below for usage guidelines.
Function Documentation
void arm_dct4_f32 (const arm_dct4_instance_f32 * S, float32_t * pState, float32_t * pInlineBuffer)
Processing function for the floating-point DCT4/IDCT4.
Parameters
[in] *S points to an instance of the floating-point DCT4/IDCT4 structure.
[in] *pState points to state buffer.
[in,out] *pInlineBuffer points to the in-place input and output buffer.
Returns
none.
Loop counter
Pointer to the Weights table
Pointer to the cos factors table
Temporary pointers for input buffer and pState buffer
Temporary variable
DCT4 computation involves DCT2 (which is calculated using RFFT) along with some pre-processing and post-processing. Computational procedure is explained as follows: (a) Pre-processing involves multiplying input with cos factor, r(n) = 2 * u(n) * cos(pi*(2*n+1)/(4*n)) where, r(n) – output of preprocessing u(n) – input to preprocessing(actual Source buffer) (b) Calculation of DCT2 using FFT is divided into three steps: Step1: Re-ordering of even and odd elements of input. Step2: Calculating FFT of the re-ordered input. Step3: Taking the real part of the product of FFT output and weights. (c) Post-processing - DCT4 can be obtained from DCT2 output using the following equation: Y4(k) = Y2(k) - Y4(k-1) and Y4(-1) = Y4(0) where, Y4 – DCT4 output, Y2 – DCT2 output (d) Multiplying the output with the normalizing factor sqrt(2/N).
Multiplying input with cos factor i.e. r(n) = 2 * x(n) * cos(pi*(2*n+1)/(4*n))
pS1 initialized to pState
pS2 initialized to pState+N-1, so that it points to the end of the state buffer
pbuff initialized to input buffer
Run the below code for Cortex-M4 and Cortex-M3
Initializing the loop counter to N/2 >> 2 for loop unrolling by 4
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
Re-ordering of even and odd elements
pState[i] = pInlineBuffer[2*i]
pState[N-i-1] = pInlineBuffer[2*i+1]
Decrement the loop counter
pbuff initialized to input buffer
pS1 initialized to pState
Initializing the loop counter to N/4 instead of N for loop unrolling
Processing with loop unrolling 4 times as N is always multiple of 4. Compute 4 outputs at a time
Writing the re-ordered output back to inplace input buffer
Decrement the loop counter
pInlineBuffer is real input of length N , pState is the complex output of length 2N
DCT-IV can be obtained from DCT-II by the equation, Y4(k) = Y2(k) - Y4(k-1) and Y4(-1) = Y4(0) Hence, Y4(0) = Y2(0)/2
Getting only real part from the output and Converting to DCT-IV
Initializing the loop counter to N >> 2 for loop unrolling by 4
pbuff initialized to input buffer.
pS1 initialized to pState
Calculating Y4(0) from Y2(0) using Y4(0) = Y2(0)/2
input buffer acts as inplace, so output values are stored in the input itself.
pState pointer is incremented twice as the real values are located alternatively in the array
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
Calculating Y4(1) to Y4(N-1) from Y2 using equation Y4(k) = Y2(k) - Y4(k-1)
pState pointer (pS1) is incremented twice as the real values are located alternatively in the array
points to the next real value
Decrement the loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
Calculating Y4(1) to Y4(N-1) from Y2 using equation Y4(k) = Y2(k) - Y4(k-1)
pState pointer (pS1) is incremented twice as the real values are located alternatively in the array
points to the next real value
Decrement the loop counter
Initializing the loop counter to N/4 instead of N for loop unrolling
pbuff initialized to the pInlineBuffer(now contains the output values)
Processing with loop unrolling 4 times as N is always multiple of 4. Compute 4 outputs at a time
Multiplying pInlineBuffer with the normalizing factor sqrt(2/N)
Decrement the loop counter
Definition at line 137 of file arm_dct4_f32.c.
References arm_mult_f32(), arm_scale_f32(), arm_dct4_instance_f32::N, arm_dct4_instance_f32::Nby2, arm_dct4_instance_f32::pCosFactor, and arm_dct4_instance_f32::pTwiddle.
arm_status arm_dct4_init_f32 (arm_dct4_instance_f32 * S, arm_rfft_instance_f32 * S_RFFT, arm_cfft_radix4_instance_f32 * S_CFFT, uint16_t N, uint16_t Nby2, float32_t normalize)
Initialization function for the floating-point DCT4/IDCT4.
Parameters
[in,out] *S points to an instance of floating-point DCT4/IDCT4 structure.
[in] *S_RFFT points to an instance of floating-point RFFT/RIFFT structure.
[in] *S_CFFT points to an instance of floating-point CFFT/CIFFT structure.
[in] N length of the DCT4.
[in] Nby2 half of the length of the DCT4.
[in] normalize normalizing factor.
Returns
arm_status function returns ARM_MATH_SUCCESS if initialization is successful or ARM_MATH_ARGUMENT_ERROR if fftLenReal is not a supported transform length.
Normalizing factor:
The normalizing factor is sqrt(2/N), which depends on the size of transform N. Floating-point normalizing factors are mentioned in the table below for different DCT sizes:
Initializing the pointer array with the weight table base addresses of different lengths
Initializing the pointer array with the cos factor table base addresses of different lengths
Initialize the DCT4 length
Initialize the half of DCT4 length
Initialize the DCT4 Normalizing factor
Initialize Real FFT Instance
Initialize Complex FFT Instance
Initialize the table modifier values
Initialize the RFFT/RIFFT
return the status of DCT4 Init function
Definition at line 16449 of file arm_dct4_init_f32.c.
References arm_rfft_init_f32(), arm_dct4_instance_f32::N, arm_dct4_instance_f32::Nby2, arm_dct4_instance_f32::normalize, arm_dct4_instance_f32::pCfft, arm_dct4_instance_f32::pCosFactor, arm_dct4_instance_f32::pRfft, and arm_dct4_instance_f32::pTwiddle.
arm_status arm_dct4_init_q15 (arm_dct4_instance_q15 * S, arm_rfft_instance_q15 * S_RFFT, arm_cfft_radix4_instance_q15 * S_CFFT, uint16_t N, uint16_t Nby2, q15_t normalize)
Initialization function for the Q15 DCT4/IDCT4.
Parameters
[in,out] *S points to an instance of Q15 DCT4/IDCT4 structure.
[in] *S_RFFT points to an instance of Q15 RFFT/RIFFT structure.
[in] *S_CFFT points to an instance of Q15 CFFT/CIFFT structure.
[in] N length of the DCT4.
[in] Nby2 half of the length of the DCT4.
[in] normalize normalizing factor.
Returns
arm_status function returns ARM_MATH_SUCCESS if initialization is successful or ARM_MATH_ARGUMENT_ERROR if N is not a supported transform length.
Normalizing factor:
The normalizing factor is sqrt(2/N), which depends on the size of transform N. Normalizing factors in 1.15 format are mentioned in the table below for different DCT sizes:
Initializing the pointer array with the weight table base addresses of different lengths
Initializing the pointer array with the cos factor table base addresses of different lengths
Initialize the DCT4 length
Initialize the half of DCT4 length
Initialize the DCT4 Normalizing factor
Initialize Real FFT Instance
Initialize Complex FFT Instance
Initialize the table modifier values
Initialize the RFFT/RIFFT
return the status of DCT4 Init function
Definition at line 4215 of file arm_dct4_init_q15.c.
References arm_rfft_init_q15(), arm_dct4_instance_q15::N, arm_dct4_instance_q15::Nby2, arm_dct4_instance_q15::normalize, arm_dct4_instance_q15::pCfft, arm_dct4_instance_q15::pCosFactor, arm_dct4_instance_q15::pRfft, and arm_dct4_instance_q15::pTwiddle.
arm_status arm_dct4_init_q31 (arm_dct4_instance_q31 * S, arm_rfft_instance_q31 * S_RFFT, arm_cfft_radix4_instance_q31 * S_CFFT, uint16_t N, uint16_t Nby2, q31_t normalize)
Initialization function for the Q31 DCT4/IDCT4.
Parameters
[in,out] *S points to an instance of Q31 DCT4/IDCT4 structure.
[in] *S_RFFT points to an instance of Q31 RFFT/RIFFT structure
[in] *S_CFFT points to an instance of Q31 CFFT/CIFFT structure
[in] N length of the DCT4.
[in] Nby2 half of the length of the DCT4.
[in] normalize normalizing factor.
Returns
arm_status function returns ARM_MATH_SUCCESS if initialization is successful or ARM_MATH_ARGUMENT_ERROR if N is not a supported transform length.
Normalizing factor:
The normalizing factor is sqrt(2/N), which depends on the size of transform N. Normalizing factors in 1.31 format are mentioned in the table below for different DCT sizes:
Initializing the pointer array with the weight table base addresses of different lengths
Initializing the pointer array with the cos factor table base addresses of different lengths
Initialize the DCT4 length
Initialize the half of DCT4 length
Initialize the DCT4 Normalizing factor
Initialize Real FFT Instance
Initialize Complex FFT Instance
Initialize the table modifier values
Initialize the RFFT/RIFFT Function
return the status of DCT4 Init function
Definition at line 8295 of file arm_dct4_init_q31.c.
References arm_rfft_init_q31(), arm_dct4_instance_q31::N, arm_dct4_instance_q31::Nby2, arm_dct4_instance_q31::normalize, arm_dct4_instance_q31::pCfft, arm_dct4_instance_q31::pCosFactor, arm_dct4_instance_q31::pRfft, and arm_dct4_instance_q31::pTwiddle.
void arm_dct4_q15 (const arm_dct4_instance_q15 * S, q15_t * pState, q15_t * pInlineBuffer)
Processing function for the Q15 DCT4/IDCT4.
Parameters
[in] *S points to an instance of the Q15 DCT4 structure.
[in] *pState points to state buffer.
[in,out] *pInlineBuffer points to the in-place input and output buffer.
Returns
none.
Input an output formats:
Internally inputs are downscaled in the RFFT process function to avoid overflows. Number of bits downscaled, depends on the size of the transform. The input and output formats for different DCT sizes and number of bits to upscale are mentioned in the table below:
Loop counter
Pointer to the Weights table
Pointer to the cos factors table
Temporary pointers for input buffer and pState buffer
Temporary variable
DCT4 computation involves DCT2 (which is calculated using RFFT) along with some pre-processing and post-processing. Computational procedure is explained as follows: (a) Pre-processing involves multiplying input with cos factor, r(n) = 2 * u(n) * cos(pi*(2*n+1)/(4*n)) where, r(n) – output of preprocessing u(n) – input to preprocessing(actual Source buffer) (b) Calculation of DCT2 using FFT is divided into three steps: Step1: Re-ordering of even and odd elements of input. Step2: Calculating FFT of the re-ordered input. Step3: Taking the real part of the product of FFT output and weights. (c) Post-processing - DCT4 can be obtained from DCT2 output using the following equation: Y4(k) = Y2(k) - Y4(k-1) and Y4(-1) = Y4(0) where, Y4 – DCT4 output, Y2 – DCT2 output (d) Multiplying the output with the normalizing factor sqrt(2/N).
Multiplying input with cos factor i.e. r(n) = 2 * x(n) * cos(pi*(2*n+1)/(4*n))
pS1 initialized to pState
pS2 initialized to pState+N-1, so that it points to the end of the state buffer
pbuff initialized to input buffer
Run the below code for Cortex-M4 and Cortex-M3
Initializing the loop counter to N/2 >> 2 for loop unrolling by 4
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
Re-ordering of even and odd elements
pState[i] = pInlineBuffer[2*i]
pState[N-i-1] = pInlineBuffer[2*i+1]
Decrement the loop counter
pbuff initialized to input buffer
pS1 initialized to pState
Initializing the loop counter to N/4 instead of N for loop unrolling
Processing with loop unrolling 4 times as N is always multiple of 4. Compute 4 outputs at a time
Writing the re-ordered output back to inplace input buffer
Decrement the loop counter
pInlineBuffer is real input of length N , pState is the complex output of length 2N
The output of complex multiplication is in 3.13 format. Hence changing the format of N (i.e. 2*N elements) complex numbers to 1.15 format by shifting left by 2 bits.
DCT-IV can be obtained from DCT-II by the equation, Y4(k) = Y2(k) - Y4(k-1) and Y4(-1) = Y4(0) Hence, Y4(0) = Y2(0)/2
Getting only real part from the output and Converting to DCT-IV
Initializing the loop counter to N >> 2 for loop unrolling by 4
pbuff initialized to input buffer.
pS1 initialized to pState
Calculating Y4(0) from Y2(0) using Y4(0) = Y2(0)/2
input buffer acts as inplace, so output values are stored in the input itself.
pState pointer is incremented twice as the real values are located alternatively in the array
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
Calculating Y4(1) to Y4(N-1) from Y2 using equation Y4(k) = Y2(k) - Y4(k-1)
pState pointer (pS1) is incremented twice as the real values are located alternatively in the array
points to the next real value
Decrement the loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
Calculating Y4(1) to Y4(N-1) from Y2 using equation Y4(k) = Y2(k) - Y4(k-1)
pState pointer (pS1) is incremented twice as the real values are located alternatively in the array
points to the next real value
Decrement the loop counter
Initializing the loop counter to N/4 instead of N for loop unrolling
pbuff initialized to the pInlineBuffer(now contains the output values)
Processing with loop unrolling 4 times as N is always multiple of 4. Compute 4 outputs at a time
Multiplying pInlineBuffer with the normalizing factor sqrt(2/N)
Decrement the loop counter
Definition at line 63 of file arm_dct4_q15.c.
References arm_mult_q15(), arm_shift_q15(), arm_dct4_instance_q15::N, arm_dct4_instance_q15::Nby2, arm_dct4_instance_q15::pCosFactor, and arm_dct4_instance_q15::pTwiddle.
void arm_dct4_q31 (const arm_dct4_instance_q31 * S, q31_t * pState, q31_t * pInlineBuffer)
Processing function for the Q31 DCT4/IDCT4.
Parameters
[in] *S points to an instance of the Q31 DCT4 structure.
[in] *pState points to state buffer.
[in,out] *pInlineBuffer points to the in-place input and output buffer.
Returns
none.
Input an output formats:
Input samples need to be downscaled by 1 bit to avoid saturations in the Q31 DCT process, as the conversion from DCT2 to DCT4 involves one subtraction. Internally inputs are downscaled in the RFFT process function to avoid overflows. Number of bits downscaled, depends on the size of the transform. The input and output formats for different DCT sizes and number of bits to upscale are mentioned in the table below:
Loop counter
Pointer to the Weights table
Pointer to the cos factors table
Temporary pointers for input buffer and pState buffer
Temporary variable
DCT4 computation involves DCT2 (which is calculated using RFFT) along with some pre-processing and post-processing. Computational procedure is explained as follows: (a) Pre-processing involves multiplying input with cos factor, r(n) = 2 * u(n) * cos(pi*(2*n+1)/(4*n)) where, r(n) – output of preprocessing u(n) – input to preprocessing(actual Source buffer) (b) Calculation of DCT2 using FFT is divided into three steps: Step1: Re-ordering of even and odd elements of input. Step2: Calculating FFT of the re-ordered input. Step3: Taking the real part of the product of FFT output and weights. (c) Post-processing - DCT4 can be obtained from DCT2 output using the following equation: Y4(k) = Y2(k) - Y4(k-1) and Y4(-1) = Y4(0) where, Y4 – DCT4 output, Y2 – DCT2 output (d) Multiplying the output with the normalizing factor sqrt(2/N).
Multiplying input with cos factor i.e. r(n) = 2 * x(n) * cos(pi*(2*n+1)/(4*n))
pS1 initialized to pState
pS2 initialized to pState+N-1, so that it points to the end of the state buffer
pbuff initialized to input buffer
Run the below code for Cortex-M4 and Cortex-M3
Initializing the loop counter to N/2 >> 2 for loop unrolling by 4
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
Re-ordering of even and odd elements
pState[i] = pInlineBuffer[2*i]
pState[N-i-1] = pInlineBuffer[2*i+1]
Decrement the loop counter
pbuff initialized to input buffer
pS1 initialized to pState
Initializing the loop counter to N/4 instead of N for loop unrolling
Processing with loop unrolling 4 times as N is always multiple of 4. Compute 4 outputs at a time
Writing the re-ordered output back to inplace input buffer
Decrement the loop counter
pInlineBuffer is real input of length N , pState is the complex output of length 2N
The output of complex multiplication is in 3.29 format. Hence changing the format of N (i.e. 2*N elements) complex numbers to 1.31 format by shifting left by 2 bits.
DCT-IV can be obtained from DCT-II by the equation, Y4(k) = Y2(k) - Y4(k-1) and Y4(-1) = Y4(0) Hence, Y4(0) = Y2(0)/2
Getting only real part from the output and Converting to DCT-IV
Initializing the loop counter to N >> 2 for loop unrolling by 4
pbuff initialized to input buffer.
pS1 initialized to pState
Calculating Y4(0) from Y2(0) using Y4(0) = Y2(0)/2
input buffer acts as inplace, so output values are stored in the input itself.
pState pointer is incremented twice as the real values are located alternatively in the array
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
Calculating Y4(1) to Y4(N-1) from Y2 using equation Y4(k) = Y2(k) - Y4(k-1)
pState pointer (pS1) is incremented twice as the real values are located alternatively in the array
points to the next real value
Decrement the loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
Calculating Y4(1) to Y4(N-1) from Y2 using equation Y4(k) = Y2(k) - Y4(k-1)
pState pointer (pS1) is incremented twice as the real values are located alternatively in the array
points to the next real value
Decrement the loop counter
Initializing the loop counter to N/4 instead of N for loop unrolling
pbuff initialized to the pInlineBuffer(now contains the output values)
Processing with loop unrolling 4 times as N is always multiple of 4. Compute 4 outputs at a time
Multiplying pInlineBuffer with the normalizing factor sqrt(2/N)
Decrement the loop counter
Definition at line 64 of file arm_dct4_q31.c.
References arm_cmplx_mult_cmplx_q31(), arm_mult_q31(), arm_rfft_q31(), arm_shift_q31(), arm_dct4_instance_q31::N, arm_dct4_instance_q31::Nby2, arm_dct4_instance_q31::normalize, arm_dct4_instance_q31::pCosFactor, arm_dct4_instance_q31::pRfft, and arm_dct4_instance_q31::pTwiddle.