HEXIWEAR MK64 Firmware Reference Manual: Cpu module documentation
Cpu module documentation
Macros
#define CPU_PERIPHERALS_INIT 0x00U /** Peripherals_Init() method is not called in PE_low_level_init() */
Functions
void Components_Init (void)
void PE_low_level_init (void)
Detailed Description
Macro Definition Documentation
#define CPU_PERIPHERALS_INIT 0x00U /** Peripherals_Init() method is not called in PE_low_level_init() */
MODULE Cpu.
Definition at line 112 of file Cpu.h.
Function Documentation
void Components_Init (void)
CPU_COMMON_INIT
Referenced by PEX_components_init().
void PE_low_level_init (void)
CPU_COMPONENTS_INIT
set clocks, configure pins and initialize RTOS and hardware components
Global routing function and crystal values initialization
CPU_HARDWARE_INIT
RTOS initialization
Components initialization, when RTOS is active this method is called in rtos_main_task() (from MainTask component)
Definition at line 75 of file PE_low_level_init.c.
References hardware_init(), PEX_components_init(), and PEX_RTOS_INIT.
Referenced by main().