HEXIWEAR MK64 Firmware Reference Manual: Clock_manager
Clock_manager
Files
file fsl_clock_manager.h
Data Structures
struct OscerConfig
OSC configuration for OSCERCLK.
struct OscUserConfig
OSC Initialization Configuration Structure.
struct RtcOscUserConfig
RTC OSC Initialization Configuration Structure.
struct McgConfig
MCG configure structure for mode change.
struct ClockUserConfig
Clock configuration structure.
struct ClockNotifyStruct
Clock notification structure passed to clock callback function.
struct ClockManagerCallbackUserConfig
Structure for callback function and its parameter.
struct ClockManagerState
Clock manager state structure.
Macros
#define CLOCK_USE_MCG /** MCG is used. */
#define CPU_LPO_CLK_HZ 1000U
Frequency of LPO.
Typedefs
typedef enum _clock_systick_src clock_systick_src_t
Systick clock source selection.
typedef enum _clock_names clock_names_t
Clock name used to get clock frequency.
typedef enum _clock_manager_error_code clock_manager_error_code_t
Error code definition for the clock manager APIs.
typedef struct OscerConfig oscer_config_t
OSC configuration for OSCERCLK.
typedef struct OscUserConfig osc_user_config_t
OSC Initialization Configuration Structure.
typedef struct RtcOscUserConfig rtc_osc_user_config_t
RTC OSC Initialization Configuration Structure.
typedef struct McgConfig mcg_config_t
MCG configure structure for mode change.
typedef struct ClockUserConfig clock_manager_user_config_t
Clock configuration structure.
typedef enum _clock_manager_notify clock_manager_notify_t
The clock notification type.
typedef enum _clock_manager_callback_type clock_manager_callback_type_t
The callback type, indicates what kinds of notification this callback handles.
typedef enum ClockManagerPolicy clock_manager_policy_t
Clock transition policy.
typedef struct ClockNotifyStruct clock_notify_struct_t
Clock notification structure passed to clock callback function.
typedef clock_manager_error_code_t(* clock_manager_callback_t) (clock_notify_struct_t *notify, void *callbackData)
Type of clock callback functions.
typedef struct ClockManagerCallbackUserConfig clock_manager_callback_user_config_t
Structure for callback function and its parameter.
typedef struct ClockManagerState clock_manager_state_t
Clock manager state structure.
Enumerations
Functions
clock_manager_error_code_t CLOCK_SYS_GetFreq (clock_names_t clockName, uint32_t *frequency)
Gets the clock frequency for a specific clock name.
uint32_t CLOCK_SYS_GetCoreClockFreq (void)
Get core clock frequency.
uint32_t CLOCK_SYS_GetSystemClockFreq (void)
Get system clock frequency.
uint32_t CLOCK_SYS_GetBusClockFreq (void)
Get bus clock frequency.
uint32_t CLOCK_SYS_GetFlashClockFreq (void)
Get flash clock frequency.
uint32_t CLOCK_SYS_GetFlexbusFreq (void)
Get flexbus clock frequency.
uint32_t CLOCK_SYS_GetPllFllClockFreq (void)
Get the MCGPLLCLK/MCGFLLCLK/IRC48MCLK clock frequency.
uint32_t CLOCK_SYS_GetExternalRefClock32kFreq (void)
Gets the external reference 32k clock frequency.
uint32_t CLOCK_SYS_GetOsc0ExternalRefClockFreq (void)
Gets the OSC0ERCLK frequency.
uint32_t CLOCK_SYS_GetRtcOutFreq (void)
Gets RTC_CLKOUT frequency.
uint32_t CLOCK_SYS_GetWdogFreq (uint32_t instance, clock_wdog_src_t wdogSrc)
Gets the watch dog clock frequency.
uint32_t CLOCK_SYS_GetTraceFreq (uint32_t instance)
Gets the debug trace clock frequency.
uint32_t CLOCK_SYS_GetPortFilterFreq (uint32_t instance, clock_port_filter_src_t src)
Gets PORTx digital input filter clock frequency.
uint32_t CLOCK_SYS_GetLptmrFreq (uint32_t instance, clock_lptmr_src_t lptmrSrc)
Gets LPTMRx pre-scaler/glitch filter clock frequency.
uint32_t CLOCK_SYS_GetEnetRmiiFreq (uint32_t instance)
Gets ethernet RMII clock frequency.
uint32_t CLOCK_SYS_GetEnetTimeStampFreq (uint32_t instance)
Gets ethernet timestamp clock frequency.
uint32_t CLOCK_SYS_GetUsbfsFreq (uint32_t instance)
Gets the clock frequency for USB FS OTG module.
uint32_t CLOCK_SYS_GetFlexcanFreq (uint32_t instance, clock_flexcan_src_t flexcanSrc)
Gets FLEXCAN clock frequency.
uint32_t CLOCK_SYS_GetSdhcFreq (uint32_t instance)
Gets the clock frequency for SDHC.
uint32_t CLOCK_SYS_GetSaiFreq (uint32_t instance, clock_sai_src_t saiSrc)
Gets the clock frequency for SAI.
uint32_t CLOCK_SYS_GetFtmExternalFreq (uint32_t instance)
Gets FTM external clock frequency.
uint32_t CLOCK_SYS_GetUartFreq (uint32_t instance)
Gets the clock frequency for UART module.
void CLOCK_SYS_EnablePortClock (uint32_t instance)
Enable the clock for PORT module.
void CLOCK_SYS_DisablePortClock (uint32_t instance)
Disable the clock for PORT module.
bool CLOCK_SYS_GetPortGateCmd (uint32_t instance)
Get the the clock gate state for PORT module.
void CLOCK_SYS_EnableAdcClock (uint32_t instance)
Enable the clock for ADC module.
void CLOCK_SYS_DisableAdcClock (uint32_t instance)
Disable the clock for ADC module.
bool CLOCK_SYS_GetAdcGateCmd (uint32_t instance)
Get the the clock gate state for ADC module.
void CLOCK_SYS_EnableDacClock (uint32_t instance)
Enable the clock for DAC module.
void CLOCK_SYS_DisableDacClock (uint32_t instance)
Disable the clock for DAC module.
bool CLOCK_SYS_GetDacGateCmd (uint32_t instance)
Get the the clock gate state for DAC module.
void CLOCK_SYS_EnableFtmClock (uint32_t instance)
Enable the clock for FTM module.
void CLOCK_SYS_DisableFtmClock (uint32_t instance)
Disable the clock for FTM module.
bool CLOCK_SYS_GetFtmGateCmd (uint32_t instance)
Get the the clock gate state for FTM module.
void CLOCK_SYS_EnableSpiClock (uint32_t instance)
Enable the clock for SPI module.
void CLOCK_SYS_DisableSpiClock (uint32_t instance)
Disable the clock for SPI module.
bool CLOCK_SYS_GetSpiGateCmd (uint32_t instance)
Get the the clock gate state for SPI module.
void CLOCK_SYS_EnableI2cClock (uint32_t instance)
Enable the clock for I2C module.
void CLOCK_SYS_DisableI2cClock (uint32_t instance)
Disable the clock for I2C module.
bool CLOCK_SYS_GetI2cGateCmd (uint32_t instance)
Get the the clock gate state for I2C module.
void CLOCK_SYS_EnableUartClock (uint32_t instance)
Enable the clock for UART module.
void CLOCK_SYS_DisableUartClock (uint32_t instance)
Disable the clock for UART module.
bool CLOCK_SYS_GetUartGateCmd (uint32_t instance)
Get the the clock gate state for UART module.
Variables
SIM_Type *const g_simBase []
The register base of SIM module.
MCG_Type *const g_mcgBase []
The register base of MCG/MCG_LITE module.
OSC_Type *const g_oscBase []
The register base of OSC module.
Dynamic clock setting
clock_manager_error_code_t CLOCK_SYS_Init (clock_manager_user_config_t const **clockConfigsPtr, uint8_t configsNumber, clock_manager_callback_user_config_t **callbacksPtr, uint8_t callbacksNumber)
Install pre-defined clock configurations.
clock_manager_error_code_t CLOCK_SYS_UpdateConfiguration (uint8_t targetConfigIndex, clock_manager_policy_t policy)
Set system clock configuration according to pre-defined structure.
clock_manager_error_code_t CLOCK_SYS_SetConfiguration (clock_manager_user_config_t const *config)
Set system clock configuration.
uint8_t CLOCK_SYS_GetCurrentConfiguration (void)
Get current system clock configuration.
clock_manager_callback_user_config_t * CLOCK_SYS_GetErrorCallback (void)
Get the callback which returns error in last clock switch.
mcg_mode_error_t CLOCK_SYS_SetMcgMode (mcg_config_t const *targetConfig, void(*fllStableDelay)(void))
Set MCG to some target mode.
OSC configuration
clock_manager_error_code_t CLOCK_SYS_OscInit (uint32_t instance, osc_user_config_t *config)
Initialize OSC.
void CLOCK_SYS_OscDeinit (uint32_t instance)
Deinitialize OSC.
void CLOCK_SYS_SetOscerConfigration (uint32_t instance, oscer_config_t const *config)
Configure the OSCERCLK.
Detailed Description
Macro Definition Documentation
#define CLOCK_USE_MCG /** MCG is used. */
DefinitionsMacro to determine which clock module is used.
Definition at line 55 of file fsl_clock_manager.h.
Typedef Documentation
typedef struct McgConfig mcg_config_t
MCG configure structure for mode change.
When porting to a new board, please set the following members according to board setting:
frdiv: If FLL uses the external reference clock, please set this value to make sure external reference clock divided by frdiv is in the range 31.25kHz to 39.0625kHz.
prdiv0/vdiv0/prdiv1/vdiv1: Please set these values for PLL, the PLL reference clock frequency after prdiv should be in the range of FSL_FEATURE_MCG_PLL_REF_MIN to FSL_FEATURE_MCG_PLL_REF_MAX.
typedef struct OscUserConfig osc_user_config_t
OSC Initialization Configuration Structure.
Defines the configuration data structure to initialize the OSC. When porting to a new board, please set the following members according to board setting:
freq: The external frequency.
hgo/range/erefs: These members should be set base on the board setting.
typedef struct RtcOscUserConfig rtc_osc_user_config_t
RTC OSC Initialization Configuration Structure.
Defines the configuration data structure to initialize the RTC OSC. When porting to a new board, please set the following members according to board setting:
freq: The external frequency for RTC.
enableOSC: RTC could use its dedicate OSC, or override the OSC0 setting and use OSC0, or use external input clock directly. This is different by SOC and board setting, please set this correctly.
Enumeration Type Documentation
enum _clock_manager_callback_type
The callback type, indicates what kinds of notification this callback handles.
Enumerator
kClockManagerCallbackBefore
Callback handles BEFORE notification.
kClockManagerCallbackAfter
Callback handles AFTER notification.
kClockManagerCallbackBeforeAfter
Callback handles BEFORE and AFTER notification
Definition at line 664 of file fsl_clock_manager.h.
enum _clock_manager_error_code
Error code definition for the clock manager APIs.
Enumerator
kClockManagerSuccess
Success
kClockManagerError
Some error occurs.
kClockManagerNoSuchClockName
Invalid name
kClockManagerInvalidParam
Invalid parameter
kClockManagerErrorOutOfRange
Configuration index out of range.
kClockManagerErrorNotificationBefore
Error occurs during send "BEFORE" notification.
kClockManagerErrorNotificationAfter
Error occurs during send "AFTER" notification.
kClockManagerErrorUnknown
Unknown error.
Definition at line 135 of file fsl_clock_manager.h.
enum _clock_manager_notify
The clock notification type.
Enumerator
kClockManagerNotifyRecover
Notify IP to recover to previous work state.
kClockManagerNotifyBefore
Notify IP that system will change clock setting.
kClockManagerNotifyAfter
Notify IP that have changed to new clock setting.
Definition at line 656 of file fsl_clock_manager.h.
enum _clock_names
Clock name used to get clock frequency.
Enumerator
kCoreClock
default clocks Core clock
kSystemClock
System clock
kPlatformClock
Platform clock
kBusClock
Bus clock
kFlexBusClock
FlexBus clock
kFlashClock
Flash clock
kFastPeripheralClock
Flash peripheral clock
kSystickClock
Clock for systick.
kOsc32kClock
other internal clocks used by peripherals osc clock ERCLK32K
kOsc0ErClock
OSC0ERCLK
kOsc1ErClock
OSC1ERCLK
kOsc0ErClockUndiv
OSC0ERCLK_UNDIV
kIrc48mClock
IRC 48M
kRtcoutClock
rtc clock RTC_CLKOUT
kMcgFfClock
mcg clocks MCG fixed frequency clock (MCGFFCLK)
kMcgFllClock
MCGFLLCLK
kMcgPll0Clock
MCGPLL0CLK
kMcgPll1Clock
MCGPLL1CLK
kMcgExtPllClock
EXT_PLLCLK
kMcgOutClock
MCGOUTCLK
kMcgIrClock
MCGIRCLK
kLpoClock
LPO clock LPO clock
Definition at line 92 of file fsl_clock_manager.h.
enum _clock_systick_src
Systick clock source selection.
Enumerator
kClockSystickSrcExtRef
Use external reference clock.
kClockSystickSrcCore
Use processer clock (Core clock).
Definition at line 85 of file fsl_clock_manager.h.
enum ClockManagerPolicy
Clock transition policy.
Enumerator
kClockManagerPolicyAgreement
Clock transfers gracefully.
kClockManagerPolicyForcible
Clock transfers forcefully.
Definition at line 672 of file fsl_clock_manager.h.
Function Documentation
void CLOCK_SYS_DisableAdcClock (uint32_t instance)
Disable the clock for ADC module.
This function disables the clock for ADC module.
Parameters
instance module device instance
Definition at line 750 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_DisableDacClock (uint32_t instance)
Disable the clock for DAC module.
This function disables the clock for DAC module.
Parameters
instance module device instance
Definition at line 799 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_DisableFtmClock (uint32_t instance)
Disable the clock for FTM module.
This function disables the clock for FTM module.
Parameters
instance module device instance
Definition at line 850 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_DisableI2cClock (uint32_t instance)
Disable the clock for I2C module.
This function disables the clock for I2C module.
Parameters
instance module device instance
Definition at line 950 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_DisablePortClock (uint32_t instance)
Disable the clock for PORT module.
This function disables the clock for PORT module.
Parameters
instance module device instance
Definition at line 701 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_DisableSpiClock (uint32_t instance)
Disable the clock for SPI module.
This function disables the clock for SPI module.
Parameters
instance module device instance
Definition at line 900 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_DisableUartClock (uint32_t instance)
Disable the clock for UART module.
This function disables the clock for UART module.
Parameters
instance module device instance
Definition at line 1003 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_EnableAdcClock (uint32_t instance)
Enable the clock for ADC module.
This function enables the clock for ADC module.
Parameters
instance module device instance
Definition at line 736 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_EnableDacClock (uint32_t instance)
Enable the clock for DAC module.
This function enables the clock for DAC module.
Parameters
instance module device instance
Definition at line 785 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_EnableFtmClock (uint32_t instance)
Enable the clock for FTM module.
This function enables the clock for FTM module.
Parameters
instance module device instance
Definition at line 836 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_EnableI2cClock (uint32_t instance)
Enable the clock for I2C module.
This function enables the clock for I2C module.
Parameters
instance module device instance
Definition at line 936 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_EnablePortClock (uint32_t instance)
Enable the clock for PORT module.
This function enables the clock for PORT module.
Parameters
instance module device instance
Definition at line 687 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_EnableSpiClock (uint32_t instance)
Enable the clock for SPI module.
This function enables the clock for SPI module.
Parameters
instance module device instance
Definition at line 886 of file fsl_clock_MK64F12.c.
References SIM.
void CLOCK_SYS_EnableUartClock (uint32_t instance)
Enable the clock for UART module.
This function enables the clock for UART module.
Parameters
instance module device instance
Definition at line 989 of file fsl_clock_MK64F12.c.
References SIM.
bool CLOCK_SYS_GetAdcGateCmd (uint32_t instance)
Get the the clock gate state for ADC module.
This function will get the clock gate state for ADC module.
Parameters
instance module device instance
Returns
state true - ungated(Enabled), false - gated (Disabled)
Definition at line 764 of file fsl_clock_MK64F12.c.
References SIM.
uint32_t CLOCK_SYS_GetBusClockFreq (void)
Get bus clock frequency.
This function gets the bus clock frequency.
Returns
Current bus clock frequency.
Definition at line 228 of file fsl_clock_MK64F12.c.
References MCG, and SIM.
Referenced by CLOCK_SYS_GetFlexcanFreq(), CLOCK_SYS_GetFreq(), CLOCK_SYS_GetPortFilterFreq(), CLOCK_SYS_GetUartFreq(), CLOCK_SYS_GetWdogFreq(), and POWER_SYS_ClearAckIsolation().
uint32_t CLOCK_SYS_GetCoreClockFreq (void)
Get core clock frequency.
This function gets the core clock frequency.
Returns
Current core clock frequency.
Definition at line 204 of file fsl_clock_MK64F12.c.
References MCG, and SIM.
Referenced by CLOCK_SYS_GetEnetTimeStampFreq(), CLOCK_SYS_GetFreq(), CLOCK_SYS_GetSdhcFreq(), CLOCK_SYS_GetTraceFreq(), CLOCK_SYS_SetConfiguration(), and POWER_SYS_ClearAckIsolation().
uint8_t CLOCK_SYS_GetCurrentConfiguration (void)
Get current system clock configuration.
Returns
Current clock configuration index.
Definition at line 231 of file fsl_clock_manager.c.
References ClockManagerState::curConfigIndex.
bool CLOCK_SYS_GetDacGateCmd (uint32_t instance)
Get the the clock gate state for DAC module.
This function will get the clock gate state for DAC module.
Parameters
instance module device instance
Returns
state true - ungated(Enabled), false - gated (Disabled)
Definition at line 813 of file fsl_clock_MK64F12.c.
References SIM.
uint32_t CLOCK_SYS_GetEnetRmiiFreq (uint32_t instance)
Gets ethernet RMII clock frequency.
This function gets the ethernet RMII clock frequency.
Parameters
instance module device instance
Returns
Current frequency.
get the sim clock source setting
OSCERCLK
ENET_1588_CLKIN
Definition at line 459 of file fsl_clock_MK64F12.c.
References CLOCK_SYS_GetOsc0ExternalRefClockFreq(), g_enet1588ClkInFreq, kClockRmiiSrcExtalClk, and SIM.
uint32_t CLOCK_SYS_GetEnetTimeStampFreq (uint32_t instance)
Gets ethernet timestamp clock frequency.
This function gets the ethernet timestamp clock frequency.
Parameters
instance module device instance
Returns
Current frequency.
Core/System clock.
FLL/PLL/IRC48M.
OSCERCLK.
ENET 1588 clock in.
Definition at line 479 of file fsl_clock_MK64F12.c.
References CLOCK_SYS_GetCoreClockFreq(), CLOCK_SYS_GetOsc0ExternalRefClockFreq(), CLOCK_SYS_GetPllFllClockFreq(), g_enet1588ClkInFreq, kClockTimeSrcCoreSysClk, kClockTimeSrcExt, kClockTimeSrcOsc0erClk, kClockTimeSrcPllFllSel, and SIM.
clock_manager_callback_user_config_t* CLOCK_SYS_GetErrorCallback (void)
Get the callback which returns error in last clock switch.
When graceful policy is used, if some IP is not ready to change clock setting, the callback will return error and system stay in current configuration. Applications can use this function to check which IP callback returns error.
Returns
Pointer to the callback which returns error.
If all callbacks return success.
Definition at line 242 of file fsl_clock_manager.c.
References ClockManagerState::callbackConfig, ClockManagerState::clockConfigNum, ClockManagerState::errorCallbackIndex, and MCG.
uint32_t CLOCK_SYS_GetExternalRefClock32kFreq (void)
Gets the external reference 32k clock frequency.
This function gets the external reference (ERCLK32K) clock frequency.
Returns
Current frequency.
OSC 32k clock
RTC 32k clock
LPO clock
Definition at line 315 of file fsl_clock_MK64F12.c.
References kClockEr32kSrcLpo, kClockEr32kSrcOsc0, kClockEr32kSrcRtc, and SIM.
Referenced by CLOCK_SYS_GetFreq(), and CLOCK_SYS_GetLptmrFreq().
uint32_t CLOCK_SYS_GetFlashClockFreq (void)
Get flash clock frequency.
This function gets the flash clock frequency.
Returns
Current flash clock frequency.
Definition at line 252 of file fsl_clock_MK64F12.c.
References MCG, and SIM.
Referenced by CLOCK_SYS_GetFreq(), and POWER_SYS_ClearAckIsolation().
uint32_t CLOCK_SYS_GetFlexbusFreq (void)
Get flexbus clock frequency.
This function gets the flexbus clock frequency.
Returns
Current flexbus clock frequency.
Definition at line 240 of file fsl_clock_MK64F12.c.
References MCG, and SIM.
Referenced by CLOCK_SYS_GetFreq().
uint32_t CLOCK_SYS_GetFlexcanFreq (uint32_t instance, clock_flexcan_src_t flexcanSrc)
Gets FLEXCAN clock frequency.
This function gets the FLEXCAN clock frequency.
Parameters
instance module device instance
flexcanSrc clock source
Returns
Current frequency.
Definition at line 542 of file fsl_clock_MK64F12.c.
References CLOCK_SYS_GetBusClockFreq(), CLOCK_SYS_GetOsc0ExternalRefClockFreq(), and kClockFlexcanSrcOsc0erClk.
clock_manager_error_code_t CLOCK_SYS_GetFreq (clock_names_t clockName, uint32_t * frequency)
Gets the clock frequency for a specific clock name.
API
This function checks the current clock configurations and then calculates the clock frequency for a specific clock name defined in clock_names_t. The MCG must be properly configured before using this function. See the reference manual for supported clock names for different chip families. The returned value is in Hertz. If it cannot find the clock name or the name is not supported for a specific chip family, it returns an error.
Parameters
clockName Clock names defined in clock_names_t
frequency Returned clock frequency value in Hertz
Returns
status Error code defined in clock_manager_error_code_t
Definition at line 132 of file fsl_clock_MK64F12.c.
References CLOCK_SYS_GetBusClockFreq(), CLOCK_SYS_GetCoreClockFreq(), CLOCK_SYS_GetExternalRefClock32kFreq(), CLOCK_SYS_GetFlashClockFreq(), CLOCK_SYS_GetFlexbusFreq(), CLOCK_SYS_GetOsc0ExternalRefClockFreq(), CLOCK_SYS_GetRtcOutFreq(), CLOCK_SYS_GetSystemClockFreq(), kBusClock, kClockManagerNoSuchClockName, kClockManagerSuccess, kCoreClock, kFlashClock, kFlexBusClock, kIrc48mClock, kLpoClock, kMcgFfClock, kMcgFllClock, kMcgIrClock, kMcgOutClock, kMcgPll0Clock, kOsc0ErClock, kOsc32kClock, kPlatformClock, kRtcoutClock, kSystemClock, kSystickClock, and MCG.
uint32_t CLOCK_SYS_GetFtmExternalFreq (uint32_t instance)
Gets FTM external clock frequency.
This function gets the FTM external clock frequency.
Parameters
instance module device instance
Returns
freq Current frequency.
Definition at line 656 of file fsl_clock_MK64F12.c.
References g_ftmClkFreq, kSimFtmClkSel0, SIM, and SIM_HAL_GetFtmExternalClkPinMode().
bool CLOCK_SYS_GetFtmGateCmd (uint32_t instance)
Get the the clock gate state for FTM module.
This function will get the clock gate state for FTM module.
Parameters
instance module device instance
Returns
state true - ungated(Enabled), false - gated (Disabled)
Definition at line 864 of file fsl_clock_MK64F12.c.
References SIM.
bool CLOCK_SYS_GetI2cGateCmd (uint32_t instance)
Get the the clock gate state for I2C module.
This function will get the clock gate state for I2C module.
Parameters
instance module device instance
Returns
state true - ungated(Enabled), false - gated (Disabled)
Definition at line 964 of file fsl_clock_MK64F12.c.
References SIM.
uint32_t CLOCK_SYS_GetLptmrFreq (uint32_t instance, clock_lptmr_src_t lptmrSrc)
Gets LPTMRx pre-scaler/glitch filter clock frequency.
This function gets the LPTMRx pre-scaler/glitch filter clock frequency.
Parameters
instance module device instance
lptmrSrc LPTMRx clock source selection.
Returns
Current frequency.
MCG out clock
LPO clock
ERCLK32K clock
OSCERCLK clock
Definition at line 426 of file fsl_clock_MK64F12.c.
References CLOCK_SYS_GetExternalRefClock32kFreq(), CLOCK_SYS_GetOsc0ExternalRefClockFreq(), kClockLptmrSrcEr32kClk, kClockLptmrSrcLpoClk, kClockLptmrSrcMcgIrClk, kClockLptmrSrcOsc0erClk, and MCG.
uint32_t CLOCK_SYS_GetOsc0ExternalRefClockFreq (void)
Gets the OSC0ERCLK frequency.
This function gets the OSC0 external reference frequency.
Returns
Current frequency.
Definition at line 348 of file fsl_clock_MK64F12.c.
References g_oscBase.
Referenced by CLOCK_SYS_GetEnetRmiiFreq(), CLOCK_SYS_GetEnetTimeStampFreq(), CLOCK_SYS_GetFlexcanFreq(), CLOCK_SYS_GetFreq(), CLOCK_SYS_GetLptmrFreq(), CLOCK_SYS_GetSaiFreq(), and CLOCK_SYS_GetSdhcFreq().
uint32_t CLOCK_SYS_GetPllFllClockFreq (void)
Get the MCGPLLCLK/MCGFLLCLK/IRC48MCLK clock frequency.
This function gets the frequency of the MCGPLLCLK/MCGFLLCLK/IRC48MCLK.
Returns
Current clock frequency.
Definition at line 264 of file fsl_clock_MK64F12.c.
References kClockPllFllSelFll, kClockPllFllSelIrc48M, kClockPllFllSelPll, MCG, and SIM.
Referenced by CLOCK_SYS_GetEnetTimeStampFreq(), CLOCK_SYS_GetSdhcFreq(), and CLOCK_SYS_GetUsbfsFreq().
uint32_t CLOCK_SYS_GetPortFilterFreq (uint32_t instance, clock_port_filter_src_t src)
Gets PORTx digital input filter clock frequency.
This function gets the PORTx digital input filter clock frequency.
Parameters
instance module device instance.
src PORTx source selection.
Returns
Current frequency.
Definition at line 407 of file fsl_clock_MK64F12.c.
References CLOCK_SYS_GetBusClockFreq(), and kClockPortFilterSrcBusClk.
bool CLOCK_SYS_GetPortGateCmd (uint32_t instance)
Get the the clock gate state for PORT module.
This function will get the clock gate state for PORT module.
Parameters
instance module device instance
Returns
state true - ungated(Enabled), false - gated (Disabled)
Definition at line 715 of file fsl_clock_MK64F12.c.
References SIM.
uint32_t CLOCK_SYS_GetRtcOutFreq (void)
Gets RTC_CLKOUT frequency.
This function gets the frequency of RTC_CLKOUT.
Returns
Current frequency.
Definition at line 296 of file fsl_clock_MK64F12.c.
References kClockRtcoutSrc1Hz.
Referenced by CLOCK_SYS_GetFreq().
uint32_t CLOCK_SYS_GetSaiFreq (uint32_t instance, clock_sai_src_t saiSrc)
Gets the clock frequency for SAI.
This function gets the clock frequency for SAI.
Parameters
instance module device instance.
saiSrc SAI clock source selection according to its internal register.
Returns
freq clock frequency for this module.
Definition at line 628 of file fsl_clock_MK64F12.c.
References CLOCK_SYS_GetOsc0ExternalRefClockFreq(), CLOCK_SYS_GetSystemClockFreq(), kClockSaiSrcOsc0erClk, kClockSaiSrcPllClk, kClockSaiSrcSysClk, and MCG.
uint32_t CLOCK_SYS_GetSdhcFreq (uint32_t instance)
Gets the clock frequency for SDHC.
This function gets the clock frequency for SDHC.
Parameters
instance module device instance
Returns
freq clock frequency for this module.
Core/system clock
Clock selected by SOPT2[PLLFLLSEL].
OSCERCLK clock
External bypass clock (SDHC0_CLKIN)
Definition at line 592 of file fsl_clock_MK64F12.c.
References CLOCK_SYS_GetCoreClockFreq(), CLOCK_SYS_GetOsc0ExternalRefClockFreq(), CLOCK_SYS_GetPllFllClockFreq(), g_sdhcClkInFreq, kClockSdhcSrcCoreSysClk, kClockSdhcSrcExt, kClockSdhcSrcOsc0erClk, kClockSdhcSrcPllFllSel, and SIM.
bool CLOCK_SYS_GetSpiGateCmd (uint32_t instance)
Get the the clock gate state for SPI module.
This function will get the clock gate state for SPI module.
Parameters
instance module device instance
Returns
state true - ungated(Enabled), false - gated (Disabled)
Definition at line 914 of file fsl_clock_MK64F12.c.
References SIM.
uint32_t CLOCK_SYS_GetSystemClockFreq (void)
Get system clock frequency.
This function gets the system clock frequency.
Returns
Current system clock frequency.
Definition at line 216 of file fsl_clock_MK64F12.c.
References MCG, and SIM.
Referenced by CLOCK_SYS_GetFreq(), CLOCK_SYS_GetSaiFreq(), CLOCK_SYS_GetUartFreq(), and POWER_SYS_ClearAckIsolation().
uint32_t CLOCK_SYS_GetTraceFreq (uint32_t instance)
Gets the debug trace clock frequency.
This function gets the debug trace clock frequency.
Parameters
instance module device instance
Returns
Current frequency.
Definition at line 386 of file fsl_clock_MK64F12.c.
References CLOCK_SYS_GetCoreClockFreq(), kClockTraceSrcMcgoutClk, MCG, and SIM.
uint32_t CLOCK_SYS_GetUartFreq (uint32_t instance)
Gets the clock frequency for UART module.
This function gets the clock frequency for UART module.
Parameters
instance module device instance
Returns
freq clock frequency for this module
Definition at line 561 of file fsl_clock_MK64F12.c.
References CLOCK_SYS_GetBusClockFreq(), and CLOCK_SYS_GetSystemClockFreq().
bool CLOCK_SYS_GetUartGateCmd (uint32_t instance)
Get the the clock gate state for UART module.
This function will get the clock gate state for UART module.
Parameters
instance module device instance
Returns
state true - ungated(Enabled), false - gated (Disabled)
Definition at line 1017 of file fsl_clock_MK64F12.c.
References SIM.
uint32_t CLOCK_SYS_GetUsbfsFreq (uint32_t instance)
Gets the clock frequency for USB FS OTG module.
This function gets the clock frequency for USB FS OTG module.
Parameters
instance module device instance
Returns
freq clock frequency for this module
USB_CLKIN
Definition at line 514 of file fsl_clock_MK64F12.c.
References CLOCK_HAL_GetUsbfsDiv(), CLOCK_SYS_GetPllFllClockFreq(), g_usbClkInFreq, kClockUsbfsSrcExt, and SIM.
uint32_t CLOCK_SYS_GetWdogFreq (uint32_t instance, clock_wdog_src_t wdogSrc)
Gets the watch dog clock frequency.
This function gets the watch dog clock frequency.
Parameters
instance module device instance
wdogSrc watch dog clock source selection, WDOG_STCTRLH[CLKSRC].
Returns
Current frequency.
Definition at line 367 of file fsl_clock_MK64F12.c.
References CLOCK_SYS_GetBusClockFreq(), and kClockWdogSrcLpoClk.
clock_manager_error_code_t CLOCK_SYS_Init (clock_manager_user_config_t const ** clockConfigsPtr, uint8_t configsNumber, clock_manager_callback_user_config_t ** callbacksPtr, uint8_t callbacksNumber)
Install pre-defined clock configurations.
This function installs the pre-defined clock configuration table to clock manager.
Parameters
clockConfigsPtr Pointer to the clock configuration table.
configsNumber Number of clock configurations in table.
callbacksPtr Pointer to the callback configuration table.
callbacksNumber Number of callback configurations in table.
Returns
Error code.
Definition at line 89 of file fsl_clock_manager.c.
References ClockManagerState::callbackConfig, ClockManagerState::callbackNum, ClockManagerState::clockConfigNum, ClockManagerState::configTable, ClockManagerState::errorCallbackIndex, and kClockManagerSuccess.
Referenced by HEXIWEAR_startup().
void CLOCK_SYS_OscDeinit (uint32_t instance)
Deinitialize OSC.
This function deinitializes OSC.
Parameters
instance Instance of the OSC.
Definition at line 643 of file fsl_clock_manager.c.
References g_oscBase, and MCG.
Referenced by CLOCK_SYS_SetMcgMode().
clock_manager_error_code_t CLOCK_SYS_OscInit (uint32_t instance, osc_user_config_t * config)
Initialize OSC.
This function initializes OSC according to board configuration.
Parameters
instance Instance of the OSC.
config Pointer to the OSC configuration structure.
Returns
kClockManagerSuccess on success.
oscillator is used.
oscillator is used.
Definition at line 588 of file fsl_clock_manager.c.
References CLOCK_SYS_SetOscerConfigration(), OscerConfig::enable, OscUserConfig::enableCapacitor16p, OscUserConfig::enableCapacitor2p, OscUserConfig::enableCapacitor4p, OscUserConfig::enableCapacitor8p, OscUserConfig::erefs, OscUserConfig::freq, g_oscBase, OscUserConfig::hgo, kClockManagerSuccess, MCG, OscUserConfig::oscerConfig, and OscUserConfig::range.
Referenced by CLOCK_SYS_SetMcgMode().
clock_manager_error_code_t CLOCK_SYS_SetConfiguration (clock_manager_user_config_t const * config)
Set system clock configuration.
This funtion sets the system to target configuration, it only sets the clock modules registers for clock mode change, but not send notifications to drivers. This function is different by different SoCs.
Parameters
config Target configuration.
Returns
Error code.
Note
If external clock is used in the target mode, please make sure it is enabled, for example, if the external oscillator is used, please setup EREFS/HGO correctly and make sure OSCINIT is set.
Set outdiv for safe output clock frequency.
Set MCG mode.
Set SIM setting.
Set OSCERCLK setting.
Definition at line 112 of file fsl_clock_MK64F12.c.
References CLOCK_HAL_SetOutDiv(), CLOCK_SYS_GetCoreClockFreq(), CLOCK_SYS_SetMcgMode(), CLOCK_SYS_SetOscerConfigration(), kClockManagerSuccess, ClockUserConfig::mcgConfig, ClockUserConfig::oscerConfig, SIM, and ClockUserConfig::simConfig.
Referenced by CLOCK_SYS_UpdateConfiguration().
mcg_mode_error_t CLOCK_SYS_SetMcgMode (mcg_config_t const * targetConfig, void(*)(void) fllStableDelay)
Set MCG to some target mode.
This function sets MCG to some target mode defined by the configure structure, if cannot switch to target mode directly, this function will choose the proper path.
Parameters
targetConfig Pointer to the target MCG mode configuration structure.
fllStableDelay Delay function to make sure FLL is stable.
Returns
Error code.
Note
If external clock is used in the target mode, please make sure it is enabled, for example, if the external oscillator is used, please setup EREFS/HGO correctly and make sure OSCINIT is set.
Enable MCGIRCLK.
Configure MCGIRCLK.
Update FCRDIV if necessary.
Definition at line 355 of file fsl_clock_manager.c.
References CLOCK_SYS_OscDeinit(), CLOCK_SYS_OscInit(), CLOCK_SYS_SetOscerConfigration(), McgConfig::dmx32, McgConfig::drs, OscerConfig::enable, OscUserConfig::enableCapacitor16p, OscUserConfig::enableCapacitor2p, OscUserConfig::enableCapacitor4p, OscUserConfig::enableCapacitor8p, OscUserConfig::erefs, McgConfig::fcrdiv, McgConfig::frdiv, OscUserConfig::freq, g_oscBase, OscUserConfig::hgo, McgConfig::irclkEnable, McgConfig::irclkEnableInStop, McgConfig::ircs, kClockManagerSuccess, MCG, McgConfig::mcg_mode, OscUserConfig::oscerConfig, and OscUserConfig::range.
Referenced by CLOCK_SYS_SetConfiguration().
void CLOCK_SYS_SetOscerConfigration (uint32_t instance, oscer_config_t const * config)
Configure the OSCERCLK.
This function configures the OSCERCLK, including whether OSCERCLK is enable or not in normal mode and stop mode.
Parameters
instance Instance of the OSC.
config Pointer to the OSCERCLK configuration structure.
Definition at line 679 of file fsl_clock_manager.c.
References OscerConfig::enable, RtcOscUserConfig::enableCapacitor16p, RtcOscUserConfig::enableCapacitor2p, RtcOscUserConfig::enableCapacitor4p, RtcOscUserConfig::enableCapacitor8p, RtcOscUserConfig::enableClockOutput, OscerConfig::enableInStop, RtcOscUserConfig::enableOsc, RtcOscUserConfig::freq, g_oscBase, and kClockManagerSuccess.
Referenced by CLOCK_SYS_OscInit(), CLOCK_SYS_SetConfiguration(), and CLOCK_SYS_SetMcgMode().
clock_manager_error_code_t CLOCK_SYS_UpdateConfiguration (uint8_t targetConfigIndex, clock_manager_policy_t policy)
Set system clock configuration according to pre-defined structure.
This function sets system to target clock configuration, before transition, clock manager will send notifications to all drivers registered to the callback table. When graceful policy is used, if some drivers are not ready to change, clock transition will not occur, all drivers still work in previous configuration and error is returned. When forceful policy is used, all drivers should stop work and system changes to new clock configuration.
Parameters
targetConfigIndex Index of the clock configuration.
policy Transaction policy, graceful or forceful.
Returns
Error code.
Note
If external clock is used in the target mode, please make sure it is enabled, for example, if the external oscillator is used, please setup EREFS/HGO correctly and make sure OSCINIT is set.
Clock configuration index is out of range.
Set errorcallbackindex as callbackNum, which means no callback error now.
First step: Send "BEFORE" notification.
Send notification to all callback.
Save the error callback index.
If all callback success or forceful policy is used.
clock mode switch.
Save the error callback index.
Error occurs, need to send "RECOVER" notification.
Definition at line 123 of file fsl_clock_manager.c.
References ClockManagerCallbackUserConfig::callback, ClockManagerState::callbackConfig, ClockManagerCallbackUserConfig::callbackData, ClockManagerState::callbackNum, ClockManagerCallbackUserConfig::callbackType, CLOCK_SYS_SetConfiguration(), ClockManagerState::clockConfigNum, ClockManagerState::configTable, ClockManagerState::curConfigIndex, ClockManagerState::errorCallbackIndex, kClockManagerErrorNotificationAfter, kClockManagerErrorNotificationBefore, kClockManagerErrorOutOfRange, kClockManagerNotifyAfter, kClockManagerNotifyBefore, kClockManagerNotifyRecover, kClockManagerPolicyAgreement, kClockManagerPolicyForcible, kClockManagerSuccess, kCriticalDisableInt, kCriticalLockSched, ClockNotifyStruct::notifyType, OSA_EnterCritical(), OSA_ExitCritical(), ClockNotifyStruct::policy, and ClockNotifyStruct::targetClockConfigIndex.
Referenced by power_TurnOFF().
Variable Documentation
SIM_Type* const g_simBase[]
The register base of SIM module.
Variables DefinitionsTable of base addresses for instances.
Definition at line 42 of file fsl_clock_manager_common.c.