HEXIWEAR MK64 Firmware Reference Manual: gui/driver/src/gui_driver.c File Reference
gui_driver.c File Reference
this file contains GUI functionality
#include "HEXIWEAR_info.h"
#include "notifications.h"
#include "bond.h"
#include "sensor_defs.h"
#include "power_driver.h"
#include "gui_driver.h"
#include "gui_types.h"
#include "gui_info.h"
#include "screens_common.h"
#include "string.h"
#include "OLED_info.h"
#include "OLED_defs.h"
#include "OLED_driver.h"
#include "GPIO.h"
#include "rtc_driver.h"
#include "error.h"
#include "error_types.h"
#include "CLOCK.h"
#include <stdio.h>
Functions
gui_status_t GuiDriver_QueueMsgPut (hostInterface_packet_t *packet)
gui_status_t GuiDriver_QueueMsgGet (hostInterface_packet_t *packet, uint32_t timeout)
gui_status_t GuiDriver_Init ()
gui_status_t GuiDriver_ButtonsHandler (hostInterface_packet_t *packet)
gui_status_t GuiDriver_Navigation (guiNavigationDir_t navigationDir, void *param)
void GuiDriver_UpdateScreen (uint8_t xCrd, uint8_t yCrd, uint8_t width, uint8_t height, const uint8_t *image)
gui_status_t GuiDriver_LabelCreate (guiLabel_t *label)
gui_status_t GuiDriver_LabelDestroy (guiLabel_t *label)
void GuiDriver_LabelSetCaption (guiLabel_t *label, uint8_t *caption)
gui_status_t GuiDriver_LabelFormatCaption (guiLabel_t *label, uint8_t *caption, uint8_t *length, guiLabelCutFormat_t format)
void GuiDriver_LabelDraw (guiLabel_t *label)
void GuiDriver_LabelAddToScr (guiLabel_t *label)
void GuiDriver_ImageDraw (guiImage_t *image)
void GuiDriver_ImageAddToScr (guiImage_t *image)
void GuiDriver_DrawButtonPointers (bool upButtonFlag, bool downButtonFlag)
void GuiDriver_ClearScr (void)
void GuiDriver_RegisterForSensors (packet_t packetToReceive, uint32_t delay_ms, bool shouldToggleTask)
void GuiDriver_RegisterMinPollDelay (uint32_t delay)
void GuiDriver_RegisterForNavigation (guiNavigationDir_t navigations)
void GuiDriver_UnregisterFromSensors (packet_t packetToReceive, bool shouldDeactivateTask)
void GuiDriver_UnregisterFromNavigation (guiNavigationDir_t navigations)
void GuiDriver_CleanMainArea ()
void GuiDriver_CleanAbout ()
gui_status_t GuiDriver_NotifyKW40 (gui_current_app_t currentApp)
Detailed Description
this file contains GUI functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file gui_driver.c.
Function Documentation
gui_status_t GuiDriver_ButtonsHandler (hostInterface_packet_t * packet)
[GuiDriver_NavigationHandler description]
Parameters
packet [description]
Definition at line 214 of file gui_driver.c.
References GuiDriver_Navigation(), GuiDriver_QueueMsgPut(), packetType_pressDown, packetType_pressLeft, packetType_pressRight, and packetType_pressUp.
void GuiDriver_CleanAbout ()
[GuiDriver_CleanMainArea description]
Definition at line 823 of file gui_driver.c.
References OLED_DrawBox(), and OLED_STATUS_SUCCESS.
Referenced by info_DestroyTasks().
void GuiDriver_CleanMainArea ()
[GuiDriver_CleanMainArea description]
Definition at line 815 of file gui_driver.c.
References OLED_DrawBox(), and OLED_STATUS_SUCCESS.
Referenced by bootloader_DestroyTasks(), gui_heartRate_QueueMsgPut(), and gui_pedometer_QueueMsgPut().
void GuiDriver_ClearScr (void)
[GuiDriver_ClearScr description]
Definition at line 757 of file gui_driver.c.
References guiDisplay_t::image, and OLED_FillScreen().
void GuiDriver_DrawButtonPointers (bool upButtonFlag, bool downButtonFlag)
Parameters
upButtonFlag
downButtonFlag
Definition at line 691 of file gui_driver.c.
References buttonsGroup_CurrnetActiveGet(), GuiDriver_ImageAddToScr(), and GuiDriver_ImageDraw().
Referenced by bootloader_DestroyTasks(), buttonsGroup_ActiveUpdate(), and info_DestroyTasks().
void GuiDriver_ImageAddToScr (guiImage_t * image)
[GuiDriver_AddToScrImage description]
Parameters
image [description]
Definition at line 679 of file gui_driver.c.
References oled_dynamic_area_t::height, OLED_AddImage(), OLED_GetImageDimensions(), OLED_SetDynamicArea(), and oled_dynamic_area_t::width.
Referenced by bluetooth_Init(), bootloader_Init(), buttonsGroup_Init(), flashlight_Init(), gui_heartRate_Init(), gui_notifications_Init(), gui_pedometer_Init(), gui_sensorTag_Init(), GuiDriver_DrawButtonPointers(), haptic_Init(), info_Init(), and watch_Init().
void GuiDriver_ImageDraw (guiImage_t * image)
[GuiDriver_ImageDraw description]
Parameters
image [description]
Definition at line 662 of file gui_driver.c.
References oled_dynamic_area_t::height, OLED_DrawImage(), OLED_GetImageDimensions(), OLED_SetDynamicArea(), OLED_STATUS_SUCCESS, and oled_dynamic_area_t::width.
Referenced by bluetooth_AdvModeUpdate(), bootloader_DestroyTasks(), buttonsGroup_ActiveUpdate(), flashlight_DestroyTasks(), gui_heartRate_QueueMsgPut(), gui_notifications_DestroyTasks(), gui_pedometer_QueueMsgPut(), gui_sensorTag_DestroyTasks(), GuiDriver_DrawButtonPointers(), haptic_CheckAtStartup(), info_DestroyTasks(), and watch_SetNotification().
gui_status_t GuiDriver_Init ()
initialize GUI
Definition at line 138 of file gui_driver.c.
References bluetooth_CreateAdvModeUpdateEvent(), bluetooth_SendGetAdvModeReq(), bluetooth_WaitForAdvModeUpdate(), buttonsGroup_CreateActiveUpdateEvent(), buttonsGroup_SendGetActiveReq(), buttonsGroup_WaitForActiveUpdate(), GuiDriver_Navigation(), HEXIWEAR_CreateVersionEvent(), HEXIWEAR_SendVersionReq(), HEXIWEAR_WaitForVersionUpdate(), kStatus_OSA_Success, OLED_Init(), OLED_STATUS_SUCCESS, oledModule, oledSettings, OSA_MsgQCreate(), OSA_MutexCreate(), OSA_TimeDelay(), watch_CreateLinkStateUpdateEvent(), watch_SendGetLinkStateReq(), and watch_WaitForLinkStateUpdate().
Referenced by HEXIWEAR_startup().
void GuiDriver_LabelAddToScr (guiLabel_t * label)
[GuiDriver_AddToScrLabel description]
Parameters
label [description]
Definition at line 650 of file gui_driver.c.
References OLED_AddText(), OLED_SetDynamicArea(), and OLED_SetTextProperties().
Referenced by bond_Init(), gui_notifications_Init(), gui_sensorTag_Init(), info_Init(), and watch_Init().
gui_status_t GuiDriver_LabelCreate (guiLabel_t * label)
[GuiDriver_LabelCreate description]
Parameters
label [description]
Definition at line 502 of file gui_driver.c.
References OSA_MemAlloc().
Referenced by bond_Init(), bootloader_Init(), gui_heartRate_Init(), gui_motionControl_Init(), gui_notifications_Init(), gui_pedometer_Init(), gui_weatherStation_Init(), info_Init(), and watch_Init().
gui_status_t GuiDriver_LabelDestroy (guiLabel_t * label)
[GuiDriver_LabelDestroy description]
Parameters
label [description]
Definition at line 525 of file gui_driver.c.
References kStatus_OSA_Success, and OSA_MemFree().
Referenced by bond_DestroyTasks(), bootloader_DestroyTasks(), gui_heartRate_DestroyTasks(), gui_motionControl_DestroyTasks(), gui_notifications_DestroyTasks(), gui_pedometer_DestroyTasks(), gui_weatherStation_DestroyTasks(), info_DestroyTasks(), and watch_DestroyTasks().
void GuiDriver_LabelDraw (guiLabel_t * label)
[GuiDriver_LabelDraw description]
Parameters
label [description]
Definition at line 633 of file gui_driver.c.
References OLED_DrawText(), OLED_SetDynamicArea(), OLED_SetTextProperties(), and OLED_STATUS_SUCCESS.
Referenced by gui_heartRate_QueueMsgPut(), gui_motionControl_DestroyTasks(), gui_notifications_DestroyTasks(), gui_pedometer_QueueMsgPut(), gui_weatherStation_DestroyTasks(), info_DestroyTasks(), and watch_SetNotification().
gui_status_t GuiDriver_LabelFormatCaption (guiLabel_t * label, uint8_t * caption, uint8_t * length, guiLabelCutFormat_t format)
[GuiDriver_LabelFormatCaption description]
Parameters
label [description]
caption [description]
length [description]
format [description]
Definition at line 561 of file gui_driver.c.
References oled_text_properties_t::font, OLED_CharCount(), and oled_dynamic_area_t::width.
void GuiDriver_LabelSetCaption (guiLabel_t * label, uint8_t * caption)
[GuiDriver_LabelSetCaption description]
Parameters
label [description]
caption [description]
length [description]
Definition at line 549 of file gui_driver.c.
Referenced by gui_heartRate_Init(), gui_pedometer_Init(), info_DestroyTasks(), info_Init(), and watch_Init().
gui_status_t GuiDriver_Navigation (guiNavigationDir_t navigationDir, void * param)
[GuiDriver_NavigationDefault description]
Parameters
navigationDir [description]
param [description]
splash screen
goto watch directly
regular navigation cases
Definition at line 287 of file gui_driver.c.
References bond_SetPasskey(), bondScreen, haptic_CurrentStateGet(), haptic_MutexLock(), haptic_MutexUnlock(), guiDisplay_t::image, kStatus_OSA_Success, OLED_DrawScreen(), OLED_GetImageDimensions(), OLED_STATUS_SUCCESS, OLED_Swap(), OLED_TRANSITION_DOWN_TOP, OLED_TRANSITION_LEFT_RIGHT, OLED_TRANSITION_NONE, OLED_TRANSITION_RIGHT_LEFT, OLED_TRANSITION_TOP_DOWN, OSA_MutexLock(), OSA_MutexUnlock(), OSA_TimeDelay(), OSA_WAIT_FOREVER, and watchScreen.
Referenced by GuiDriver_ButtonsHandler(), and GuiDriver_Init().
gui_status_t GuiDriver_NotifyKW40 (gui_current_app_t currentApp)
notify KW40 which app is being runned currently
Parameters
currentApp current app descriptor
Returns
[description]
Definition at line 833 of file gui_driver.c.
References HostInterface_TxQueueMsgPut(), kStatus_OSA_Success, and packetType_appMode.
Referenced by bluetooth_AdvModeUpdate(), gui_heartRate_DestroyTasks(), gui_heartRate_Init(), gui_pedometer_DestroyTasks(), gui_pedometer_Init(), gui_sensorTag_TurnOFF(), gui_sensorTag_TurnON(), and watch_LinkStateUpdate().
gui_status_t GuiDriver_QueueMsgGet (hostInterface_packet_t * packet, uint32_t timeout)
This function gets a message from the head of the designated queue
Parameters
packet Pointer to a memory to save the packet.
Returns
kStatus_OSA_Success Message successfully obtained from the queue. kStatus_OSA_Error Process fail.
Definition at line 115 of file gui_driver.c.
References kStatus_OSA_Error, and OSA_MsgQGet().
Referenced by bluetooth_AdvModeUpdate(), bootloader_DestroyTasks(), buttonsGroup_ActiveUpdate(), flashlight_DestroyTasks(), gui_heartRate_QueueMsgPut(), gui_motionControl_DestroyTasks(), gui_pedometer_QueueMsgPut(), gui_sensorTag_DestroyTasks(), gui_weatherStation_DestroyTasks(), haptic_CheckAtStartup(), info_DestroyTasks(), reset_DestroyTasks(), and watch_SetNotification().
gui_status_t GuiDriver_QueueMsgPut (hostInterface_packet_t * packet)
This function puts a message to the end of the Tx message queue.
Parameters
packet Packet that will be placed into Tx message queue.
Returns
kStatus_OSA_Success Message successfully put into the queue. kStatus_OSA_Error Process fail.
Definition at line 89 of file gui_driver.c.
References OSA_WAIT_FOREVER.
Referenced by GuiDriver_ButtonsHandler(), and sensor_InitAcc().
void GuiDriver_RegisterForNavigation (guiNavigationDir_t navigations)
[GuiDriver_RegisterForNavigation description]
Parameters
navigationDir [description]
Definition at line 789 of file gui_driver.c.
Referenced by bluetooth_Init(), bootloader_DestroyTasks(), bootloader_Init(), buttonsGroup_Init(), flashlight_Init(), gui_heartRate_Init(), gui_pedometer_Init(), gui_sensorTag_Init(), haptic_Init(), info_Init(), and reset_Init().
void GuiDriver_RegisterForSensors (packet_t packetToReceive, uint32_t delay_ms, bool shouldToggleTask)
[GuiDriver_RegisterForSensor description]
Parameters
packetToReceive [description]
Definition at line 767 of file gui_driver.c.
References sensor_GetPacketTargets(), sensor_RegisterPacketDelay(), and sensor_SetPacketTargets().
Referenced by gui_motionControl_Init(), gui_weatherStation_Init(), and watch_Init().
void GuiDriver_RegisterMinPollDelay (uint32_t delay)
[GuiDriver_RegisterForSensor description]
Parameters
packetToReceive [description]
Definition at line 780 of file gui_driver.c.
References sensor_SetMinimumDelay().
Referenced by gui_motionControl_Init(), gui_weatherStation_Init(), heartRate_Init(), pedometer_Init(), and watch_Init().
void GuiDriver_UnregisterFromNavigation (guiNavigationDir_t navigations)
[GuiDriver_UnregisterFromNavigation description]
Parameters
navigationDir [description]
Definition at line 807 of file gui_driver.c.
Referenced by bluetooth_DestroyTasks(), bootloader_DestroyTasks(), buttonsGroup_DestroyTasks(), flashlight_DestroyTasks(), gui_heartRate_DestroyTasks(), gui_pedometer_DestroyTasks(), gui_sensorTag_DestroyTasks(), haptic_DestroyTasks(), info_DestroyTasks(), and reset_DestroyTasks().
void GuiDriver_UnregisterFromSensors (packet_t packetToReceive, bool shouldDeactivateTask)
[GuiDriver_UnregisterFromSensor description]
Parameters
packetToReceive [description]
Definition at line 798 of file gui_driver.c.
References sensor_GetPacketTargets(), and sensor_SetPacketTargets().
Referenced by gui_motionControl_DestroyTasks(), gui_weatherStation_DestroyTasks(), and watch_DestroyTasks().
void GuiDriver_UpdateScreen (uint8_t xCrd, uint8_t yCrd, uint8_t width, uint8_t height, const uint8_t * image)
update the main screen buffer with the given image
Definition at line 476 of file gui_driver.c.
References guiDisplay_t::image.
Referenced by OLED_AddImage(), and OLED_AddText().