HEXIWEAR MK64 Firmware Reference Manual: gui/screens/2. apps/2.3 fitness/2.3.2 gui_heartRate/src/gui_heartRate_driver.c File Reference
gui_heartRate_driver.c File Reference
this file contains heart-rate app GUI main task and functionality
#include "gui_heartRate.h"
#include "gui_heartRate_private.h"
#include "screens_common.h"
#include "fsl_os_abstraction.h"
#include "error.h"
#include "heartRate_driver.h"
Functions
MSG_QUEUE_DECLARE (gui_heartRate_queue, 1, sizeof(uint32_t))
void gui_heartRate_Init (void *param)
void gui_heartRate_CreateTasks (void *param)
void gui_heartRate_DestroyTasks (void *param)
gui_heartRate_status_t gui_heartRate_QueueMsgPut (uint32_t *packet)
Detailed Description
this file contains heart-rate app GUI main task and functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file gui_heartRate_driver.c.
Function Documentation
void gui_heartRate_CreateTasks (void * param)
create HR GUI tasks
Parameters
param optional parameter
Definition at line 116 of file gui_heartRate_driver.c.
References kStatus_OSA_Success, and OSA_TaskCreate().
void gui_heartRate_DestroyTasks (void * param)
destroy HR GUI tasks
Parameters
param optional parameter
Definition at line 154 of file gui_heartRate_driver.c.
References GUI_CURRENT_APP_IDLE, gui_sensorTag_IsActive(), GuiDriver_LabelDestroy(), GuiDriver_NotifyKW40(), GuiDriver_UnregisterFromNavigation(), heartRate_Deinit(), OLED_DestroyDynamicArea(), OSA_MsgQDestroy(), OSA_TaskDestroy(), and power_EnablePowerSave().
void gui_heartRate_Init (void * param)
initialize heart-rate GUI
Parameters
param optional parameter
Definition at line 80 of file gui_heartRate_driver.c.
References GUI_CURRENT_APP_HEART_RATE, GuiDriver_ImageAddToScr(), GuiDriver_LabelCreate(), GuiDriver_LabelSetCaption(), GuiDriver_NotifyKW40(), GuiDriver_RegisterForNavigation(), heartRate_Init(), and OSA_MsgQCreate().
gui_heartRate_status_t gui_heartRate_QueueMsgPut (uint32_t * packet)
put data into designated HR GUI queue
Parameters
packet data to display
Returns
status flag
Definition at line 187 of file gui_heartRate_driver.c.
References GuiDriver_CleanMainArea(), GuiDriver_ImageDraw(), GuiDriver_LabelDraw(), GuiDriver_QueueMsgGet(), heartRate_Pause(), heartRate_Resume(), kStatus_OSA_Error, OSA_MsgQGet(), OSA_WAIT_FOREVER, packetType_pressRight, power_DisablePowerSave(), and power_EnablePowerSave().
Referenced by heartRate_Process().
MSG_QUEUE_DECLARE (gui_heartRate_queue , 1 , sizeof(uint32_t))
private variables