HEXIWEAR MK64 Firmware Reference Manual: gui/screens/4. settings/4.4 haptic/inc/haptic.h File Reference
haptic.h File Reference
this file contains haptic feedback public objects
#include "gui_driver.h"
Functions
hapticState_t haptic_CurrentStateGet (void)
osa_status_t haptic_MutexCreate (void)
osa_status_t haptic_MutexLock (uint32_t timeout)
osa_status_t haptic_MutexUnlock (void)
void haptic_CheckAtStartup ()
Variables
guiScreen_t hapticScreen
Detailed Description
this file contains haptic feedback public objects
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file haptic.h.
Function Documentation
void haptic_CheckAtStartup ()
check if haptic feedback should be enabled at startup
Definition at line 196 of file haptic_driver.c.
References GuiDriver_ImageDraw(), GuiDriver_QueueMsgGet(), haptic_MutexLock(), haptic_MutexUnlock(), HEXIWEAR_SetFlags(), OSA_WAIT_FOREVER, and packetType_pressRight.
Referenced by HEXIWEAR_startup().
hapticState_t haptic_CurrentStateGet (void)
get current haptic feedback state
Returns
current state
Definition at line 188 of file haptic_driver.c.
Referenced by GuiDriver_Navigation().
osa_status_t haptic_MutexCreate (void)
create the mutex to ensure the exclusive right to haptic feedback
Returns
status flag
Definition at line 97 of file haptic_driver.c.
References OSA_MutexCreate().
Referenced by HEXIWEAR_startup().
osa_status_t haptic_MutexLock (uint32_t timeout)
take the haptic feedback mutex
Returns
status flag
Definition at line 106 of file haptic_driver.c.
References OSA_MutexLock().
Referenced by GuiDriver_Navigation(), haptic_CheckAtStartup(), and PORTC_IRQHandler().
osa_status_t haptic_MutexUnlock (void)
release the haptic feedback mutex
Returns
status flag
Definition at line 115 of file haptic_driver.c.
References OSA_MutexUnlock().
Referenced by GuiDriver_Navigation(), haptic_CheckAtStartup(), and PORTC_IRQHandler().
Variable Documentation
guiScreen_t hapticScreen
haptic screen structure
Definition at line 43 of file haptic_objects.c.