HEXIWEAR MK64 Firmware Reference Manual: gui/screens/4. settings/4.4 haptic/src/haptic_driver.c File Reference
haptic_driver.c File Reference
this file contains haptic feedback functionality
#include "gui_driver.h"
#include "screens_common.h"
#include "haptic_private.h"
#include "host_mcu_interface.h"
#include "fsl_os_abstraction.h"
Macros
#define MSEC_TO_TICK(msec)
Converts milliseconds to ticks.
Functions
osa_status_t haptic_MutexCreate ()
osa_status_t haptic_MutexLock (uint32_t timeout)
osa_status_t haptic_MutexUnlock ()
void haptic_Init (void *param)
void haptic_CreateTasks (void *param)
void haptic_DestroyTasks (void *param)
hapticState_t haptic_CurrentStateGet ()
void haptic_CheckAtStartup ()
Variables
task_handler_t haptic_StateToggleHandler
Detailed Description
this file contains haptic feedback functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file haptic_driver.c.
Macro Definition Documentation
#define MSEC_TO_TICK (msec)
Value:
(((uint32_t)(msec)+500uL/(uint32_t)configTICK_RATE_HZ) \
                             *(uint32_t)configTICK_RATE_HZ/1000uL)
Converts milliseconds to ticks.
includes private type definitions private macros
Definition at line 51 of file haptic_driver.c.
Function Documentation
void haptic_CheckAtStartup ()
check if haptic feedback should be enabled at startup
Definition at line 196 of file haptic_driver.c.
References GuiDriver_ImageDraw(), GuiDriver_QueueMsgGet(), haptic_MutexLock(), haptic_MutexUnlock(), HEXIWEAR_SetFlags(), OSA_WAIT_FOREVER, and packetType_pressRight.
Referenced by HEXIWEAR_startup().
void haptic_CreateTasks (void * param)
create the GUI task for toggling haptic feedback
Parameters
param optional parameter
Definition at line 144 of file haptic_driver.c.
References haptic_StateToggleHandler, kStatus_OSA_Success, and OSA_TaskCreate().
hapticState_t haptic_CurrentStateGet (void)
get current haptic feedback state
Returns
current state
Definition at line 188 of file haptic_driver.c.
Referenced by GuiDriver_Navigation().
void haptic_DestroyTasks (void * param)
destroy the GUI task for toggling haptic feedback
Parameters
param optional parameter
Definition at line 169 of file haptic_driver.c.
References GuiDriver_UnregisterFromNavigation(), haptic_StateToggleHandler, kStatus_OSA_Success, OLED_DestroyDynamicArea(), and OSA_TaskDestroy().
void haptic_Init (void * param)
initialize the haptic feedback screen
Parameters
param optional parameter
Definition at line 124 of file haptic_driver.c.
References GuiDriver_ImageAddToScr(), and GuiDriver_RegisterForNavigation().
osa_status_t haptic_MutexCreate (void)
create the mutex to ensure the exclusive right to haptic feedback
Returns
status flag
Definition at line 97 of file haptic_driver.c.
References OSA_MutexCreate().
Referenced by HEXIWEAR_startup().
osa_status_t haptic_MutexLock (uint32_t timeout)
take the haptic feedback mutex
Returns
status flag
Definition at line 106 of file haptic_driver.c.
References OSA_MutexLock().
Referenced by GuiDriver_Navigation(), haptic_CheckAtStartup(), and PORTC_IRQHandler().
osa_status_t haptic_MutexUnlock (void)
release the haptic feedback mutex
Returns
status flag
Definition at line 115 of file haptic_driver.c.
References OSA_MutexUnlock().
Referenced by GuiDriver_Navigation(), haptic_CheckAtStartup(), and PORTC_IRQHandler().
Variable Documentation
task_handler_t haptic_StateToggleHandler
public memory declarations
Definition at line 60 of file haptic_driver.c.
Referenced by haptic_CreateTasks(), and haptic_DestroyTasks().