HEXIWEAR MK64 Firmware Reference Manual: gui/screens/4. settings/4.7 reset/inc/reset.h File Reference
reset.h File Reference
this file contains HEXIWEAR Reset Screen objects
#include "gui_driver.h"
Functions
void reset_Init (void *param)
void reset_CreateTasks (void *param)
void reset_DestroyTasks (void *param)
Detailed Description
this file contains HEXIWEAR Reset Screen objects
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file reset.h.
Function Documentation
void reset_CreateTasks (void * param)
[reset_CreateTasks description]
Parameters
param [description]
Definition at line 70 of file reset_driver.c.
References kStatus_OSA_Success, and OSA_TaskCreate().
void reset_DestroyTasks (void * param)
[reset_DestroyTasks description]
Parameters
param [description]
Definition at line 94 of file reset_driver.c.
References GuiDriver_QueueMsgGet(), GuiDriver_UnregisterFromNavigation(), HEXIWEAR_ResetMCU(), kStatus_OSA_Success, OLED_DestroyDynamicArea(), OSA_TaskDestroy(), OSA_WAIT_FOREVER, and packetType_pressRight.
void reset_Init (void * param)
[reset_Init description]
Parameters
param [description]
Definition at line 61 of file reset_driver.c.
References GuiDriver_RegisterForNavigation().