HEXIWEAR MK64 Firmware Reference Manual: rtc/inc/rtc_driver.h File Reference
rtc_driver.h File Reference
this file contains RTC-related function wrappers and callbacks
#include "CLOCK.h"
#include "fsl_rtc_driver.h"
#include "rtc_types.h"
Functions
_rtc_status_t RTC_Init ()
_rtc_status_t RTC_SetAlarmInterval (uint32_t seconds)
uint32_t RTC_GetAlarmInterval ()
_rtc_status_t RTC_TriggerAlarm (rtc_datetime_t *currentTime, uint16_t duration)
_rtc_status_t RTC_GetAlarmTime (rtc_datetime_t *timeToReturn)
_rtc_status_t RTC_GetCurrentTime (rtc_datetime_t *timeToReturn)
_rtc_status_t RTC_UpdateCurrentTime (uint32_t timestamp)
void RTC_AlarmCallback ()
_rtc_status_t RTC_WatchUpdateEventWait (rtc_datetime_t *dateTime, bool *dateUpdateFlag, bool *timeUpdateFlag, uint32_t timeout)
_rtc_status_t RTC_AlarmEventWait (uint32_t timeout)
void RTC_UpdateAlarm ()
void RTC_DisableAlarm ()
void RTC_EnableAlarm ()
void RTC_SetSleepReloadValue (uint32_t interval)
uint32_t RTC_GetSleepReloadValue ()
Detailed Description
this file contains RTC-related function wrappers and callbacks
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP Semiconductor, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
support: http://www.mikroe.com/forum and https://community.freescale.com
Project HEXIWEAR, 2015
Definition in file rtc_driver.h.
Function Documentation
void RTC_AlarmCallback ()
interrupt callback
RTC interrupt handler callback
RTC also puts MCU to sleep
if we're in normal mode, proceed to go to sleep
in case of the shallow and total sleep mode, trigger the sleep task to finish the procedure
for the sensor tag sleep mode, announce that we're ready for sensor tag sleep mode
this shouldn't happen, if RTC is enabled, we shouldn't be sleeping
Definition at line 208 of file rtc_driver.c.
References OSA_EventSet(), POWER_CURRENT_MODE_SLEEP_SENSOR_TAG, POWER_CURRENT_MODE_SLEEP_SHALLOW, POWER_CURRENT_MODE_SLEEP_TOTAL, power_GetCurrentMode(), power_GetSleepMode(), power_GotoSleep(), power_SetCurrentMode(), power_SetSleepSource(), POWER_SLEEP_MODE_SENSOR_TAG, POWER_SLEEP_MODE_SHALLOW, POWER_SLEEP_MODE_TOTAL, RTC_DisableAlarm(), RTC_GetCurrentTime(), and RTC_TriggerAlarm().
Referenced by SPI2_IRQHandler().
_rtc_status_t RTC_AlarmEventWait (uint32_t timeout)
wait for the RTC event for updating date-time
Parameters
timeout timeout value in [ms]
Returns
status flag
Definition at line 327 of file rtc_driver.c.
References kStatus_OSA_Success, and OSA_EventWait().
void RTC_DisableAlarm ()
disable the RTC alarm
Definition at line 344 of file rtc_driver.c.
References FSL_CLOCK.
Referenced by power_DisablePowerSave(), and RTC_AlarmCallback().
void RTC_EnableAlarm ()
enable the RTC alarm
Definition at line 352 of file rtc_driver.c.
References FSL_CLOCK.
Referenced by power_EnablePowerSave(), and power_TurnOFF().
uint32_t RTC_GetAlarmInterval ()
get current RTC alarm interval
Returns
seconds interval in [s]
get the current alarm interval
Returns
status flag
Definition at line 130 of file rtc_driver.c.
_rtc_status_t RTC_GetAlarmTime (rtc_datetime_t * timeToReturn)
get the RTC alarm time
Returns
status flag
get the time alarm is scheduled for
Returns
status flag
Definition at line 169 of file rtc_driver.c.
References FSL_CLOCK.
_rtc_status_t RTC_GetCurrentTime (rtc_datetime_t * timeToReturn)
get the actual RTC time
Returns
status flag
get current RTC time
Returns
status flag
Definition at line 179 of file rtc_driver.c.
References FSL_CLOCK.
Referenced by RTC_AlarmCallback(), RTC_Init(), and watch_Init().
uint32_t RTC_GetSleepReloadValue ()
get the current RTC sleep counter value
Returns
counter value
Definition at line 371 of file rtc_driver.c.
_rtc_status_t RTC_Init ()
setup IRQ, set RTC datetime and trigger the initial alarm
Returns
status flag
initialize RTC module, set the time create the alarm event and set the next alarm occurrence
Returns
status flag
Definition at line 84 of file rtc_driver.c.
References FSL_CLOCK, HEXIWEAR_RTC_IRQ_PRIO, kEventAutoClear, kStatus_OSA_Success, NVIC_SetPriority(), OSA_EventCreate(), RTC_GetCurrentTime(), and RTC_TriggerAlarm().
Referenced by HEXIWEAR_startup().
_rtc_status_t RTC_SetAlarmInterval (uint32_t seconds)
set RTC alarm interval
Parameters
seconds interval in [s]
Returns
status flag
set the time interval alarm is triggered on
Parameters
seconds time interval in [s]
Returns
status flag
Definition at line 112 of file rtc_driver.c.
void RTC_SetSleepReloadValue (uint32_t interval)
set the new RTC counter for MCU sleep
Parameters
interval interval in [ms]
Definition at line 361 of file rtc_driver.c.
References RTC_UpdateAlarm().
_rtc_status_t RTC_TriggerAlarm (rtc_datetime_t * time, uint16_t duration)
set next RTC alarm occurence
Returns
status flag
wind the clock
Parameters
time current time
duration interval for the next alarm (default will be used is 0 is passed)
Returns
status flag
Definition at line 141 of file rtc_driver.c.
References foo, and FSL_CLOCK.
Referenced by RTC_AlarmCallback(), RTC_Init(), and RTC_UpdateCurrentTime().
void RTC_UpdateAlarm ()
update RTC counter's value to the default one
Definition at line 379 of file rtc_driver.c.
Referenced by PORTC_IRQHandler(), power_TurnOFF(), RTC_SetSleepReloadValue(), and watch_CheckBatteryStatus().
_rtc_status_t RTC_UpdateCurrentTime (uint32_t timestamp)
set new RTC date-time
Returns
status flag
update current RTC time
Returns
status flag
Definition at line 189 of file rtc_driver.c.
References FSL_CLOCK, OSA_EventSet(), and RTC_TriggerAlarm().
_rtc_status_t RTC_WatchUpdateEventWait (rtc_datetime_t * dateTime, bool * dateUpdateFlag, bool * timeUpdateFlag, uint32_t timeout)
set RTC event for updating date-time
Parameters
dateTime new date-time
dateUpdateFlag flag to update date
timeUpdateFlag flag to update time
timeout timeout in [ms]
Returns
status flag
Definition at line 295 of file rtc_driver.c.
References kStatus_OSA_Success, and OSA_EventWait().
Referenced by watch_DestroyTasks().