HEXIWEAR MK64 Firmware Reference Manual: Events.h File Reference
Events.h File Reference
various events' handlers should be placed here, such as interrupts' handlers, etc.
#include "fsl_device_registers.h"
#include "CLK_manager.h"
#include "DMA_controller.h"
#include "pin_mux.h"
#include "OLED_SPI.h"
#include "FLASH_SPI.h"
#include "GPIO.h"
#include "KW40_UART.h"
#include "DEBUG_UART.h"
#include "FS_I2C.h"
#include "NFS_I2C.h"
#include "PWR_Manager.h"
#include "HEXI_OS.h"
#include "free_rtos.h"
#include "CLOCK.h"
#include "BATTERY_ADC.h"
#include "sensor_timer.h"
#include "test_uart.h"
Functions
void LLWU_IRQHandler (void)
void I2C0_IRQHandler (void)
void I2C1_IRQHandler (void)
void SPI1_IRQHandler (void)
void SPI2_IRQHandler (void)
void RTC_Seconds_IRQHandler (void)
void ADC0_IRQHandler (void)
void PORTC_IRQHandler (void)
void PORTB_IRQHandler (void)
Detailed Description
various events' handlers should be placed here, such as interrupts' handlers, etc.
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file Events.h.
Function Documentation
void ADC0_IRQHandler (void)
BATTERY_ADC IRQ handler
Write your code here ...
Definition at line 103 of file Events.c.
References FSL_SENSOR_TIMER.
void I2C0_IRQHandler (void)
NFS_I2C IRQ handler
Definition at line 59 of file Events.c.
References FSL_NFS_I2C.
void I2C1_IRQHandler (void)
FS_I2C IRQ handler
Definition at line 65 of file Events.c.
References FSL_FS_I2C.
void LLWU_IRQHandler (void)
User includes (#include below this line is not maintained by Processor Expert)
Write your code here. For example clear LLWU wake up flags ...
Definition at line 53 of file Events.c.
void PORTB_IRQHandler (void)
Write your code here ...
Definition at line 187 of file Events.c.
void PORTC_IRQHandler (void)
special consideration is also required for the sensor tag sleep mode, since we might not be actually sleeping when UART interrupt occurs
Definition at line 113 of file Events.c.
References FXOS_IsTapEnabled(), GPIO_DRV_ClearPinOutput(), GPIO_DRV_SetPinOutput(), haptic_MutexLock(), haptic_MutexUnlock(), HostInterface_SetWakingTouch(), kStatus_OSA_Success, OSA_TimeDelay(), POWER_CURRENT_MODE_SLEEP_SENSOR_TAG, POWER_CURRENT_MODE_SLEEP_SHALLOW, POWER_CURRENT_MODE_SLEEP_TOTAL, power_GetCurrentMode(), power_SetCurrentMode(), power_SetWakeSource(), RTC_UpdateAlarm(), and watch_CheckBatteryStatus().
void RTC_Seconds_IRQHandler (void)
Write your code here ...
Definition at line 97 of file Events.c.
void SPI1_IRQHandler (void)
FLASH_SPI IRQ handler
Write your code here ...
Definition at line 71 of file Events.c.
References FSL_FLASH_SPI.
void SPI2_IRQHandler (void)
OLED_SPI IRQ handler
Write your code here ...
Definition at line 82 of file Events.c.
References FSL_OLED_SPI, and RTC_AlarmCallback().