HEXIWEAR MK64 Firmware Reference Manual: extern_flash/inc/FLASH_driver.h File Reference
FLASH_driver.h File Reference
this file contains external FLASH functionality
#include "FLASH_defs.h"
Functions
statusFLASH_t FLASH_Init (handleFLASH_t *self, settingsFLASH_t *settings)
statusFLASH_t FLASH_Deinit ()
statusFLASH_t FLASH_WriteData (const uint32_t flashAddress, const uint8_t *dataToSend, uint32_t dataSize)
statusFLASH_t FLASH_ReadStatus (uint8_t *flashStatus)
statusFLASH_t FLASH_ReadData (uint32_t flashAddress, uint8_t *dataToRead, uint32_t dataSize)
Detailed Description
this file contains external FLASH functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file FLASH_driver.h.
Function Documentation
statusFLASH_t FLASH_Deinit ()
deinitialize the protocol FLASH uses
Definition at line 295 of file FLASH_driver.c.
References SPI_Deinit(), STATUS_FLASH_PROTOCOL_ERROR, STATUS_FLASH_SUCCESS, and STATUS_SPI_SUCCESS.
statusFLASH_t FLASH_Init (handleFLASH_t * flashHandle, settingsFLASH_t * flashSettings)
initialize FLASH
inititalize intern FLASH structures, which will be used from now on
set IRQ priority
set pins
Definition at line 248 of file FLASH_driver.c.
References GPIO_DRV_SetPinOutput(), HEXIWEAR_FLASH_SPI_IRQ_PRIO, NVIC_SetPriority(), SPI_Init(), STATUS_FLASH_PROTOCOL_ERROR, STATUS_FLASH_SUCCESS, and STATUS_SPI_SUCCESS.
Referenced by HEXIWEAR_startup().
statusFLASH_t FLASH_ReadData (uint32_t flashAddress, uint8_t * dataToRead, uint32_t dataSize)
read data from FLASH
Definition at line 527 of file FLASH_driver.c.
References FLASH_CMD_CNT, GPIO_DRV_ClearPinOutput(), GPIO_DRV_SetPinOutput(), STATUS_FLASH_PROTOCOL_ERROR, and STATUS_FLASH_SUCCESS.
statusFLASH_t FLASH_ReadStatus (uint8_t * flashStatus)
read FLASH status register
Definition at line 400 of file FLASH_driver.c.
References FLASH_CMD_CNT, GPIO_DRV_SetPinOutput(), STATUS_FLASH_PROTOCOL_ERROR, and STATUS_FLASH_SUCCESS.
statusFLASH_t FLASH_WriteData (const uint32_t flashAddress, const uint8_t * dataToSend, uint32_t dataSize)
write data to FLASH
write data
send data
mark the end of sending data as soon as CS is driven HIGH, the self-timed WRITE STATUS REGISTER cycle is initiated
while the WRITE STATUS REGISTER cycle is in progress, the status register may still be read to check the value of the WIP bit the WIP bit is 1 during the self-timed WRITE STATUS REGISTER cycle, and is 0 when the cycle is completed
when the cycle is completed, the WEL bit is reset
Definition at line 315 of file FLASH_driver.c.
References FLASH_CMD_CNT, GPIO_DRV_ClearPinOutput(), GPIO_DRV_SetPinOutput(), STATUS_FLASH_ERROR, and STATUS_FLASH_SUCCESS.