HEXIWEAR MK64 Firmware Reference Manual: sensors/FXAS/inc/FXAS_driver.h File Reference
FXAS_driver.h File Reference
this file contains sensor FXAS21002's functionality
#include "FXAS_types.h"
Functions
fxas_status_t FXAS_Init (handleFXAS_t *self, const settingsFXAS_t *settings)
fxas_status_t FXAS_Deinit ()
fxas_status_t FXAS_ReadRawData (int16_t *sensorData)
fxas_status_t FXAS_GotoStandby ()
fxas_status_t FXAS_GetReady ()
fxas_status_t FXAS_SetActive ()
void FXAS_SoftReset ()
void gyro_fmtDef2Float (const void *src, void *dst, uint32_t idx)
void gyro_fmtDef2Me (const void *src, void *dst, uint32_t idx)
void gyro_fmtDef2Byte (const void *src, void *dst, uint32_t idx)
Detailed Description
this file contains sensor FXAS21002's functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file FXAS_driver.h.
Function Documentation
fxas_status_t FXAS_Deinit ()
turn off the sensor
Returns
sensor's status
Definition at line 152 of file FXAS_driver.c.
References I2C_Deinit(), and STATUS_I2C_SUCCESS.
fxas_status_t FXAS_GetReady ()
set the FXAS21000 to Ready mode it's necessary to be in this mode to output data
Returns
status flag
clear bits 0 and 1; standby mode
and then set bit 0 to 1; ready mode, no data acquisition yet
Definition at line 294 of file FXAS_driver.c.
References I2C_ReadReg(), I2C_WriteReg(), and STATUS_I2C_SUCCESS.
fxas_status_t FXAS_GotoStandby ()
put the FXAS21002C into standby mode standby mode is necessary before attempting to modify most of the registers
Returns
status flag
Definition at line 227 of file FXAS_driver.c.
References I2C_ReadReg(), I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by FXAS_Init(), and sensor_InitAcc().
fxas_status_t FXAS_Init (handleFXAS_t * fxasHandle, const settingsFXAS_t * fxasSettings)
initialize the sensor
Parameters
fxasHandle handle to be populated with sensor info
fxasSettings user settings
Returns
status flag
initialize intern structures, which will be used from now on
put the sensor in the standby mode to change registers
set up the scale range in [dps] (degrees per second)
setup the data rate bits [4:2]
disable FIFO, route FIFO and rate threshold interrupts to INT2, enable data ready interrupt, route to INT1
active HIGH, push-pull output driver on interrupts
set up rate threshold detection; at max rate threshold = FSR; rate threshold = THS*FSR/128
enable rate threshold detection on all axes
unsigned 7-bit THS, set to one-tenth FSR; set clearing debounce counter
set to 4 (can set up to 255)
set the sensor to active mode
Definition at line 85 of file FXAS_driver.c.
References FXAS_GotoStandby(), FXAS_SetActive(), I2C_Init(), I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by sensor_InitAcc().
fxas_status_t FXAS_ReadRawData (int16_t * sensorData)
read raw data from the sensor
Parameters
sensorData pointer where to save sensor's data
Returns
status flag
gyro data: 16-bit 2's complement data
get gyro data
Definition at line 174 of file FXAS_driver.c.
References I2C_DRV_MasterReceiveDataBlocking(), and kStatus_I2C_Success.
Referenced by sensor_Init().
fxas_status_t FXAS_SetActive ()
put the FXAS21002C into active mode it's necessary to be in this mode to output data
Returns
status flag
clear bits 0 and 1; standby mode
set bit 1 to 1; active mode, data acquisition enabled
Definition at line 259 of file FXAS_driver.c.
References I2C_ReadReg(), I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by FXAS_Init(), and sensor_InitAcc().
void FXAS_SoftReset ()
reset the module
set reset bit to 1 to assert software reset to zero at end of boot process
wait for boot end flag to be set
Definition at line 324 of file FXAS_driver.c.
References foo, I2C_ReadReg(), I2C_WriteReg(), OSA_TimeDelay(), and STATUS_I2C_SUCCESS.
Referenced by sensor_Init().
void gyro_fmtDef2Byte (const void * src, void * dst, uint32_t idx)
format raw to byte - currently unimplemented
Definition at line 417 of file FXAS_driver.c.
void gyro_fmtDef2Float (const void * src, void * dst, uint32_t idx)
format data from raw to float
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
formatting functions format data from raw to float
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
convert data
Definition at line 376 of file FXAS_driver.c.
void gyro_fmtDef2Me (const void * src, void * dst, uint32_t idx)
format data from raw to mE format
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
convert data
Definition at line 398 of file FXAS_driver.c.