HEXIWEAR MK64 Firmware Reference Manual: sensors/FXOS/inc/FXOS_driver.h File Reference
FXOS_driver.h File Reference
this file contains sensor FXOS8700cq implemented functionality
#include "FXOS_types.h"
#include "FXOS_defs.h"
#include "sensor_types.h"
Functions
fxos_status_t FXOS_Init (handleFXOS_t *self, const settingsFXOS_t *settings)
fxos_status_t FXOS_Deinit ()
fxos_status_t FXOS_ReadRawData (int16_t *sensorData)
fxos_status_t FXOS_CalibrateAcc ()
fxos_status_t FXOS_CalibrateMag ()
void acc_fmtDef2Float (const void *src, void *dst, uint32_t idx)
void acc_fmtDef2Me (const void *src, void *dst, uint32_t idx)
void mag_fmtDef2Float (const void *src, void *dst, uint32_t idx)
void mag_fmtDef2Me (const void *src, void *dst, uint32_t idx)
void mag_fmtDef2Byte (const void *src, void *dst, uint32_t idx)
void acc_fmtDef2Byte (const void *src, void *dst, uint32_t idx)
void acc_fmtMe2Def (const void *src, void *dst)
fxos_status_t FXOS_GotoStandby ()
fxos_status_t FXOS_SetActive ()
fxos_status_t FXOS_SoftReset ()
fxos_status_t FXOS_ReadRawTemp (uint8_t *tempVal)
fxos_status_t FXOS_ConfigureTapEvent ()
fxos_status_t FXOS_EnableTap ()
fxos_status_t FXOS_DisableTap ()
bool FXOS_IsTapEnabled ()
fxos_status_t FXOS_Callback ()
void FXOS_TapHandler ()
fxos_status_t FXOS_RecoverI2C ()
fxos_status_t FXOS_ReadStatus (uint8_t *sensorStatus)
bool FXOS_CheckForTap ()
Detailed Description
this file contains sensor FXOS8700cq implemented functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file FXOS_driver.h.
Function Documentation
void acc_fmtDef2Byte (const void * src, void * dst, uint32_t idx)
format raw to byte - currently unimplemented
Definition at line 551 of file FXOS_driver.c.
void acc_fmtDef2Float (const void * src, void * dst, uint32_t idx)
formatting pointers format raw to float
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
formatting functions format raw to float
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
Definition at line 504 of file FXOS_driver.c.
void acc_fmtDef2Me (const void * src, void * dst, uint32_t idx)
format raw to mE format
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
Definition at line 529 of file FXOS_driver.c.
void acc_fmtMe2Def (const void * src, void * dst)
format mE to raw format
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
Definition at line 558 of file FXOS_driver.c.
Referenced by pedometer_GetCalories().
fxos_status_t FXOS_CalibrateAcc ()
accelerometer offset calibration
Definition at line 286 of file FXOS_driver.c.
References FXOS_CTRL_REG1, FXOS_OFF_X_REG, I2C_DRV_MasterReceiveDataBlocking(), I2C_ModifyReg(), I2C_WriteReg(), kStatus_I2C_Success, and STATUS_I2C_SUCCESS.
fxos_status_t FXOS_CalibrateMag ()
magnetometer offset calibration
compute the average
Left-shift by one as magnetometer offset registers are left justified 15-bit
Definition at line 363 of file FXOS_driver.c.
References FXOS_CTRL_REG1, I2C_DRV_MasterReceiveDataBlocking(), I2C_ModifyReg(), I2C_WriteReg(), kStatus_I2C_Success, M_OFF_X_MSB_REG, M_OUT_X_MSB_REG, OSA_TimeDelay(), and STATUS_I2C_SUCCESS.
fxos_status_t FXOS_Callback ()
callback for the interrupt
Returns
status flag
Definition at line 953 of file FXOS_driver.c.
References I2C_ReadReg(), and STATUS_I2C_SUCCESS.
bool FXOS_CheckForTap ()
check if tap is enabled
Returns
status flag
Definition at line 871 of file FXOS_driver.c.
References PULSE_CFG_REG.
Referenced by sensor_Init().
fxos_status_t FXOS_ConfigureTapEvent ()
[FXOS_ConfigureTapEvent description]
Returns
[description]
set the threshold - minimum required acceleration to cause a tap. write the value as a current sensitivity multiplier to get the desired value in [g] current z-threshold is set at 0.25g
set the time limit - the maximum time that a tap can be above the threshold 2.55s time limit at 100Hz odr, this is very dependent on data rate, see the app note
set the pulse latency - the minimum required time between one pulse and the next 5.1s 100Hz odr between taps min, this also depends on the data rate
Definition at line 814 of file FXOS_driver.c.
References FXOS_CTRL_REG5, FXOS_EnableTap(), HP_FILTER_CUTOFF_REG, I2C_WriteReg(), PULSE_CFG_REG, PULSE_LTCY_REG, PULSE_TMLT_REG, and STATUS_I2C_SUCCESS.
Referenced by FXOS_Init().
fxos_status_t FXOS_Deinit ()
Deinit the fxos8700 codec. Mainly used to close the I2C controller
Parameters
handler fxos8700 handler structure pointer
turn off the sensor
Returns
[description]
Definition at line 208 of file FXOS_driver.c.
References I2C_Deinit(), and STATUS_I2C_SUCCESS.
fxos_status_t FXOS_DisableTap ()
disable tap detection
Definition at line 917 of file FXOS_driver.c.
References FXOS_CTRL_REG4, FXOS_GotoStandby(), FXOS_SetActive(), I2C_ReadReg(), I2C_WriteReg(), and PULSE_SRC_REG.
fxos_status_t FXOS_EnableTap ()
enable tap detection
Definition at line 899 of file FXOS_driver.c.
References FXOS_CTRL_REG4, FXOS_GotoStandby(), FXOS_SetActive(), and I2C_WriteReg().
Referenced by FXOS_ConfigureTapEvent().
fxos_status_t FXOS_GotoStandby ()
[FXOS_Sleep description]
Returns
[description]
Definition at line 713 of file FXOS_driver.c.
References FXOS_CTRL_REG1, I2C_ModifyReg(), and STATUS_I2C_SUCCESS.
Referenced by FXOS_DisableTap(), FXOS_EnableTap(), and FXOS_Init().
fxos_status_t FXOS_Init (handleFXOS_t * fxosHandle, const settingsFXOS_t * fxosSettings)
If the fxos_Config is NULL, it would initialize fxos8700 using default settings The default setting: fxos_Config->odr = kFxosODR1, fxos_Config->osr = kFxosOSR7, fxos_Config->hms = kFxosBoth, fxos_Config->range = kFxos4gMode,
Parameters
handler fxos8700 handler structure
fxos_Config fxos8700 configuration structure
intern functions visible functions initialize the FXOS8700
Parameters
self [description]
settings [description]
Returns
[description]
initialize intern structures, which will be used from now on
wait a bit
go to standby
Definition at line 124 of file FXOS_driver.c.
References FXOS_ConfigureTapEvent(), FXOS_CTRL_REG1, FXOS_GotoStandby(), FXOS_M_CTRL_REG1, FXOS_M_CTRL_REG2, FXOS_SetActive(), I2C_Init(), I2C_ModifyReg(), I2C_WriteReg(), STATUS_I2C_SUCCESS, and XYZ_DATA_CFG_REG.
Referenced by sensor_InitAcc().
bool FXOS_IsTapEnabled ()
check if tap is enabled
Definition at line 944 of file FXOS_driver.c.
Referenced by PORTC_IRQHandler().
fxos_status_t FXOS_ReadRawData (int16_t * sensorData)
read sensor data from FXOS using I2C
Parameters
handler FXOS8700 handler structure
val Sensor data read from FXOS
read raw sensor data Description : Read sensor data value from FXOS8700 The reading process is through I2C
acc-data is 14-bit left-justified 2's complement data mag-data is 16-bit 2's complement data
Definition at line 230 of file FXOS_driver.c.
References I2C_DRV_MasterReceiveDataBlocking(), and kStatus_I2C_Success.
Referenced by sensor_Init().
fxos_status_t FXOS_ReadRawTemp (uint8_t * tempVal)
[FXOS_ReadTemp description]
Returns
[description]
Definition at line 794 of file FXOS_driver.c.
References I2C_ReadReg(), STATUS_I2C_SUCCESS, and TEMP_REG.
fxos_status_t FXOS_ReadStatus (uint8_t * sensorStatus)
read FXOS status register
Parameters
sensorStatus variable tu put the status register value in
Returns
reading status flag
Definition at line 1021 of file FXOS_driver.c.
Referenced by sensor_Init().
fxos_status_t FXOS_RecoverI2C ()
check if I2C bus needs to be recovered
Returns
status flag
Definition at line 1000 of file FXOS_driver.c.
References I2C_Recover(), and STATUS_I2C_SUCCESS.
Referenced by sensor_Init().
fxos_status_t FXOS_SetActive ()
[FXOS_Wake description]
Returns
[description]
Definition at line 755 of file FXOS_driver.c.
References FXOS_CTRL_REG1, I2C_ModifyReg(), and STATUS_I2C_SUCCESS.
Referenced by FXOS_DisableTap(), FXOS_EnableTap(), and FXOS_Init().
fxos_status_t FXOS_SoftReset ()
reset the module
Definition at line 775 of file FXOS_driver.c.
References FXOS_CTRL_REG2, I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by sensor_Init().
void FXOS_TapHandler ()
read the status of the tap source register
Definition at line 979 of file FXOS_driver.c.
References I2C_ReadReg(), PULSE_SRC_REG, and STATUS_I2C_SUCCESS.
void mag_fmtDef2Byte (const void * src, void * dst, uint32_t idx)
format raw to byte - currently unimplemented
Definition at line 630 of file FXOS_driver.c.
References I2C_DRV_MasterReceiveDataBlocking(), I2C_DRV_MasterSendDataBlocking(), and kStatus_I2C_Success.
void mag_fmtDef2Float (const void * src, void * dst, uint32_t idx)
format raw to float
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
Definition at line 583 of file FXOS_driver.c.
void mag_fmtDef2Me (const void * src, void * dst, uint32_t idx)
format raw to mE format
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
Definition at line 608 of file FXOS_driver.c.