HEXIWEAR MK64 Firmware Reference Manual: sensors/MPL/src/MPL_driver.c File Reference
MPL_driver.c File Reference
this file contains sensor MPL3115A2's implemented functionality
#include "MPL_driver.h"
#include "fsl_i2c_master_driver.h"
#include "generic_i2c_driver.h"
#include "FS_I2C.h"
#include "sensor_types.h"
#include "HEXIWEAR_types.h"
#include "string.h"
#include "error.h"
Functions
mpl_status_t MPL_Init (handleMPL_t *mplHandle, const settingsMPL_t *mplSettings)
mpl_status_t MPL_Deinit ()
mpl_status_t MPL_SoftReset ()
mpl_status_t MPL_ToggleOneShot ()
mpl_status_t MPL_SetMode (modeMPL_t mode)
mpl_status_t MPL_GotoStandby ()
mpl_status_t MPL_SetActive ()
mpl_status_t MPL_SetOversampleRate (uint8_t sampleRate)
mpl_status_t MPL_EnableEventFlags ()
mpl_status_t MPL_ReadRawData (modeMPL_t mode, int16_t *sensorData)
void pres_fmtDef2Float (const void *src, void *dst, uint32_t idx)
void pres_fmtDef2Me (const void *src, void *dst, uint32_t idx)
void pres_fmtDef2Byte (const void *src, void *dst, uint32_t idx)
Detailed Description
this file contains sensor MPL3115A2's implemented functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file MPL_driver.c.
Function Documentation
mpl_status_t MPL_Deinit ()
shutdown the sensor
Definition at line 144 of file MPL_driver.c.
References I2C_Deinit(), and STATUS_I2C_SUCCESS.
mpl_status_t MPL_EnableEventFlags ()
enables the pressure and temp measurement event flags so that we can test against them this is recommended in datasheet during setup
Definition at line 452 of file MPL_driver.c.
References I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by MPL_Init().
mpl_status_t MPL_GotoStandby ()
put the sensor in stand-by mode this is needed so that we can modify major control registers
Definition at line 330 of file MPL_driver.c.
References I2C_ReadReg(), I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by MPL_Init(), MPL_ReadRawData(), and sensor_InitAcc().
mpl_status_t MPL_Init (handleMPL_t * mplHandle, const settingsMPL_t * mplSettings)
intern functions visible functions initialize underlying protocol and other stuff
initialize intern structures, which will be used from now on
Definition at line 87 of file MPL_driver.c.
References I2C_Init(), MPL_EnableEventFlags(), MPL_GotoStandby(), MPL_SetActive(), MPL_SetMode(), MPL_SetOversampleRate(), and STATUS_I2C_SUCCESS.
Referenced by sensor_InitAcc().
mpl_status_t MPL_ReadRawData (modeMPL_t mode, int16_t * sensorData)
read sensor raw data
set the new working mode, if given one
prepare for reading data
read sensor data
save data
Definition at line 475 of file MPL_driver.c.
References foo, I2C_DRV_MasterReceiveDataBlocking(), I2C_ReadReg(), kStatus_I2C_Success, MPL_GotoStandby(), MPL_SetActive(), MPL_SetMode(), MPL_ToggleOneShot(), and STATUS_I2C_SUCCESS.
Referenced by sensor_Init().
mpl_status_t MPL_SetActive ()
put the sensor in active mode
Definition at line 366 of file MPL_driver.c.
References I2C_ReadReg(), I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by MPL_Init(), MPL_ReadRawData(), and sensor_InitAcc().
mpl_status_t MPL_SetMode (modeMPL_t mode)
set the device to be barometer or altimeter
Parameters
mode 1 - barometer 0 - altimeter
Definition at line 286 of file MPL_driver.c.
References I2C_ReadReg(), I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by MPL_Init(), and MPL_ReadRawData().
mpl_status_t MPL_SetOversampleRate (uint8_t sampleRate)
set the over-sample rate datasheet calls for 128, but you can set it from 1 to 128 samples The higher the oversample rate, the greater the time between data samples
Definition at line 403 of file MPL_driver.c.
References I2C_ReadReg(), I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by MPL_Init().
mpl_status_t MPL_SoftReset ()
software reset the reset mechanism can be enabled in standby and active mode when this bit is enabled, the reset mechanism resets all functional block registers and loads the respective internal registers with default values if the system was already in standby mode, the reboot process will immediately begin; else if the system was in active mode, the boot mechanism will automatically transition the system from active mode to standby mode, and only then can the reboot process begin
Definition at line 170 of file MPL_driver.c.
References I2C_DRV_MasterSendDataBlocking(), I2C_ReadReg(), kStatus_I2C_Success, OSA_WAIT_FOREVER, and STATUS_I2C_SUCCESS.
Referenced by sensor_Init().
mpl_status_t MPL_ToggleOneShot ()
clears then sets the OST bit which causes the sensor to immediately take another reading, necessary to sample faster than 1Hz
Definition at line 248 of file MPL_driver.c.
References I2C_ReadReg(), I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by MPL_ReadRawData().
void pres_fmtDef2Byte (const void * src, void * dst, uint32_t idx)
format raw to byte - currently unimplemented
Definition at line 734 of file MPL_driver.c.
void pres_fmtDef2Float (const void * src, void * dst, uint32_t idx)
formatting functions format raw to float
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
Definition at line 689 of file MPL_driver.c.
void pres_fmtDef2Me (const void * src, void * dst, uint32_t idx)
format raw to mE format
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
Definition at line 713 of file MPL_driver.c.