HEXIWEAR MK64 Firmware Reference Manual: sensors/TSL/inc/TSL_driver.h File Reference
TSL_driver.h File Reference
this file contains sensor TSL2561's implemented functionality
#include "TSL_types.h"
Functions
tsl_status_t TSL_Init (handleTSL_t *self, const settingsTSL_t *settings)
tsl_status_t TSL_Deinit ()
void TSL_Enable ()
void TSL_Disable ()
tsl_status_t TSL_SetGain (gainTSL_t gain)
tsl_status_t TSL_SetTiming (integrationTSL_t integration)
tsl_status_t TSL_ReadRawData (channelTSL_t channel, uint16_t *sensorData)
tsl_status_t TSL_CalculateLux (uint16_t *channelValues, uint32_t *luxVal)
void ambi_fmtDef2Float (const void *src, void *dst, uint32_t idx)
void ambi_fmtDef2Me (const void *src, void *dst, uint32_t idx)
void ambi_fmtDef2Byte (const void *src, void *dst, uint32_t idx)
void TSL_FormatLux (uint32_t luxVal, uint8_t *ambLight)
Detailed Description
this file contains sensor TSL2561's implemented functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file TSL_driver.h.
Function Documentation
void ambi_fmtDef2Byte (const void * src, void * dst, uint32_t idx)
format raw to byte format
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
Definition at line 489 of file TSL_driver.c.
void ambi_fmtDef2Float (const void * src, void * dst, uint32_t idx)
formatting functions format raw to float
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
helper pointers
Definition at line 454 of file TSL_driver.c.
void ambi_fmtDef2Me (const void * src, void * dst, uint32_t idx)
format raw to mE format - currently unimplemented
format raw to mE format - currently unimplemented
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
Definition at line 476 of file TSL_driver.c.
tsl_status_t TSL_CalculateLux (uint16_t * channelValues, uint32_t * luxVal)
calculate luminance
simplified lux calculation
Parameters
channelValues ADC values from both channels
luxVal value in [lx]
Returns
status flag
find the ratio of the channel values (Channel1/Channel0) protect against divide by zero
Definition at line 311 of file TSL_driver.c.
References foo.
Referenced by sensor_Init().
tsl_status_t TSL_Deinit ()
shut down the sensor
deinit I2C for the sensor
Returns
status flag
Definition at line 155 of file TSL_driver.c.
References I2C_Deinit(), STATUS_I2C_SUCCESS, and TSL_Disable().
void TSL_Disable ()
disable the sensor
Definition at line 86 of file TSL_driver.c.
References I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by TSL_Deinit(), and TSL_Init().
void TSL_Enable ()
enable the sensor
intern functions public API enable the sensor
Definition at line 72 of file TSL_driver.c.
References I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by TSL_Init().
void TSL_FormatLux (uint32_t luxVal, uint8_t * ambLight)
[TSL_FormatLux description]
Parameters
luxVal [description]
ambLight [description]
convert lux value to light percentage
Parameters
luxVal value in [lx]
ambLight value in [%]
Definition at line 510 of file TSL_driver.c.
Referenced by sensor_Init().
tsl_status_t TSL_Init (handleTSL_t * tslHandle, const settingsTSL_t * tslSettings)
initialize the sensor
Parameters
tslHandle handle to be populated with sensor info
tslSettings user settings
Returns
status flag
initialize the intern structures, which will be used from now on
Definition at line 103 of file TSL_driver.c.
References I2C_Init(), STATUS_I2C_SUCCESS, TSL_Disable(), TSL_Enable(), TSL_SetGain(), and TSL_SetTiming().
Referenced by sensor_InitAcc().
tsl_status_t TSL_ReadRawData (channelTSL_t channel, uint16_t * sensorData)
read raw sensor data
Parameters
channel TSL channel (red or infrared)
sensorData sensor data to be filled
Returns
status flag
Definition at line 225 of file TSL_driver.c.
References I2C_ReadReg(), and STATUS_I2C_SUCCESS.
Referenced by sensor_Init().
tsl_status_t TSL_SetGain (gainTSL_t gain)
set sensor gain
Parameters
gain [description]
Returns
status flag
set sensor's gain
Parameters
gain desired gain
Returns
status flag
Definition at line 178 of file TSL_driver.c.
References I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by TSL_Init().
tsl_status_t TSL_SetTiming (integrationTSL_t integration)
set sensor integration time
Parameters
integration integration time
Returns
status flag
Definition at line 201 of file TSL_driver.c.
References I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by TSL_Init().