HEXIWEAR MK64 Firmware Reference Manual: gui/screens/4. settings/4.1 bluetooth/inc/bluetooth_private.h File Reference
bluetooth_private.h File Reference
this file contains bluetooth GUI related private objects
#include "gui_driver.h"
Functions
void bluetooth_Init (void *param)
void bluetooth_CreateTasks (void *param)
void bluetooth_DestroyTasks (void *param)
Detailed Description
this file contains bluetooth GUI related private objects
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file bluetooth_private.h.
Function Documentation
void bluetooth_CreateTasks (void * param)
create bluetooth GUI tasks
Parameters
param optional parameter
Definition at line 115 of file bluetooth_driver.c.
References bluetooth_AdvModeToggleHandler, kStatus_OSA_Success, and OSA_TaskCreate().
void bluetooth_DestroyTasks (void * param)
destroy bluetooth GUI tasks
Parameters
param optional parameter
Definition at line 158 of file bluetooth_driver.c.
References bluetooth_AdvModeToggleHandler, GuiDriver_UnregisterFromNavigation(), kStatus_OSA_Success, OLED_DestroyDynamicArea(), and OSA_TaskDestroy().
void bluetooth_Init (void * param)
initialize bluetooth GUI
Parameters
param optional parameter
Definition at line 94 of file bluetooth_driver.c.
References GuiDriver_ImageAddToScr(), and GuiDriver_RegisterForNavigation().