HEXIWEAR MK64 Firmware Reference Manual: gui/screens/4. settings/4.2 bootloader/inc/bootloader.h File Reference
bootloader.h File Reference
this file contains bootloader related constants, prototypes and objects
#include "fsl_os_abstraction.h"
#include "gui_driver.h"
#include "HEXIWEAR_driver.h"
Functions
void bootloader_Init (task_param_t param)
void bootloader_CreateTasks (task_param_t param)
void bootloader_DestroyTasks (task_param_t param)
bootloader_status_t boootloader_QueueMsgPut (hostInterface_packet_t *packet)
Detailed Description
this file contains bootloader related constants, prototypes and objects
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file bootloader.h.
Function Documentation
bootloader_status_t boootloader_QueueMsgPut (hostInterface_packet_t * packet)
put the packet into the designated bootloader's queue
Parameters
packet data to put
Returns
status flag
Definition at line 149 of file bootloader_driver.c.
References OSA_WAIT_FOREVER.
void bootloader_CreateTasks (void * param)
create the bootloader app task
Parameters
param [description]
Definition at line 178 of file bootloader_driver.c.
References kStatus_OSA_Success, and OSA_TaskCreate().
void bootloader_DestroyTasks (void * param)
destroy the bootloader app task, queue and unregister from listening to touch buttons
Definition at line 202 of file bootloader_driver.c.
References bootloader_labelLoad, bootloader_selectMK64, GuiDriver_CleanMainArea(), GuiDriver_DrawButtonPointers(), GuiDriver_ImageDraw(), GuiDriver_LabelDestroy(), GuiDriver_QueueMsgGet(), GuiDriver_RegisterForNavigation(), GuiDriver_UnregisterFromNavigation(), HEXIWEAR_ResetMCU(), HostInterface_TxQueueMsgPut(), INTFLASH_EraseSector(), INTFLASH_Program(), kStatus_OSA_Success, OLED_DestroyDynamicArea(), OLED_DrawBox(), OSA_MsgQDestroy(), OSA_MsgQGet(), OSA_TaskDestroy(), OSA_TimeDelay(), OSA_WAIT_FOREVER, packetType_pressDown, packetType_pressRight, packetType_pressUp, power_DisablePowerSave(), and power_EnablePowerSave().
void bootloader_Init (void * param)
public API initialize the bootloader app
Parameters
param [description]
insert default screen, which will be updated upon user's input
Definition at line 93 of file bootloader_driver.c.
References bluetooth_CurrentAdvModeGet(), bootloader_labelLoad, GuiDriver_ImageAddToScr(), GuiDriver_LabelCreate(), GuiDriver_RegisterForNavigation(), and OSA_MsgQCreate().