HEXIWEAR MK64 Firmware Reference Manual: gui/screens/4. settings/4.3 buttons group/inc/buttons_group_private.h File Reference
buttons_group_private.h File Reference
this file contains button group private objects' declarations
#include "gui_driver.h"
Functions
void buttonsGroup_Init (void *param)
void buttonsGroup_CreateTasks (void *param)
void buttonsGroup_DestroyTasks (void *param)
Detailed Description
this file contains button group private objects' declarations
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file buttons_group_private.h.
Function Documentation
void buttonsGroup_CreateTasks (void * param)
create the button group GUI task
Parameters
param optional parameter
Definition at line 121 of file buttons_group_driver.c.
References buttonsGroup_handler, kStatus_OSA_Success, and OSA_TaskCreate().
void buttonsGroup_DestroyTasks (void * param)
destroy the button group GUI task
Parameters
param optional parameter
Definition at line 163 of file buttons_group_driver.c.
References buttonsGroup_handler, GuiDriver_UnregisterFromNavigation(), kStatus_OSA_Success, OLED_DestroyDynamicArea(), OSA_MsgQDestroy(), and OSA_TaskDestroy().
void buttonsGroup_Init (void * param)
initialize the button group screen
Parameters
param optional parameter
Definition at line 97 of file buttons_group_driver.c.
References GuiDriver_ImageAddToScr(), GuiDriver_RegisterForNavigation(), and OSA_MsgQCreate().