HEXIWEAR MK64 Firmware Reference Manual: Complex Magnitude
Complex Magnitude
Complex Math Functions
Functions
void arm_cmplx_mag_f32 (float32_t *pSrc, float32_t *pDst, uint32_t numSamples)
Floating-point complex magnitude.
void arm_cmplx_mag_q15 (q15_t *pSrc, q15_t *pDst, uint32_t numSamples)
Q15 complex magnitude.
void arm_cmplx_mag_q31 (q31_t *pSrc, q31_t *pDst, uint32_t numSamples)
Q31 complex magnitude.
Detailed Description
Computes the magnitude of the elements of a complex data vector.
The pSrc points to the source data and pDst points to the where the result should be written. numSamples specifies the number of complex samples in the input array and the data is stored in an interleaved fashion (real, imag, real, imag, ...). The input array has a total of 2*numSamples values; the output array has a total of numSamples values. The underlying algorithm is used:
for(n=0; n<numSamples; n++) {
    pDst[n] = sqrt(pSrc[(2*n)+0]^2 + pSrc[(2*n)+1]^2);
}
There are separate functions for floating-point, Q15, and Q31 data types.
Function Documentation
void arm_cmplx_mag_f32 (float32_t * pSrc, float32_t * pDst, uint32_t numSamples)
Floating-point complex magnitude.
Parameters
[in] *pSrc points to complex input buffer
[out] *pDst points to real output buffer
[in] numSamples number of complex samples in the input vector
Returns
none.
Temporary variables to hold input values
Run the below code for Cortex-M4 and Cortex-M3
loop counter
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C[0] = sqrt(A[0] * A[0] + A[1] * A[1])
store the result in the destination buffer.
Decrement the loop counter
If the numSamples is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C[0] = sqrt(A[0] * A[0] + A[1] * A[1])
store the result in the destination buffer.
Decrement the loop counter
Definition at line 84 of file arm_cmplx_mag_f32.c.
Referenced by heartRate_Process().
void arm_cmplx_mag_q15 (q15_t * pSrc, q15_t * pDst, uint32_t numSamples)
Q15 complex magnitude.
Parameters
*pSrc points to the complex input vector
*pDst points to the real output vector
numSamples number of complex samples in the input vector
Returns
none.
Scaling and Overflow Behavior:
The function implements 1.15 by 1.15 multiplications and finally output is converted into 2.14 format.
Accumulators
Run the below code for Cortex-M4 and Cortex-M3
loop counter
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C[0] = sqrt(A[0] * A[0] + A[1] * A[1])
store the result in 2.14 format in the destination buffer.
Decrement the loop counter
If the numSamples is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C[0] = sqrt(A[0] * A[0] + A[1] * A[1])
store the result in 2.14 format in the destination buffer.
Decrement the loop counter
Definition at line 65 of file arm_cmplx_mag_q15.c.
References arm_sqrt_q15().
void arm_cmplx_mag_q31 (q31_t * pSrc, q31_t * pDst, uint32_t numSamples)
Q31 complex magnitude.
Parameters
*pSrc points to the complex input vector
*pDst points to the real output vector
numSamples number of complex samples in the input vector
Returns
none.
Scaling and Overflow Behavior:
The function implements 1.31 by 1.31 multiplications and finally output is converted into 2.30 format. Input down scaling is not required.
Temporary variables to hold input values
Accumulators
loop counter
Run the below code for Cortex-M4 and Cortex-M3
Temporary variables to hold input values
Accumulators
Temporary variables
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
read complex input from source buffer
calculate power of input values
get the result to 3.29 format
add real and imaginary accumulators
read complex input from source buffer
calculate square root
calculate power of input values
calculate square root
calculate power of input values
get the result to 3.29 format
add real and imaginary accumulators
calculate square root
increment destination by 8 to process next samples
calculate square root
increment destination by 4 to process next samples
Decrement the loop counter
If the numSamples is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C[0] = sqrt(A[0] * A[0] + A[1] * A[1])
store the result in 2.30 format in the destination buffer.
Decrement the loop counter
Definition at line 65 of file arm_cmplx_mag_q31.c.
References arm_sqrt_q31().