HEXIWEAR MK64 Firmware Reference Manual: Sim_hal
Sim_hal
Files
file fsl_sim_hal.h
Typedefs
typedef enum _sim_hal_status sim_hal_status_t
SIM HAL API return status.
Enumerations
Functions
void CLOCK_HAL_SetUsbfsDiv (SIM_Type *base, uint8_t usbdiv, uint8_t usbfrac)
Set USB FS divider setting.
void CLOCK_HAL_GetUsbfsDiv (SIM_Type *base, uint8_t *usbdiv, uint8_t *usbfrac)
Get USB FS divider setting.
void CLOCK_HAL_SetOutDiv (SIM_Type *base, uint8_t outdiv1, uint8_t outdiv2, uint8_t outdiv3, uint8_t outdiv4)
Sets the clock out dividers setting.
void CLOCK_HAL_GetOutDiv (SIM_Type *base, uint8_t *outdiv1, uint8_t *outdiv2, uint8_t *outdiv3, uint8_t *outdiv4)
Gets the clock out dividers setting.
void SIM_HAL_SetAdcAlternativeTriggerCmd (SIM_Type *base, uint32_t instance, bool enable)
Sets the ADCx alternate trigger enable setting.
bool SIM_HAL_GetAdcAlternativeTriggerCmd (SIM_Type *base, uint32_t instance)
Gets the ADCx alternate trigger enable setting.
void SIM_HAL_SetAdcPreTriggerMode (SIM_Type *base, uint32_t instance, sim_adc_pretrg_sel_t select)
Sets the ADCx pre-trigger select setting.
sim_adc_pretrg_sel_t SIM_HAL_GetAdcPreTriggerMode (SIM_Type *base, uint32_t instance)
Gets the ADCx pre-trigger select setting.
void SIM_HAL_SetAdcTriggerMode (SIM_Type *base, uint32_t instance, sim_adc_trg_sel_t select)
Sets the ADCx trigger select setting.
sim_adc_trg_sel_t SIM_HAL_GetAdcTriggerMode (SIM_Type *base, uint32_t instance)
Gets the ADCx trigger select setting.
void SIM_HAL_SetAdcTriggerModeOneStep (SIM_Type *base, uint32_t instance, bool altTrigEn, sim_adc_pretrg_sel_t preTrigSel, sim_adc_trg_sel_t trigSel)
Sets the ADCx trigger select setting in one function.
void SIM_HAL_SetUartRxSrcMode (SIM_Type *base, uint32_t instance, sim_uart_rxsrc_t select)
Sets the UARTx receive data source select setting.
sim_uart_rxsrc_t SIM_HAL_GetUartRxSrcMode (SIM_Type *base, uint32_t instance)
Gets the UARTx receive data source select setting.
void SIM_HAL_SetUartTxSrcMode (SIM_Type *base, uint32_t instance, sim_uart_txsrc_t select)
Sets the UARTx transmit data source select setting.
sim_uart_txsrc_t SIM_HAL_GetUartTxSrcMode (SIM_Type *base, uint32_t instance)
Gets the UARTx transmit data source select setting.
void SIM_HAL_SetFtmTriggerSrcMode (SIM_Type *base, uint32_t instance, uint8_t trigger, sim_ftm_trg_src_t select)
Sets the FlexTimer x hardware trigger y source select setting.
sim_ftm_trg_src_t SIM_HAL_GetFtmTriggerSrcMode (SIM_Type *base, uint32_t instance, uint8_t trigger)
Gets the FlexTimer x hardware trigger y source select setting.
void SIM_HAL_SetFtmExternalClkPinMode (SIM_Type *base, uint32_t instance, sim_ftm_clk_sel_t select)
Sets the FlexTimer x external clock pin select setting.
sim_ftm_clk_sel_t SIM_HAL_GetFtmExternalClkPinMode (SIM_Type *base, uint32_t instance)
Gets the FlexTimer x external clock pin select setting.
void SIM_HAL_SetFtmChSrcMode (SIM_Type *base, uint32_t instance, uint8_t channel, sim_ftm_ch_src_t select)
Sets the FlexTimer x channel y input capture source select setting.
sim_ftm_ch_src_t SIM_HAL_GetFtmChSrcMode (SIM_Type *base, uint32_t instance, uint8_t channel)
Gets the FlexTimer x channel y input capture source select setting.
void SIM_HAL_SetFtmFaultSelMode (SIM_Type *base, uint32_t instance, uint8_t fault, sim_ftm_flt_sel_t select)
Sets the FlexTimer x fault y select setting.
sim_ftm_flt_sel_t SIM_HAL_GetFtmFaultSelMode (SIM_Type *base, uint32_t instance, uint8_t fault)
Gets the FlexTimer x fault y select setting.
Detailed Description
API
Typedef Documentation
typedef enum _sim_hal_status sim_hal_status_t
SIM HAL API return status.
Definitions
Enumeration Type Documentation
enum _sim_hal_status
SIM HAL API return status.
Definitions
Enumerator
kSimHalSuccess
Success.
kSimHalFail
Error occurs.
Definition at line 49 of file fsl_sim_hal.h.
Function Documentation
void CLOCK_HAL_GetOutDiv (SIM_Type * base, uint8_t * outdiv1, uint8_t * outdiv2, uint8_t * outdiv3, uint8_t * outdiv4)
Gets the clock out dividers setting.
This function gets the setting for all clock out dividers at the same time.
Parameters
base Base address for current SIM instance.
outdiv1 Outdivider1 setting
outdiv2 Outdivider2 setting
outdiv3 Outdivider3 setting
outdiv4 Outdivider4 setting
Definition at line 105 of file fsl_sim_hal_MK64F12.c.
void CLOCK_HAL_GetUsbfsDiv (SIM_Type * base, uint8_t * usbdiv, uint8_t * usbfrac)
Get USB FS divider setting.
This function gets USB FS divider setting. Divider output clock = Divider input clock * [ (USBFSFRAC+1) / (USBFSDIV+1) ]
Parameters
base Base address for current SIM instance.
usbdiv Value of USBFSDIV.
usbfrac Value of USBFSFRAC.
Definition at line 67 of file fsl_sim_hal_MK64F12.c.
Referenced by CLOCK_SYS_GetUsbfsFreq().
void CLOCK_HAL_SetOutDiv (SIM_Type * base, uint8_t outdiv1, uint8_t outdiv2, uint8_t outdiv3, uint8_t outdiv4)
Sets the clock out dividers setting.
This function sets the setting for all clock out dividers at the same time.
Parameters
base Base address for current SIM instance.
outdiv1 Outdivider1 setting
outdiv2 Outdivider2 setting
outdiv3 Outdivider3 setting
outdiv4 Outdivider4 setting
Definition at line 82 of file fsl_sim_hal_MK64F12.c.
Referenced by CLOCK_SYS_SetConfiguration().
void CLOCK_HAL_SetUsbfsDiv (SIM_Type * base, uint8_t usbdiv, uint8_t usbfrac)
Set USB FS divider setting.
This function sets USB FS divider setting. Divider output clock = Divider input clock * [ (USBFSFRAC+1) / (USBFSDIV+1) ]
Parameters
base Base address for current SIM instance.
usbdiv Value of USBFSDIV.
usbfrac Value of USBFSFRAC.
Definitions APIs
Definition at line 52 of file fsl_sim_hal_MK64F12.c.
bool SIM_HAL_GetAdcAlternativeTriggerCmd (SIM_Type * base, uint32_t instance)
Gets the ADCx alternate trigger enable setting.
This function gets the ADCx alternate trigger enable setting.
Parameters
base Base address for current SIM instance.
instance device instance.
Returns
enabled True if ADCx alternate trigger is enabled
Definition at line 150 of file fsl_sim_hal_MK64F12.c.
sim_adc_pretrg_sel_t SIM_HAL_GetAdcPreTriggerMode (SIM_Type * base, uint32_t instance)
Gets the ADCx pre-trigger select setting.
This function gets the ADCx pre-trigger select setting.
Parameters
base Base address for current SIM instance.
instance device instance.
Returns
select ADCx pre-trigger select setting
Definition at line 206 of file fsl_sim_hal_MK64F12.c.
sim_adc_trg_sel_t SIM_HAL_GetAdcTriggerMode (SIM_Type * base, uint32_t instance)
Gets the ADCx trigger select setting.
This function gets the ADCx trigger select setting.
Parameters
base Base address for current SIM instance.
instance device instance.
Returns
ADCx trigger select setting
Definition at line 262 of file fsl_sim_hal_MK64F12.c.
sim_ftm_ch_src_t SIM_HAL_GetFtmChSrcMode (SIM_Type * base, uint32_t instance, uint8_t channel)
Gets the FlexTimer x channel y input capture source select setting.
This function gets the FlexTimer x channel y input capture source select setting.
Parameters
base Base address for current SIM instance.
instance device instance.
channel FlexTimer channel y
Returns
select FlexTimer x channel y input capture source select setting
Definition at line 651 of file fsl_sim_hal_MK64F12.c.
sim_ftm_clk_sel_t SIM_HAL_GetFtmExternalClkPinMode (SIM_Type * base, uint32_t instance)
Gets the FlexTimer x external clock pin select setting.
This function gets the FlexTimer x external clock pin select setting.
Parameters
base Base address for current SIM instance.
instance device instance.
Returns
select FlexTimer x external clock pin select setting
Definition at line 574 of file fsl_sim_hal_MK64F12.c.
Referenced by CLOCK_SYS_GetFtmExternalFreq().
sim_ftm_flt_sel_t SIM_HAL_GetFtmFaultSelMode (SIM_Type * base, uint32_t instance, uint8_t fault)
Gets the FlexTimer x fault y select setting.
This function gets the FlexTimer x fault y select setting.
Parameters
base Base address for current SIM instance.
instance device instance.
fault fault y
Returns
select FlexTimer x fault y select setting
Definition at line 741 of file fsl_sim_hal_MK64F12.c.
sim_ftm_trg_src_t SIM_HAL_GetFtmTriggerSrcMode (SIM_Type * base, uint32_t instance, uint8_t trigger)
Gets the FlexTimer x hardware trigger y source select setting.
This function gets the FlexTimer x hardware trigger y source select setting.
Parameters
base Base address for current SIM instance.
instance device instance.
trigger hardware trigger y
Returns
select FlexTimer x hardware trigger y source select setting
Definition at line 491 of file fsl_sim_hal_MK64F12.c.
sim_uart_rxsrc_t SIM_HAL_GetUartRxSrcMode (SIM_Type * base, uint32_t instance)
Gets the UARTx receive data source select setting.
This function gets the UARTx receive data source select setting.
Parameters
base Base address for current SIM instance.
instance device instance.
Returns
select UARTx receive data source select setting
Definition at line 361 of file fsl_sim_hal_MK64F12.c.
sim_uart_txsrc_t SIM_HAL_GetUartTxSrcMode (SIM_Type * base, uint32_t instance)
Gets the UARTx transmit data source select setting.
This function gets the UARTx transmit data source select setting.
Parameters
base Base address for current SIM instance.
instance device instance.
Returns
select UARTx transmit data source select setting
Definition at line 415 of file fsl_sim_hal_MK64F12.c.
void SIM_HAL_SetAdcAlternativeTriggerCmd (SIM_Type * base, uint32_t instance, bool enable)
Sets the ADCx alternate trigger enable setting.
This function enables/disables the alternative conversion triggers for ADCx.
Parameters
base Base address for current SIM instance.
instance device instance.
enable Enable alternative conversion triggers for ADCx
true: Select alternative conversion trigger.
false: Select PDB trigger.
Definition at line 124 of file fsl_sim_hal_MK64F12.c.
void SIM_HAL_SetAdcPreTriggerMode (SIM_Type * base, uint32_t instance, sim_adc_pretrg_sel_t select)
Sets the ADCx pre-trigger select setting.
This function selects the ADCx pre-trigger source when the alternative triggers are enabled through ADCxALTTRGEN.
Parameters
base Base address for current SIM instance.
instance device instance.
select pre-trigger select setting for ADCx
Definition at line 180 of file fsl_sim_hal_MK64F12.c.
void SIM_HAL_SetAdcTriggerMode (SIM_Type * base, uint32_t instance, sim_adc_trg_sel_t select)
Sets the ADCx trigger select setting.
This function selects the ADCx trigger source when alternative triggers are enabled through ADCxALTTRGEN.
Parameters
base Base address for current SIM instance.
instance device instance.
select trigger select setting for ADCx
Definition at line 236 of file fsl_sim_hal_MK64F12.c.
void SIM_HAL_SetAdcTriggerModeOneStep (SIM_Type * base, uint32_t instance, bool altTrigEn, sim_adc_pretrg_sel_t preTrigSel, sim_adc_trg_sel_t trigSel)
Sets the ADCx trigger select setting in one function.
This function sets ADC alternate trigger, pre-trigger mode and trigger mode.
Parameters
base Base address for current SIM instance.
instance device instance.
altTrigEn Alternative trigger enable or not.
preTrigSel Pre-trigger mode.
trigSel Trigger mode.
Definition at line 290 of file fsl_sim_hal_MK64F12.c.
void SIM_HAL_SetFtmChSrcMode (SIM_Type * base, uint32_t instance, uint8_t channel, sim_ftm_ch_src_t select)
Sets the FlexTimer x channel y input capture source select setting.
This function selects the FlexTimer x channel y input capture source.
Parameters
base Base address for current SIM instance.
instance device instance.
channel FlexTimer channel y
select FlexTimer x channel y input capture source
Definition at line 609 of file fsl_sim_hal_MK64F12.c.
void SIM_HAL_SetFtmExternalClkPinMode (SIM_Type * base, uint32_t instance, sim_ftm_clk_sel_t select)
Sets the FlexTimer x external clock pin select setting.
This function selects the source of FTMx external clock pin select.
Parameters
base Base address for current SIM instance.
instance device instance.
select FTMx external clock pin select
0: FTMx external clock driven by FTM CLKIN0 pin.
1: FTMx external clock driven by FTM CLKIN1 pin.
Definition at line 542 of file fsl_sim_hal_MK64F12.c.
void SIM_HAL_SetFtmFaultSelMode (SIM_Type * base, uint32_t instance, uint8_t fault, sim_ftm_flt_sel_t select)
Sets the FlexTimer x fault y select setting.
This function sets the FlexTimer x fault y select setting.
Parameters
base Base address for current SIM instance.
instance device instance.
fault fault y
select FlexTimer x fault y select setting
0: FlexTimer x fault y select 0.
1: FlexTimer x fault y select 1.
Definition at line 695 of file fsl_sim_hal_MK64F12.c.
void SIM_HAL_SetFtmTriggerSrcMode (SIM_Type * base, uint32_t instance, uint8_t trigger, sim_ftm_trg_src_t select)
Sets the FlexTimer x hardware trigger y source select setting.
This function selects the source of FTMx hardware trigger y.
Parameters
base Base address for current SIM instance.
instance device instance.
trigger hardware trigger y
select FlexTimer x hardware trigger y
0: Pre-trigger A selected for ADCx.
1: Pre-trigger B selected for ADCx.
Definition at line 443 of file fsl_sim_hal_MK64F12.c.
void SIM_HAL_SetUartRxSrcMode (SIM_Type * base, uint32_t instance, sim_uart_rxsrc_t select)
Sets the UARTx receive data source select setting.
This function selects the source for the UARTx receive data.
Parameters
base Base address for current SIM instance.
instance device instance.
select the source for the UARTx receive data
Definition at line 335 of file fsl_sim_hal_MK64F12.c.
void SIM_HAL_SetUartTxSrcMode (SIM_Type * base, uint32_t instance, sim_uart_txsrc_t select)
Sets the UARTx transmit data source select setting.
This function selects the source for the UARTx transmit data.
Parameters
base Base address for current SIM instance.
instance device instance.
select the source for the UARTx transmit data
Definition at line 389 of file fsl_sim_hal_MK64F12.c.