HEXIWEAR MK64 Firmware Reference Manual: Power_manager
Power_manager
Data Structures
struct _power_manager_mode_user_config
Power mode user configuration structure.
struct _power_notify_struct
Power notification structure passed to registered callback function.
struct _power_manager_callback_user_config
callback configuration structure
struct _power_manager_state
Power manager internal state structure.
Typedefs
typedef enum _power_manager_modes power_manager_modes_t
Power modes enumeration.
typedef enum _power_manager_error_code power_manager_error_code_t
Power manager success code and error codes.
typedef enum _power_manager_policy power_manager_policy_t
Power manager policies.
typedef enum _power_manager_notify power_manager_notify_t
The PM notification type. Used to notify registered callbacks.
typedef enum _power_manager_callback_type power_manager_callback_type_t
The callback type, indicates what kinds of notification this callback handles.
typedef void power_manager_callback_data_t
Callback-specific data.
typedef struct _power_manager_mode_user_config power_manager_user_config_t
Power mode user configuration structure.
typedef struct _power_notify_struct power_manager_notify_struct_t
Power notification structure passed to registered callback function.
typedef power_manager_error_code_t(* power_manager_callback_t) (power_manager_notify_struct_t *notify, power_manager_callback_data_t *dataPtr)
Callback prototype.
typedef struct _power_manager_callback_user_config power_manager_callback_user_config_t
callback configuration structure
typedef struct _power_manager_state power_manager_state_t
Power manager internal state structure.
Enumerations
Functions
power_manager_error_code_t POWER_SYS_Init (power_manager_user_config_t const **powerConfigsPtr, uint8_t configsNumber, power_manager_callback_user_config_t **callbacksPtr, uint8_t callbacksNumber)
Power manager initialization for operation.
power_manager_error_code_t POWER_SYS_Deinit (void)
This function deinitializes the Power manager.
power_manager_error_code_t POWER_SYS_SetMode (uint8_t powerModeIndex, power_manager_policy_t policy)
This function configures the power mode.
power_manager_error_code_t POWER_SYS_GetLastMode (uint8_t *powerModeIndexPtr)
This function returns power mode set as the last one.
power_manager_error_code_t POWER_SYS_GetLastModeConfig (power_manager_user_config_t const **powerModePtr)
This function returns user configuration structure of power mode set as the last one.
power_manager_modes_t POWER_SYS_GetCurrentMode (void)
This function returns currently running power mode.
uint8_t POWER_SYS_GetErrorCallbackIndex (void)
This function returns the last failed notification callback.
power_manager_callback_user_config_t * POWER_SYS_GetErrorCallback (void)
This function returns the last failed notification callback configuration structure.
bool POWER_SYS_GetVeryLowPowerModeStatus (void)
This function returns whether very low power mode is running.
bool POWER_SYS_GetLowLeakageWakeupResetStatus (void)
This function returns whether reset was caused by low leakage wake up.
bool POWER_SYS_GetAckIsolation (void)
Gets the acknowledge isolation flag.
void POWER_SYS_ClearAckIsolation (void)
Clears the acknowledge isolation flag.
Detailed Description
Typedef Documentation
typedef void power_manager_callback_data_t
Callback-specific data.
Reference to data of this type is passed during callback registration. The reference is part of the power_manager_callback_user_config_t structure and is passed to the callback during power mode change notifications.
Definition at line 173 of file fsl_power_manager.h.
typedef power_manager_error_code_t(* power_manager_callback_t) (power_manager_notify_struct_t *notify, power_manager_callback_data_t *dataPtr)
Callback prototype.
Declaration of callback. It is common for registered callbacks. Reference to function of this type is part of power_manager_callback_user_config_t callback configuration structure. Depending on callback type, function of this prototype is called during power mode change (see POWER_SYS_SetMode()) before the mode change, after it or in both cases to notify about the change progress (see power_manager_callback_type_t). When called, type of the notification is passed as parameter along with reference to entered power mode configuration structure (see power_manager_notify_struct_t) and any data passed during the callback registration (see power_manager_callback_data_t). When notified before the mode change, depending on the power mode change policy (see power_manager_policy_t) the callback may deny the mode change by returning any error code different from kPowerManagerSuccess (see POWER_SYS_SetMode()).
Parameters
notify Notification structure.
dataPtr Callback data. Refers to the data passed during callback registration. Intended to pass any driver or application data such as internal state information.
Returns
An error code or kPowerManagerSuccess.
Definition at line 267 of file fsl_power_manager.h.
typedef enum _power_manager_callback_type power_manager_callback_type_t
The callback type, indicates what kinds of notification this callback handles.
Used in the callback configuration structures (power_manager_callback_user_config_t) to specify when the registered callback will be called during power mode change initiated by POWER_SYS_SetMode(). Callback can be invoked in following situations:
before the power mode change (Callback return value can affect POWER_SYS_SetMode() execution. Refer to the POWER_SYS_SetMode() and power_manager_policy_t documentation).
after entering one of the run modes or after exiting from one of the (deep) sleep power modes back to the run mode.
after unsuccessful attempt to switch power mode
typedef struct _power_manager_callback_user_config power_manager_callback_user_config_t
callback configuration structure
This structure holds configuration of callbacks passed to the Power manager during its initialization. Callbacks of this type are expected to be statically allocated. This structure contains following application-defined data: callback - pointer to the callback function callbackType - specifies when the callback is called callbackData - pointer to the data passed to the callback
typedef enum _power_manager_error_code power_manager_error_code_t
Power manager success code and error codes.
Used as return value of Power manager functions.
typedef enum _power_manager_modes power_manager_modes_t
Power modes enumeration.
Definitions
Defines power mode. Used in the power mode configuration structure (power_manager_user_config_t). From ARM core perspective, Power modes can be generally divided to run modes (High speed run, Run and Very low power run), sleep (Wait and Very low power wait) and deep sleep modes (all Stop modes). List of power modes supported by specific chip along with requirements for entering and exiting of these modes can be found in chip documentation. List of all supported power modes:
kPowerManagerHsrun - High speed run mode. Chip-specific.
kPowerManagerRun - Run mode. All Kinetis chips.
kPowerManagerVlpr - Very low power run mode. All Kinetis chips.
kPowerManagerWait - Wait mode. All Kinetis chips.
kPowerManagerVlpw - Very low power wait mode. All Kinetis chips.
kPowerManagerStop - Stop mode. All Kinetis chips.
kPowerManagerVlps - Very low power stop mode. All Kinetis chips.
kPowerManagerPstop1 - Partial stop 1 mode. Chip-specific.
kPowerManagerPstop2 - Partial stop 2 mode. Chip-specific.
kPowerManagerLls - Low leakage stop mode. All Kinetis chips.
kPowerManagerLls2 - Low leakage stop 2 mode. Chip-specific.
kPowerManagerLls3 - Low leakage stop 3 mode. Chip-specific.
kPowerManagerVlls0 - Very low leakage stop 0 mode. Chip-specific.
kPowerManagerVlls1 - Very low leakage stop 1 mode. All Kinetis chips.
kPowerManagerVlls2 - Very low leakage stop 2 mode. All Kinetis chips.
kPowerManagerVlls3 - Very low leakage stop 3 mode. All Kinetis chips.
typedef enum _power_manager_policy power_manager_policy_t
Power manager policies.
Define whether the power mode change is forced or not. Used to specify whether the mode switch initiated by the POWER_SYS_SetMode() depends on the callback notification results. For kPowerManagerPolicyForcible the power mode is changed regardless of the results, while kPowerManagerPolicyAgreement policy is used the POWER_SYS_SetMode() is exited when any of the callbacks returns error code. See also POWER_SYS_SetMode() description.
typedef struct _power_manager_state power_manager_state_t
Power manager internal state structure.
Power manager internal structure. Contains data necessary for Power manager proper function. Stores references to registered power mode configurations, callbacks, information about their numbers and other internal data. This structure is statically allocated and initialized after POWER_SYS_Init() call.
typedef struct _power_manager_mode_user_config power_manager_user_config_t
Power mode user configuration structure.
This structure defines Kinetis power mode with additional power options and specifies transition to and out of this mode. Application may define multiple power modes and switch between them. List of defined power modes is passed to the Power manager during initialization as an array of references to structures of this type (see POWER_SYS_Init()). Power modes can be switched by calling POWER_SYS_SetMode() which accepts index to the list of power modes passed during manager initialization. Currently used power mode can be retrieved by calling POWER_SYS_GetLastMode(), which returns index of the current power mode, or by POWER_SYS_GetLastModeConfig(), which returns reference to the structure of current mode. List of power mode configuration structure members depends on power options available for specific chip. Complete list contains: mode - Kinetis power mode. List of available modes is chip-specific. See power_manager_modes_t list of modes. This item is common for all Kinetis chips. sleepOnExitOption - Controls whether the sleep-on-exit option value is used (when set to true) or ignored (when set to false). See sleepOnExitValue. This item is common for all Kinetis chips. sleepOnExitValue - When set to true, ARM core returns to sleep (Kinetis wait modes) or deep sleep state (Kinetis stop modes) after interrupt service finishes. When set to false, core stays woken-up. This item is common for all Kinetis chips. lowPowerWakeUpOnInterruptOption - Controls whether the wake-up-on-interrupt option value is used (when set to true) or ignored (when set to false). See lowPowerWakeUpOnInterruptValue. This item is chip-specific. lowPowerWakeUpOnInterruptValue - When set to true, system exits to Run mode when any interrupt occurs while in Very low power run, Very low power wait or Very low power stop mode. This item is chip-specific. powerOnResetDetectionOption - Controls whether the power on reset detection option value is used (when set to true) or ignored (when set to false). See powerOnResetDetectionValue. This item is chip-specific. powerOnResetDetectionValue - When set to true, power on reset detection circuit is enabled in Very low leakage stop 0 mode. When set to false, circuit is disabled. This item is chip-specific. RAM2PartitionOption - Controls whether the RAM2 partition power option value is used (when set to true) or ignored (when set to false). See RAM2PartitionValue. This item is chip-specific. RAM2PartitionValue - When set to true, RAM2 partition content is retained through Very low leakage stop 2 mode. When set to false, RAM2 partition power is disabled and memory content lost. This item is chip-specific. lowPowerOscillatorOption - Controls whether the Low power oscillator power option value is used (when set to true) or ignored (when set to false). See lowPowerOscillatorValue. This item is chip-specific. lowPowerOscillatorValue - When set to true, the 1 kHz Low power oscillator is enabled in any Low leakage or Very low leakage stop mode. When set to false, oscillator is disabled in these modes. This item is chip-specific.
Enumeration Type Documentation
enum _power_manager_callback_type
The callback type, indicates what kinds of notification this callback handles.
Used in the callback configuration structures (power_manager_callback_user_config_t) to specify when the registered callback will be called during power mode change initiated by POWER_SYS_SetMode(). Callback can be invoked in following situations:
before the power mode change (Callback return value can affect POWER_SYS_SetMode() execution. Refer to the POWER_SYS_SetMode() and power_manager_policy_t documentation).
after entering one of the run modes or after exiting from one of the (deep) sleep power modes back to the run mode.
after unsuccessful attempt to switch power mode
Enumerator
kPowerManagerCallbackBefore
Before callback.
kPowerManagerCallbackAfter
After callback.
kPowerManagerCallbackBeforeAfter
Before-After callback.
Definition at line 160 of file fsl_power_manager.h.
enum _power_manager_error_code
Power manager success code and error codes.
Used as return value of Power manager functions.
Enumerator
kPowerManagerSuccess
Success
kPowerManagerError
Some error occurs.
kPowerManagerErrorOutOfRange
Configuration index out of range.
kPowerManagerErrorSwitch
Error occurs during mode switch.
kPowerManagerErrorNotificationBefore
Error occurs during send "BEFORE" notification.
kPowerManagerErrorNotificationAfter
Error occurs during send "AFTER" notification.
kPowerManagerErrorClock
Error occurs due to wrong clock setup for power modes
Definition at line 114 of file fsl_power_manager.h.
enum _power_manager_modes
Power modes enumeration.
Definitions
Defines power mode. Used in the power mode configuration structure (power_manager_user_config_t). From ARM core perspective, Power modes can be generally divided to run modes (High speed run, Run and Very low power run), sleep (Wait and Very low power wait) and deep sleep modes (all Stop modes). List of power modes supported by specific chip along with requirements for entering and exiting of these modes can be found in chip documentation. List of all supported power modes:
kPowerManagerHsrun - High speed run mode. Chip-specific.
kPowerManagerRun - Run mode. All Kinetis chips.
kPowerManagerVlpr - Very low power run mode. All Kinetis chips.
kPowerManagerWait - Wait mode. All Kinetis chips.
kPowerManagerVlpw - Very low power wait mode. All Kinetis chips.
kPowerManagerStop - Stop mode. All Kinetis chips.
kPowerManagerVlps - Very low power stop mode. All Kinetis chips.
kPowerManagerPstop1 - Partial stop 1 mode. Chip-specific.
kPowerManagerPstop2 - Partial stop 2 mode. Chip-specific.
kPowerManagerLls - Low leakage stop mode. All Kinetis chips.
kPowerManagerLls2 - Low leakage stop 2 mode. Chip-specific.
kPowerManagerLls3 - Low leakage stop 3 mode. Chip-specific.
kPowerManagerVlls0 - Very low leakage stop 0 mode. Chip-specific.
kPowerManagerVlls1 - Very low leakage stop 1 mode. All Kinetis chips.
kPowerManagerVlls2 - Very low leakage stop 2 mode. All Kinetis chips.
kPowerManagerVlls3 - Very low leakage stop 3 mode. All Kinetis chips.
Enumerator
kPowerManagerRun
Run mode. All Kinetis chips.
kPowerManagerVlpr
Very low power run mode. All Kinetis chips.
kPowerManagerWait
Wait mode. All Kinetis chips.
kPowerManagerVlpw
Very low power wait mode. All Kinetis chips.
kPowerManagerStop
Stop mode. All Kinetis chips.
kPowerManagerVlps
Very low power stop mode. All Kinetis chips.
kPowerManagerVlls1
Very low leakage stop 1 mode. All Kinetis chips.
kPowerManagerVlls3
Very low leakage stop 3 mode. All Kinetis chips.
Definition at line 77 of file fsl_power_manager.h.
enum _power_manager_notify
The PM notification type. Used to notify registered callbacks.
Enumerator
kPowerManagerNotifyRecover
Notify IP to recover to previous work state.
kPowerManagerNotifyBefore
Notify IP that system will change power setting.
kPowerManagerNotifyAfter
Notify IP that have changed to new power setting.
Definition at line 140 of file fsl_power_manager.h.
enum _power_manager_policy
Power manager policies.
Define whether the power mode change is forced or not. Used to specify whether the mode switch initiated by the POWER_SYS_SetMode() depends on the callback notification results. For kPowerManagerPolicyForcible the power mode is changed regardless of the results, while kPowerManagerPolicyAgreement policy is used the POWER_SYS_SetMode() is exited when any of the callbacks returns error code. See also POWER_SYS_SetMode() description.
Enumerator
kPowerManagerPolicyAgreement
POWER_SYS_SetMode() method is exited when any of the callbacks returns error code.
kPowerManagerPolicyForcible
Power mode is changed regardless of the results.
Definition at line 134 of file fsl_power_manager.h.
Function Documentation
void POWER_SYS_ClearAckIsolation (void)
Clears the acknowledge isolation flag.
This function clears the ACK Isolation flag. Clearing releases the I/O pads and certain peripherals to their normal run mode state.
After recovery from VLLS, the LLWU continues to detect wake-up events until the user has acknowledged the wake-up via POWER_SYS_ClearAckIsolation()
Definition at line 702 of file fsl_power_manager.c.
References CLOCK_SYS_GetBusClockFreq(), CLOCK_SYS_GetCoreClockFreq(), CLOCK_SYS_GetFlashClockFreq(), CLOCK_SYS_GetSystemClockFreq(), GpioInputPinUserConfig::config, GPIO_DRV_InputPinInit(), kPowerManagerErrorClock, kPowerManagerErrorSwitch, kPowerManagerRun, kPowerManagerSuccess, kPowerManagerVlpr, kPowerManagerVlpw, kPowerManagerWait, LLWU, MCG, GpioInputPinUserConfig::pinName, PMC, and SMC.
power_manager_error_code_t POWER_SYS_Deinit (void)
This function deinitializes the Power manager.
Returns
An error code or kPowerManagerSuccess.
Deinitialize internal state structure lock
Definition at line 173 of file fsl_power_manager.c.
References kPowerManagerSuccess.
bool POWER_SYS_GetAckIsolation (void)
Gets the acknowledge isolation flag.
This function is used to check certain peripherals and the I/O pads are in a latched state as a result of having been in a VLLS mode.
After recovery from VLLS, the LLWU continues to detect wake-up events until the user has acknowledged the wake-up via POWER_SYS_ClearAckIsolation()
Returns
Returns true if ACK isolation is set.
Definition at line 692 of file fsl_power_manager.c.
References PMC.
power_manager_modes_t POWER_SYS_GetCurrentMode (void)
This function returns currently running power mode.
This function reads hardware settings and returns currently running power mode. Generally, this function can return only kPowerManagerRun, kPowerManagerVlpr or kPowerManagerHsrun value.
Returns
Currently used run power mode.
Run mode
Very low power run mode
This should never happen - core has to be in some run mode to execute code
Definition at line 594 of file fsl_power_manager.c.
References kPowerManagerRun, kPowerManagerVlpr, and SMC.
Referenced by power_TurnOFF().
power_manager_callback_user_config_t* POWER_SYS_GetErrorCallback (void)
This function returns the last failed notification callback configuration structure.
This function returns pointer to configuration structure of the last callback that failed during the power mode switch while the last POWER_SYS_SetMode() was called. If the last POWER_SYS_SetMode() call ended successfully value NULL is returned.
Returns
Pointer to the callback configuration which returns error.
If all callbacks return success.
Definition at line 643 of file fsl_power_manager.c.
References _power_manager_state::errorCallbackIndex, _power_manager_state::staticCallbacks, and _power_manager_state::staticCallbacksNumber.
uint8_t POWER_SYS_GetErrorCallbackIndex (void)
This function returns the last failed notification callback.
This function returns index of the last callback that failed during the power mode switch while the last POWER_SYS_SetMode() was called. If the last POWER_SYS_SetMode() call ended successfully value equal to callbacks number is returned. Returned value represents index in the array of static call-backs.
Returns
Callback index of last failed callback or value equal to callbacks count.
Definition at line 632 of file fsl_power_manager.c.
References _power_manager_state::errorCallbackIndex.
power_manager_error_code_t POWER_SYS_GetLastMode (uint8_t * powerModeIndexPtr)
This function returns power mode set as the last one.
This function returns index of power mode which was set using POWER_SYS_SetMode() as the last one. If the power mode was entered even though some of the registered callback denied the mode change, or if any of the callbacks invoked after the entering/restoring run mode failed, then the return code of this function has kPowerManagerError value.
Parameters
powerModeIndexPtr Power mode which has been set represented as an index into array of power mode configurations passed to the POWER_SYS_Init().
Returns
An error code or kPowerManagerSuccess.
Pass index of user-defined configuration structure of currently running power mode
Return whether all call-backs executed without error
Definition at line 541 of file fsl_power_manager.c.
References _power_manager_state::currentConfig, _power_manager_state::errorCallbackIndex, kPowerManagerError, kPowerManagerSuccess, and _power_manager_state::staticCallbacksNumber.
power_manager_error_code_t POWER_SYS_GetLastModeConfig (power_manager_user_config_t const ** powerModePtr)
This function returns user configuration structure of power mode set as the last one.
This function returns reference to configuration structure which was set using POWER_SYS_SetMode() as the last one. If the current power mode was entered even though some of the registered callback denied the mode change, or if any of the callbacks invoked after the entering/restoring run mode failed, then the return code of this function has kPowerManagerError value.
Parameters
powerModePtr Pointer to power mode configuration structure of power mode set as last one.
Returns
An error code or kPowerManagerSuccess.
Pass reference to user-defined configuration structure of currently running power mode
Return whether all call-backs executed without error
Definition at line 570 of file fsl_power_manager.c.
References _power_manager_state::configs, _power_manager_state::currentConfig, _power_manager_state::errorCallbackIndex, kPowerManagerError, kPowerManagerSuccess, and _power_manager_state::staticCallbacksNumber.
bool POWER_SYS_GetLowLeakageWakeupResetStatus (void)
This function returns whether reset was caused by low leakage wake up.
This function is used to check that processor exited low leakage power mode through reset.
Returns
Returns true if processor was reset by low leakage wake up, otherwise false.
Definition at line 682 of file fsl_power_manager.c.
References RCM.
bool POWER_SYS_GetVeryLowPowerModeStatus (void)
This function returns whether very low power mode is running.
This function is used to detect whether very low power mode is running.
Returns
Returns true if processor runs in very low power mode, otherwise false.
Get current power mode and return true if it is very low power mode
Definition at line 662 of file fsl_power_manager.c.
References SMC.
power_manager_error_code_t POWER_SYS_Init (power_manager_user_config_t const ** powerConfigsPtr, uint8_t configsNumber, power_manager_callback_user_config_t ** callbacksPtr, uint8_t callbacksNumber)
Power manager initialization for operation.
API
This function initializes the Power manager and its run-time state structure. Reference to an array of Power mode configuration structures has to be passed as a parameter along with a parameter specifying its size. At least one power mode configuration is required. Optionally, reference to the array of predefined callbacks can be passed with its size parameter. For details about callbacks, refer to the power_manager_callback_user_config_t. As Power manager stores only references to array of these structures, they have to exist while Power manager is used. It is expected that prior to the POWER_SYS_Init() call the write-once protection register was configured appropriately allowing for entry to all required low power modes. The following is an example of how to set up two power modes and three callbacks, and initialize the Power manager with structures containing their settings. The example shows two possible ways the configuration structures can be stored (ROM or RAM), although it is expected that they will be placed in the read-only memory to save the RAM space. (Note: In the example it is assumed that the programmed chip doesn't support any optional power options described in the power_manager_user_config_t) :
 const power_manager_user_config_t waitConfig = {
     kPowerManagerVlpw,
     true,
     true,
 };
 const power_manager_callback_user_config_t callbackCfg0 = {
     callback0,
     kPowerManagerCallbackBefore,
     &callback_data0
 };
 const power_manager_callback_user_config_t callbackCfg1 = {
     callback1,
     kPowerManagerCallbackAfter,
     &callback_data1
 };
 const power_manager_callback_user_config_t callbackCfg2 = {
     callback2,
     kPowerManagerCallbackBeforeAfter,
     &callback_data2
 };
 const power_manager_callback_user_config_t * const callbacks[] = {&callbackCfg0, &callbackCfg1, &callbackCfg2};
 void main(void)
 {
     power_manager_user_config_t idleConfig;
     power_manager_user_config_t *powerConfigs[] = {&idleConfig, &waitConfig};
     idleConfig.mode = kPowerManagerVlps;
     idleConfig.sleepOnExitOption = true;
     idleConfig.sleepOnExitValue = false;
     POWER_SYS_Init(&powerConfigs, 2U, &callbacks, 3U);
     POWER_SYS_SetMode(0U, kPowerManagerPolicyAgreement);
 }
Parameters
powerConfigsPtr A pointer to an array with references to all power configurations which will be handled by Power manager.
configsNumber Number of power configurations. Size of powerConfigsPtr array.
callbacksPtr A pointer to an array with references to callback configurations. If there are no callbacks to register during Power manager initialization, use NULL value.
callbacksNumber Number of registered callbacks. Size of callbacksPtr array.
Returns
An error code or kPowerManagerSuccess.
Code
Check input parameter - at least one power mode configuration is required
Initialize internal state structure lock
Initialize internal state structure
Store references to user-defined power mode configurations
Store references to user-defined callback configurations and increment call-back handle counter
Default value of handle of last call-back that returned error
Enables clock gate for LLWU
Definition at line 135 of file fsl_power_manager.c.
References _power_manager_state::configs, _power_manager_state::configsNumber, _power_manager_state::errorCallbackIndex, kPowerManagerError, kPowerManagerSuccess, SIM, _power_manager_state::staticCallbacks, and _power_manager_state::staticCallbacksNumber.
Referenced by HEXIWEAR_startup().
power_manager_error_code_t POWER_SYS_SetMode (uint8_t powerModeIndex, power_manager_policy_t policy)
This function configures the power mode.
This function switches to one of the defined power modes. Requested mode number is passed as an input parameter. This function notifies all registered callback functions before the mode change (using kPowerManagerCallbackBefore set as callback type parameter), sets specific power options defined in the power mode configuration and enters the specified mode. In case of run modes (for example, Run, Very low power run, or High speed run), this function also invokes all registered callbacks after the mode change (using kPowerManagerCallbackAfter). In case of sleep or deep sleep modes, if the requested mode is not exited through a reset, these notifications are sent after the core wakes up. Callbacks are invoked in the following order: All registered callbacks are notified ordered by index in the callbacks array (see callbacksPtr parameter of POWER_SYS_Init()). The same order is used for before and after switch notifications. The notifications before the power mode switch can be used to obtain confirmation about the change from registered callbacks. If any registered callback denies the power mode change, further execution of this function depends on mode change policy: the mode change is either forced (kPowerManagerPolicyForcible) or exited (kPowerManagerPolicyAgreement). When mode change is forced, the result of the before switch notifications are ignored. If agreement is required, if any callback returns an error code then further notifications before switch notifications are cancelled and all already notified callbacks are re-invoked with kPowerManagerCallbackAfter set as callback type parameter. The index of the callback which returned error code during pre-switch notifications is stored (any error codes during callbacks re-invocation are ignored) and POWER_SYS_GetErrorCallback() can be used to get it. Regardless of the policies, if any callback returned an error code, an error code denoting in which phase the error occurred is returned when POWER_SYS_SetMode() exits. It is possible to enter any mode supported by the processor. Refer to the chip reference manual for list of available power modes. If it is necessary to switch into intermediate power mode prior to entering requested mode (for example, when switching from Run into Very low power wait through Very low power run mode), then the intermediate mode is entered without invoking the callback mechanism.
Parameters
powerModeIndex Requested power mode represented as an index into array of user-defined power mode configurations passed to the POWER_SYS_Init().
policy Transaction policy
Returns
An error code or kPowerManagerSuccess.
Local variable with requested power mode
SMC HAL layer configuration structure
Index to array of statically registered call-backs
Function return
Return code from clock checks
Pointer to callback configuration
Default value of handle of last call-back that returned error
Requested power mode configuration availability check
Initialization of local variables from the Power manager state structure
Check that requested power mode is not protected
From all statically registered call-backs...
Check pointer to static callback configuration
In case that call-back returned error code mark it, store the call-back handle and eventually cancel the mode switch
If not forcing power mode switch, call all already notified call-backs to revert their state as the mode change is canceled
Clocks should be in desired range. Some registered callback can change the clock so checks clock after callbacks
Power mode switch
In case that any call-back returned error code and policy doesn't force the mode switch go to after switch call-backs
Configure the HAL layer
Run mode
Very low power run mode
Wait mode
Very low power wait mode
Very low leakage stop modes
Stop mode
Very low power stop mode
Configure ARM core what to do after interrupt invoked in (deep) sleep state
Go back to (deep) sleep state on ISR exit
Do not re-enter (deep) sleep state on ISR exit
Switch the mode
Wait until new run mode is entered
End of successful switch
Update current configuration index
From all statically registered call-backs...
Check pointer to static callback configuration
In case that call-back returned error code mark it and store the call-back handle
End of unsuccessful switch
Checks if we can't switch due to clock
Check pointer to static callback configuration
Definition at line 214 of file fsl_power_manager.c.
References _power_manager_state::configs, _power_manager_state::configsNumber, _power_manager_state::currentConfig, _power_manager_state::errorCallbackIndex, kPowerManagerCallbackAfter, kPowerManagerCallbackBefore, kPowerManagerError, kPowerManagerErrorNotificationAfter, kPowerManagerErrorNotificationBefore, kPowerManagerErrorOutOfRange, kPowerManagerErrorSwitch, kPowerManagerNotifyAfter, kPowerManagerNotifyBefore, kPowerManagerNotifyRecover, kPowerManagerPolicyForcible, kPowerManagerRun, kPowerManagerStop, kPowerManagerSuccess, kPowerManagerVlls1, kPowerManagerVlls3, kPowerManagerVlpr, kPowerManagerVlps, kPowerManagerVlpw, kPowerManagerWait, _power_manager_mode_user_config::mode, _power_notify_struct::notifyType, _power_notify_struct::policy, SCB, SCB_SCR_SLEEPONEXIT_Msk, _power_manager_mode_user_config::sleepOnExitValue, SMC, _power_manager_state::staticCallbacks, _power_manager_state::staticCallbacksNumber, _power_notify_struct::targetPowerConfigIndex, and _power_notify_struct::targetPowerConfigPtr.
Referenced by power_TurnOFF().