HEXIWEAR MK64 Firmware Reference Manual: Os_abstraction
Os_abstraction
Macros
#define USE_RTOS 0
Typedefs
typedef enum _osa_status_t osa_status_t
Defines the return status of OSA's functions.
typedef enum _osa_event_clear_mode_t osa_event_clear_mode_t
The event flags are cleared automatically or manually.
typedef enum _osa_critical_section_mode_t osa_critical_section_mode_t
Locks the task scheduler or disables interrupt in critical section.
typedef void(* osa_int_handler_t) (void)
OSA interrupt handler.
Enumerations
Counting Semaphore
API
osa_status_t OSA_SemaCreate (semaphore_t *pSem, uint8_t initValue)
Creates a semaphore with a given value.
osa_status_t OSA_SemaWait (semaphore_t *pSem, uint32_t timeout)
Pending a semaphore with timeout.
osa_status_t OSA_SemaPost (semaphore_t *pSem)
Signals for someone waiting on the semaphore to wake up.
osa_status_t OSA_SemaDestroy (semaphore_t *pSem)
Destroys a previously created semaphore.
Mutex
osa_status_t OSA_MutexCreate (mutex_t *pMutex)
Create an unlocked mutex.
osa_status_t OSA_MutexLock (mutex_t *pMutex, uint32_t timeout)
Waits for a mutex and locks it.
osa_status_t OSA_MutexUnlock (mutex_t *pMutex)
Unlocks a previously locked mutex.
osa_status_t OSA_MutexDestroy (mutex_t *pMutex)
Destroys a previously created mutex.
Event signalling
osa_status_t OSA_EventCreate (event_t *pEvent, osa_event_clear_mode_t clearMode)
Initializes an event object with all flags cleared.
osa_status_t OSA_EventWait (event_t *pEvent, event_flags_t flagsToWait, bool waitAll, uint32_t timeout, event_flags_t *setFlags)
Waits for specified event flags to be set.
osa_status_t OSA_EventSet (event_t *pEvent, event_flags_t flagsToSet)
Sets one or more event flags.
osa_status_t OSA_EventClear (event_t *pEvent, event_flags_t flagsToClear)
Clears one or more flags.
event_flags_t OSA_EventGetFlags (event_t *pEvent)
Gets event flags status.
osa_status_t OSA_EventDestroy (event_t *pEvent)
Destroys a previously created event object.
Task management
osa_status_t OSA_TaskCreate (task_t task, uint8_t *name, uint16_t stackSize, task_stack_t *stackMem, uint16_t priority, task_param_t param, bool usesFloat, task_handler_t *handler)
Creates a task.
osa_status_t OSA_TaskDestroy (task_handler_t handler)
Destroys a previously created task.
osa_status_t OSA_TaskYield (void)
Puts the active task to the end of scheduler's queue.
task_handler_t OSA_TaskGetHandler (void)
Gets the handler of active task.
uint16_t OSA_TaskGetPriority (task_handler_t handler)
Gets the priority of a task.
osa_status_t OSA_TaskSetPriority (task_handler_t handler, uint16_t priority)
Sets the priority of a task.
Message queues
msg_queue_handler_t OSA_MsgQCreate (msg_queue_t *queue, uint16_t message_number, uint16_t message_size)
Initializes a message queue.
osa_status_t OSA_MsgQPut (msg_queue_handler_t handler, void *pMessage)
Puts a message at the end of the queue.
osa_status_t OSA_MsgQGet (msg_queue_handler_t handler, void *pMessage, uint32_t timeout)
Reads and remove a message at the head of the queue.
osa_status_t OSA_MsgQDestroy (msg_queue_handler_t handler)
Destroys a previously created queue.
Memory Management
void * OSA_MemAlloc (size_t size)
Reserves the requested amount of memory in bytes.
void * OSA_MemAllocZero (size_t size)
Reserves the requested amount of memory in bytes and initializes it to 0.
osa_status_t OSA_MemFree (void *ptr)
Releases the memory previously reserved.
Time management
void OSA_TimeDelay (uint32_t delay)
Delays execution for a number of milliseconds.
uint32_t OSA_TimeGetMsec (void)
Gets the current time since system boot in milliseconds.
Interrupt management
osa_int_handler_t OSA_InstallIntHandler (int32_t IRQNumber, osa_int_handler_t handler)
Installs the interrupt handler.
Critical section
void OSA_EnterCritical (osa_critical_section_mode_t mode)
Enters the critical section to ensure some code is not preempted.
void OSA_ExitCritical (osa_critical_section_mode_t mode)
Exits the critical section.
OSA initialize
osa_status_t OSA_Init (void)
Initializes the RTOS services.
osa_status_t OSA_Start (void)
Starts the RTOS.
Detailed Description
Macro Definition Documentation
#define USE_RTOS 0
Include required header file based on RTOS selection
Definition at line 91 of file fsl_os_abstraction.h.
Enumeration Type Documentation
enum _osa_critical_section_mode_t
Locks the task scheduler or disables interrupt in critical section.
Enumerator
kCriticalLockSched
Lock scheduler in critical section.
kCriticalDisableInt
Disable interrupt in critical selection.
Definition at line 64 of file fsl_os_abstraction.h.
enum _osa_event_clear_mode_t
The event flags are cleared automatically or manually.
Enumerator
kEventAutoClear
The flags of the event will be cleared automatically.
kEventManualClear
The flags of the event will be cleared manually.
Definition at line 57 of file fsl_os_abstraction.h.
enum _osa_status_t
Defines the return status of OSA's functions.
Enumerator
kStatus_OSA_Success
Success
kStatus_OSA_Error
Failed
kStatus_OSA_Timeout
Timeout occurs while waiting
kStatus_OSA_Idle
Used for bare metal only, the wait object is not ready and timeout still not occur
Definition at line 47 of file fsl_os_abstraction.h.
Function Documentation
void OSA_EnterCritical (osa_critical_section_mode_t mode)
Enters the critical section to ensure some code is not preempted.
Parameters
mode Lock task scheduler of disable interrupt in critical section. Pass kCriticalLockSched to lock task scheduler, pass kCriticalDisableInt to disable interrupt.
Referenced by CLOCK_SYS_UpdateConfiguration(), INTFLASH_SetEEEEnable(), and pedometer_GetCalories().
osa_status_t OSA_EventClear (event_t * pEvent, event_flags_t flagsToClear)
Clears one or more flags.
Clears specified flags of an event object.
Parameters
pEvent Pointer to the event.
flagsToClear Flags to be clear.
Return values
kStatus_OSA_Success The flags were successfully cleared.
kStatus_OSA_Error An incorrect parameter was passed.
Example:
 osa_status_t  status;
 status = OSA_EventClear(&myEvent, 0x01);
 switch (status)
 {
     //...
 }
Referenced by HostInterface_EventsInit(), and Notification_ArriveEventClear().
osa_status_t OSA_EventCreate (event_t * pEvent, osa_event_clear_mode_t clearMode)
Initializes an event object with all flags cleared.
This function creates an event object and set its clear mode. If clear mode is kEventAutoClear, when a task gets the event flags, these flags will be cleared automatically. If clear mode is kEventManualClear, these flags must be cleared manually.
Parameters
pEvent Pointer to the event object to initialize.
clearMode The event is auto-clear or manual-clear.
Return values
kStatus_OSA_Success The event object is successfully created.
kStatus_OSA_Error The event object is not created.
Example:
 event_t myEvent;
 OSA_EventCreate(&myEvent, kEventAutoClear);
Referenced by bluetooth_CreateAdvModeUpdateEvent(), buttonsGroup_CreateActiveUpdateEvent(), HEXIWEAR_CreateVersionEvent(), HostInterface_EventsInit(), Notification_EventInit(), Notification_Init(), RTC_Init(), and watch_CreateLinkStateUpdateEvent().
osa_status_t OSA_EventDestroy (event_t * pEvent)
Destroys a previously created event object.
Parameters
pEvent Pointer to the event.
Return values
kStatus_OSA_Success The event is successfully destroyed.
kStatus_OSA_Error Event destruction failed.
Example:
 osa_status_t  status;
 status = OSA_EventDestroy(&myEvent);
 switch (status)
 {
     //...
 }
event_flags_t OSA_EventGetFlags (event_t * pEvent)
Gets event flags status.
Gets the event flags status.
Parameters
pEvent Pointer to the event.
Returns
event_flags_t Current event flags.
Example:
 event_flags_t flags;
 flags = OSA_EventGetFlags(&myEvent);
osa_status_t OSA_EventSet (event_t * pEvent, event_flags_t flagsToSet)
Sets one or more event flags.
Sets specified flags of an event object.
Parameters
pEvent Pointer to the event.
flagsToSet Flags to be set.
Return values
kStatus_OSA_Success The flags were successfully set.
kStatus_OSA_Error An incorrect parameter was passed.
Example:
 osa_status_t  status;
 status = OSA_EventSet(&myEvent, 0x01);
 switch (status)
 {
     //...
 }
Referenced by bluetooth_AdvModeUpdate(), buttonsGroup_ActiveUpdate(), HEXIWEAR_UpdateVersion(), HostInterface_EventsInit(), Notification_ArriveEventSet(), Notification_SetEvent(), RTC_AlarmCallback(), RTC_UpdateCurrentTime(), watch_DestroyTasks(), watch_LinkStateUpdate(), watch_SetBatteryChargeEvent(), and watch_SetNotification().
osa_status_t OSA_EventWait (event_t * pEvent, event_flags_t flagsToWait, bool waitAll, uint32_t timeout, event_flags_t * setFlags)
Waits for specified event flags to be set.
This function waits for a combination of flags to be set in an event object. Applications can wait for any/all bits to be set. Also this function could obtain the flags who wakeup the waiting task.
Parameters
pEvent Pointer to the event.
flagsToWait Flags that to wait.
waitAll Wait all flags or any flag to be set.
timeout The maximum number of milliseconds to wait for the event. If the wait condition is not met, pass OSA_WAIT_FOREVER will wait indefinitely, pass 0 will return kStatus_OSA_Timeout immediately.
setFlags Flags that wakeup the waiting task are obtained by this parameter.
Return values
kStatus_OSA_Success The wait condition met and function returns successfully.
kStatus_OSA_Timeout Has not met wait condition within timeout.
kStatus_OSA_Error An incorrect parameter was passed.
kStatus_OSA_Idle The wait condition is not met and 'timeout' is not exhausted, This is only for bare metal.
Note
1. With bare metal, a event object cannot be waited on by more than one tasks at the same time.
Please pay attention to the flags bit width, FreeRTOS uses the most significant 8 bis as control bits, so do not wait these bits while using FreeRTOS.
Example:
 osa_status_t  status;
 event_flags_t setFlags;
 status = OSA_EventWait(&myEvent, 0x01, true, 100, &setFlags);
 switch (status)
 {
     //...
 }
Referenced by bluetooth_WaitForAdvModeUpdate(), buttonsGroup_WaitForActiveUpdate(), HEXIWEAR_WaitForVersionUpdate(), HostInterface_EventsInit(), Notification_ArriveEventWait(), Notification_WaitForEvent(), RTC_AlarmEventWait(), RTC_WatchUpdateEventWait(), watch_SetNotification(), and watch_WaitForLinkStateUpdate().
void OSA_ExitCritical (osa_critical_section_mode_t mode)
Exits the critical section.
Parameters
mode Lock task scheduler of disable interrupt in critical section. Pass kCriticalLockSched to lock task scheduler, pass kCriticalDisableInt to disable interrupt.
Referenced by CLOCK_SYS_UpdateConfiguration(), INTFLASH_SetEEEEnable(), and pedometer_GetCalories().
osa_status_t OSA_Init (void)
Initializes the RTOS services.
This function sets up the basic RTOS services. It should be called first in the main function.
Return values
kStatus_OSA_Success RTOS services are initialized successfully.
kStatus_OSA_Error Error occurs during initialization.
osa_int_handler_t OSA_InstallIntHandler (int32_t IRQNumber, osa_int_handler_t handler)
Installs the interrupt handler.
Parameters
IRQNumber IRQ number of the interrupt.
handler The interrupt handler to install.
Returns
This function returns the old interrupt handler installed in vector table. If could not install ISR, this function returns NULL; The return value could be compared with OSA_DEFAULT_INT_HANDLER to detect whether this is the first interrupt handler installed.
void* OSA_MemAlloc (size_t size)
Reserves the requested amount of memory in bytes.
Parameters
size Amount of bytes to reserve.
Returns
Pointer to the reserved memory. NULL if memory could not be allocated.
Referenced by GuiDriver_LabelCreate(), and OLED_Swap().
void* OSA_MemAllocZero (size_t size)
Reserves the requested amount of memory in bytes and initializes it to 0.
Parameters
size Amount of bytes to reserve.
Returns
Pointer to the reserved memory. NULL if memory could not be allocated.
osa_status_t OSA_MemFree (void * ptr)
Releases the memory previously reserved.
Parameters
ptr Pointer to the start of the memory block previously reserved.
Return values
kStatus_OSA_Success Memory correctly freed.
kStatus_OSA_Error Error occurs during free the memory.
Referenced by GuiDriver_LabelDestroy(), and OLED_Swap().
msg_queue_handler_t OSA_MsgQCreate (msg_queue_t * queue, uint16_t message_number, uint16_t message_size)
Initializes a message queue.
This function initializes the message queue that was declared previously. This is an example demonstrating the use of the function:
 msg_queue_handler_t handler;
 MSG_QUEUE_DECLARE(my_message, msg_num, msg_size);
 handler = OSA_MsgQCreate(my_message, msg_num, msg_size);
Parameters
queue The queue declared through the MSG_QUEUE_DECLARE macro.
message_number The number of elements in the queue.
message_size Size of every elements in words.
Returns
Handler to access the queue for put and get operations. If message queue created failed, return 0.
Referenced by bootloader_Init(), buttonsGroup_Init(), gui_heartRate_Init(), gui_pedometer_Init(), gui_sensorTag_Init(), GuiDriver_Init(), HostInterface_RxInit(), HostInterface_TxInit(), and pedometer_Init().
osa_status_t OSA_MsgQDestroy (msg_queue_handler_t handler)
Destroys a previously created queue.
Parameters
handler Queue handler returned by the OSA_MsgQCreate function.
Return values
kStatus_OSA_Success The queue was successfully destroyed.
kStatus_OSA_Error Message queue destruction failed.
Example:
 osa_status_t status;
 status = OSA_MsgQDestroy(queueHandler);
 switch (status)
 {
     //...
 }
Referenced by bootloader_DestroyTasks(), buttonsGroup_DestroyTasks(), gui_heartRate_DestroyTasks(), gui_pedometer_DestroyTasks(), gui_sensorTag_DestroyTasks(), and pedometer_Deinit().
osa_status_t OSA_MsgQGet (msg_queue_handler_t handler, void * pMessage, uint32_t timeout)
Reads and remove a message at the head of the queue.
This function gets a message from the head of the message queue. If the queue is empty, timeout is used to wait.
Parameters
handler Queue handler returned by the OSA_MsgQCreate function.
pMessage Pointer to a memory to save the message.
timeout The number of milliseconds to wait for a message. If the queue is empty, pass OSA_WAIT_FOREVER will wait indefinitely, pass 0 will return kStatus_OSA_Timeout immediately.
Return values
kStatus_OSA_Success Message successfully obtained from the queue.
kStatus_OSA_Timeout The queue remains empty after timeout.
kStatus_OSA_Error Invalid parameter.
kStatus_OSA_Idle The queue is empty and 'timeout' is not exhausted, This is only for bare metal.
Note
With bere metal, there should be only one process waiting on the queue.
Example:
 osa_status_t status;
 struct MESSAGE messageToGet;
 status = OSA_MsgQGet(queueHandler, &messageToGet, 100);
 switch (status)
 {
     //...
 }
Referenced by bootloader_DestroyTasks(), gui_heartRate_QueueMsgPut(), gui_pedometer_QueueMsgPut(), GuiDriver_QueueMsgGet(), HostInterface_RxQueueMsgPut(), HostInterface_TxQueueMsgPut(), and pedometer_GetCalories().
osa_status_t OSA_MsgQPut (msg_queue_handler_t handler, void * pMessage)
Puts a message at the end of the queue.
This function puts a message to the end of the message queue. If the queue is full, this function returns the kStatus_OSA_Error;
Parameters
handler Queue handler returned by the OSA_MsgQCreate function.
pMessage Pointer to the message to be put into the queue.
Return values
kStatus_OSA_Success Message successfully put into the queue.
kStatus_OSA_Error The queue was full or an invalid parameter was passed.
Example:
 osa_status_t status;
 struct MESSAGE messageToPut = ...;
 status = OSA_MsgQPut(queueHandler, &messageToPut);
 switch (status)
 {
     //...
 }
Referenced by HostInterface_RxQueueMsgPut().
osa_status_t OSA_MutexCreate (mutex_t * pMutex)
Create an unlocked mutex.
This function creates a non-recursive mutex and sets it to unlocked status.
Parameters
pMutex Pointer to the Mutex.
Return values
kStatus_OSA_Success The mutex is created successfully.
kStatus_OSA_Error The mutex cannot be created.
Example:
 mutex_t myMutex;
 osa_status_t status;
 status = OSA_MutexCreate(&myMutex);
 switch (status)
 {
     //...
 }
Referenced by GuiDriver_Init(), haptic_MutexCreate(), HostInterface_TxInit(), I2C_Init(), OLED_Init(), and sensor_Init().
osa_status_t OSA_MutexDestroy (mutex_t * pMutex)
Destroys a previously created mutex.
Parameters
pMutex Pointer to the Mutex.
Return values
kStatus_OSA_Success The mutex is successfully destroyed.
kStatus_OSA_Error The mutex cannot be destroyed.
Example:
 osa_status_t status;
 status = OSA_MutexDestroy(&myMutex);
 switch (status)
 {
     //...
 }
osa_status_t OSA_MutexLock (mutex_t * pMutex, uint32_t timeout)
Waits for a mutex and locks it.
This function checks the mutex's status. If it is unlocked, locks it and returns the kStatus_OSA_Success. Otherwise, waits for a timeout in milliseconds to lock.
Parameters
pMutex Pointer to the Mutex.
timeout The maximum number of milliseconds to wait for the mutex. If the mutex is locked, Pass the value OSA_WAIT_FOREVER will wait indefinitely, pass 0 will return kStatus_OSA_Timeout immediately.
Return values
kStatus_OSA_Success The mutex is locked successfully.
kStatus_OSA_Timeout Timeout occurred.
kStatus_OSA_Error Incorrect parameter was passed.
kStatus_OSA_Idle The mutex is not available and 'timeout' is not exhausted, This is only for bare metal.
Note
This is non-recursive mutex, a task cannot try to lock the mutex it has locked.
Example:
 osa_status_t status;
 status = OSA_MutexLock(&myMutex, 100);
 switch (status)
 {
     //...
 }
Referenced by GuiDriver_Navigation(), haptic_MutexLock(), HostInterface_TxQueueMsgPut(), I2C_ReadReg(), I2C_WriteReg(), OLED_Swap(), and sensor_Init().
osa_status_t OSA_MutexUnlock (mutex_t * pMutex)
Unlocks a previously locked mutex.
Parameters
pMutex Pointer to the Mutex.
Return values
kStatus_OSA_Success The mutex is successfully unlocked.
kStatus_OSA_Error The mutex cannot be unlocked or invalid parameter.
Example:
 osa_status_t status;
 status = OSA_MutexUnlock(&myMutex);
 switch (status)
 {
     //...
 }
Referenced by GuiDriver_Navigation(), haptic_MutexUnlock(), HostInterface_TxQueueMsgPut(), I2C_ReadReg(), I2C_WriteReg(), OLED_Swap(), and sensor_Init().
osa_status_t OSA_SemaCreate (semaphore_t * pSem, uint8_t initValue)
Creates a semaphore with a given value.
This function creates a semaphore and sets the value to the parameter initValue.
Parameters
pSem Pointer to the semaphore.
initValue Initial value the semaphore will be set to.
Return values
kStatus_OSA_Success The semaphore is created successfully.
kStatus_OSA_Error The semaphore cannot be created.
Example:
 semaphore_t mySem;
 OSA_SemaCreate(&mySem, 0);
Referenced by power_Init().
osa_status_t OSA_SemaDestroy (semaphore_t * pSem)
Destroys a previously created semaphore.
Parameters
pSem Pointer to the semaphore to destroy.
Return values
kStatus_OSA_Success The semaphore is successfully destroyed.
kStatus_OSA_Error The semaphore cannot be destroyed.
Example:
 osa_status_t status;
 status = OSA_SemaDestroy(&mySem);
 switch(status)
 {
     //...
 }
osa_status_t OSA_SemaPost (semaphore_t * pSem)
Signals for someone waiting on the semaphore to wake up.
Wakes up one task that is waiting on the semaphore. If no task is waiting, increases the semaphore's counting value.
Parameters
pSem Pointer to the semaphore to signal.
Return values
kStatus_OSA_Success The semaphore is successfully signaled.
kStatus_OSA_Error The object cannot be signaled or invalid parameter.
Example:
 osa_status_t status;
 status = OSA_SemaPost(&mySem);
 switch(status)
 {
     //...
 }
Referenced by power_CallBeforeSleep(), power_PostToSTSema(), power_TurnOFF(), and sensor_StopWait().
osa_status_t OSA_SemaWait (semaphore_t * pSem, uint32_t timeout)
Pending a semaphore with timeout.
This function checks the semaphore's counting value. If it is positive, decreases it and returns kStatus_OSA_Success. Otherwise, a timeout is used to wait.
Parameters
pSem Pointer to the semaphore.
timeout The maximum number of milliseconds to wait if semaphore is not positive. Pass OSA_WAIT_FOREVER to wait indefinitely, pass 0 will return kStatus_OSA_Timeout immediately.
Return values
kStatus_OSA_Success The semaphore is received.
kStatus_OSA_Timeout The semaphore is not received within the specified 'timeout'.
kStatus_OSA_Error An incorrect parameter was passed.
kStatus_OSA_Idle The semaphore is not available and 'timeout' is not exhausted, This is only for bare metal.
Note
With bare metal, a semaphore cannot be waited on by more than one task at the same time.
Example:
 osa_status_t status;
 status = OSA_SemaWait(&mySem, 100);
 switch(status)
 {
     //...
 }
Referenced by power_SetWakeSource(), power_TakeFromSTSema(), power_TurnOFF(), and sensor_RegisterPacketDelay().
osa_status_t OSA_Start (void)
Starts the RTOS.
This function starts the RTOS scheduler and may never return.
Return values
kStatus_OSA_Success RTOS starts to run successfully.
kStatus_OSA_Error Error occurs when start RTOS.
osa_status_t OSA_TaskCreate (task_t task, uint8_t * name, uint16_t stackSize, task_stack_t * stackMem, uint16_t priority, task_param_t param, bool usesFloat, task_handler_t * handler)
Creates a task.
This function is used to create task based on the resources defined by the macro OSA_TASK_DEFINE.
Parameters
task The task function entry.
name The name of this task.
stackSize The stack size in byte.
stackMem Pointer to the stack.
priority Initial priority of the task.
param Pointer to be passed to the task when it is created.
usesFloat This task will use float register or not.
handler Pointer to the task handler.
Return values
kStatus_OSA_Success The task is successfully created.
kStatus_OSA_Error The task cannot be created..
Example:
 osa_status_t status;
 OSA_TASK_DEFINE(task_func, stackSize);
 status = OSA_TaskCreate(task_func,
                      "task_name",
                      stackSize,
                      task_func_stack,
                      prio,
                      param,
                      false,
                      &task_func_task_handler);
 switch (status)
 {
     //...
 }
Note
Use the return value to check whether the task is created successfully. DO NOT check handler. For uC/OS-III, handler is not NULL even if the task creation has failed.
Referenced by bluetooth_CreateTasks(), bootloader_CreateTasks(), buttonsGroup_CreateTasks(), flashlight_CreateTasks(), gui_heartRate_CreateTasks(), gui_motionControl_CreateTasks(), gui_notifications_CreateTasks(), gui_pedometer_CreateTasks(), gui_sensorTag_CreateTasks(), gui_weatherStation_CreateTasks(), haptic_CreateTasks(), HEXIWEAR_Init(), HostInterface_RxInit(), HostInterface_TxInit(), info_CreateTasks(), pedometer_CreateTask(), power_Init(), reset_CreateTasks(), sensor_Init(), and watch_CreateTasks().
osa_status_t OSA_TaskDestroy (task_handler_t handler)
Destroys a previously created task.
Parameters
handler The handler of the task to destroy. Returned by the OSA_TaskCreate function.
Return values
kStatus_OSA_Success The task was successfully destroyed.
kStatus_OSA_Error Task destruction failed or invalid parameter.
Example:
 osa_status_t status;
 status = OSA_TaskDestroy(myTaskHandler);
 switch (status)
 {
     //...
 }
Referenced by bluetooth_DestroyTasks(), bootloader_DestroyTasks(), buttonsGroup_DestroyTasks(), flashlight_DestroyTasks(), gui_heartRate_DestroyTasks(), gui_motionControl_DestroyTasks(), gui_notifications_DestroyTasks(), gui_pedometer_DestroyTasks(), gui_sensorTag_DestroyTasks(), gui_weatherStation_DestroyTasks(), haptic_DestroyTasks(), HEXIWEAR_startup(), info_DestroyTasks(), pedometer_Deinit(), reset_DestroyTasks(), and watch_DestroyTasks().
task_handler_t OSA_TaskGetHandler (void)
Gets the handler of active task.
Returns
Handler to current active task.
Example:
 task_handler_t handler = OSA_TaskYield();
uint16_t OSA_TaskGetPriority (task_handler_t handler)
Gets the priority of a task.
Parameters
handler The handler of the task whose priority is received.
Returns
Task's priority.
Example:
 uint16_t taskPrio = OSA_TaskGetPriority(taskHandler);
osa_status_t OSA_TaskSetPriority (task_handler_t handler, uint16_t priority)
Sets the priority of a task.
Parameters
handler The handler of the task whose priority is received.
priority The priority to set.
Return values
kStatus_OSA_Success Task's priority is set successfully.
kStatus_OSA_Error Task's priority cannot be set.
Example:
 osa_status_t status;
 status = OSA_TaskSetPriority(taskHandler, newPrio);
 switch (status)
 {
     //...
 }
osa_status_t OSA_TaskYield (void)
Puts the active task to the end of scheduler's queue.
When a task calls this function, it gives up the CPU and puts itself to the end of a task ready list.
Return values
kStatus_OSA_Success The function is called successfully.
kStatus_OSA_Error Error occurs with this function.
Example:
 osa_status_t status;
 status = OSA_TaskYield();
 switch (status)
 {
     //...
 }
void OSA_TimeDelay (uint32_t delay)
Delays execution for a number of milliseconds.
Parameters
delay The time in milliseconds to wait.
Referenced by bluetooth_AdvModeUpdate(), bootloader_DestroyTasks(), FXAS_SoftReset(), FXOS_CalibrateMag(), GuiDriver_Init(), GuiDriver_Navigation(), I2C_Recover(), MAXIM_Init(), MAXIM_Reset(), MAXIM_Test(), OLED_DimScreenON(), OLED_Init(), PORTC_IRQHandler(), power_ResetKW40(), power_TurnOFF(), power_TurnScreenON(), sensor_Init(), and sensor_InitAcc().
uint32_t OSA_TimeGetMsec (void)
Gets the current time since system boot in milliseconds.
Returns
Current time in milliseconds.