HEXIWEAR MK64 Firmware Reference Manual: Vector Multiplication
Vector Multiplication
Basic Math Functions
Functions
void arm_mult_f32 (float32_t *pSrcA, float32_t *pSrcB, float32_t *pDst, uint32_t blockSize)
Floating-point vector multiplication.
void arm_mult_q15 (q15_t *pSrcA, q15_t *pSrcB, q15_t *pDst, uint32_t blockSize)
Q15 vector multiplication.
void arm_mult_q31 (q31_t *pSrcA, q31_t *pSrcB, q31_t *pDst, uint32_t blockSize)
Q31 vector multiplication.
void arm_mult_q7 (q7_t *pSrcA, q7_t *pSrcB, q7_t *pDst, uint32_t blockSize)
Q7 vector multiplication.
Detailed Description
Element-by-element multiplication of two vectors.
    pDst[n] = pSrcA[n] * pSrcB[n],   0 <= n < blockSize.
There are separate functions for floating-point, Q7, Q15, and Q31 data types.
Function Documentation
void arm_mult_f32 (float32_t * pSrcA, float32_t * pSrcB, float32_t * pDst, uint32_t blockSize)
Floating-point vector multiplication.
Parameters
[in] *pSrcA points to the first input vector
[in] *pSrcB points to the second input vector
[out] *pDst points to the output vector
[in] blockSize number of samples in each vector
Returns
none.
loop counters
Run the below code for Cortex-M4 and Cortex-M3
temporary input variables
temporary input variables
temporary output variables
loop Unrolling
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C = A * B
Multiply the inputs and store the results in output buffer
read sample from sourceA
read sample from sourceB
read sample from sourceA
read sample from sourceB
out = sourceA * sourceB
read sample from sourceA
read sample from sourceB
out = sourceA * sourceB
read sample from sourceA
store result to destination buffer
read sample from sourceB
out = sourceA * sourceB
store result to destination buffer
out = sourceA * sourceB
store result to destination buffer
store result to destination buffer
update pointers to process next samples
Decrement the blockSize loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = A * B
Multiply the inputs and store the results in output buffer
Decrement the blockSize loop counter
Definition at line 73 of file arm_mult_f32.c.
Referenced by arm_dct4_f32().
void arm_mult_q15 (q15_t * pSrcA, q15_t * pSrcB, q15_t * pDst, uint32_t blockSize)
Q15 vector multiplication.
Parameters
[in] *pSrcA points to the first input vector
[in] *pSrcB points to the second input vector
[out] *pDst points to the output vector
[in] blockSize number of samples in each vector
Returns
none.
Scaling and Overflow Behavior:
The function uses saturating arithmetic. Results outside of the allowable Q15 range [0x8000 0x7FFF] will be saturated.
loop counters
Run the below code for Cortex-M4 and Cortex-M3
temporary input variables
temporary output variables
temporary variables
loop Unrolling
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
read two samples at a time from sourceA
read two samples at a time from sourceB
read two samples at a time from sourceA
read two samples at a time from sourceB
multiply mul = sourceA * sourceB
saturate result to 16 bit
store the result
Decrement the blockSize loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = A * B
Multiply the inputs and store the result in the destination buffer
Decrement the blockSize loop counter
Definition at line 67 of file arm_mult_q15.c.
Referenced by arm_dct4_q15().
void arm_mult_q31 (q31_t * pSrcA, q31_t * pSrcB, q31_t * pDst, uint32_t blockSize)
Q31 vector multiplication.
Parameters
[in] *pSrcA points to the first input vector
[in] *pSrcB points to the second input vector
[out] *pDst points to the output vector
[in] blockSize number of samples in each vector
Returns
none.
Scaling and Overflow Behavior:
The function uses saturating arithmetic. Results outside of the allowable Q31 range[0x80000000 0x7FFFFFFF] will be saturated.
loop counters
Run the below code for Cortex-M4 and Cortex-M3
temporary input variables
temporary input variables
temporary output variables
loop Unrolling
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C = A * B
Multiply the inputs and then store the results in the destination buffer.
Decrement the blockSize loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = A * B
Multiply the inputs and then store the results in the destination buffer.
Decrement the blockSize loop counter
Definition at line 66 of file arm_mult_q31.c.
Referenced by arm_dct4_q31().
void arm_mult_q7 (q7_t * pSrcA, q7_t * pSrcB, q7_t * pDst, uint32_t blockSize)
Q7 vector multiplication.
Parameters
[in] *pSrcA points to the first input vector
[in] *pSrcB points to the second input vector
[out] *pDst points to the output vector
[in] blockSize number of samples in each vector
Returns
none.
Scaling and Overflow Behavior:
The function uses saturating arithmetic. Results outside of the allowable Q7 range [0x80 0x7F] will be saturated.
loop counters
Run the below code for Cortex-M4 and Cortex-M3
Temporary variables to store the product
loop Unrolling
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C = A * B
Multiply the inputs and store the results in temporary variables
Store the results of 4 inputs in the destination buffer in single cycle by packing
Decrement the blockSize loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = A * B
Multiply the inputs and store the result in the destination buffer
Decrement the blockSize loop counter
Definition at line 66 of file arm_mult_q7.c.