HEXIWEAR MK64 Firmware Reference Manual: Transform Functions
Transform Functions
Modules
Complex FFT Functions
Radix-8 Complex FFT Functions
DCT Type IV Functions
Real FFT Functions
Complex FFT Tables
RealFFT
Functions
void arm_radix4_butterfly_f32 (float32_t *pSrc, uint16_t fftLen, float32_t *pCoef, uint16_t twidCoefModifier)
void arm_split_rfft_f32 (float32_t *pSrc, uint32_t fftLen, float32_t *pATable, float32_t *pBTable, float32_t *pDst, uint32_t modifier)
Core Real FFT process.
Detailed Description
Function Documentation
void arm_radix4_butterfly_f32 (float32_t * pSrc, uint16_t fftLen, float32_t * pCoef, uint16_t twidCoefModifier)
Run the below code for Cortex-M4 and Cortex-M3
n2 = fftLen/4
xa + xc
xb + xd
ya + yc
yb + yd
xa - xc
xb - xd
ya - yc
yb - yd
xa' = xa + xb + xc + xd
ya' = ya + yb + yc + yd
xb' = (xa+yb-xc-yd)co1 - (ya-xb-yc+xd)(si1)
yb' = (ya-xb-yc+xd)co1 + (xa+yb-xc-yd)(si1)
xc' = (xa-xb+xc-xd)co2 - (ya-yb+yc-yd)(si2)
yc' = (ya-yb+yc-yd)co2 + (xa-xb+xc-xd)(si2)
xd' = (xa-yb-xc+yd)co3 - (ya+xb-yc-xd)(si3)
yd' = (ya+xb-yc-xd)co3 + (xa-yb-xc+yd)(si3)
xc' = (xa-xb+xc-xd)co2 + (ya-yb+yc-yd)(si2)
yc' = (ya-yb+yc-yd)co2 - (xa-xb+xc-xd)(si2)
xb' = (xa+yb-xc-yd)co1 + (ya-xb-yc+xd)(si1)
yb' = (ya-xb-yc+xd)co1 - (xa+yb-xc-yd)(si1)
xd' = (xa-yb-xc+yd)co3 + (ya+xb-yc-xd)(si3)
yd' = (ya+xb-yc-xd)co3 - (xa-yb-xc+yd)(si3)
xa - xc
ya - yc
xa + xc
xb + xd
ya + yc
yb + yd
xa + xc -(xb + xd)
xb' = (xa+yb-xc-yd)co1 - (ya-xb-yc+xd)(si1)
yb' = (ya-xb-yc+xd)co1 + (xa+yb-xc-yd)(si1)
xc' = (xa-xb+xc-xd)co2 - (ya-yb+yc-yd)(si2)
yc' = (ya-yb+yc-yd)co2 + (xa-xb+xc-xd)(si2)
xd' = (xa-yb-xc+yd)co3 - (ya+xb-yc-xd)(si3)
yd' = (ya+xb-yc-xd)co3 + (xa-yb-xc+yd)(si3)
xc' = (xa-xb+xc-xd)co2 + (ya-yb+yc-yd)(si2)
yc' = (ya-yb+yc-yd)co2 - (xa-xb+xc-xd)(si2)
xb' = (xa+yb-xc-yd)co1 + (ya-xb-yc+xd)(si1)
yb' = (ya-xb-yc+xd)co1 - (xa+yb-xc-yd)(si1)
xd' = (xa-yb-xc+yd)co3 + (ya+xb-yc-xd)(si3)
yd' = (ya+xb-yc-xd)co3 - (xa-yb-xc+yd)(si3)
xa + xc
xa - xc
ya + yc
ya - yc
xb + xd
yb + yd
xa' = xa + xb + xc + xd
ya' = ya + yb + yc + yd
xc' = (xa-xb+xc-xd)
yc' = (ya-yb+yc-yd)
xb' = (xa+yb-xc-yd)
yb' = (ya-xb-yc+xd)
xd' = (xa-yb-xc+yd))
yd' = (ya+xb-yc-xd)
increment pointer by 8
Definition at line 67 of file arm_cfft_radix4_f32.c.
Referenced by arm_cfft_radix4_f32(), and arm_rfft_f32().
void arm_split_rfft_f32 (float32_t * pSrc, uint32_t fftLen, float32_t * pATable, float32_t * pBTable, float32_t * pDst, uint32_t modifier)
Core Real FFT process.
end of RealFFT group
Parameters
[in] *pSrc points to the input buffer.
[in] fftLen length of FFT.
[in] *pATable points to the twiddle Coef A buffer.
[in] *pBTable points to the twiddle Coef B buffer.
[out] *pDst points to the output buffer.
[in] modifier twiddle coefficient modifier that supports different size FFTs with the same twiddle factor table.
Returns
none.
Loop Counter
Temporary variables for output
Temporary pointers for twiddle factors
Temporary variables for twiddle coefficients
temp pointers for output buffer
temp pointers for input buffer
Init coefficient pointers
outI = (pIn[2 * i + 1] * pATable[2 * i] + pIn[2 * i] * pATable[2 * i + 1] + pIn[2 * n - 2 * i] * pBTable[2 * i + 1] - pIn[2 * n - 2 * i + 1] * pBTable[2 * i]);
read pATable[2 * i]
pATable[2 * i + 1]
pSrc[2 * i] * pATable[2 * i]
pSrc[2 * i] * CoefA2
pSrc[2 * i + 1] * CoefA1
pSrc[2 * fftLen - 2 * i + 1] * CoefB1
pSrc[2 * fftLen - 2 * i] * CoefA2
pSrc[2 * fftLen - 2 * i] * CoefB1
write output
write complex conjugate output
update coefficient pointer
Definition at line 168 of file arm_rfft_f32.c.
Referenced by arm_rfft_f32().