HEXIWEAR MK64 Firmware Reference Manual: Partial Convolution
Partial Convolution
Filtering Functions
Functions
arm_status arm_conv_partial_f32 (float32_t *pSrcA, uint32_t srcALen, float32_t *pSrcB, uint32_t srcBLen, float32_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of floating-point sequences.
arm_status arm_conv_partial_fast_opt_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, uint32_t firstIndex, uint32_t numPoints, q15_t *pScratch1, q15_t *pScratch2)
Partial convolution of Q15 sequences (fast version) for Cortex-M3 and Cortex-M4.
arm_status arm_conv_partial_fast_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q15 sequences (fast version) for Cortex-M3 and Cortex-M4.
arm_status arm_conv_partial_fast_q31 (q31_t *pSrcA, uint32_t srcALen, q31_t *pSrcB, uint32_t srcBLen, q31_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q31 sequences (fast version) for Cortex-M3 and Cortex-M4.
arm_status arm_conv_partial_opt_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, uint32_t firstIndex, uint32_t numPoints, q15_t *pScratch1, q15_t *pScratch2)
Partial convolution of Q15 sequences.
arm_status arm_conv_partial_opt_q7 (q7_t *pSrcA, uint32_t srcALen, q7_t *pSrcB, uint32_t srcBLen, q7_t *pDst, uint32_t firstIndex, uint32_t numPoints, q15_t *pScratch1, q15_t *pScratch2)
Partial convolution of Q7 sequences.
arm_status arm_conv_partial_q15 (q15_t *pSrcA, uint32_t srcALen, q15_t *pSrcB, uint32_t srcBLen, q15_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q15 sequences.
arm_status arm_conv_partial_q31 (q31_t *pSrcA, uint32_t srcALen, q31_t *pSrcB, uint32_t srcBLen, q31_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q31 sequences.
arm_status arm_conv_partial_q7 (q7_t *pSrcA, uint32_t srcALen, q7_t *pSrcB, uint32_t srcBLen, q7_t *pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q7 sequences.
Detailed Description
Partial Convolution is equivalent to Convolution except that a subset of the output samples is generated. Each function has two additional arguments. firstIndex specifies the starting index of the subset of output samples. numPoints is the number of output samples to compute. The function computes the output in the range [firstIndex, ..., firstIndex+numPoints-1]. The output array pDst contains numPoints values.
The allowable range of output indices is [0 srcALen+srcBLen-2]. If the requested subset does not fall in this range then the functions return ARM_MATH_ARGUMENT_ERROR. Otherwise the functions return ARM_MATH_SUCCESS.
Note
Refer arm_conv_f32() for details on fixed point behavior.
Fast Versions
Fast versions are supported for Q31 and Q15 of partial convolution. Cycles for Fast versions are less compared to Q31 and Q15 of partial conv and the design requires the input signals should be scaled down to avoid intermediate overflows.
Opt Versions
Opt versions are supported for Q15 and Q7. Design uses internal scratch buffer for getting good optimisation. These versions are optimised in cycles and consumes more memory(Scratch memory) compared to Q15 and Q7 versions of partial convolution
Function Documentation
arm_status arm_conv_partial_f32 (float32_t * pSrcA, uint32_t srcALen, float32_t * pSrcB, uint32_t srcBLen, float32_t * pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of floating-point sequences.
Parameters
[in] *pSrcA points to the first input sequence.
[in] srcALen length of the first input sequence.
[in] *pSrcB points to the second input sequence.
[in] srcBLen length of the second input sequence.
[out] *pDst points to the location where the output result is written.
[in] firstIndex is the first output sample to start with.
[in] numPoints is the number of output points to be computed.
Returns
Returns either ARM_MATH_SUCCESS if the function completed correctly or ARM_MATH_ARGUMENT_ERROR if the requested subset is not in the range [0 srcALen+srcBLen-2].
Run the below code for Cortex-M4 and Cortex-M3
inputA pointer
inputB pointer
output pointer
Intermediate inputA pointer
Intermediate inputB pointer
Intermediate pointers
Accumulator
Temporary variables to hold state and coefficient values
loop counters
status of Partial convolution
Check for range of output samples to be calculated
Set status as ARM_MATH_ARGUMENT_ERROR
The algorithm implementation is based on the lengths of the inputs.
srcB is always made to slide across srcA.
So srcBLen is always considered as shorter or equal to srcALen
Initialization of inputA pointer
Initialization of inputB pointer
Initialization of inputA pointer
Initialization of inputB pointer
srcBLen is always considered as shorter or equal to srcALen
Conditions to check which loopCounter holds the first and last indices of the output samples to be calculated.
conv(x,y) at n = x[n] * y[0] + x[n-1] * y[1] + x[n-2] * y[2] + ...+ x[n-N+1] * y[N -1]
The function is internally divided into three stages according to the number of multiplications that has to be taken place between inputA samples and inputB samples. In the first stage of the algorithm, the multiplications increase by one for every iteration. In the second stage of the algorithm, srcBLen number of multiplications are done. In the third stage of the algorithm, the multiplications decrease by one for every iteration.
Set the output pointer to point to the firstIndex of the output sample to be calculated.
sum = x[0] * y[0] sum = x[0] * y[1] + x[1] * y[0] .... sum = x[0] * y[srcBlen - 1] + x[1] * y[srcBlen - 2] +...+ x[srcBLen - 1] * y[0]
In this stage the MAC operations are increased by 1 for every iteration. The count variable holds the number of MAC operations performed. Since the partial convolution starts from from firstIndex Number of Macs to be performed is firstIndex + 1
Working pointer of inputA
Working pointer of inputB
The first stage starts here
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
x[0] * y[srcBLen - 1]
x[1] * y[srcBLen - 2]
x[2] * y[srcBLen - 3]
x[3] * y[srcBLen - 4]
Decrement the loop counter
If the count is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulates
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Increment the MAC count
Decrement the loop counter
sum = x[0] * y[srcBLen-1] + x[1] * y[srcBLen-2] +...+ x[srcBLen-1] * y[0] sum = x[1] * y[srcBLen-1] + x[2] * y[srcBLen-2] +...+ x[srcBLen] * y[0] .... sum = x[srcALen-srcBLen-2] * y[srcBLen-1] + x[srcALen] * y[srcBLen-2] +...+ x[srcALen-1] * y[0]
Working pointer of inputA
Working pointer of inputB
count is index by which the pointer pIn1 to be incremented
Stage2 depends on srcBLen as in this stage srcBLen number of MACS are performed. So, to loop unroll over blockSize2, srcBLen should be greater than or equal to 4
Loop unroll over blockSize2, by 4
Set all accumulators to zero
read x[0], x[1], x[2] samples
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Read y[srcBLen - 1] sample
Read x[3] sample
Perform the multiply-accumulate
acc0 += x[0] * y[srcBLen - 1]
acc1 += x[1] * y[srcBLen - 1]
acc2 += x[2] * y[srcBLen - 1]
acc3 += x[3] * y[srcBLen - 1]
Read y[srcBLen - 2] sample
Read x[4] sample
Perform the multiply-accumulate
acc0 += x[1] * y[srcBLen - 2]
acc1 += x[2] * y[srcBLen - 2]
acc2 += x[3] * y[srcBLen - 2]
acc3 += x[4] * y[srcBLen - 2]
Read y[srcBLen - 3] sample
Read x[5] sample
Perform the multiply-accumulates
acc0 += x[2] * y[srcBLen - 3]
acc1 += x[3] * y[srcBLen - 2]
acc2 += x[4] * y[srcBLen - 2]
acc3 += x[5] * y[srcBLen - 2]
Read y[srcBLen - 4] sample
Read x[6] sample
Perform the multiply-accumulates
acc0 += x[3] * y[srcBLen - 4]
acc1 += x[4] * y[srcBLen - 4]
acc2 += x[5] * y[srcBLen - 4]
acc3 += x[6] * y[srcBLen - 4]
If the srcBLen is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Read y[srcBLen - 5] sample
Read x[7] sample
Perform the multiply-accumulates
acc0 += x[4] * y[srcBLen - 5]
acc1 += x[5] * y[srcBLen - 5]
acc2 += x[6] * y[srcBLen - 5]
acc3 += x[7] * y[srcBLen - 5]
Reuse the present samples for the next MAC
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the pointer pIn1 index, count by 1
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
If the blockSize2 is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Perform the multiply-accumulates
Decrement the loop counter
If the srcBLen is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulate
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the MAC count
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
If the srcBLen is not a multiple of 4, the blockSize2 loop cannot be unrolled by 4
Accumulator is made zero for every iteration
srcBLen number of MACS should be performed
Perform the multiply-accumulate
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the MAC count
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
sum += x[srcALen-srcBLen+1] * y[srcBLen-1] + x[srcALen-srcBLen+2] * y[srcBLen-2] +...+ x[srcALen-1] * y[1] sum += x[srcALen-srcBLen+2] * y[srcBLen-1] + x[srcALen-srcBLen+3] * y[srcBLen-2] +...+ x[srcALen-1] * y[2] .... sum += x[srcALen-2] * y[srcBLen-1] + x[srcALen-1] * y[srcBLen-2] sum += x[srcALen-1] * y[srcBLen-1]
In this stage the MAC operations are decreased by 1 for every iteration. The count variable holds the number of MAC operations performed
Working pointer of inputA
Working pointer of inputB
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
sum += x[srcALen - srcBLen + 1] * y[srcBLen - 1]
sum += x[srcALen - srcBLen + 2] * y[srcBLen - 2]
sum += x[srcALen - srcBLen + 3] * y[srcBLen - 3]
sum += x[srcALen - srcBLen + 4] * y[srcBLen - 4]
Decrement the loop counter
If the count is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulates
sum += x[srcALen-1] * y[srcBLen-1]
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Decrement the MAC count
Decrement the loop counter
set status as ARM_MATH_SUCCESS
Return to application
Definition at line 95 of file arm_conv_partial_f32.c.
arm_status arm_conv_partial_fast_opt_q15 (q15_t * pSrcA, uint32_t srcALen, q15_t * pSrcB, uint32_t srcBLen, q15_t * pDst, uint32_t firstIndex, uint32_t numPoints, q15_t * pScratch1, q15_t * pScratch2)
Partial convolution of Q15 sequences (fast version) for Cortex-M3 and Cortex-M4.
Parameters
[in] *pSrcA points to the first input sequence.
[in] srcALen length of the first input sequence.
[in] *pSrcB points to the second input sequence.
[in] srcBLen length of the second input sequence.
[out] *pDst points to the location where the output result is written.
[in] firstIndex is the first output sample to start with.
[in] numPoints is the number of output points to be computed.
[in] *pScratch1 points to scratch buffer of size max(srcALen, srcBLen) + 2*min(srcALen, srcBLen) - 2.
[in] *pScratch2 points to scratch buffer of size min(srcALen, srcBLen).
Returns
Returns either ARM_MATH_SUCCESS if the function completed correctly or ARM_MATH_ARGUMENT_ERROR if the requested subset is not in the range [0 srcALen+srcBLen-2].
See arm_conv_partial_q15() for a slower implementation of this function which uses a 64-bit accumulator to avoid wrap around distortion.
Restrictions
If the silicon does not support unaligned memory access enable the macro UNALIGNED_SUPPORT_DISABLE In this case input, output, scratch1 and scratch2 buffers should be aligned by 32-bit
output pointer
Temporary pointer for scratch1
Temporary pointer for scratch1
Accumulator
Temporary variables to hold state and coefficient values
State variables
inputA pointer
inputB pointer
Intermediate inputA pointer
Intermediate inputB pointer
loop counter
loop count
Check for range of output samples to be calculated
Set status as ARM_MATH_ARGUMENT_ERROR
The algorithm implementation is based on the lengths of the inputs.
srcB is always made to slide across srcA.
So srcBLen is always considered as shorter or equal to srcALen
Initialization of inputA pointer
Initialization of inputB pointer
Initialization of inputA pointer
Initialization of inputB pointer
srcBLen is always considered as shorter or equal to srcALen
Temporary pointer for scratch2
pointer to take end of scratch2 buffer
points to smaller length sequence
Apply loop unrolling and do 4 Copies simultaneously.
First part of the processing with loop unrolling copies 4 data points at a time. a second loop below copies for the remaining 1 to 3 samples.
Copy smaller length input sequence in reverse order into second scratch buffer
copy second buffer in reversal manner
Decrement the loop counter
If the count is not a multiple of 4, copy remaining samples here. No loop unrolling is used.
copy second buffer in reversal manner for remaining samples
Decrement the loop counter
Initialze temporary scratch pointer
Assuming scratch1 buffer is aligned by 32-bit
Fill (srcBLen - 1u) zeros in scratch buffer
Update temporary scratch pointer
Copy bigger length sequence(srcALen) samples in scratch1 buffer
Copy (srcALen) samples in scratch buffer
Update pointers
Fill (srcBLen - 1u) zeros at end of scratch buffer
Update pointer
Initialization of pIn2 pointer
First part of the processing with loop unrolling process 4 data points at a time. a second loop below process for the remaining 1 to 3 samples.
Actual convolution process starts here
Initialze temporary scratch pointer as scratch1
Clear Accumlators
Read two samples from scratch1 buffer
Read next two samples from scratch1 buffer
Read four samples from smaller buffer
multiply and accumlate
pack input data
multiply and accumlate
Read next two samples from scratch1 buffer
multiply and accumlate
pack input data
update scratch pointers
Decrement the loop counter
Update scratch pointer for remaining samples of smaller length sequence
apply same above for remaining samples of smaller length sequence
accumlate the results
Decrement the loop counter
Store the results in the accumulators in the destination buffer.
Initialization of inputB pointer
Calculate convolution for remaining samples of Bigger length sequence
Initialze temporary scratch pointer as scratch1
Clear Accumlators
Read next two samples from scratch1 buffer
Read two samples from smaller buffer
Decrement the loop counter
apply same above for remaining samples of smaller length sequence
accumlate the results
Decrement the loop counter
The result is in 2.30 format. Convert to 1.15 with saturation. Then store the output in the destination buffer.
Initialization of inputB pointer
set status as ARM_MATH_SUCCESS
Return to application
Definition at line 75 of file arm_conv_partial_fast_opt_q15.c.
References arm_conv_partial_fast_opt_q15(), arm_copy_q15(), and arm_fill_q15().
Referenced by arm_conv_partial_fast_opt_q15().
arm_status arm_conv_partial_fast_q15 (q15_t * pSrcA, uint32_t srcALen, q15_t * pSrcB, uint32_t srcBLen, q15_t * pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q15 sequences (fast version) for Cortex-M3 and Cortex-M4.
Parameters
[in] *pSrcA points to the first input sequence.
[in] srcALen length of the first input sequence.
[in] *pSrcB points to the second input sequence.
[in] srcBLen length of the second input sequence.
[out] *pDst points to the location where the output result is written.
[in] firstIndex is the first output sample to start with.
[in] numPoints is the number of output points to be computed.
Returns
Returns either ARM_MATH_SUCCESS if the function completed correctly or ARM_MATH_ARGUMENT_ERROR if the requested subset is not in the range [0 srcALen+srcBLen-2].
See arm_conv_partial_q15() for a slower implementation of this function which uses a 64-bit accumulator to avoid wrap around distortion.
inputA pointer
inputB pointer
output pointer
Accumulator
Intermediate inputA pointer
Intermediate inputB pointer
Intermediate pointers
loop counters
status of Partial convolution
Check for range of output samples to be calculated
Set status as ARM_MATH_ARGUMENT_ERROR
The algorithm implementation is based on the lengths of the inputs.
srcB is always made to slide across srcA.
So srcBLen is always considered as shorter or equal to srcALen
Initialization of inputA pointer
Initialization of inputB pointer
Initialization of inputA pointer
Initialization of inputB pointer
srcBLen is always considered as shorter or equal to srcALen
Conditions to check which loopCounter holds the first and last indices of the output samples to be calculated.
conv(x,y) at n = x[n] * y[0] + x[n-1] * y[1] + x[n-2] * y[2] + ...+ x[n-N+1] * y[N -1]
The function is internally divided into three stages according to the number of multiplications that has to be taken place between inputA samples and inputB samples. In the first stage of the algorithm, the multiplications increase by one for every iteration. In the second stage of the algorithm, srcBLen number of multiplications are done. In the third stage of the algorithm, the multiplications decrease by one for every iteration.
Set the output pointer to point to the firstIndex of the output sample to be calculated.
sum = x[0] * y[0] sum = x[0] * y[1] + x[1] * y[0] .... sum = x[0] * y[srcBlen - 1] + x[1] * y[srcBlen - 2] +...+ x[srcBLen - 1] * y[0]
In this stage the MAC operations are increased by 1 for every iteration. The count variable holds the number of MAC operations performed. Since the partial convolution starts from firstIndex Number of Macs to be performed is firstIndex + 1
Working pointer of inputA
Working pointer of inputB
For loop unrolling by 4, this stage is divided into two.
First part of this stage computes the MAC operations less than 4
Second part of this stage computes the MAC operations greater than or equal to 4
The first part of the stage starts here
Accumulator is made zero for every iteration
Loop over number of MAC operations between inputA samples and inputB samples
Perform the multiply-accumulates
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Increment the MAC count
Decrement the loop counter
The second part of the stage starts here
The internal loop, over count, is unrolled by 4
To, read the last two inputB samples using SIMD: y[srcBLen] and y[srcBLen-1] coefficients, py is decremented by 1
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Perform the multiply-accumulates
x[0], x[1] are multiplied with y[srcBLen - 1], y[srcBLen - 2] respectively
x[2], x[3] are multiplied with y[srcBLen - 3], y[srcBLen - 4] respectively
Decrement the loop counter
For the next MAC operations, the pointer py is used without SIMD So, py is incremented by 1
If the count is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulates
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Increment the MAC count
Decrement the loop counter
sum = x[0] * y[srcBLen-1] + x[1] * y[srcBLen-2] +...+ x[srcBLen-1] * y[0] sum = x[1] * y[srcBLen-1] + x[2] * y[srcBLen-2] +...+ x[srcBLen] * y[0] .... sum = x[srcALen-srcBLen-2] * y[srcBLen-1] + x[srcALen] * y[srcBLen-2] +...+ x[srcALen-1] * y[0]
Working pointer of inputA
Working pointer of inputB
count is the index by which the pointer pIn1 to be incremented
Stage2 depends on srcBLen as in this stage srcBLen number of MACS are performed. So, to loop unroll over blockSize2, srcBLen should be greater than or equal to 4
Loop unroll over blockSize2, by 4
Set all accumulators to zero
read x[0], x[1] samples
read x[1], x[2] samples
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Read the last two inputB samples using SIMD: y[srcBLen - 1] and y[srcBLen - 2]
acc0 += x[0] * y[srcBLen - 1] + x[1] * y[srcBLen - 2]
acc1 += x[1] * y[srcBLen - 1] + x[2] * y[srcBLen - 2]
Read x[2], x[3]
Read x[3], x[4]
acc2 += x[2] * y[srcBLen - 1] + x[3] * y[srcBLen - 2]
acc3 += x[3] * y[srcBLen - 1] + x[4] * y[srcBLen - 2]
Read y[srcBLen - 3] and y[srcBLen - 4]
acc0 += x[2] * y[srcBLen - 3] + x[3] * y[srcBLen - 4]
acc1 += x[3] * y[srcBLen - 3] + x[4] * y[srcBLen - 4]
Read x[4], x[5]
Read x[5], x[6]
acc2 += x[4] * y[srcBLen - 3] + x[5] * y[srcBLen - 4]
acc3 += x[5] * y[srcBLen - 3] + x[6] * y[srcBLen - 4]
For the next MAC operations, SIMD is not used So, the 16 bit pointer if inputB, py is updated
If the srcBLen is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Read y[srcBLen - 5]
Read x[7]
Perform the multiply-accumulates
Read y[srcBLen - 5], y[srcBLen - 6]
Read x[7], x[8]
Read x[9]
Perform the multiply-accumulates
Read y[srcBLen - 5], y[srcBLen - 6]
Read x[7], x[8]
Read x[9]
Perform the multiply-accumulates
Read x[10]
Perform the multiply-accumulates
Store the results in the accumulators in the destination buffer.
Increment the pointer pIn1 index, count by 4
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
If the blockSize2 is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Perform the multiply-accumulates
Decrement the loop counter
If the srcBLen is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulates
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the pointer pIn1 index, count by 1
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
If the srcBLen is not a multiple of 4, the blockSize2 loop cannot be unrolled by 4
Accumulator is made zero for every iteration
srcBLen number of MACS should be performed
Perform the multiply-accumulate
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the MAC count
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
sum += x[srcALen-srcBLen+1] * y[srcBLen-1] + x[srcALen-srcBLen+2] * y[srcBLen-2] +...+ x[srcALen-1] * y[1] sum += x[srcALen-srcBLen+2] * y[srcBLen-1] + x[srcALen-srcBLen+3] * y[srcBLen-2] +...+ x[srcALen-1] * y[2] .... sum += x[srcALen-2] * y[srcBLen-1] + x[srcALen-1] * y[srcBLen-2] sum += x[srcALen-1] * y[srcBLen-1]
In this stage the MAC operations are decreased by 1 for every iteration. The count variable holds the number of MAC operations performed
Working pointer of inputA
Working pointer of inputB
For loop unrolling by 4, this stage is divided into two.
First part of this stage computes the MAC operations greater than 4
Second part of this stage computes the MAC operations less than or equal to 4
The first part of the stage starts here
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
x[srcALen - srcBLen + 1], x[srcALen - srcBLen + 2] are multiplied with y[srcBLen - 1], y[srcBLen - 2] respectively
x[srcALen - srcBLen + 3], x[srcALen - srcBLen + 4] are multiplied with y[srcBLen - 3], y[srcBLen - 4] respectively
Decrement the loop counter
For the next MAC operations, the pointer py is used without SIMD So, py is incremented by 1
If the count is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
sum += x[srcALen - srcBLen + 5] * y[srcBLen - 5]
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Decrement the MAC count
Decrement the loop counter
The second part of the stage starts here
SIMD is not used for the next MAC operations, so pointer py is updated to read only one sample at a time
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
Perform the multiply-accumulates
sum += x[srcALen-1] * y[srcBLen-1]
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Decrement the MAC count
Decrement the loop counter
set status as ARM_MATH_SUCCESS
Return to application
Definition at line 67 of file arm_conv_partial_fast_q15.c.
arm_status arm_conv_partial_fast_q31 (q31_t * pSrcA, uint32_t srcALen, q31_t * pSrcB, uint32_t srcBLen, q31_t * pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q31 sequences (fast version) for Cortex-M3 and Cortex-M4.
Parameters
[in] *pSrcA points to the first input sequence.
[in] srcALen length of the first input sequence.
[in] *pSrcB points to the second input sequence.
[in] srcBLen length of the second input sequence.
[out] *pDst points to the location where the output result is written.
[in] firstIndex is the first output sample to start with.
[in] numPoints is the number of output points to be computed.
Returns
Returns either ARM_MATH_SUCCESS if the function completed correctly or ARM_MATH_ARGUMENT_ERROR if the requested subset is not in the range [0 srcALen+srcBLen-2].
See arm_conv_partial_q31() for a slower implementation of this function which uses a 64-bit accumulator to provide higher precision.
inputA pointer
inputB pointer
output pointer
Intermediate inputA pointer
Intermediate inputB pointer
Intermediate pointers
Accumulators
loop counters
status of Partial convolution
Check for range of output samples to be calculated
Set status as ARM_MATH_ARGUMENT_ERROR
The algorithm implementation is based on the lengths of the inputs.
srcB is always made to slide across srcA.
So srcBLen is always considered as shorter or equal to srcALen
Initialization of inputA pointer
Initialization of inputB pointer
Initialization of inputA pointer
Initialization of inputB pointer
srcBLen is always considered as shorter or equal to srcALen
Conditions to check which loopCounter holds the first and last indices of the output samples to be calculated.
conv(x,y) at n = x[n] * y[0] + x[n-1] * y[1] + x[n-2] * y[2] + ...+ x[n-N+1] * y[N -1]
The function is internally divided into three stages according to the number of multiplications that has to be taken place between inputA samples and inputB samples. In the first stage of the algorithm, the multiplications increase by one for every iteration. In the second stage of the algorithm, srcBLen number of multiplications are done. In the third stage of the algorithm, the multiplications decrease by one for every iteration.
Set the output pointer to point to the firstIndex of the output sample to be calculated.
sum = x[0] * y[0] sum = x[0] * y[1] + x[1] * y[0] .... sum = x[0] * y[srcBlen - 1] + x[1] * y[srcBlen - 2] +...+ x[srcBLen - 1] * y[0]
In this stage the MAC operations are increased by 1 for every iteration. The count variable holds the number of MAC operations performed. Since the partial convolution starts from firstIndex Number of Macs to be performed is firstIndex + 1
Working pointer of inputA
Working pointer of inputB
The first loop starts here
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
x[0] * y[srcBLen - 1]
x[1] * y[srcBLen - 2]
x[2] * y[srcBLen - 3]
x[3] * y[srcBLen - 4]
Decrement the loop counter
If the count is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulates
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Increment the MAC count
Decrement the loop counter
sum = x[0] * y[srcBLen-1] + x[1] * y[srcBLen-2] +...+ x[srcBLen-1] * y[0] sum = x[1] * y[srcBLen-1] + x[2] * y[srcBLen-2] +...+ x[srcBLen] * y[0] .... sum = x[srcALen-srcBLen-2] * y[srcBLen-1] + x[srcALen] * y[srcBLen-2] +...+ x[srcALen-1] * y[0]
Working pointer of inputA
Working pointer of inputB
count is index by which the pointer pIn1 to be incremented
Stage2 depends on srcBLen as in this stage srcBLen number of MACS are performed. So, to loop unroll over blockSize2, srcBLen should be greater than or equal to 4
Loop unroll over blockSize2
Set all accumulators to zero
read x[0], x[1], x[2] samples
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Read y[srcBLen - 1] sample
Read x[3] sample
Perform the multiply-accumulate
acc0 += x[0] * y[srcBLen - 1]
acc1 += x[1] * y[srcBLen - 1]
acc2 += x[2] * y[srcBLen - 1]
acc3 += x[3] * y[srcBLen - 1]
Read y[srcBLen - 2] sample
Read x[4] sample
Perform the multiply-accumulate
acc0 += x[1] * y[srcBLen - 2]
acc1 += x[2] * y[srcBLen - 2]
acc2 += x[3] * y[srcBLen - 2]
acc3 += x[4] * y[srcBLen - 2]
Read y[srcBLen - 3] sample
Read x[5] sample
Perform the multiply-accumulates
acc0 += x[2] * y[srcBLen - 3]
acc1 += x[3] * y[srcBLen - 2]
acc2 += x[4] * y[srcBLen - 2]
acc3 += x[5] * y[srcBLen - 2]
Read y[srcBLen - 4] sample
Read x[6] sample
Perform the multiply-accumulates
acc0 += x[3] * y[srcBLen - 4]
acc1 += x[4] * y[srcBLen - 4]
acc2 += x[5] * y[srcBLen - 4]
acc3 += x[6] * y[srcBLen - 4]
If the srcBLen is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Read y[srcBLen - 5] sample
Read x[7] sample
Perform the multiply-accumulates
acc0 += x[4] * y[srcBLen - 5]
acc1 += x[5] * y[srcBLen - 5]
acc2 += x[6] * y[srcBLen - 5]
acc3 += x[7] * y[srcBLen - 5]
Reuse the present samples for the next MAC
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the pointer pIn1 index, count by 4
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
If the blockSize2 is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Perform the multiply-accumulates
Decrement the loop counter
If the srcBLen is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulate
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the MAC count
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
If the srcBLen is not a multiple of 4, the blockSize2 loop cannot be unrolled by 4
Accumulator is made zero for every iteration
srcBLen number of MACS should be performed
Perform the multiply-accumulate
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the MAC count
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
sum += x[srcALen-srcBLen+1] * y[srcBLen-1] + x[srcALen-srcBLen+2] * y[srcBLen-2] +...+ x[srcALen-1] * y[1] sum += x[srcALen-srcBLen+2] * y[srcBLen-1] + x[srcALen-srcBLen+3] * y[srcBLen-2] +...+ x[srcALen-1] * y[2] .... sum += x[srcALen-2] * y[srcBLen-1] + x[srcALen-1] * y[srcBLen-2] sum += x[srcALen-1] * y[srcBLen-1]
In this stage the MAC operations are decreased by 1 for every iteration. The count variable holds the number of MAC operations performed
Working pointer of inputA
Working pointer of inputB
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
sum += x[srcALen - srcBLen + 1] * y[srcBLen - 1]
sum += x[srcALen - srcBLen + 2] * y[srcBLen - 2]
sum += x[srcALen - srcBLen + 3] * y[srcBLen - 3]
sum += x[srcALen - srcBLen + 4] * y[srcBLen - 4]
Decrement the loop counter
If the count is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulates
sum += x[srcALen-1] * y[srcBLen-1]
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Decrement the MAC count
Decrement the loop counter
set status as ARM_MATH_SUCCESS
Return to application
Definition at line 67 of file arm_conv_partial_fast_q31.c.
arm_status arm_conv_partial_opt_q15 (q15_t * pSrcA, uint32_t srcALen, q15_t * pSrcB, uint32_t srcBLen, q15_t * pDst, uint32_t firstIndex, uint32_t numPoints, q15_t * pScratch1, q15_t * pScratch2)
Partial convolution of Q15 sequences.
Parameters
[in] *pSrcA points to the first input sequence.
[in] srcALen length of the first input sequence.
[in] *pSrcB points to the second input sequence.
[in] srcBLen length of the second input sequence.
[out] *pDst points to the location where the output result is written.
[in] firstIndex is the first output sample to start with.
[in] numPoints is the number of output points to be computed.
[in] *pScratch1 points to scratch buffer of size max(srcALen, srcBLen) + 2*min(srcALen, srcBLen) - 2.
[in] *pScratch2 points to scratch buffer of size min(srcALen, srcBLen).
Returns
Returns either ARM_MATH_SUCCESS if the function completed correctly or ARM_MATH_ARGUMENT_ERROR if the requested subset is not in the range [0 srcALen+srcBLen-2].
Restrictions
If the silicon does not support unaligned memory access enable the macro UNALIGNED_SUPPORT_DISABLE In this case input, output, state buffers should be aligned by 32-bit
Refer to arm_conv_partial_fast_q15() for a faster but less precise version of this function for Cortex-M3 and Cortex-M4.
output pointer
Temporary pointer for scratch1
Temporary pointer for scratch1
Accumulator
Temporary variables to hold state and coefficient values
State variables
inputA pointer
inputB pointer
Intermediate inputA pointer
Intermediate inputB pointer
loop counter
Status variable
loop count
Check for range of output samples to be calculated
Set status as ARM_MATH_ARGUMENT_ERROR
The algorithm implementation is based on the lengths of the inputs.
srcB is always made to slide across srcA.
So srcBLen is always considered as shorter or equal to srcALen
Initialization of inputA pointer
Initialization of inputB pointer
Initialization of inputA pointer
Initialization of inputB pointer
srcBLen is always considered as shorter or equal to srcALen
Temporary pointer for scratch2
pointer to take end of scratch2 buffer
points to smaller length sequence
Apply loop unrolling and do 4 Copies simultaneously.
First part of the processing with loop unrolling copies 4 data points at a time. a second loop below copies for the remaining 1 to 3 samples.
copy second buffer in reversal manner
Decrement the loop counter
If the count is not a multiple of 4, copy remaining samples here. No loop unrolling is used.
copy second buffer in reversal manner for remaining samples
Decrement the loop counter
Initialze temporary scratch pointer
Fill (srcBLen - 1u) zeros in scratch buffer
Update temporary scratch pointer
Copy bigger length sequence(srcALen) samples in scratch1 buffer
Copy (srcALen) samples in scratch buffer
Update pointers
Fill (srcBLen - 1u) zeros at end of scratch buffer
Update pointer
Initialization of pIn2 pointer
Actual convolution process starts here
Initialze temporary scratch pointer as scratch1
Clear Accumlators
Read two samples from scratch1 buffer
Read next two samples from scratch1 buffer
Read four samples from smaller buffer
multiply and accumlate
pack input data
multiply and accumlate
Read next two samples from scratch1 buffer
multiply and accumlate
pack input data
update scratch pointers
Decrement the loop counter
Update scratch pointer for remaining samples of smaller length sequence
apply same above for remaining samples of smaller length sequence
accumlate the results
Decrement the loop counter
Store the results in the accumulators in the destination buffer.
Initialization of inputB pointer
Calculate convolution for remaining samples of Bigger length sequence
Initialze temporary scratch pointer as scratch1
Clear Accumlators
Read next two samples from scratch1 buffer
Read two samples from smaller buffer
Decrement the loop counter
apply same above for remaining samples of smaller length sequence
accumlate the results
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Initialization of inputB pointer
set status as ARM_MATH_SUCCESS
Return to application
Definition at line 76 of file arm_conv_partial_opt_q15.c.
References arm_conv_partial_opt_q15(), arm_copy_q15(), and arm_fill_q15().
Referenced by arm_conv_partial_opt_q15().
arm_status arm_conv_partial_opt_q7 (q7_t * pSrcA, uint32_t srcALen, q7_t * pSrcB, uint32_t srcBLen, q7_t * pDst, uint32_t firstIndex, uint32_t numPoints, q15_t * pScratch1, q15_t * pScratch2)
Partial convolution of Q7 sequences.
Parameters
[in] *pSrcA points to the first input sequence.
[in] srcALen length of the first input sequence.
[in] *pSrcB points to the second input sequence.
[in] srcBLen length of the second input sequence.
[out] *pDst points to the location where the output result is written.
[in] firstIndex is the first output sample to start with.
[in] numPoints is the number of output points to be computed.
[in] *pScratch1 points to scratch buffer(of type q15_t) of size max(srcALen, srcBLen) + 2*min(srcALen, srcBLen) - 2.
[in] *pScratch2 points to scratch buffer (of type q15_t) of size min(srcALen, srcBLen).
Returns
Returns either ARM_MATH_SUCCESS if the function completed correctly or ARM_MATH_ARGUMENT_ERROR if the requested subset is not in the range [0 srcALen+srcBLen-2].
Restrictions
If the silicon does not support unaligned memory access enable the macro UNALIGNED_SUPPORT_DISABLE In this case input, output, scratch1 and scratch2 buffers should be aligned by 32-bit
Intermediate pointers for scratch pointers
Temporary input variable
inputA and inputB pointer
loop counter
Temporary input1 pointer
Temporary input2 pointer
Accumulator
Temporary input variables
output pointer
temporary variables
Check for range of output samples to be calculated
Set status as ARM_MATH_ARGUMENT_ERROR
The algorithm implementation is based on the lengths of the inputs.
srcB is always made to slide across srcA.
So srcBLen is always considered as shorter or equal to srcALen
Initialization of inputA pointer
Initialization of inputB pointer
Initialization of inputA pointer
Initialization of inputB pointer
srcBLen is always considered as shorter or equal to srcALen
pointer to take end of scratch2 buffer
points to smaller length sequence
Apply loop unrolling and do 4 Copies simultaneously.
First part of the processing with loop unrolling copies 4 data points at a time. a second loop below copies for the remaining 1 to 3 samples.
copy second buffer in reversal manner
Decrement the loop counter
If the count is not a multiple of 4, copy remaining samples here. No loop unrolling is used.
copy second buffer in reversal manner for remaining samples
Decrement the loop counter
Initialze temporary scratch pointer
Fill (srcBLen - 1u) zeros in scratch buffer
Update temporary scratch pointer
Copy (srcALen) samples in scratch buffer
Apply loop unrolling and do 4 Copies simultaneously.
First part of the processing with loop unrolling copies 4 data points at a time. a second loop below copies for the remaining 1 to 3 samples.
copy second buffer in reversal manner
Decrement the loop counter
If the count is not a multiple of 4, copy remaining samples here. No loop unrolling is used.
copy second buffer in reversal manner for remaining samples
Decrement the loop counter
Fill (srcBLen - 1u) zeros at end of scratch buffer
Update pointer
Temporary pointer for scratch2
Initialization of pIn2 pointer
Actual convolution process starts here
Initialze temporary scratch pointer as scratch1
Clear Accumlators
Read two samples from scratch1 buffer
Read next two samples from scratch1 buffer
Read four samples from smaller buffer
multiply and accumlate
pack input data
multiply and accumlate
Read next two samples from scratch1 buffer
pack input data
Read four samples from smaller buffer
Decrement the loop counter
Update scratch pointer for remaining samples of smaller length sequence
apply same above for remaining samples of smaller length sequence
accumlate the results
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Initialization of inputB pointer
Calculate convolution for remaining samples of Bigger length sequence
Initialze temporary scratch pointer as scratch1
Clear Accumlators
Read next two samples from scratch1 buffer
Read two samples from smaller buffer
Decrement the loop counter
apply same above for remaining samples of smaller length sequence
accumlate the results
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Initialization of inputB pointer
set status as ARM_MATH_SUCCESS
Definition at line 76 of file arm_conv_partial_opt_q7.c.
References arm_conv_partial_opt_q7(), and arm_fill_q15().
Referenced by arm_conv_partial_opt_q7().
arm_status arm_conv_partial_q15 (q15_t * pSrcA, uint32_t srcALen, q15_t * pSrcB, uint32_t srcBLen, q15_t * pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q15 sequences.
Parameters
[in] *pSrcA points to the first input sequence.
[in] srcALen length of the first input sequence.
[in] *pSrcB points to the second input sequence.
[in] srcBLen length of the second input sequence.
[out] *pDst points to the location where the output result is written.
[in] firstIndex is the first output sample to start with.
[in] numPoints is the number of output points to be computed.
Returns
Returns either ARM_MATH_SUCCESS if the function completed correctly or ARM_MATH_ARGUMENT_ERROR if the requested subset is not in the range [0 srcALen+srcBLen-2].
Refer to arm_conv_partial_fast_q15() for a faster but less precise version of this function for Cortex-M3 and Cortex-M4.
Refer the function arm_conv_partial_opt_q15() for a faster implementation of this function using scratch buffers.
Run the below code for Cortex-M0
inputA pointer
inputB pointer
Accumulator
loop counters
status of Partial convolution
Check for range of output samples to be calculated
Set status as ARM_ARGUMENT_ERROR
Loop to calculate convolution for output length number of values
Initialize sum with zero to carry on MAC operations
Loop to perform MAC operations according to convolution equation
Check the array limitations
z[i] += x[i-j] * y[j]
Store the output in the destination buffer
set status as ARM_SUCCESS as there are no argument errors
Definition at line 71 of file arm_conv_partial_q15.c.
arm_status arm_conv_partial_q31 (q31_t * pSrcA, uint32_t srcALen, q31_t * pSrcB, uint32_t srcBLen, q31_t * pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q31 sequences.
Parameters
[in] *pSrcA points to the first input sequence.
[in] srcALen length of the first input sequence.
[in] *pSrcB points to the second input sequence.
[in] srcBLen length of the second input sequence.
[out] *pDst points to the location where the output result is written.
[in] firstIndex is the first output sample to start with.
[in] numPoints is the number of output points to be computed.
Returns
Returns either ARM_MATH_SUCCESS if the function completed correctly or ARM_MATH_ARGUMENT_ERROR if the requested subset is not in the range [0 srcALen+srcBLen-2].
See arm_conv_partial_fast_q31() for a faster but less precise implementation of this function for Cortex-M3 and Cortex-M4.
Run the below code for Cortex-M4 and Cortex-M3
inputA pointer
inputB pointer
output pointer
Intermediate inputA pointer
Intermediate inputB pointer
Intermediate pointers
Accumulator
loop counter
status of Partial convolution
Check for range of output samples to be calculated
Set status as ARM_MATH_ARGUMENT_ERROR
The algorithm implementation is based on the lengths of the inputs.
srcB is always made to slide across srcA.
So srcBLen is always considered as shorter or equal to srcALen
Initialization of inputA pointer
Initialization of inputB pointer
Initialization of inputA pointer
Initialization of inputB pointer
srcBLen is always considered as shorter or equal to srcALen
Conditions to check which loopCounter holds the first and last indices of the output samples to be calculated.
conv(x,y) at n = x[n] * y[0] + x[n-1] * y[1] + x[n-2] * y[2] + ...+ x[n-N+1] * y[N -1]
The function is internally divided into three stages according to the number of multiplications that has to be taken place between inputA samples and inputB samples. In the first stage of the algorithm, the multiplications increase by one for every iteration. In the second stage of the algorithm, srcBLen number of multiplications are done. In the third stage of the algorithm, the multiplications decrease by one for every iteration.
Set the output pointer to point to the firstIndex of the output sample to be calculated.
sum = x[0] * y[0] sum = x[0] * y[1] + x[1] * y[0] .... sum = x[0] * y[srcBlen - 1] + x[1] * y[srcBlen - 2] +...+ x[srcBLen - 1] * y[0]
In this stage the MAC operations are increased by 1 for every iteration. The count variable holds the number of MAC operations performed. Since the partial convolution starts from firstIndex Number of Macs to be performed is firstIndex + 1
Working pointer of inputA
Working pointer of inputB
The first loop starts here
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
x[0] * y[srcBLen - 1]
x[1] * y[srcBLen - 2]
x[2] * y[srcBLen - 3]
x[3] * y[srcBLen - 4]
Decrement the loop counter
If the count is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulate
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Increment the MAC count
Decrement the loop counter
sum = x[0] * y[srcBLen-1] + x[1] * y[srcBLen-2] +...+ x[srcBLen-1] * y[0] sum = x[1] * y[srcBLen-1] + x[2] * y[srcBLen-2] +...+ x[srcBLen] * y[0] .... sum = x[srcALen-srcBLen-2] * y[srcBLen-1] + x[srcALen] * y[srcBLen-2] +...+ x[srcALen-1] * y[0]
Working pointer of inputA
Working pointer of inputB
count is index by which the pointer pIn1 to be incremented
Stage2 depends on srcBLen as in this stage srcBLen number of MACS are performed. So, to loop unroll over blockSize2, srcBLen should be greater than or equal to 4
Loop unroll over blkCnt
Set all accumulators to zero
read x[0], x[1] samples
Apply loop unrolling and compute 3 MACs simultaneously.
First part of the processing with loop unrolling. Compute 3 MACs at a time. a second loop below computes MACs for the remaining 1 to 2 samples.
Read y[srcBLen - 1] sample
Read x[2] sample
Perform the multiply-accumulates
acc0 += x[0] * y[srcBLen - 1]
acc1 += x[1] * y[srcBLen - 1]
acc2 += x[2] * y[srcBLen - 1]
Read y[srcBLen - 2] sample
Read x[3] sample
Perform the multiply-accumulate
acc0 += x[1] * y[srcBLen - 2]
acc1 += x[2] * y[srcBLen - 2]
acc2 += x[3] * y[srcBLen - 2]
Read y[srcBLen - 3] sample
Read x[4] sample
Perform the multiply-accumulates
acc0 += x[2] * y[srcBLen - 3]
acc1 += x[3] * y[srcBLen - 2]
acc2 += x[4] * y[srcBLen - 2]
If the srcBLen is not a multiple of 3, compute any remaining MACs here. No loop unrolling is used.
Read y[srcBLen - 5] sample
Read x[7] sample
Perform the multiply-accumulates
acc0 += x[4] * y[srcBLen - 5]
acc1 += x[5] * y[srcBLen - 5]
acc2 += x[6] * y[srcBLen - 5]
Reuse the present samples for the next MAC
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the pointer pIn1 index, count by 3
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
If the blockSize2 is not a multiple of 3, compute any remaining output samples here. No loop unrolling is used.
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Perform the multiply-accumulates
Decrement the loop counter
If the srcBLen is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulate
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the MAC count
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
If the srcBLen is not a multiple of 4, the blockSize2 loop cannot be unrolled by 4
Accumulator is made zero for every iteration
srcBLen number of MACS should be performed
Perform the multiply-accumulate
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the MAC count
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
sum += x[srcALen-srcBLen+1] * y[srcBLen-1] + x[srcALen-srcBLen+2] * y[srcBLen-2] +...+ x[srcALen-1] * y[1] sum += x[srcALen-srcBLen+2] * y[srcBLen-1] + x[srcALen-srcBLen+3] * y[srcBLen-2] +...+ x[srcALen-1] * y[2] .... sum += x[srcALen-2] * y[srcBLen-1] + x[srcALen-1] * y[srcBLen-2] sum += x[srcALen-1] * y[srcBLen-1]
In this stage the MAC operations are decreased by 1 for every iteration. The blockSize3 variable holds the number of MAC operations performed
Working pointer of inputA
Working pointer of inputB
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Decrement the loop counter
If the blockSize3 is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulate
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Decrement the MAC count
Decrement the loop counter
set status as ARM_MATH_SUCCESS
Return to application
Definition at line 66 of file arm_conv_partial_q31.c.
arm_status arm_conv_partial_q7 (q7_t * pSrcA, uint32_t srcALen, q7_t * pSrcB, uint32_t srcBLen, q7_t * pDst, uint32_t firstIndex, uint32_t numPoints)
Partial convolution of Q7 sequences.
Parameters
[in] *pSrcA points to the first input sequence.
[in] srcALen length of the first input sequence.
[in] *pSrcB points to the second input sequence.
[in] srcBLen length of the second input sequence.
[out] *pDst points to the location where the output result is written.
[in] firstIndex is the first output sample to start with.
[in] numPoints is the number of output points to be computed.
Returns
Returns either ARM_MATH_SUCCESS if the function completed correctly or ARM_MATH_ARGUMENT_ERROR if the requested subset is not in the range [0 srcALen+srcBLen-2].
Refer the function arm_conv_partial_opt_q7() for a faster implementation of this function.
Run the below code for Cortex-M4 and Cortex-M3
inputA pointer
inputB pointer
output pointer
Intermediate inputA pointer
Intermediate inputB pointer
Intermediate pointers
Accumulator
loop counter
Check for range of output samples to be calculated
Set status as ARM_MATH_ARGUMENT_ERROR
The algorithm implementation is based on the lengths of the inputs.
srcB is always made to slide across srcA.
So srcBLen is always considered as shorter or equal to srcALen
Initialization of inputA pointer
Initialization of inputB pointer
Initialization of inputA pointer
Initialization of inputB pointer
srcBLen is always considered as shorter or equal to srcALen
Conditions to check which loopCounter holds the first and last indices of the output samples to be calculated.
conv(x,y) at n = x[n] * y[0] + x[n-1] * y[1] + x[n-2] * y[2] + ...+ x[n-N+1] * y[N -1]
The function is internally divided into three stages according to the number of multiplications that has to be taken place between inputA samples and inputB samples. In the first stage of the algorithm, the multiplications increase by one for every iteration. In the second stage of the algorithm, srcBLen number of multiplications are done. In the third stage of the algorithm, the multiplications decrease by one for every iteration.
Set the output pointer to point to the firstIndex of the output sample to be calculated.
sum = x[0] * y[0] sum = x[0] * y[1] + x[1] * y[0] .... sum = x[0] * y[srcBlen - 1] + x[1] * y[srcBlen - 2] +...+ x[srcBLen - 1] * y[0]
In this stage the MAC operations are increased by 1 for every iteration. The count variable holds the number of MAC operations performed. Since the partial convolution starts from from firstIndex Number of Macs to be performed is firstIndex + 1
Working pointer of inputA
Working pointer of inputB
The first stage starts here
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
x[0] , x[1]
y[srcBLen - 1] , y[srcBLen - 2]
x[0] * y[srcBLen - 1]
x[1] * y[srcBLen - 2]
x[2] , x[3]
y[srcBLen - 3] , y[srcBLen - 4]
x[2] * y[srcBLen - 3]
x[3] * y[srcBLen - 4]
Decrement the loop counter
If the count is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulates
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Increment the MAC count
Decrement the loop counter
sum = x[0] * y[srcBLen-1] + x[1] * y[srcBLen-2] +...+ x[srcBLen-1] * y[0] sum = x[1] * y[srcBLen-1] + x[2] * y[srcBLen-2] +...+ x[srcBLen] * y[0] .... sum = x[srcALen-srcBLen-2] * y[srcBLen-1] + x[srcALen] * y[srcBLen-2] +...+ x[srcALen-1] * y[0]
Working pointer of inputA
Working pointer of inputB
count is index by which the pointer pIn1 to be incremented
Stage2 depends on srcBLen as in this stage srcBLen number of MACS are performed. So, to loop unroll over blockSize2, srcBLen should be greater than or equal to 4
Loop unroll over blockSize2, by 4
Set all accumulators to zero
read x[0], x[1], x[2] samples
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Read y[srcBLen - 1] sample
Read y[srcBLen - 2] sample
Read x[3] sample
x[0] and x[1] are packed
y[srcBLen - 1] and y[srcBLen - 2] are packed
acc0 += x[0] * y[srcBLen - 1] + x[1] * y[srcBLen - 2]
x[1] and x[2] are packed
acc1 += x[1] * y[srcBLen - 1] + x[2] * y[srcBLen - 2]
x[2] and x[3] are packed
acc2 += x[2] * y[srcBLen - 1] + x[3] * y[srcBLen - 2]
Read x[4] sample
x[3] and x[4] are packed
acc3 += x[3] * y[srcBLen - 1] + x[4] * y[srcBLen - 2]
Read y[srcBLen - 3] sample
Read y[srcBLen - 4] sample
Read x[5] sample
x[2] and x[3] are packed
y[srcBLen - 3] and y[srcBLen - 4] are packed
acc0 += x[2] * y[srcBLen - 3] + x[3] * y[srcBLen - 4]
x[3] and x[4] are packed
acc1 += x[3] * y[srcBLen - 3] + x[4] * y[srcBLen - 4]
x[4] and x[5] are packed
acc2 += x[4] * y[srcBLen - 3] + x[5] * y[srcBLen - 4]
Read x[6] sample
x[5] and x[6] are packed
acc3 += x[5] * y[srcBLen - 3] + x[6] * y[srcBLen - 4]
If the srcBLen is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Read y[srcBLen - 5] sample
Read x[7] sample
Perform the multiply-accumulates
acc0 += x[4] * y[srcBLen - 5]
acc1 += x[5] * y[srcBLen - 5]
acc2 += x[6] * y[srcBLen - 5]
acc3 += x[7] * y[srcBLen - 5]
Reuse the present samples for the next MAC
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the pointer pIn1 index, count by 4
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
If the blockSize2 is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Reading two inputs of SrcA buffer and packing
Reading two inputs of SrcB buffer and packing
Perform the multiply-accumulates
Reading two inputs of SrcA buffer and packing
Reading two inputs of SrcB buffer and packing
Perform the multiply-accumulates
Decrement the loop counter
If the srcBLen is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulates
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the pointer pIn1 index, count by 1
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
If the srcBLen is not a multiple of 4, the blockSize2 loop cannot be unrolled by 4
Accumulator is made zero for every iteration
srcBLen number of MACS should be performed
Perform the multiply-accumulate
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Increment the MAC count
Update the inputA and inputB pointers for next MAC calculation
Decrement the loop counter
sum += x[srcALen-srcBLen+1] * y[srcBLen-1] + x[srcALen-srcBLen+2] * y[srcBLen-2] +...+ x[srcALen-1] * y[1] sum += x[srcALen-srcBLen+2] * y[srcBLen-1] + x[srcALen-srcBLen+3] * y[srcBLen-2] +...+ x[srcALen-1] * y[2] .... sum += x[srcALen-2] * y[srcBLen-1] + x[srcALen-1] * y[srcBLen-2] sum += x[srcALen-1] * y[srcBLen-1]
In this stage the MAC operations are decreased by 1 for every iteration. The count variable holds the number of MAC operations performed
Working pointer of inputA
Working pointer of inputB
Accumulator is made zero for every iteration
Apply loop unrolling and compute 4 MACs simultaneously.
First part of the processing with loop unrolling. Compute 4 MACs at a time. a second loop below computes MACs for the remaining 1 to 3 samples.
Reading two inputs, x[srcALen - srcBLen + 1] and x[srcALen - srcBLen + 2] of SrcA buffer and packing
Reading two inputs, y[srcBLen - 1] and y[srcBLen - 2] of SrcB buffer and packing
sum += x[srcALen - srcBLen + 1] * y[srcBLen - 1]
sum += x[srcALen - srcBLen + 2] * y[srcBLen - 2]
Reading two inputs, x[srcALen - srcBLen + 3] and x[srcALen - srcBLen + 4] of SrcA buffer and packing
Reading two inputs, y[srcBLen - 3] and y[srcBLen - 4] of SrcB buffer and packing
sum += x[srcALen - srcBLen + 3] * y[srcBLen - 3]
sum += x[srcALen - srcBLen + 4] * y[srcBLen - 4]
Decrement the loop counter
If the count is not a multiple of 4, compute any remaining MACs here. No loop unrolling is used.
Perform the multiply-accumulates
sum += x[srcALen-1] * y[srcBLen-1]
Decrement the loop counter
Store the result in the accumulator in the destination buffer.
Update the inputA and inputB pointers for next MAC calculation
Decrement the MAC count
Decrement the loop counter
set status as ARM_MATH_SUCCESS
Return to application
Definition at line 68 of file arm_conv_partial_q7.c.