HEXIWEAR MK64 Firmware Reference Manual: gui/screens/6. sensorTag/inc/gui_sensorTag.h File Reference
gui_sensorTag.h File Reference
this file contains Sensor Tag mode objects' declarations and prototypes
#include "gui_driver.h"
Functions
void gui_sensorTag_Init (void *param)
void gui_sensorTag_CreateTasks (void *param)
void gui_sensorTag_DestroyTasks (void *param)
bool gui_sensorTag_IsActive ()
void gui_sensorTag_TurnOFF ()
void gui_sensorTag_TurnON ()
void gui_sensorTag_CheckAtStartup ()
Detailed Description
this file contains Sensor Tag mode objects' declarations and prototypes
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file gui_sensorTag.h.
Function Documentation
void gui_sensorTag_CheckAtStartup ()
check if sensor tag should be enabled at startup
Definition at line 256 of file gui_sensorTag_driver.c.
References gui_sensorTag_TurnON().
Referenced by HEXIWEAR_startup().
void gui_sensorTag_CreateTasks (void * param)
create sensor tag mode task
Parameters
param optional parameter
Definition at line 100 of file gui_sensorTag_driver.c.
References kStatus_OSA_Success, and OSA_TaskCreate().
void gui_sensorTag_DestroyTasks (void * param)
destroy sensor tag mode task
Parameters
param optional parameter
Definition at line 124 of file gui_sensorTag_driver.c.
References gui_sensorTag_TurnOFF(), gui_sensorTag_TurnON(), GuiDriver_ImageDraw(), GuiDriver_QueueMsgGet(), GuiDriver_UnregisterFromNavigation(), HEXIWEAR_SetFlags(), OLED_DestroyDynamicArea(), OSA_MsgQDestroy(), OSA_TaskDestroy(), OSA_WAIT_FOREVER, and packetType_pressRight.
void gui_sensorTag_Init (void * param)
initialize sensor tag mode structures and tasks
Parameters
param optional parameter
public API initialize sensor tag mode structures and tasks
Parameters
param optional parameter
Definition at line 76 of file gui_sensorTag_driver.c.
References oled_text_properties_t::fontColor, GuiDriver_ImageAddToScr(), GuiDriver_LabelAddToScr(), GuiDriver_RegisterForNavigation(), OSA_MsgQCreate(), and screen_labelEnter.
bool gui_sensorTag_IsActive ()
return task state
Returns
sensor tag mode status
return task state
Definition at line 181 of file gui_sensorTag_driver.c.
References sensor_GetPacketTargets(), sensor_RegisterPacketDelay(), sensor_ResetTargetsForKW40(), sensor_SetMinimumDelay(), and sensor_SetPacketTargets().
Referenced by bluetooth_AdvModeUpdate(), gui_heartRate_DestroyTasks(), gui_motionControl_Init(), gui_pedometer_DestroyTasks(), gui_weatherStation_Init(), heartRate_Init(), pedometer_Init(), sensor_Init(), watch_Init(), and watch_LinkStateUpdate().
void gui_sensorTag_TurnOFF ()
turn off sensor tag
Definition at line 237 of file gui_sensorTag_driver.c.
References GUI_CURRENT_APP_IDLE, GuiDriver_NotifyKW40(), power_SetSleepMode(), and POWER_SLEEP_MODE_TOTAL.
Referenced by gui_sensorTag_DestroyTasks(), heartRate_Init(), and pedometer_Init().
void gui_sensorTag_TurnON ()
turn on sensor tag
check for the bluetooth connection, to determine sleep mode
Definition at line 217 of file gui_sensorTag_driver.c.
References GUI_CURRENT_APP_SENSOR_TAG, GuiDriver_NotifyKW40(), watch_CurrentLinkStateGet(), and watch_LinkStateUpdate().
Referenced by gui_sensorTag_CheckAtStartup(), gui_sensorTag_DestroyTasks(), heartRate_Deinit(), and pedometer_Deinit().