HEXIWEAR MK64 Firmware Reference Manual: intf/inc/host_mcu_interface.h File Reference
host_mcu_interface.h File Reference
this file contains MCU-to-MCU interface info and routines' declarations
#include "fsl_os_abstraction.h"
#include "KW40_UART.h"
#include "hexiwear_info.h"
Data Structures
struct hostInterface_packet_t
Macros
#define gHostInterfaceRxTaskStackSize_c (0x1000)
Enumerations
Functions
osa_status_t HostInterface_Init (void)
osa_status_t HostInterface_TxQueueMsgPut (hostInterface_packet_t *hostInterface_Packet, bool confirmationReq)
osa_status_t HostInterface_TxInit (void)
osa_status_t HostInterface_RxInit (void)
osa_status_t HostInterface_RxQueueMsgPut (hostInterface_packet_t *pHostInterface_packet)
osa_status_t HostInterface_EventsInit (void)
osa_status_t HostInterface_EventConfirmPacketWait (void)
osa_status_t HostInterface_EventConfirmPacketSet (void)
osa_status_t HostInterface_EventConfirmPacketClear (void)
osa_status_t HostInterface_EventSendOkPacketSet (void)
osa_status_t HostInterface_EventSendOkPacketWait (void)
void HostInterface_SetWakingTouch ()
Detailed Description
this file contains MCU-to-MCU interface info and routines' declarations
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file host_mcu_interface.h.
Macro Definition Documentation
#define gHostInterfaceRxTaskStackSize_c (0x1000)
packet constants
Definition at line 46 of file host_mcu_interface.h.
Referenced by HostInterface_RxInit().
Enumeration Type Documentation
enum hostInterface_alertIn_type_t
incoming alert types
Definition at line 155 of file host_mcu_interface.h.
enum hostInterface_packetType_t
packet types
Enumerator
packetType_pressUp
touch press up
packetType_pressDown
touch press down
packetType_pressLeft
touch press left
packetType_pressRight
touch press right
packetType_slide
touch slide
packetType_batteryLevel
battery Service
packetType_accel
motion service
packetType_ambiLight
weather service
packetType_pressure
weather service
packetType_gyro
motion service
packetType_temperature
weather service
packetType_humidity
weather service
packetType_magnet
motion service
packetType_heartRate
health service
packetType_steps
health service
packetType_calories
health service
packetType_alertIn
incoming alerts
packetType_alertOut
outcoming alerts
packetType_passDisplay
key display type
packetType_appMode
app mode service
packetType_linkStateGet
connected
packetType_linkStateSend
disconnected
packetType_buildVersion
build version
packetType_sleepON
sleep ON
packetType_sleepOFF
sleep OFF
packetType_OK
OK packet
Definition at line 78 of file host_mcu_interface.h.
Function Documentation
osa_status_t HostInterface_EventConfirmPacketClear (void)
clear the OK packet event
Returns
status flag
Definition at line 147 of file host_mcu_interface_events.c.
Referenced by HostInterface_TxQueueMsgPut().
osa_status_t HostInterface_EventConfirmPacketSet (void)
set the OK packet event, i.e. confirm that the packet arrived
Returns
status flag
Definition at line 122 of file host_mcu_interface_events.c.
Referenced by HostInterface_RxInit().
osa_status_t HostInterface_EventConfirmPacketWait (void)
wait for the OK packet event
Returns
status flag
Definition at line 131 of file host_mcu_interface_events.c.
Referenced by HostInterface_TxQueueMsgPut().
osa_status_t HostInterface_EventSendOkPacketSet (void)
set the "send OK packet" event
Returns
status flag
Definition at line 156 of file host_mcu_interface_events.c.
References gHostInterface_eventSendOkPacketMask.
Referenced by HostInterface_RxQueueMsgPut().
osa_status_t HostInterface_EventSendOkPacketWait (void)
wait for the event "send OK packet"
Returns
status flag
Definition at line 165 of file host_mcu_interface_events.c.
References gHostInterface_eventSendOkPacketMask, and OSA_WAIT_FOREVER.
Referenced by HostInterface_TxQueueMsgPut().
osa_status_t HostInterface_EventsInit (void)
private prototypes functions definitions This function creates event object which will be used to wait for confirmation (OK packet) for previously sent packet
Returns
status flag
Definition at line 63 of file host_mcu_interface_events.c.
References kEventAutoClear, OSA_EventClear(), OSA_EventCreate(), OSA_EventSet(), and OSA_EventWait().
Referenced by HostInterface_Init().
osa_status_t HostInterface_Init (void)
Public prototypes
includes private memory declarations private prototypes functions definitions initialize comm module and set necessary objects
Returns
status flag
set the interrupt priority level
Definition at line 59 of file host_mcu_interface.c.
References HostInterface_EventsInit(), HostInterface_RxInit(), HostInterface_TxInit(), kStatus_OSA_Success, and NVIC_SetPriority().
Referenced by HEXIWEAR_startup().
osa_status_t HostInterface_RxInit (void)
initialize RX tasks and queues
Returns
task initialization status
Definition at line 335 of file host_mcu_interface_rx.c.
References gHostInterfaceRxTaskStackSize_c, hexiwear_intf_RX_handler, HostInterface_EventConfirmPacketSet(), HostInterface_RxQueueMsgPut(), hostInterface_rxState_dataWait, hostInterface_rxState_headerReceived, hostInterface_rxState_idle, hostInterface_rxState_trailerWait, kStatus_OSA_Success, OSA_MsgQCreate(), OSA_TaskCreate(), packetType_OK, UartState::rxBuff, and UART_DRV_InstallRxCallback().
Referenced by HostInterface_Init().
osa_status_t HostInterface_RxQueueMsgPut (hostInterface_packet_t * pHostInterface_packet)
This function puts a message to the end of the Tx message queue.
Parameters
pHostInterface_packet Packet that will be placed into Tx message queue.
Returns
kStatus_OSA_Success Message successfully put into the queue. kStatus_OSA_Error Process fail.
Definition at line 498 of file host_mcu_interface_rx.c.
References HostInterface_EventSendOkPacketSet(), kStatus_OSA_Error, kStatus_OSA_Success, OSA_MsgQGet(), and OSA_MsgQPut().
Referenced by HostInterface_RxInit().
void HostInterface_SetWakingTouch ()
mark registered touch as the first after wake-up
Definition at line 565 of file host_mcu_interface_rx.c.
Referenced by PORTC_IRQHandler(), and UART4_RX_TX_IRQHandler().
osa_status_t HostInterface_TxInit (void)
functions definitions create RTOS structures for sending data via communication interface
Returns
status flag
Definition at line 93 of file host_mcu_interface_tx.c.
References hexiwear_intf_OK_handler, hexiwear_intf_TX_handler, kStatus_OSA_Error, kStatus_OSA_Success, OSA_MsgQCreate(), OSA_MutexCreate(), and OSA_TaskCreate().
Referenced by HostInterface_Init().
osa_status_t HostInterface_TxQueueMsgPut (hostInterface_packet_t * pHostInterface_packet, bool confirmationReq)
This function puts a message to the end of the Tx message queue.
Parameters
pHostInterface_packet Packet that will be placed into Tx message queue.
Returns
kStatus_OSA_Success Message successfully put into the queue. kStatus_OSA_Error Process fail.
Definition at line 164 of file host_mcu_interface_tx.c.
References HostInterface_EventConfirmPacketClear(), HostInterface_EventConfirmPacketWait(), HostInterface_EventSendOkPacketWait(), kStatus_OSA_Error, kStatus_OSA_Success, kStatus_OSA_Timeout, OSA_MsgQGet(), OSA_MutexLock(), OSA_MutexUnlock(), OSA_WAIT_FOREVER, packetType_accel, POWER_CURRENT_MODE_SLEEP_SENSOR_TAG, power_GetCurrentMode(), power_GotoSleep(), power_SetSleepSource(), power_TurnScreenON(), UART_DRV_SendDataBlocking(), and UART_TIMEOUT.
Referenced by bluetooth_SendGetAdvModeReq(), bluetooth_SendToggleAdvModeReq(), bootloader_DestroyTasks(), buttonsGroup_SendGetActiveReq(), buttonsGroup_SendToggleActiveReq(), GuiDriver_NotifyKW40(), heartRate_Process(), HEXIWEAR_SendVersionReq(), pedometer_GetCalories(), power_AlertKW40(), sensor_InitAcc(), and watch_SendGetLinkStateReq().