HEXIWEAR MK64 Firmware Reference Manual: intf/src/host_mcu_interface.c File Reference
host_mcu_interface.c File Reference
this file contains MCU-to-MCU interface related routines
#include <stdint.h>
#include <stddef.h>
#include "board.h"
#include "fsl_os_abstraction.h"
#include "fsl_interrupt_manager.h"
#include "host_mcu_interface.h"
#include "fsl_uart_driver.h"
#include "error.h"
#include "HEXIWEAR_info.h"
Functions
osa_status_t HostInterface_Init ()
Detailed Description
this file contains MCU-to-MCU interface related routines
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file host_mcu_interface.c.
Function Documentation
osa_status_t HostInterface_Init (void)
includes private memory declarations private prototypes functions definitions initialize comm module and set necessary objects
Returns
status flag
set the interrupt priority level
Definition at line 59 of file host_mcu_interface.c.
References HostInterface_EventsInit(), HostInterface_RxInit(), HostInterface_TxInit(), kStatus_OSA_Success, and NVIC_SetPriority().
Referenced by HEXIWEAR_startup().