HEXIWEAR MK64 Firmware Reference Manual: intf/src/host_mcu_interface_events.c File Reference
host_mcu_interface_events.c File Reference
this file contains MCU-to-MCU interface events
#include <stdint.h>
#include <stddef.h>
#include "board.h"
#include "host_mcu_interface.h"
#include "fsl_interrupt_manager.h"
Functions
osa_status_t HostInterface_EventsInit ()
osa_status_t HostInterface_EventConfirmPacketSet ()
osa_status_t HostInterface_EventConfirmPacketWait ()
osa_status_t HostInterface_EventConfirmPacketClear ()
osa_status_t HostInterface_EventSendOkPacketSet ()
osa_status_t HostInterface_EventSendOkPacketWait ()
Variables
const event_flags_t gHostInterface_eventSendOkPacketMask = 1 << 1
Detailed Description
this file contains MCU-to-MCU interface events
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file host_mcu_interface_events.c.
Function Documentation
osa_status_t HostInterface_EventConfirmPacketClear (void)
clear the OK packet event
Returns
status flag
Definition at line 147 of file host_mcu_interface_events.c.
Referenced by HostInterface_TxQueueMsgPut().
osa_status_t HostInterface_EventConfirmPacketSet (void)
set the OK packet event, i.e. confirm that the packet arrived
Returns
status flag
Definition at line 122 of file host_mcu_interface_events.c.
Referenced by HostInterface_RxInit().
osa_status_t HostInterface_EventConfirmPacketWait (void)
wait for the OK packet event
Returns
status flag
Definition at line 131 of file host_mcu_interface_events.c.
Referenced by HostInterface_TxQueueMsgPut().
osa_status_t HostInterface_EventSendOkPacketSet (void)
set the "send OK packet" event
Returns
status flag
Definition at line 156 of file host_mcu_interface_events.c.
References gHostInterface_eventSendOkPacketMask.
Referenced by HostInterface_RxQueueMsgPut().
osa_status_t HostInterface_EventSendOkPacketWait (void)
wait for the event "send OK packet"
Returns
status flag
Definition at line 165 of file host_mcu_interface_events.c.
References gHostInterface_eventSendOkPacketMask, and OSA_WAIT_FOREVER.
Referenced by HostInterface_TxQueueMsgPut().
osa_status_t HostInterface_EventsInit (void)
private prototypes functions definitions This function creates event object which will be used to wait for confirmation (OK packet) for previously sent packet
Returns
status flag
Definition at line 63 of file host_mcu_interface_events.c.
References kEventAutoClear, OSA_EventClear(), OSA_EventCreate(), OSA_EventSet(), and OSA_EventWait().
Referenced by HostInterface_Init().
Variable Documentation
const event_flags_t gHostInterface_eventSendOkPacketMask = 1 << 1
include global constants declarations
Definition at line 47 of file host_mcu_interface_events.c.
Referenced by HostInterface_EventSendOkPacketSet(), and HostInterface_EventSendOkPacketWait().