HEXIWEAR MK64 Firmware Reference Manual: notifications/inc/notifications_driver.h File Reference
notifications_driver.h File Reference
this file contains incoming alert routines
#include "fsl_os_abstraction.h"
#include "notifications_types.h"
Functions
void Notification_SetUnreadCounter (notification_type_t notifType, uint8_t value)
uint8_t Notification_GetUnreadCounter (notification_type_t notifType)
notification_status_t Notification_Init ()
notification_status_t Notification_WaitForEvent (notification_type_t *notifType, uint32_t timeout)
notification_status_t Notification_SetEvent (notification_type_t notifType)
Detailed Description
this file contains incoming alert routines
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file notifications_driver.h.
Function Documentation
uint8_t Notification_GetUnreadCounter (notification_type_t notifType)
get the notifications' counter's value
Parameters
notifType notification type
Returns
counter's value
Definition at line 204 of file notifications_driver.c.
Referenced by gui_notifications_DestroyTasks(), gui_notifications_Init(), watch_Init(), and watch_SetNotification().
notification_status_t Notification_Init ()
initialize the notification event
Returns
status flag
public API initialize the notification event
Returns
status flag
Definition at line 67 of file notifications_driver.c.
References kEventAutoClear, kStatus_OSA_Success, and OSA_EventCreate().
Referenced by HEXIWEAR_startup().
notification_status_t Notification_SetEvent (notification_type_t notifType)
set the notification event
Parameters
type notification type
Returns
status flag
Definition at line 126 of file notifications_driver.c.
References kStatus_OSA_Success, and OSA_EventSet().
void Notification_SetUnreadCounter (notification_type_t notifType, uint8_t value)
public API prototypes set the notifications' counter's value
Parameters
notifType notification type
value counter's value
set the notifications' counter's value
Parameters
notifType notification type
value counter's value
Definition at line 174 of file notifications_driver.c.
Referenced by watch_LinkStateUpdate().
notification_status_t Notification_WaitForEvent (notification_type_t * notifType, uint32_t timeout)
wait for the notification event
Parameters
type notification type
timeout timeout value in [ms]
Returns
status flag
Definition at line 85 of file notifications_driver.c.
References kStatus_OSA_Success, and OSA_EventWait().
Referenced by gui_notifications_DestroyTasks().