HEXIWEAR MK64 Firmware Reference Manual: power/src/power_driver.c File Reference
power_driver.c File Reference
this file contains power management routines
#include "power.h"
#include "OLED_driver.h"
#include "OLED_info.h"
#include "sensor_driver.h"
#include "timer_driver.h"
#include "PWR_Manager.h"
#include "screens_common.h"
#include "error.h"
#include "GPIO.h"
#include "fsl_i2c_master_driver.h"
Functions
power_status_t power_Init ()
bool power_IsActive (power_peripheral_t peripheral)
power_status_t power_TurnON (power_peripheral_t peripheral)
power_status_t power_TurnOFF (power_peripheral_t peripheral)
void power_GotoSleep ()
void power_SensorManagement ()
void power_ResetKW40 ()
void power_EnablePowerSave ()
void power_DisablePowerSave ()
void power_SetSleepSource (power_sleep_src_t sleepSrc)
power_sleep_src_t power_GetSleepSource ()
power_status_t power_SetWakeSource (power_wake_src_t wakeSrc)
power_wake_src_t power_GetWakeSource ()
bool power_HasJustExitSleep ()
void power_SetCurrentMode (power_current_mode_t newMode)
power_current_mode_t power_GetCurrentMode ()
void power_SetSleepMode (power_sleep_mode_t newMode)
power_sleep_mode_t power_GetSleepMode ()
void power_TurnScreenOFF ()
void power_TurnScreenON ()
power_status_t power_PostToSTSema ()
power_status_t power_TakeFromSTSema ()
power_status_t power_AlertKW40 (power_sleepState_t sleepState)
power_manager_error_code_t power_CallBeforeSleep (power_manager_notify_struct_t *notify, power_manager_callback_data_t *callbackData)
power_manager_error_code_t power_CallAfterSleep (power_manager_notify_struct_t *notify, power_manager_callback_data_t *callbackData)
bool power_IsBatteryLow ()
void power_SetBatteryLow ()
void power_UnsetBatteryLow ()
Detailed Description
this file contains power management routines
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file power_driver.c.
Function Documentation
power_status_t power_AlertKW40 (power_sleepState_t sleepState)
send sleep ON/OFF packet to KW40
Parameters
sleepState desired sleep state
Returns
status flag
Definition at line 872 of file power_driver.c.
References HostInterface_TxQueueMsgPut(), kStatus_OSA_Success, packetType_sleepOFF, and packetType_sleepON.
power_manager_error_code_t power_CallAfterSleep (power_manager_notify_struct_t * notify, power_manager_callback_data_t * callbackData)
call after exiting sleep mode
Parameters
notify optional parameters
callbackData optional parameters
Returns
flag
disable UART edge interrupt circuit
Definition at line 938 of file power_driver.c.
References g_uartBase, and kPowerManagerSuccess.
power_manager_error_code_t power_CallBeforeSleep (power_manager_notify_struct_t * notify, power_manager_callback_data_t * callbackData)
call before entering sleep mode
Parameters
notify optional parameters
callbackData optional parameters
Returns
status flag
enable UART edge interrupt circuit,
post to semaphore to make it available to interrupts
Definition at line 916 of file power_driver.c.
References g_uartBase, kPowerManagerSuccess, and OSA_SemaPost().
void power_DisablePowerSave ()
disable the power save feature: disable OLED disable current sensor subscriptions
Definition at line 696 of file power_driver.c.
References RTC_DisableAlarm().
Referenced by bond_Init(), bootloader_DestroyTasks(), getApp_Init(), gui_heartRate_QueueMsgPut(), and gui_pedometer_QueueMsgPut().
void power_EnablePowerSave ()
enable the power save feature: enable OLED enable current sensor subscriptions
Definition at line 685 of file power_driver.c.
References RTC_EnableAlarm().
Referenced by bond_DestroyTasks(), bootloader_DestroyTasks(), getApp_Destroy(), gui_heartRate_DestroyTasks(), gui_heartRate_QueueMsgPut(), gui_pedometer_DestroyTasks(), and gui_pedometer_QueueMsgPut().
power_current_mode_t power_GetCurrentMode ()
get current HEXIWEAR mode
Returns
current mode
Definition at line 771 of file power_driver.c.
Referenced by HostInterface_TxQueueMsgPut(), PORTC_IRQHandler(), RTC_AlarmCallback(), sensor_Init(), sensor_InitAcc(), timer_Stop(), and UART4_RX_TX_IRQHandler().
power_sleep_mode_t power_GetSleepMode ()
get currently selected sleep mode
Returns
current sleep mode
Definition at line 792 of file power_driver.c.
Referenced by power_TurnOFF(), and RTC_AlarmCallback().
power_sleep_src_t power_GetSleepSource ()
get sleep source
Returns
current entity which will put the MCU to sleep
Definition at line 715 of file power_driver.c.
power_wake_src_t power_GetWakeSource ()
get wakeup source
Returns
current entity which will wake up the MCU
Definition at line 741 of file power_driver.c.
void power_GotoSleep ()
public API put HEXIWEAR to sleep
Definition at line 601 of file power_driver.c.
Referenced by HostInterface_TxQueueMsgPut(), RTC_AlarmCallback(), and sensor_Init().
bool power_HasJustExitSleep ()
check if this was the touch that woken the MCU
Returns
touch flag
Definition at line 750 of file power_driver.c.
power_status_t power_Init ()
initialize the power task and relevant power objects
Returns
status flag
Definition at line 116 of file power_driver.c.
References HEXIWEAR_STARTUP_PRIO, kStatus_OSA_Success, OSA_SemaCreate(), and OSA_TaskCreate().
Referenced by HEXIWEAR_startup().
bool power_IsActive (power_peripheral_t peripheral)
return power flags
Parameters
peripheral peripheral which flags to return
Returns
flag
Definition at line 160 of file power_driver.c.
Referenced by sensor_InitAcc().
bool power_IsBatteryLow ()
check for battery status
Returns
status flag
Definition at line 952 of file power_driver.c.
Referenced by sensor_Init().
power_status_t power_PostToSTSema ()
fill the semaphore for wake-up sources to take
Returns
status flag
Definition at line 833 of file power_driver.c.
References kStatus_OSA_Success, and OSA_SemaPost().
void power_ResetKW40 ()
set BLE_RST pin to 0 and then release it
Definition at line 672 of file power_driver.c.
References GPIO_DRV_ClearPinOutput(), GPIO_DRV_SetPinOutput(), and OSA_TimeDelay().
Referenced by HEXIWEAR_startup().
void power_SensorManagement ()
activate/deactivate power supplies for sensors
humidity & ambient light
MAXIM
battery reading
Definition at line 612 of file power_driver.c.
References sensor_GetPacketTargets().
Referenced by sensor_Init().
void power_SetBatteryLow ()
set battery status as low
Definition at line 960 of file power_driver.c.
Referenced by sensor_InitAcc().
void power_SetCurrentMode (power_current_mode_t newMode)
set current HEXIWEAR mode
Parameters
newMode mode to set
Definition at line 759 of file power_driver.c.
Referenced by PORTC_IRQHandler(), RTC_AlarmCallback(), and UART4_RX_TX_IRQHandler().
void power_SetSleepMode (power_sleep_mode_t newMode)
set new power mode
Parameters
new desired power mode
Definition at line 780 of file power_driver.c.
Referenced by gui_sensorTag_TurnOFF(), and watch_LinkStateUpdate().
void power_SetSleepSource (power_sleep_src_t sleepSrc)
set sleep source
Parameters
sleepSrc entity which will put the MCU to sleep
Definition at line 706 of file power_driver.c.
Referenced by HostInterface_TxQueueMsgPut(), RTC_AlarmCallback(), and sensor_Init().
power_status_t power_SetWakeSource (power_wake_src_t wakeSrc)
set wakeup source
Parameters
wakeupSrc entity which will wake up the MCU
Definition at line 724 of file power_driver.c.
References kStatus_OSA_Success, and OSA_SemaWait().
Referenced by PORTC_IRQHandler(), timer_Stop(), and UART4_RX_TX_IRQHandler().
power_status_t power_TakeFromSTSema ()
take semaphore to signalize the wake-up happened
Returns
status flag
Definition at line 852 of file power_driver.c.
References kStatus_OSA_Success, and OSA_SemaWait().
power_status_t power_TurnOFF (power_peripheral_t peripheral)
turn the selected peripheral OFF
Parameters
peripheral peripheral to turn off
Returns
status flag
Definition at line 221 of file power_driver.c.
References CLOCK_SYS_UpdateConfiguration(), I2C_DRV_MasterGetReceiveStatus(), I2C_DRV_MasterGetSendStatus(), kClockManagerPolicyForcible, kPowerManagerPolicyAgreement, kPowerManagerRun, kStatus_I2C_Success, kStatus_OSA_Error, kStatus_OSA_Success, OSA_SemaPost(), OSA_SemaWait(), OSA_TimeDelay(), OSA_WAIT_FOREVER, POWER_CURRENT_MODE_SLEEP_SENSOR_TAG, POWER_CURRENT_MODE_SLEEP_SHALLOW, POWER_CURRENT_MODE_SLEEP_TOTAL, power_GetSleepMode(), POWER_SLEEP_MODE_SENSOR_TAG, POWER_SLEEP_MODE_SHALLOW, POWER_SLEEP_MODE_TOTAL, POWER_SYS_GetCurrentMode(), POWER_SYS_SetMode(), power_TurnScreenOFF(), power_TurnScreenON(), RTC_EnableAlarm(), RTC_UpdateAlarm(), timer_IsActive(), timer_Start(), and timer_Stop().
Referenced by OLED_Init().
power_status_t power_TurnON (power_peripheral_t peripheral)
turn the selected peripheral ON
Parameters
peripheral peripheral to turn on
Returns
status flag
Definition at line 200 of file power_driver.c.
Referenced by OLED_Init().
void power_TurnScreenOFF ()
turn the screen off by sending the command and turning off the power supply
Definition at line 801 of file power_driver.c.
References GPIO_DRV_ClearPinOutput(), OLED_SendCmd(), and OLED_STATUS_SUCCESS.
Referenced by power_TurnOFF().
void power_TurnScreenON ()
turn the screen on by switching on the power supply and sending the command
Definition at line 816 of file power_driver.c.
References GPIO_DRV_SetPinOutput(), GPIO_DRV_TogglePinOutput(), OLED_SendCmd(), OLED_STATUS_SUCCESS, and OSA_TimeDelay().
Referenced by HostInterface_TxQueueMsgPut(), and power_TurnOFF().
void power_UnsetBatteryLow ()
unset battery status as low
Definition at line 968 of file power_driver.c.
Referenced by sensor_InitAcc().