HEXIWEAR MK64 Firmware Reference Manual: timers/src/timer_driver.c File Reference
timer_driver.c File Reference
this file contains functionality for timers used throughout HEXIWEAR
#include "timer_driver.h"
#include "power_driver.h"
#include "gui_sensorTag.h"
Functions
void timer_Init (hexiwear_timer_t timerToUse)
void timer_Deinit (hexiwear_timer_t timerToUse)
bool timer_IsActive (hexiwear_timer_t timerToUse)
void timer_Start (hexiwear_timer_t timerToUse)
void timer_SetPeriod (hexiwear_timer_t timerToUse, uint32_t newPeriod)
void timer_Stop (hexiwear_timer_t timerToUse)
Detailed Description
this file contains functionality for timers used throughout HEXIWEAR
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file timer_driver.c.
Function Documentation
void timer_Deinit (hexiwear_timer_t timerToUse)
deinitialize the timer
Parameters
timerToUse selected timer peripheral
Definition at line 77 of file timer_driver.c.
References FSL_SENSOR_TIMER.
void timer_Init (hexiwear_timer_t timerToUse)
initialize the timer
Parameters
timerToUse selected timer peripheral
Definition at line 54 of file timer_driver.c.
References FSL_SENSOR_TIMER, HEXIWEAR_TIMER_IRQ_PRIO, and NVIC_SetPriority().
Referenced by HEXIWEAR_startup().
bool timer_IsActive (hexiwear_timer_t timerToUse)
get timer state
Parameters
timerToUse selected timer peripheral
Definition at line 99 of file timer_driver.c.
Referenced by power_TurnOFF().
void timer_SetPeriod (hexiwear_timer_t timerToUse, uint32_t newPeriod)
set the period for the chosen timer
Parameters
timerToUse selected timer peripheral
newPeriod new desired timer period
Definition at line 142 of file timer_driver.c.
References FSL_SENSOR_TIMER.
Referenced by sensor_InitAcc().
void timer_Start (hexiwear_timer_t timerToUse)
start the timer
Parameters
timerToUse selected timer peripheral
Definition at line 119 of file timer_driver.c.
References FSL_SENSOR_TIMER.
Referenced by power_TurnOFF(), and sensor_Resume().
void timer_Stop (hexiwear_timer_t timerToUse)
stop the timer
Parameters
timerToUse selected timer peripheral
Definition at line 159 of file timer_driver.c.
References FSL_SENSOR_TIMER, POWER_CURRENT_MODE_SLEEP_SENSOR_TAG, POWER_CURRENT_MODE_SLEEP_SHALLOW, POWER_CURRENT_MODE_SLEEP_TOTAL, power_GetCurrentMode(), power_SetWakeSource(), and sensor_StopWait().
Referenced by power_TurnOFF(), and sensor_Suspend().