HEXIWEAR MK64 Firmware Reference Manual: gui/screens/1. watch/inc/watch.h File Reference
watch.h File Reference
this file contains watch screen objects and prototypes intended to be available for the rest of the project
#include "fsl_rtc_driver.h"
#include "gui_driver.h"
Functions
void watch_CheckBatteryStatus ()
linkState_t watch_CurrentLinkStateGet (void)
void watch_SendGetLinkStateReq (void)
osa_status_t watch_WaitForLinkStateUpdate (uint32_t timeout)
osa_status_t watch_LinkStateUpdate (linkState_t new_linkState)
void watch_CreateLinkStateUpdateEvent (void)
void watch_SetNotification ()
bool watch_IsBatteryCharging ()
Variables
guiScreen_t watchScreen
Detailed Description
this file contains watch screen objects and prototypes intended to be available for the rest of the project
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file watch.h.
Function Documentation
void watch_CheckBatteryStatus ()
check charging status on the interrupt
check for the charging status in the interrupt
Definition at line 653 of file watch_driver.c.
References RTC_UpdateAlarm(), and watch_SetBatteryChargeEvent().
Referenced by PORTC_IRQHandler(), and watch_SetNotification().
void watch_CreateLinkStateUpdateEvent (void)
create the event for the watch screen
Definition at line 120 of file watch_driver.c.
References kEventAutoClear, and OSA_EventCreate().
Referenced by GuiDriver_Init().
linkState_t watch_CurrentLinkStateGet (void)
check for the current bluetooth link state
Returns
bluetooth link state
Definition at line 129 of file watch_driver.c.
Referenced by gui_sensorTag_TurnON(), heartRate_Process(), pedometer_GetCalories(), and sensor_Init().
bool watch_IsBatteryCharging ()
return battery charge status flag
Returns
charge status flag
Definition at line 681 of file watch_driver.c.
Referenced by watch_SetNotification().
osa_status_t watch_LinkStateUpdate (linkState_t new_linkState)
update local flags and notifications counters upon receiving the current link state from KW40
Parameters
new_linkState new bluetooth link state
Returns
status flag
Definition at line 177 of file watch_driver.c.
References GUI_CURRENT_APP_SENSOR_TAG, gui_sensorTag_IsActive(), GuiDriver_NotifyKW40(), kStatus_OSA_Success, Notification_SetUnreadCounter(), OSA_EventSet(), power_SetSleepMode(), POWER_SLEEP_MODE_SENSOR_TAG, POWER_SLEEP_MODE_TOTAL, sensor_RestoreTargetsForKW40(), sensor_SaveTargetsForKW40(), and watch_SetNotification().
Referenced by bluetooth_AdvModeUpdate(), and gui_sensorTag_TurnON().
void watch_SendGetLinkStateReq (void)
send the bluetooth link state query to KW40
Definition at line 137 of file watch_driver.c.
References HostInterface_TxQueueMsgPut(), kStatus_OSA_Success, and packetType_linkStateGet.
Referenced by GuiDriver_Init().
void watch_SetNotification ()
set notifications event
Definition at line 453 of file watch_driver.c.
References GuiDriver_ImageDraw(), GuiDriver_LabelDraw(), GuiDriver_QueueMsgGet(), kStatus_OSA_Success, Notification_GetUnreadCounter(), OSA_EventSet(), OSA_EventWait(), OSA_WAIT_FOREVER, packetType_batteryLevel, packetType_temperature, sensor_ResetPacketcounter(), watch_CheckBatteryStatus(), watch_imgBattery, watch_imgBluetoothLogo, watch_imgCall, watch_imgMail, watch_imgSms, watch_IsBatteryCharging(), watch_labelDate, watch_labelTemp, and watch_labelTime.
Referenced by watch_LinkStateUpdate().
osa_status_t watch_WaitForLinkStateUpdate (uint32_t timeout)
wait for the bluetooth link state query response from KW40
Parameters
timeout timeout value in [ms]
Returns
status flag
Definition at line 156 of file watch_driver.c.
References kStatus_OSA_Error, kStatus_OSA_Success, and OSA_EventWait().
Referenced by GuiDriver_Init().
Variable Documentation
guiScreen_t watchScreen
Definition of watch screen
Definition at line 45 of file watch_objects.c.
Referenced by GuiDriver_Navigation().