<?xml version='1.0' encoding='UTF-8'?>
<workspace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workingsets.xsd">
	<projects>
		<project>
			<name>HEXIWEAR_MK64_MK64FN1M0VDC12</name>
			<path>.</path>
			<open>true</open>
			<activeconfig>debug</activeconfig>
			<buildreferences config="debug">false</buildreferences>
			<activeconfig>release</activeconfig>
			<buildreferences config="release">false</buildreferences>
		</project>
	</projects>
	<workingsets>
		<workingSet editPageId="org.eclipse.cdt.ui.CElementWorkingSetPage" id="1323268527287_1" label="HEXIWEAR_MK64" name="HEXIWEAR_MK64">
			<item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/HEXIWEAR_MK64_MK64FN1M0VDC12" type="4" />
		</workingSet>
	</workingsets>
	<cdtconfigurations>
		<workingSet name="HEXIWEAR_MK64">
			<config name="debug">
				<project config="com.freescale.arm.cdt.toolchain.config.arm.release.695495605" configName="debug" name="HEXIWEAR_MK64_MK64FN1M0VDC12" />
			</config>
			<config name="release">
				<project config="com.freescale.arm.cdt.toolchain.config.arm.release.695495605" configName="release" name="HEXIWEAR_MK64_MK64FN1M0VDC12" />
			</config>
		</workingSet>
	</cdtconfigurations>
</workspace>