HEXIWEAR MK64 Firmware Reference Manual: sensors/MAXIM/inc/MAXIM_driver.h File Reference
MAXIM_driver.h File Reference
this file contains sensor MAX30101's implemented functionality
#include "MAXIM_types.h"
#include "arm_math.h"
Functions
maxim_status_t MAXIM_Init (handleMAXIM_t *maximHandle, const settingsMAXIM_t *maximSettings)
maxim_status_t MAXIM_Deinit ()
maxim_status_t MAXIM_Reset ()
maxim_status_t MAXIM_ReadRawData (uint8_t *dataBuff, uint8_t *sampleNum)
void hr_fmtDef2Float (const void *src, void *dst, uint32_t idx)
void hr_fmtDef2Me (const void *src, void *dst, uint32_t idx)
maxim_status_t MAXIM_Enable ()
maxim_status_t MAXIM_Disable ()
void MAXIM_InstallCallback (maxim_callback_t callback)
void MAXIM_Test ()
Detailed Description
this file contains sensor MAX30101's implemented functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file MAXIM_driver.h.
Function Documentation
void hr_fmtDef2Float (const void * src, void * dst, uint32_t idx)
format raw to float
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
formatting functions format raw to float
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
Definition at line 485 of file MAXIM_driver.c.
void hr_fmtDef2Me (const void * src, void * dst, uint32_t idx)
format raw to mE format
Parameters
src original data array
dst new format data array
idx index of the sample to be formatted
Definition at line 498 of file MAXIM_driver.c.
maxim_status_t MAXIM_Deinit ()
shutdown the sensor
shutdown the sensor
Returns
status flag
Definition at line 151 of file MAXIM_driver.c.
References I2C_Deinit(), and STATUS_I2C_SUCCESS.
maxim_status_t MAXIM_Disable ()
[MAXIM_Disable description]
Returns
[description]
disable the sensor
Returns
status flag
Definition at line 429 of file MAXIM_driver.c.
Referenced by heartRate_Process(), MAXIM_Test(), and sensor_InitAcc().
maxim_status_t MAXIM_Enable ()
[MAXIM_Enable description]
Returns
[description]
enable the sensor
Returns
status flag
Definition at line 395 of file MAXIM_driver.c.
References I2C_WriteReg(), and STATUS_I2C_SUCCESS.
Referenced by heartRate_Process(), MAXIM_Test(), and sensor_InitAcc().
maxim_status_t MAXIM_Init (handleMAXIM_t * maximHandle, const settingsMAXIM_t * maximSettings)
initialize MAXIM module
initialize MAXIM module
Parameters
maximHandle sensor's handle structure
maximSettings sensor's user settings
Returns
status flag
initialize intern structures, which will be used from now on
set up the registers
clear FIFO pointers
Definition at line 85 of file MAXIM_driver.c.
References I2C_Init(), I2C_WriteReg(), MAXIM_Reset(), OSA_TimeDelay(), and STATUS_I2C_SUCCESS.
Referenced by MAXIM_Test(), and sensor_InitAcc().
void MAXIM_InstallCallback (maxim_callback_t callback)
[MAXIM_InstallCallback description]
Parameters
callback [description]
callback to be invoked during sensor's read
Parameters
callback callback's function pointer
Definition at line 459 of file MAXIM_driver.c.
Referenced by sensor_InitAcc().
maxim_status_t MAXIM_ReadRawData (uint8_t * dataBuff, uint8_t * sampleNum)
read raw sensor data
read raw sensor data
Parameters
dataBuff buffer to place the samples in
sampleNum number of read samples
Returns
status flag
dummy read
reset the pointers
NUM_AVAILABLE_SAMPLES = FIFO_WR_PTR – FIFO_RD_PTR NUM_SAMPLES_TO_READ = < less than or equal to NUM_AVAILABLE_SAMPLES >
read all the available samples, FIFO RD pointer is implicitly incremented after each successful sample read
save data
Definition at line 237 of file MAXIM_driver.c.
References I2C_DRV_MasterReceiveDataBlocking(), I2C_ReadReg(), and STATUS_I2C_SUCCESS.
Referenced by sensor_Init().
maxim_status_t MAXIM_Reset ()
reset the module when the reset-bit is set to one, all configuration, threshold, and data registers are reset to their power-on-state through a power-on reset
the reset bit is cleared automatically back to zero after the reset sequence is completed
reset the module when the reset-bit is set to one, all configuration, threshold, and data registers are reset to their power-on-state through a power-on reset the reset bit is cleared automatically back to zero after the reset sequence is completed
Returns
[description]
Definition at line 182 of file MAXIM_driver.c.
References foo, I2C_ReadReg(), I2C_WriteReg(), OSA_TimeDelay(), and STATUS_I2C_SUCCESS.
Referenced by MAXIM_Init(), and MAXIM_Test().
void MAXIM_Test ()
testing HR sensor
test the sensor
Definition at line 467 of file MAXIM_driver.c.
References MAXIM_Disable(), MAXIM_Enable(), MAXIM_Init(), MAXIM_Reset(), and OSA_TimeDelay().