HEXIWEAR MK64 Firmware Reference Manual: gui/screens/4. settings/4.1 bluetooth/src/bluetooth_driver.c File Reference
bluetooth_driver.c File Reference
this file contains bluetooth GUI functionality
#include "gui_driver.h"
#include "screens_common.h"
#include "bluetooth_private.h"
#include "host_mcu_interface.h"
#include "fsl_os_abstraction.h"
Macros
#define MSEC_TO_TICK(msec)
Converts milliseconds to ticks.
Functions
void bluetooth_CreateAdvModeUpdateEvent ()
void bluetooth_Init (void *param)
void bluetooth_CreateTasks (void *param)
void bluetooth_DestroyTasks (void *param)
bluetooth_advMode_t bluetooth_CurrentAdvModeGet ()
void bluetooth_SendGetAdvModeReq ()
void bluetooth_SendToggleAdvModeReq ()
osa_status_t bluetooth_WaitForAdvModeUpdate (uint32_t timeout)
osa_status_t bluetooth_AdvModeUpdate (bluetooth_advMode_t bluetooth_advMode)
Variables
task_handler_t bluetooth_AdvModeToggleHandler
Detailed Description
this file contains bluetooth GUI functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file bluetooth_driver.c.
Macro Definition Documentation
#define MSEC_TO_TICK (msec)
Value:
(((uint32_t)(msec)+500uL/(uint32_t)configTICK_RATE_HZ) \
                             *(uint32_t)configTICK_RATE_HZ/1000uL)
Converts milliseconds to ticks.
includes private type definitions private macros
Definition at line 52 of file bluetooth_driver.c.
Function Documentation
osa_status_t bluetooth_AdvModeUpdate (bluetooth_advMode_t bluetooth_advMode)
update the advertisement mode
Parameters
bluetooth_advMode new mode
Returns
status flag
Definition at line 251 of file bluetooth_driver.c.
References bluetooth_SendGetAdvModeReq(), bluetooth_SendToggleAdvModeReq(), bluetooth_WaitForAdvModeUpdate(), GUI_CURRENT_APP_SENSOR_TAG, gui_sensorTag_IsActive(), GuiDriver_ImageDraw(), GuiDriver_NotifyKW40(), GuiDriver_QueueMsgGet(), kStatus_OSA_Success, OSA_EventSet(), OSA_TimeDelay(), OSA_WAIT_FOREVER, packetType_pressRight, and watch_LinkStateUpdate().
void bluetooth_CreateAdvModeUpdateEvent (void)
create the event for bluetooth update
Definition at line 85 of file bluetooth_driver.c.
References kEventAutoClear, and OSA_EventCreate().
Referenced by GuiDriver_Init().
void bluetooth_CreateTasks (void * param)
create bluetooth GUI tasks
Parameters
param optional parameter
Definition at line 115 of file bluetooth_driver.c.
References bluetooth_AdvModeToggleHandler, kStatus_OSA_Success, and OSA_TaskCreate().
bluetooth_advMode_t bluetooth_CurrentAdvModeGet (void)
get current advertisement mode
Returns
current mode
Definition at line 185 of file bluetooth_driver.c.
Referenced by bootloader_Init().
void bluetooth_DestroyTasks (void * param)
destroy bluetooth GUI tasks
Parameters
param optional parameter
Definition at line 158 of file bluetooth_driver.c.
References bluetooth_AdvModeToggleHandler, GuiDriver_UnregisterFromNavigation(), kStatus_OSA_Success, OLED_DestroyDynamicArea(), and OSA_TaskDestroy().
void bluetooth_Init (void * param)
initialize bluetooth GUI
Parameters
param optional parameter
Definition at line 94 of file bluetooth_driver.c.
References GuiDriver_ImageAddToScr(), and GuiDriver_RegisterForNavigation().
void bluetooth_SendGetAdvModeReq (void)
send request to get advertisement mode
Definition at line 193 of file bluetooth_driver.c.
References HostInterface_TxQueueMsgPut(), and kStatus_OSA_Success.
Referenced by bluetooth_AdvModeUpdate(), and GuiDriver_Init().
void bluetooth_SendToggleAdvModeReq (void)
send request to toggle advertisement mode
Definition at line 211 of file bluetooth_driver.c.
References HostInterface_TxQueueMsgPut(), and kStatus_OSA_Success.
Referenced by bluetooth_AdvModeUpdate().
osa_status_t bluetooth_WaitForAdvModeUpdate (uint32_t timeout)
wait for the mode update
Parameters
timeout time to wait in [ms]
Returns
status flag
Definition at line 231 of file bluetooth_driver.c.
References kStatus_OSA_Error, kStatus_OSA_Success, and OSA_EventWait().
Referenced by bluetooth_AdvModeUpdate(), and GuiDriver_Init().
Variable Documentation
task_handler_t bluetooth_AdvModeToggleHandler
Public memory declarations
Definition at line 67 of file bluetooth_driver.c.
Referenced by bluetooth_CreateTasks(), and bluetooth_DestroyTasks().