HEXIWEAR MK64 Firmware Reference Manual: intern_flash/src/flash_boot_kinetis.c File Reference
flash_boot_kinetis.c File Reference
This file this file contains internal FLASH functionality.
#include "FLASH_boot_kinetis.h"
#include "MK64F12.h"
#include "MK64F12_cfg.h"
#include "fsl_os_abstraction.h"
Macros
#define FLASH_PGM_SIZE (8)
Functions
void INTFLASH_Init ()
uint8_t INTFLASH_Program (uint32_t dest, uint32_t source, uint32_t size)
uint8_t INTFLASH_ProgramLongWords (uint32_t destination, uint32_t source, uint32_t size)
uint8_t INTFLASH_ProgramLongWord (uint32_t destination, uint32_t data32b)
uint8_t INTFLASH_ProgramSection (uint32_t destination, uint32_t *pSource, uint32_t size)
uint8_t INTFLASH_ProgramSectionPhrases (uint32_t destination, uint32_t *pSource, uint32_t size)
uint8_t INTFLASH_ProgramByte (uint32_t destination, uint8_t data8b)
uint8_t INTFLASH_ProgramHwRev (hexiwear_hw_rev_t *source)
uint8_t INTFLASH_ReadHwRev (hexiwear_hw_rev_t *dst)
uint8_t INTFLASH_EraseSector (uint32_t destination)
uint8_t INTFLASH_MassErase (void)
uint8_t INTFLASH_SetEEEEnable (uint8_t ctrl_code)
Variables
uint8_t pCommandArray [FCCOB_REGS]
volatile uint32_t foo
Detailed Description
This file this file contains internal FLASH functionality.
Copyright (c) 2015, NXP Semiconductor, Inc. All rights reserved.
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
o Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
o Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
o Neither the name of NXP Semiconductor, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file flash_boot_kinetis.c.
Macro Definition Documentation
#define FLASH_PGM_SIZE (8)
include private macros
Definition at line 46 of file flash_boot_kinetis.c.
Referenced by INTFLASH_Program().
Function Documentation
uint8_t INTFLASH_EraseSector (uint32_t destination)
erase FLASH memory sector (0x800)
Parameters
destination FLASH address
Returns
status flag
Definition at line 437 of file flash_boot_kinetis.c.
Referenced by bootloader_DestroyTasks(), and HEXIWEAR_SetFlags().
void INTFLASH_Init ()
public API initialize the FLASH module
Definition at line 81 of file flash_boot_kinetis.c.
References foo.
Referenced by HEXIWEAR_startup().
uint8_t INTFLASH_MassErase (void)
erase of all block of memory
Definition at line 449 of file flash_boot_kinetis.c.
uint8_t INTFLASH_Program (uint32_t dest, uint32_t source, uint32_t size)
generically program FLASH
Parameters
dest FLASH address
source data address
size data size to program
Returns
status flag
Check for unaligned destination address
data must be multiple of FLASH_PGM_SIZE
preparing passing parameter to program the FLASH block
calling FLASH command sequence function to execute the command
update destination address for next iteration
update size for next iteration
Definition at line 123 of file flash_boot_kinetis.c.
References FLASH_PGM_SIZE.
Referenced by bootloader_DestroyTasks(), and HEXIWEAR_SetFlags().
uint8_t INTFLASH_ProgramByte (uint32_t destination, uint8_t data8b)
program one byte
Parameters
destination FLASH address
data8b byte to program
Returns
status flag
Definition at line 353 of file flash_boot_kinetis.c.
References FLASH_PROGRAM_BYTE.
uint8_t INTFLASH_ProgramHwRev (hexiwear_hw_rev_t * source)
program HW revision structure
Parameters
source HW revision structure's address
Returns
status flag
preparing passing parameter to program the FLASH block
calling FLASH command sequence function to execute the command
Definition at line 367 of file flash_boot_kinetis.c.
uint8_t INTFLASH_ProgramLongWord (uint32_t destination, uint32_t data32b)
program one long word
Parameters
dest FLASH address
source data address
size data size to program
Returns
status flag
preparing passing parameter to program the FLASH block
Definition at line 235 of file flash_boot_kinetis.c.
Referenced by INTFLASH_ProgramLongWords(), and INTFLASH_ProgramSectionPhrases().
uint8_t INTFLASH_ProgramLongWords (uint32_t destination, uint32_t source, uint32_t size)
program multiple long words
Parameters
dest FLASH address
source data address
size data size to program
Returns
status flag
Go to previous aligned address
Definition at line 187 of file flash_boot_kinetis.c.
References INTFLASH_ProgramLongWord().
uint8_t INTFLASH_ProgramSection (uint32_t destination, uint32_t * pSource, uint32_t size)
program one section (maximum is 2048 Bytes)
Parameters
destination FLASH address
pSource data address
size data size to program
Returns
status flag
preparing passing parameter to program the FLASH block
Definition at line 253 of file flash_boot_kinetis.c.
uint8_t INTFLASH_ProgramSectionPhrases (uint32_t destination, uint32_t * pSource, uint32_t size)
program section phrases
Parameters
destination FLASH address
pSource data address
size data size to program
Returns
status flag
preparing passing parameter to program the FLASH block
Definition at line 298 of file flash_boot_kinetis.c.
References INTFLASH_ProgramLongWord().
uint8_t INTFLASH_ReadHwRev (hexiwear_hw_rev_t * dst)
read HW revision
Parameters
dst HW revision structure to populate with info
Returns
status flag
preparing passing parameter to program the FLASH block
calling FLASH command sequence function to execute the command
Definition at line 397 of file flash_boot_kinetis.c.
References foo.
Referenced by info_Init().
uint8_t INTFLASH_SetEEEEnable (uint8_t ctrl_code)
enable the EERAM
Definition at line 458 of file flash_boot_kinetis.c.
References kCriticalDisableInt, OSA_EnterCritical(), and OSA_ExitCritical().
Variable Documentation
volatile uint32_t foo
dummy variables
Definition at line 73 of file flash_boot_kinetis.c.
Referenced by FXAS_SoftReset(), heartRate_Process(), hum_fmtDef2Me(), INTFLASH_Init(), INTFLASH_ReadHwRev(), MAXIM_Reset(), MPL_ReadRawData(), OLED_DimScreenOFF(), RTC_TriggerAlarm(), temp_fmtDef2Me(), and TSL_CalculateLux().
uint8_t pCommandArray[FCCOB_REGS]
private memory declarations
Definition at line 53 of file flash_boot_kinetis.c.