HEXIWEAR MK64 Firmware Reference Manual: protocols/I2C/inc/generic_i2c_driver.h File Reference
generic_i2c_driver.h File Reference
this file contains wrappers to manipulate with specific registers via I2C
#include "generic_i2c_types.h"
#include <stdbool.h>
Functions
statusI2C_t I2C_Init (genericI2cHandle_t *self, uint8_t devAddr, uint16_t baudrate_kbps)
statusI2C_t I2C_Deinit (genericI2cHandle_t *self)
statusI2C_t I2C_WriteReg (genericI2cHandle_t *self, uint8_t reg, uint8_t val)
statusI2C_t I2C_ReadReg (genericI2cHandle_t *self, uint8_t regAddr, uint8_t *valToReceive)
statusI2C_t I2C_ModifyReg (genericI2cHandle_t *self, uint8_t reg, uint8_t clrMask, uint8_t setMask)
statusI2C_t I2C_Recover (genericI2cHandle_t *self)
Detailed Description
this file contains wrappers to manipulate with specific registers via I2C
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file generic_i2c_driver.h.
Function Documentation
statusI2C_t I2C_Deinit (genericI2cHandle_t * self)
deinitialize I2C (not used)
Definition at line 110 of file generic_i2c_driver.c.
References STATUS_I2C_DEINIT_ERROR, and STATUS_I2C_SUCCESS.
Referenced by FXAS_Deinit(), FXOS_Deinit(), HTU_Deinit(), MAXIM_Deinit(), MPL_Deinit(), and TSL_Deinit().
statusI2C_t I2C_Init (genericI2cHandle_t * self, uint8_t devAddr, uint16_t baudrate_kbps)
initialize I2C
Parameters
self I2C handle
devAddr device address
baudrate_kbps desired baud-rate
Returns
status flag
Definition at line 64 of file generic_i2c_driver.c.
References FSL_FS_I2C, FSL_NFS_I2C, I2C_DRV_MasterInit(), I2C_DRV_MasterSetBaudRate(), NVIC_SetPriority(), OSA_MutexCreate(), and STATUS_I2C_SUCCESS.
Referenced by FXAS_Init(), FXOS_Init(), HTU_Init(), MAXIM_Init(), MPL_Init(), and TSL_Init().
statusI2C_t I2C_ModifyReg (genericI2cHandle_t * self, uint8_t reg, uint8_t clrMask, uint8_t setMask)
modify the specified register value the process is done via I2C
Parameters
self I2C handle
reg register address
clrMask mask to clear register value bits
setMask mask to set register value bits
Returns
status flag
Definition at line 261 of file generic_i2c_driver.c.
References I2C_ReadReg(), I2C_WriteReg(), kStatus_I2C_Success, and STATUS_I2C_ERROR.
Referenced by FXOS_CalibrateAcc(), FXOS_CalibrateMag(), FXOS_GotoStandby(), FXOS_Init(), and FXOS_SetActive().
statusI2C_t I2C_ReadReg (genericI2cHandle_t * self, uint8_t regAddr, uint8_t * valToReceive)
Read the specified register value The reading process is done via I2C
Parameters
self I2C handle
regAddr register address
valToReceive register value to receive
Returns
[description]
Definition at line 202 of file generic_i2c_driver.c.
References I2C_DRV_MasterReceiveDataBlocking(), kStatus_I2C_Success, OSA_MutexLock(), OSA_MutexUnlock(), OSA_WAIT_FOREVER, STATUS_I2C_ERROR, and STATUS_I2C_SUCCESS.
Referenced by FXAS_GetReady(), FXAS_GotoStandby(), FXAS_SetActive(), FXAS_SoftReset(), FXOS_Callback(), FXOS_DisableTap(), FXOS_ReadRawTemp(), FXOS_TapHandler(), I2C_ModifyReg(), MAXIM_ReadRawData(), MAXIM_Reset(), MPL_GotoStandby(), MPL_ReadRawData(), MPL_SetActive(), MPL_SetMode(), MPL_SetOversampleRate(), MPL_SoftReset(), MPL_ToggleOneShot(), and TSL_ReadRawData().
statusI2C_t I2C_Recover (genericI2cHandle_t * self)
if needed, recover I2C by resetting the state on the bus
Parameters
self I2C handle
Returns
status flag
reset I2C bus
Definition at line 293 of file generic_i2c_driver.c.
References FSL_FS_I2C, FSL_NFS_I2C, g_gpioBase, g_portBase, GPIO_HAL_SetPinDir(), I2C_DRV_MasterDeinit(), I2C_DRV_MasterGetReceiveStatus(), I2C_DRV_MasterGetSendStatus(), I2C_DRV_MasterInit(), kGpioDigitalOutput, kPortMuxAsGpio, kStatus_I2C_Success, OSA_TimeDelay(), STATUS_I2C_ERROR, STATUS_I2C_INIT_ERROR, STATUS_I2C_SUCCESS, and STATUS_I2C_TIMEOUT_ERROR.
Referenced by FXOS_RecoverI2C(), and HTU_RecoverI2C().
statusI2C_t I2C_WriteReg (genericI2cHandle_t * self, uint8_t reg, uint8_t val)
Write to the specified register The writing process is done via I2C
Parameters
self I2C handle
reg register address
val register value to send
Returns
status flag
Definition at line 145 of file generic_i2c_driver.c.
References I2C_DRV_MasterSendDataBlocking(), kStatus_I2C_Success, OSA_MutexLock(), OSA_MutexUnlock(), OSA_WAIT_FOREVER, STATUS_I2C_ERROR, and STATUS_I2C_SUCCESS.
Referenced by FXAS_GetReady(), FXAS_GotoStandby(), FXAS_Init(), FXAS_SetActive(), FXAS_SoftReset(), FXOS_CalibrateAcc(), FXOS_CalibrateMag(), FXOS_ConfigureTapEvent(), FXOS_DisableTap(), FXOS_EnableTap(), FXOS_Init(), FXOS_SoftReset(), HTU_SetUserRegister(), I2C_ModifyReg(), MAXIM_Enable(), MAXIM_Init(), MAXIM_Reset(), MPL_EnableEventFlags(), MPL_GotoStandby(), MPL_SetActive(), MPL_SetMode(), MPL_SetOversampleRate(), MPL_ToggleOneShot(), TSL_Disable(), TSL_Enable(), TSL_SetGain(), and TSL_SetTiming().