HEXIWEAR MK64 Firmware Reference Manual: protocols/SPI/src/generic_spi_driver.c File Reference
generic_spi_driver.c File Reference
this file contains generic SPI driver routines
#include "generic_spi_driver.h"
#include "generic_spi_types.h"
#include "generic_spi_info.h"
#include "OLED_SPI.h"
#include "FLASH_SPI.h"
Functions
statusSPI_t SPI_Init (genericSpiHandle_t *self)
statusSPI_t SPI_Deinit (genericSpiHandle_t *self)
Detailed Description
this file contains generic SPI driver routines
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file generic_spi_driver.c.
Function Documentation
statusSPI_t SPI_Deinit (genericSpiHandle_t * self)
deinitialize SPI interface (not used)
Definition at line 100 of file generic_spi_driver.c.
References STATUS_SPI_DEINIT_ERROR, STATUS_SPI_ERROR, and STATUS_SPI_SUCCESS.
Referenced by FLASH_Deinit(), and OLED_Deinit().
statusSPI_t SPI_Init (genericSpiHandle_t * self)
initialize SPI interface and its required structures
Parameters
self SPI handle
Returns
status flag
Definition at line 54 of file generic_spi_driver.c.
References FLASH_SPI_BusConfig, FLASH_SPI_MasterState, FSL_FLASH_SPI, FSL_OLED_SPI, OLED_SPI_BusConfig, OLED_SPI_MasterState, and STATUS_SPI_SUCCESS.
Referenced by FLASH_Init(), and OLED_Init().