HEXIWEAR MK64 Firmware Reference Manual: Vector Copy
Vector Copy
Support Functions
Functions
void arm_copy_f32 (float32_t *pSrc, float32_t *pDst, uint32_t blockSize)
Copies the elements of a floating-point vector.
void arm_copy_q15 (q15_t *pSrc, q15_t *pDst, uint32_t blockSize)
Copies the elements of a Q15 vector.
void arm_copy_q31 (q31_t *pSrc, q31_t *pDst, uint32_t blockSize)
Copies the elements of a Q31 vector.
void arm_copy_q7 (q7_t *pSrc, q7_t *pDst, uint32_t blockSize)
Copies the elements of a Q7 vector.
Detailed Description
Copies sample by sample from source vector to destination vector.
    pDst[n] = pSrc[n];   0 <= n < blockSize.
There are separate functions for floating point, Q31, Q15, and Q7 data types.
Function Documentation
void arm_copy_f32 (float32_t * pSrc, float32_t * pDst, uint32_t blockSize)
Copies the elements of a floating-point vector.
Parameters
[in] *pSrc points to input vector
[out] *pDst points to output vector
[in] blockSize length of the input vector
Returns
none.
loop counter
Run the below code for Cortex-M4 and Cortex-M3
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C = A
Copy and then store the results in the destination buffer
Decrement the loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = A
Copy and then store the results in the destination buffer
Decrement the loop counter
Definition at line 74 of file arm_copy_f32.c.
void arm_copy_q15 (q15_t * pSrc, q15_t * pDst, uint32_t blockSize)
Copies the elements of a Q15 vector.
Parameters
[in] *pSrc points to input vector
[out] *pDst points to output vector
[in] blockSize length of the input vector
Returns
none.
loop counter
Run the below code for Cortex-M4 and Cortex-M3
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C = A
Read two inputs
Decrement the loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = A
Copy and then store the value in the destination buffer
Decrement the loop counter
Definition at line 60 of file arm_copy_q15.c.
Referenced by arm_conv_fast_opt_q15(), arm_conv_opt_q15(), arm_conv_partial_fast_opt_q15(), arm_conv_partial_opt_q15(), arm_correlate_fast_opt_q15(), and arm_correlate_opt_q15().
void arm_copy_q31 (q31_t * pSrc, q31_t * pDst, uint32_t blockSize)
Copies the elements of a Q31 vector.
Parameters
[in] *pSrc points to input vector
[out] *pDst points to output vector
[in] blockSize length of the input vector
Returns
none.
loop counter
Run the below code for Cortex-M4 and Cortex-M3
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C = A
Copy and then store the values in the destination buffer
Decrement the loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = A
Copy and then store the value in the destination buffer
Decrement the loop counter
Definition at line 61 of file arm_copy_q31.c.
void arm_copy_q7 (q7_t * pSrc, q7_t * pDst, uint32_t blockSize)
Copies the elements of a Q7 vector.
Parameters
[in] *pSrc points to input vector
[out] *pDst points to output vector
[in] blockSize length of the input vector
Returns
none.
loop counter
Run the below code for Cortex-M4 and Cortex-M3
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C = A
Copy and then store the results in the destination buffer
Decrement the loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = A
Copy and then store the results in the destination buffer
Decrement the loop counter
Definition at line 61 of file arm_copy_q7.c.