HEXIWEAR MK64 Firmware Reference Manual: pin_mux module documentation
pin_mux module documentation
Functions
void hardware_init (void)
void init_adc_pins (uint32_t instance)
ADC method sets registers according routing settings. Call this method code to route desired pins into: ADC0, ADC1 peripherals.
void deinit_adc_pins (uint32_t instance)
ADC method sets registers according routing settings. Call this method code to disable routing of desired pins for: ADC0, ADC1 peripherals.
void init_can_pins (uint32_t instance)
CAN method sets registers according routing settings. Call this method code to route desired pins into CAN0 periphery.
void deinit_can_pins (uint32_t instance)
CAN method sets registers according routing settings. Call this method code to disable routing of desired pins for CAN0 periphery.
void init_cmp_pins (uint32_t instance)
CMP method sets registers according routing settings. Call this method code to route desired pins into: CMP0, CMP1, CMP2 peripherals.
void deinit_cmp_pins (uint32_t instance)
CMP method sets registers according routing settings. Call this method code to disable routing of desired pins for: CMP0, CMP1, CMP2 peripherals.
void init_cmt_pins (uint32_t instance)
CMT method sets registers according routing settings. Call this method code to route desired pins into CMT periphery.
void deinit_cmt_pins (uint32_t instance)
CMT method sets registers according routing settings. Call this method code to disable routing of desired pins for CMT periphery.
void init_dac_pins (uint32_t instance)
DAC method sets registers according routing settings. Call this method code to route desired pins into: DAC0, DAC1 peripherals.
void deinit_dac_pins (uint32_t instance)
DAC method sets registers according routing settings. Call this method code to disable routing of desired pins for: DAC0, DAC1 peripherals.
void init_dma_pins (uint32_t instance)
DMA method sets registers according routing settings. Call this method code to route desired pins into DMA periphery.
void deinit_dma_pins (uint32_t instance)
DMA method sets registers according routing settings. Call this method code to disable routing of desired pins for DMA periphery.
void init_enet_pins (uint32_t instance)
ENET method sets registers according routing settings. Call this method code to route desired pins into ENET periphery.
void deinit_enet_pins (uint32_t instance)
ENET method sets registers according routing settings. Call this method code to disable routing of desired pins for ENET periphery.
void init_ewm_pins (uint32_t instance)
EWM method sets registers according routing settings. Call this method code to route desired pins into EWM periphery.
void deinit_ewm_pins (uint32_t instance)
EWM method sets registers according routing settings. Call this method code to disable routing of desired pins for EWM periphery.
void init_fb_pins (uint32_t instance)
FB method sets registers according routing settings. Call this method code to route desired pins into FB periphery.
void deinit_fb_pins (uint32_t instance)
FB method sets registers according routing settings. Call this method code to disable routing of desired pins for FB periphery.
void init_ftm_pins (uint32_t instance)
FTM method sets registers according routing settings. Call this method code to route desired pins into: FTM0, FTM1, FTM2, FTM3 peripherals.
void deinit_ftm_pins (uint32_t instance)
FTM method sets registers according routing settings. Call this method code to disable routing of desired pins for: FTM0, FTM1, FTM2, FTM3 peripherals.
void init_gpio_pins (uint32_t instance)
GPIO method sets registers according routing settings. Call this method code to route desired pins into: PTA, PTB, PTC, PTD, PTE peripherals.
void deinit_gpio_pins (uint32_t instance)
GPIO method sets registers according routing settings. Call this method code to disable routing of desired pins for: PTA, PTB, PTC, PTD, PTE peripherals.
void init_i2c_pins (uint32_t instance)
I2C method sets registers according routing settings. Call this method code to route desired pins into: I2C0, I2C1, I2C2 peripherals.
void deinit_i2c_pins (uint32_t instance)
I2C method sets registers according routing settings. Call this method code to disable routing of desired pins for: I2C0, I2C1, I2C2 peripherals.
void init_i2s_pins (uint32_t instance)
I2S method sets registers according routing settings. Call this method code to route desired pins into I2S0 periphery.
void deinit_i2s_pins (uint32_t instance)
I2S method sets registers according routing settings. Call this method code to disable routing of desired pins for I2S0 periphery.
void init_jtag_pins (uint32_t instance)
JTAG method sets registers according routing settings. Call this method code to route desired pins into JTAG periphery.
void deinit_jtag_pins (uint32_t instance)
JTAG method sets registers according routing settings. Call this method code to disable routing of desired pins for JTAG periphery.
void init_llwu_pins (uint32_t instance)
LLWU method sets registers according routing settings. Call this method code to route desired pins into LLWU periphery.
void deinit_llwu_pins (uint32_t instance)
LLWU method sets registers according routing settings. Call this method code to disable routing of desired pins for LLWU periphery.
void init_lptmr_pins (uint32_t instance)
LPTMR method sets registers according routing settings. Call this method code to route desired pins into LPTMR0 periphery.
void deinit_lptmr_pins (uint32_t instance)
LPTMR method sets registers according routing settings. Call this method code to disable routing of desired pins for LPTMR0 periphery.
void init_osc_pins (uint32_t instance)
OSC method sets registers according routing settings. Call this method code to route desired pins into OSC periphery.
void deinit_osc_pins (uint32_t instance)
OSC method sets registers according routing settings. Call this method code to disable routing of desired pins for OSC periphery.
void init_pdb_pins (uint32_t instance)
PDB method sets registers according routing settings. Call this method code to route desired pins into PDB0 periphery.
void deinit_pdb_pins (uint32_t instance)
PDB method sets registers according routing settings. Call this method code to disable routing of desired pins for PDB0 periphery.
void init_rcm_pins (uint32_t instance)
RCM method sets registers according routing settings. Call this method code to route desired pins into RCM periphery.
void deinit_rcm_pins (uint32_t instance)
RCM method sets registers according routing settings. Call this method code to disable routing of desired pins for RCM periphery.
void init_rtc_pins (uint32_t instance)
RTC method sets registers according routing settings. Call this method code to route desired pins into RTC periphery.
void deinit_rtc_pins (uint32_t instance)
RTC method sets registers according routing settings. Call this method code to disable routing of desired pins for RTC periphery.
void init_scb_pins (uint32_t instance)
SCB method sets registers according routing settings. Call this method code to route desired pins into SystemControl periphery.
void deinit_scb_pins (uint32_t instance)
SCB method sets registers according routing settings. Call this method code to disable routing of desired pins for SystemControl periphery.
void init_sdhc_pins (uint32_t instance)
SDHC method sets registers according routing settings. Call this method code to route desired pins into SDHC periphery.
void deinit_sdhc_pins (uint32_t instance)
SDHC method sets registers according routing settings. Call this method code to disable routing of desired pins for SDHC periphery.
void init_sim_pins (uint32_t instance)
SIM method sets registers according routing settings. Call this method code to route desired pins into SIM periphery.
void deinit_sim_pins (uint32_t instance)
SIM method sets registers according routing settings. Call this method code to disable routing of desired pins for SIM periphery.
void init_spi_pins (uint32_t instance)
SPI method sets registers according routing settings. Call this method code to route desired pins into: SPI0, SPI1, SPI2 peripherals.
void deinit_spi_pins (uint32_t instance)
SPI method sets registers according routing settings. Call this method code to disable routing of desired pins for: SPI0, SPI1, SPI2 peripherals.
void init_supply_pins (uint32_t instance)
SUPPLY method sets registers according routing settings. Call this method code to route desired pins into SUPPLY periphery.
void deinit_supply_pins (uint32_t instance)
SUPPLY method sets registers according routing settings. Call this method code to disable routing of desired pins for SUPPLY periphery.
void init_tpiu_pins (uint32_t instance)
TPIU method sets registers according routing settings. Call this method code to route desired pins into TPIU periphery.
void deinit_tpiu_pins (uint32_t instance)
TPIU method sets registers according routing settings. Call this method code to disable routing of desired pins for TPIU periphery.
void init_uart_pins (uint32_t instance)
UART method sets registers according routing settings. Call this method code to route desired pins into: UART0, UART1, UART2, UART3, UART4, UART5 peripherals.
void deinit_uart_pins (uint32_t instance)
UART method sets registers according routing settings. Call this method code to disable routing of desired pins for: UART0, UART1, UART2, UART3, UART4, UART5 peripherals.
void init_usb_pins (uint32_t instance)
USB method sets registers according routing settings. Call this method code to route desired pins into USB0 periphery.
void deinit_usb_pins (uint32_t instance)
USB method sets registers according routing settings. Call this method code to disable routing of desired pins for USB0 periphery.
void init_usbdcd_pins (uint32_t instance)
USBDCD method sets registers according routing settings. Call this method code to route desired pins into USBDCD periphery.
void deinit_usbdcd_pins (uint32_t instance)
USBDCD method sets registers according routing settings. Call this method code to disable routing of desired pins for USBDCD periphery.
void init_vref_pins (uint32_t instance)
VREF method sets registers according routing settings. Call this method code to route desired pins into VREF periphery.
void deinit_vref_pins (uint32_t instance)
VREF method sets registers according routing settings. Call this method code to disable routing of desired pins for VREF periphery.
Detailed Description
Function Documentation
void deinit_adc_pins (uint32_t instance)
ADC method sets registers according routing settings. Call this method code to disable routing of desired pins for: ADC0, ADC1 peripherals.
Parameters
instance - ADC instance number 0..1
void deinit_can_pins (uint32_t instance)
CAN method sets registers according routing settings. Call this method code to disable routing of desired pins for CAN0 periphery.
Parameters
instance - CAN instance number (0 is expected)
void deinit_cmp_pins (uint32_t instance)
CMP method sets registers according routing settings. Call this method code to disable routing of desired pins for: CMP0, CMP1, CMP2 peripherals.
Parameters
instance - CMP instance number 0..2
void deinit_cmt_pins (uint32_t instance)
CMT method sets registers according routing settings. Call this method code to disable routing of desired pins for CMT periphery.
Parameters
instance - CMT instance number (0 is expected)
void deinit_dac_pins (uint32_t instance)
DAC method sets registers according routing settings. Call this method code to disable routing of desired pins for: DAC0, DAC1 peripherals.
Parameters
instance - DAC instance number 0..1
void deinit_dma_pins (uint32_t instance)
DMA method sets registers according routing settings. Call this method code to disable routing of desired pins for DMA periphery.
Parameters
instance - DMA instance number (0 is expected)
void deinit_enet_pins (uint32_t instance)
ENET method sets registers according routing settings. Call this method code to disable routing of desired pins for ENET periphery.
Parameters
instance - ENET instance number (0 is expected)
void deinit_ewm_pins (uint32_t instance)
EWM method sets registers according routing settings. Call this method code to disable routing of desired pins for EWM periphery.
Parameters
instance - EWM instance number (0 is expected)
void deinit_fb_pins (uint32_t instance)
FB method sets registers according routing settings. Call this method code to disable routing of desired pins for FB periphery.
Parameters
instance - FB instance number (0 is expected)
void deinit_ftm_pins (uint32_t instance)
FTM method sets registers according routing settings. Call this method code to disable routing of desired pins for: FTM0, FTM1, FTM2, FTM3 peripherals.
Parameters
instance - FTM instance number 0..3
void deinit_gpio_pins (uint32_t instance)
GPIO method sets registers according routing settings. Call this method code to disable routing of desired pins for: PTA, PTB, PTC, PTD, PTE peripherals.
Parameters
instance - GPIO instance number 0..4
PORTA_IDX
PORTB_IDX
PORTC_IDX
PORTD_IDX
PORTE_IDX
Definition at line 1690 of file pin_mux.c.
References kPortPinDisabled, PORTA, PORTB, PORTC, PORTD, and PORTE.
void deinit_i2c_pins (uint32_t instance)
I2C method sets registers according routing settings. Call this method code to disable routing of desired pins for: I2C0, I2C1, I2C2 peripherals.
Parameters
instance - I2C instance number 0..2
I2C0_IDX
I2C1_IDX
Definition at line 1755 of file pin_mux.c.
References kPortPinDisabled, PORTB, and PORTC.
void deinit_i2s_pins (uint32_t instance)
I2S method sets registers according routing settings. Call this method code to disable routing of desired pins for I2S0 periphery.
Parameters
instance - I2S instance number (0 is expected)
void deinit_jtag_pins (uint32_t instance)
JTAG method sets registers according routing settings. Call this method code to disable routing of desired pins for JTAG periphery.
Parameters
instance - JTAG instance number (0 is expected)
Definition at line 1794 of file pin_mux.c.
References kPortPinDisabled, and PORTA.
void deinit_llwu_pins (uint32_t instance)
LLWU method sets registers according routing settings. Call this method code to disable routing of desired pins for LLWU periphery.
Parameters
instance - LLWU instance number (0 is expected)
Definition at line 1823 of file pin_mux.c.
References kPortPinDisabled, PORTC, and PORTD.
void deinit_lptmr_pins (uint32_t instance)
LPTMR method sets registers according routing settings. Call this method code to disable routing of desired pins for LPTMR0 periphery.
Parameters
instance - LPTMR instance number (0 is expected)
void deinit_osc_pins (uint32_t instance)
OSC method sets registers according routing settings. Call this method code to disable routing of desired pins for OSC periphery.
Parameters
instance - OSC instance number (0 is expected)
void deinit_pdb_pins (uint32_t instance)
PDB method sets registers according routing settings. Call this method code to disable routing of desired pins for PDB0 periphery.
Parameters
instance - PDB instance number (0 is expected)
void deinit_rcm_pins (uint32_t instance)
RCM method sets registers according routing settings. Call this method code to disable routing of desired pins for RCM periphery.
Parameters
instance - RCM instance number (0 is expected)
void deinit_rtc_pins (uint32_t instance)
RTC method sets registers according routing settings. Call this method code to disable routing of desired pins for RTC periphery.
Parameters
instance - RTC instance number (0 is expected)
void deinit_scb_pins (uint32_t instance)
SCB method sets registers according routing settings. Call this method code to disable routing of desired pins for SystemControl periphery.
Parameters
instance - SCB instance number (0 is expected)
void deinit_sdhc_pins (uint32_t instance)
SDHC method sets registers according routing settings. Call this method code to disable routing of desired pins for SDHC periphery.
Parameters
instance - SDHC instance number (0 is expected)
void deinit_sim_pins (uint32_t instance)
SIM method sets registers according routing settings. Call this method code to disable routing of desired pins for SIM periphery.
Parameters
instance - SIM instance number (0 is expected)
void deinit_spi_pins (uint32_t instance)
SPI method sets registers according routing settings. Call this method code to disable routing of desired pins for: SPI0, SPI1, SPI2 peripherals.
Parameters
instance - SPI instance number 0..2
SPI1_IDX
SPI2_IDX
Definition at line 1862 of file pin_mux.c.
References kPortPinDisabled, PORTB, and PORTD.
void deinit_supply_pins (uint32_t instance)
SUPPLY method sets registers according routing settings. Call this method code to disable routing of desired pins for SUPPLY periphery.
Parameters
instance - SUPPLY instance number (0 is expected)
void deinit_tpiu_pins (uint32_t instance)
TPIU method sets registers according routing settings. Call this method code to disable routing of desired pins for TPIU periphery.
Parameters
instance - TPIU instance number (0 is expected)
Definition at line 1896 of file pin_mux.c.
References kPortPinDisabled, and PORTA.
void deinit_uart_pins (uint32_t instance)
UART method sets registers according routing settings. Call this method code to disable routing of desired pins for: UART0, UART1, UART2, UART3, UART4, UART5 peripherals.
Parameters
instance - UART instance number 0..5
UART3_IDX
UART4_IDX
Definition at line 1931 of file pin_mux.c.
References kPortPinDisabled, PORTC, and PORTE.
void deinit_usb_pins (uint32_t instance)
USB method sets registers according routing settings. Call this method code to disable routing of desired pins for USB0 periphery.
Parameters
instance - USB instance number (0 is expected)
void deinit_usbdcd_pins (uint32_t instance)
USBDCD method sets registers according routing settings. Call this method code to disable routing of desired pins for USBDCD periphery.
Parameters
instance - USBDCD instance number (0 is expected)
void deinit_vref_pins (uint32_t instance)
VREF method sets registers according routing settings. Call this method code to disable routing of desired pins for VREF periphery.
Parameters
instance - VREF instance number (0 is expected)
void hardware_init (void)
Enable clock for PORTs
Setup board clock source.
Value of the external crystal or oscillator clock frequency of the system oscillator (OSC) in Hz
Value of the external 32k crystal or oscillator clock frequency of the RTC in Hz
Definition at line 1624 of file hardware_init.c.
References init_gpio_pins(), init_i2c_pins(), init_jtag_pins(), init_llwu_pins(), init_spi_pins(), init_tpiu_pins(), init_uart_pins(), and SIM.
Referenced by PE_low_level_init().
void init_adc_pins (uint32_t instance)
ADC method sets registers according routing settings. Call this method code to route desired pins into: ADC0, ADC1 peripherals.
MODULE pin_mux.
Parameters
instance - ADC instance number 0..1
void init_can_pins (uint32_t instance)
CAN method sets registers according routing settings. Call this method code to route desired pins into CAN0 periphery.
Parameters
instance - CAN instance number (0 is expected)
void init_cmp_pins (uint32_t instance)
CMP method sets registers according routing settings. Call this method code to route desired pins into: CMP0, CMP1, CMP2 peripherals.
Parameters
instance - CMP instance number 0..2
void init_cmt_pins (uint32_t instance)
CMT method sets registers according routing settings. Call this method code to route desired pins into CMT periphery.
Parameters
instance - CMT instance number (0 is expected)
void init_dac_pins (uint32_t instance)
DAC method sets registers according routing settings. Call this method code to route desired pins into: DAC0, DAC1 peripherals.
Parameters
instance - DAC instance number 0..1
void init_dma_pins (uint32_t instance)
DMA method sets registers according routing settings. Call this method code to route desired pins into DMA periphery.
Parameters
instance - DMA instance number (0 is expected)
void init_enet_pins (uint32_t instance)
ENET method sets registers according routing settings. Call this method code to route desired pins into ENET periphery.
Parameters
instance - ENET instance number (0 is expected)
void init_ewm_pins (uint32_t instance)
EWM method sets registers according routing settings. Call this method code to route desired pins into EWM periphery.
Parameters
instance - EWM instance number (0 is expected)
void init_fb_pins (uint32_t instance)
FB method sets registers according routing settings. Call this method code to route desired pins into FB periphery.
Parameters
instance - FB instance number (0 is expected)
void init_ftm_pins (uint32_t instance)
FTM method sets registers according routing settings. Call this method code to route desired pins into: FTM0, FTM1, FTM2, FTM3 peripherals.
Parameters
instance - FTM instance number 0..3
void init_gpio_pins (uint32_t instance)
GPIO method sets registers according routing settings. Call this method code to route desired pins into: PTA, PTB, PTC, PTD, PTE peripherals.
Parameters
instance - GPIO instance number 0..4
MODULE pin_mux.
PORTA_IDX
Affects PORTA_PCR29 register
PORTB_IDX
Affects PORTB_PCR12 register
Affects PORTB_PCR16 register
Affects PORTB_PCR20 register
Affects PORTB_PCR23 register
PORTC_IDX
Affects PORTC_PCR1 register
Affects PORTC_PCR8 register
Affects PORTC_PCR9 register
Affects PORTC_PCR12 register
Affects PORTC_PCR13 register
Affects PORTC_PCR14 register
PORTD_IDX
Affects PORTD_PCR0 register
Affects PORTD_PCR4 register
Affects PORTD_PCR14 register
Affects PORTD_PCR15 register
PORTE_IDX
Affects PORTE_PCR6 register
Affects PORTE_PCR26 register
Definition at line 1633 of file pin_mux.c.
References kPortMuxAsGpio, PORTA, PORTB, PORTC, PORTD, and PORTE.
Referenced by hardware_init().
void init_i2c_pins (uint32_t instance)
I2C method sets registers according routing settings. Call this method code to route desired pins into: I2C0, I2C1, I2C2 peripherals.
Parameters
instance - I2C instance number 0..2
I2C0_IDX
Affects PORTB_PCR0 register
Affects PORTB_PCR1 register
I2C1_IDX
Affects PORTC_PCR10 register
Affects PORTC_PCR11 register
Definition at line 1730 of file pin_mux.c.
References kPortMuxAlt2, PORTB, and PORTC.
Referenced by hardware_init().
void init_i2s_pins (uint32_t instance)
I2S method sets registers according routing settings. Call this method code to route desired pins into I2S0 periphery.
Parameters
instance - I2S instance number (0 is expected)
void init_jtag_pins (uint32_t instance)
JTAG method sets registers according routing settings. Call this method code to route desired pins into JTAG periphery.
Parameters
instance - JTAG instance number (0 is expected)
Affects PORTA_PCR0 register
Affects PORTA_PCR1 register
Affects PORTA_PCR2 register
Affects PORTA_PCR3 register
Definition at line 1777 of file pin_mux.c.
References kPortMuxAlt7, and PORTA.
Referenced by hardware_init().
void init_llwu_pins (uint32_t instance)
LLWU method sets registers according routing settings. Call this method code to route desired pins into LLWU periphery.
Parameters
instance - LLWU instance number (0 is expected)
Affects PORTC_PCR1 register
Affects PORTD_PCR0 register
Affects PORTD_PCR4 register
Definition at line 1808 of file pin_mux.c.
References kPortMuxAsGpio, PORTC, and PORTD.
Referenced by hardware_init().
void init_lptmr_pins (uint32_t instance)
LPTMR method sets registers according routing settings. Call this method code to route desired pins into LPTMR0 periphery.
Parameters
instance - LPTMR instance number (0 is expected)
void init_osc_pins (uint32_t instance)
OSC method sets registers according routing settings. Call this method code to route desired pins into OSC periphery.
Parameters
instance - OSC instance number (0 is expected)
void init_pdb_pins (uint32_t instance)
PDB method sets registers according routing settings. Call this method code to route desired pins into PDB0 periphery.
Parameters
instance - PDB instance number (0 is expected)
void init_rcm_pins (uint32_t instance)
RCM method sets registers according routing settings. Call this method code to route desired pins into RCM periphery.
Parameters
instance - RCM instance number (0 is expected)
void init_rtc_pins (uint32_t instance)
RTC method sets registers according routing settings. Call this method code to route desired pins into RTC periphery.
Parameters
instance - RTC instance number (0 is expected)
void init_scb_pins (uint32_t instance)
SCB method sets registers according routing settings. Call this method code to route desired pins into SystemControl periphery.
Parameters
instance - SCB instance number (0 is expected)
void init_sdhc_pins (uint32_t instance)
SDHC method sets registers according routing settings. Call this method code to route desired pins into SDHC periphery.
Parameters
instance - SDHC instance number (0 is expected)
void init_sim_pins (uint32_t instance)
SIM method sets registers according routing settings. Call this method code to route desired pins into SIM periphery.
Parameters
instance - SIM instance number (0 is expected)
void init_spi_pins (uint32_t instance)
SPI method sets registers according routing settings. Call this method code to route desired pins into: SPI0, SPI1, SPI2 peripherals.
Parameters
instance - SPI instance number 0..2
SPI1_IDX
Affects PORTD_PCR7 register
Affects PORTD_PCR5 register
Affects PORTD_PCR6 register
SPI2_IDX
Affects PORTB_PCR21 register
Affects PORTB_PCR22 register
Definition at line 1835 of file pin_mux.c.
References kPortMuxAlt2, kPortMuxAlt7, PORTB, and PORTD.
Referenced by hardware_init().
void init_supply_pins (uint32_t instance)
SUPPLY method sets registers according routing settings. Call this method code to route desired pins into SUPPLY periphery.
Parameters
instance - SUPPLY instance number (0 is expected)
void init_tpiu_pins (uint32_t instance)
TPIU method sets registers according routing settings. Call this method code to route desired pins into TPIU periphery.
Parameters
instance - TPIU instance number (0 is expected)
Affects PORTA_PCR2 register
Definition at line 1885 of file pin_mux.c.
References kPortMuxAlt7, and PORTA.
Referenced by hardware_init().
void init_uart_pins (uint32_t instance)
UART method sets registers according routing settings. Call this method code to route desired pins into: UART0, UART1, UART2, UART3, UART4, UART5 peripherals.
Parameters
instance - UART instance number 0..5
UART3_IDX
Affects PORTC_PCR16 register
Affects PORTC_PCR17 register
UART4_IDX
Affects PORTE_PCR25 register
Affects PORTE_PCR24 register
Definition at line 1906 of file pin_mux.c.
References kPortMuxAlt3, PORTC, and PORTE.
Referenced by hardware_init().
void init_usb_pins (uint32_t instance)
USB method sets registers according routing settings. Call this method code to route desired pins into USB0 periphery.
Parameters
instance - USB instance number (0 is expected)
void init_usbdcd_pins (uint32_t instance)
USBDCD method sets registers according routing settings. Call this method code to route desired pins into USBDCD periphery.
Parameters
instance - USBDCD instance number (0 is expected)
void init_vref_pins (uint32_t instance)
VREF method sets registers according routing settings. Call this method code to route desired pins into VREF periphery.
Parameters
instance - VREF instance number (0 is expected)