HEXIWEAR MK64 Firmware Reference Manual: KW40_UART module documentation
KW40_UART module documentation
Macros
#define FSL_KW40_UART UART4_IDX
Functions
void UART_DRV_IRQHandler (uint32_t instance)
void UART4_RX_TX_IRQHandler (void)
Variables
uart_state_t KW40_UART_State
const uart_user_config_t KW40_UART_InitConfig0
UART configuration declaration.
const uart_user_config_t KW40_UART_InitConfig0
UART configuration declaration.
uart_state_t KW40_UART_State
Detailed Description
Macro Definition Documentation
#define FSL_KW40_UART UART4_IDX
MODULE KW40_UART. Include inherited beans
Device instance number
Definition at line 78 of file KW40_UART.h.
Referenced by UART4_RX_TX_IRQHandler().
Function Documentation
void UART4_RX_TX_IRQHandler (void)
special consideration is also required for the sensor tag sleep mode, since we might not be actually sleeping when UART interrupt occurs
Definition at line 76 of file KW40_UART.c.
References FSL_KW40_UART, HostInterface_SetWakingTouch(), POWER_CURRENT_MODE_SLEEP_SENSOR_TAG, POWER_CURRENT_MODE_SLEEP_SHALLOW, POWER_CURRENT_MODE_SLEEP_TOTAL, power_GetCurrentMode(), power_SetCurrentMode(), power_SetWakeSource(), and UART_DRV_IRQHandler().
void UART_DRV_IRQHandler (uint32_t instance)
Implementation of UART4 handler named in startup code.
Referenced by UART4_RX_TX_IRQHandler().
Variable Documentation
const uart_user_config_t KW40_UART_InitConfig0
Initial value:
= {
  .baudRate = 230400U,
  .parityMode = kUartParityDisabled,
  .stopBitCount = kUartTwoStopBit,
  .bitCountPerChar = kUart8BitsPerChar,
}
UART configuration declaration.
MODULE KW40_UART.
KW40_UART configuration structure
Definition at line 63 of file KW40_UART.c.
const uart_user_config_t KW40_UART_InitConfig0
UART configuration declaration.
MODULE KW40_UART.
KW40_UART configuration structure
Definition at line 63 of file KW40_UART.c.
uart_state_t KW40_UART_State
Driver state structure without DMA
Definition at line 72 of file KW40_UART.c.
uart_state_t KW40_UART_State
Driver state structure without DMA
Definition at line 72 of file KW40_UART.c.