HEXIWEAR MK64 Firmware Reference Manual: Vector Fill
Vector Fill
Support Functions
Functions
void arm_fill_f32 (float32_t value, float32_t *pDst, uint32_t blockSize)
Fills a constant value into a floating-point vector.
void arm_fill_q15 (q15_t value, q15_t *pDst, uint32_t blockSize)
Fills a constant value into a Q15 vector.
void arm_fill_q31 (q31_t value, q31_t *pDst, uint32_t blockSize)
Fills a constant value into a Q31 vector.
void arm_fill_q7 (q7_t value, q7_t *pDst, uint32_t blockSize)
Fills a constant value into a Q7 vector.
Detailed Description
Fills the destination vector with a constant value.
    pDst[n] = value;   0 <= n < blockSize.
There are separate functions for floating point, Q31, Q15, and Q7 data types.
Function Documentation
void arm_fill_f32 (float32_t value, float32_t * pDst, uint32_t blockSize)
Fills a constant value into a floating-point vector.
Parameters
[in] value input value to be filled
[out] *pDst points to output vector
[in] blockSize length of the output vector
Returns
none.
loop counter
Run the below code for Cortex-M4 and Cortex-M3
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C = value
Fill the value in the destination buffer
Decrement the loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = value
Fill the value in the destination buffer
Decrement the loop counter
Definition at line 74 of file arm_fill_f32.c.
void arm_fill_q15 (q15_t value, q15_t * pDst, uint32_t blockSize)
Fills a constant value into a Q15 vector.
Parameters
[in] value input value to be filled
[out] *pDst points to output vector
[in] blockSize length of the output vector
Returns
none.
loop counter
Run the below code for Cortex-M4 and Cortex-M3
value packed to 32 bits
Packing two 16 bit values to 32 bit value in order to use SIMD
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C = value
Fill the value in the destination buffer
Decrement the loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = value
Fill the value in the destination buffer
Decrement the loop counter
Definition at line 61 of file arm_fill_q15.c.
Referenced by arm_conv_fast_opt_q15(), arm_conv_opt_q15(), arm_conv_opt_q7(), arm_conv_partial_fast_opt_q15(), arm_conv_partial_opt_q15(), arm_conv_partial_opt_q7(), arm_correlate_fast_opt_q15(), arm_correlate_opt_q15(), and arm_correlate_opt_q7().
void arm_fill_q31 (q31_t value, q31_t * pDst, uint32_t blockSize)
Fills a constant value into a Q31 vector.
Parameters
[in] value input value to be filled
[out] *pDst points to output vector
[in] blockSize length of the output vector
Returns
none.
loop counter
Run the below code for Cortex-M4 and Cortex-M3
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C = value
Fill the value in the destination buffer
Decrement the loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = value
Fill the value in the destination buffer
Decrement the loop counter
Definition at line 61 of file arm_fill_q31.c.
void arm_fill_q7 (q7_t value, q7_t * pDst, uint32_t blockSize)
Fills a constant value into a Q7 vector.
Parameters
[in] value input value to be filled
[out] *pDst points to output vector
[in] blockSize length of the output vector
Returns
none.
loop counter
Run the below code for Cortex-M4 and Cortex-M3
value packed to 32 bits
Packing four 8 bit values to 32 bit value in order to use SIMD
First part of the processing with loop unrolling. Compute 4 outputs at a time. a second loop below computes the remaining 1 to 3 samples.
C = value
Fill the value in the destination buffer
Decrement the loop counter
If the blockSize is not a multiple of 4, compute any remaining output samples here. No loop unrolling is used.
C = value
Fill the value in the destination buffer
Decrement the loop counter
Definition at line 61 of file arm_fill_q7.c.