HEXIWEAR MK64 Firmware Reference Manual: gui/screens/2. apps/2.3 fitness/2.3.1 gui_pedometer/src/gui_pedometer_driver.c File Reference
gui_pedometer_driver.c File Reference
this file contains pedometer app GUI main task and functionality
#include "gui_pedometer.h"
#include "gui_pedometer_private.h"
#include "screens_common.h"
#include "fsl_os_abstraction.h"
#include "error.h"
#include "pedometer_driver.h"
Functions
MSG_QUEUE_DECLARE (gui_pedometer_queue, 1, sizeof(uint32_t))
void gui_pedometer_Init (void *param)
void gui_pedometer_CreateTasks (void *param)
void gui_pedometer_DestroyTasks (void *param)
gui_pedometer_status_t gui_pedometer_QueueMsgPut (uint32_t *packet)
Detailed Description
this file contains pedometer app GUI main task and functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file gui_pedometer_driver.c.
Function Documentation
void gui_pedometer_CreateTasks (void * param)
create the pedometer GUI app tasks
Parameters
param optional parameter
Definition at line 133 of file gui_pedometer_driver.c.
References kStatus_OSA_Success, OSA_TaskCreate(), and pedometer_CreateTask().
void gui_pedometer_DestroyTasks (void * param)
destroy the pedometer GUI app tasks
Parameters
param optional parameter
Definition at line 173 of file gui_pedometer_driver.c.
References GUI_CURRENT_APP_IDLE, gui_sensorTag_IsActive(), GuiDriver_LabelDestroy(), GuiDriver_NotifyKW40(), GuiDriver_UnregisterFromNavigation(), OLED_DestroyDynamicArea(), OSA_MsgQDestroy(), OSA_TaskDestroy(), pedometer_Deinit(), and power_EnablePowerSave().
void gui_pedometer_Init (void * param)
initialize pedometer app GUI
Parameters
param optional parameter
Definition at line 91 of file gui_pedometer_driver.c.
References GUI_CURRENT_APP_PEDOMETER, GuiDriver_ImageAddToScr(), GuiDriver_LabelCreate(), GuiDriver_LabelSetCaption(), GuiDriver_NotifyKW40(), GuiDriver_RegisterForNavigation(), OSA_MsgQCreate(), and pedometer_Init().
gui_pedometer_status_t gui_pedometer_QueueMsgPut (uint32_t * packet)
put the packet into pedometer app GUI queue
Parameters
packet data to be put into the queue
Returns
status flag
Definition at line 206 of file gui_pedometer_driver.c.
References GuiDriver_CleanMainArea(), GuiDriver_ImageDraw(), GuiDriver_LabelDraw(), GuiDriver_QueueMsgGet(), kStatus_OSA_Error, OSA_MsgQGet(), OSA_WAIT_FOREVER, packetType_pressRight, pedometer_Pause(), pedometer_Resume(), power_DisablePowerSave(), and power_EnablePowerSave().
Referenced by pedometer_GetCalories().
MSG_QUEUE_DECLARE (gui_pedometer_queue , 1 , sizeof(uint32_t))
private variables