HEXIWEAR MK64 Firmware Reference Manual: gui/screens/3. gui_notifications/src/gui_notifications_driver.c File Reference
gui_notifications_driver.c File Reference
this file contains notifications GUI related functionality
#include "gui_notifications.h"
#include "gui_notifications_private.h"
Functions
void gui_notifications_Init (void *param)
void gui_notifications_CreateTasks (void *param)
void gui_notifications_DestroyTasks (void *param)
Detailed Description
this file contains notifications GUI related functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file gui_notifications_driver.c.
Function Documentation
void gui_notifications_CreateTasks (void * param)
create the notification task
Parameters
param optional parameter
Definition at line 109 of file gui_notifications_driver.c.
References OSA_TaskCreate().
void gui_notifications_DestroyTasks (void * param)
destroy the notification task
Parameters
param optional parameter
Definition at line 128 of file gui_notifications_driver.c.
References gui_notifications_labelMail, gui_notifications_mailIcon, GuiDriver_ImageDraw(), GuiDriver_LabelDestroy(), GuiDriver_LabelDraw(), Notification_GetUnreadCounter(), Notification_WaitForEvent(), OLED_DestroyDynamicArea(), OSA_TaskDestroy(), and OSA_WAIT_FOREVER.
void gui_notifications_Init (void * param)
notifications task initialization
Parameters
param optional parameter
Definition at line 50 of file gui_notifications_driver.c.
References gui_notifications_labelMail, gui_notifications_mailIcon, GuiDriver_ImageAddToScr(), GuiDriver_LabelAddToScr(), GuiDriver_LabelCreate(), and Notification_GetUnreadCounter().