HEXIWEAR MK64 Firmware Reference Manual: gui/screens/2. apps/2.2 motionControl/src/gui_motionControl_driver.c File Reference
gui_motionControl_driver.c File Reference
this file contains motion control app functionality
#include "fsl_os_abstraction.h"
#include "gui_sensorTag.h"
#include "gui_motionControl.h"
#include "gui_motionControl_private.h"
#include "HEXIWEAR_driver.h"
Enumerations
Functions
void gui_motionControl_Init (void *param)
void gui_motionControl_CreateTasks (void *param)
void gui_motionControl_DestroyTasks (void *param)
Detailed Description
this file contains motion control app functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file gui_motionControl_driver.c.
Enumeration Type Documentation
enum activeScreen_t
private typedefs
Definition at line 49 of file gui_motionControl_driver.c.
Function Documentation
void gui_motionControl_CreateTasks (void * param)
create the app main task
Parameters
param optional parameter
Definition at line 133 of file gui_motionControl_driver.c.
References kStatus_OSA_Success, and OSA_TaskCreate().
void gui_motionControl_DestroyTasks (void * param)
destroy the app task
Parameters
param optional parameter
Definition at line 157 of file gui_motionControl_driver.c.
References gui_motionControl_labelX, gui_motionControl_labelY, gui_motionControl_labelZ, GuiDriver_LabelDestroy(), GuiDriver_LabelDraw(), GuiDriver_QueueMsgGet(), GuiDriver_UnregisterFromSensors(), HEXIWEAR_SetBackupList(), HEXIWEAR_SetTargetApp(), OLED_DestroyDynamicArea(), OSA_TaskDestroy(), OSA_WAIT_FOREVER, packetType_accel, and packetType_gyro.
void gui_motionControl_Init (void * param)
public API initialize the motion control app
Parameters
param optional parameter
Definition at line 83 of file gui_motionControl_driver.c.
References gui_motionControl_labelX, gui_motionControl_labelY, gui_motionControl_labelZ, gui_sensorTag_IsActive(), GuiDriver_LabelCreate(), GuiDriver_RegisterForSensors(), GuiDriver_RegisterMinPollDelay(), HEXIWEAR_SetBackupList(), and HEXIWEAR_SetTargetApp().