HEXIWEAR MK64 Firmware Reference Manual: apps/heartRate/src/heartRate_driver.c File Reference
heartRate_driver.c File Reference
this file contains heart-rate functionality
#include "heartRate_driver.h"
#include "error.h"
#include "sensor_driver.h"
#include "gui_sensorTag.h"
#include "watch.h"
#include "fitness.h"
#include "gui_heartRate.h"
#include <math.h>
#include "arm_math.h"
Macros
#define heartRate_IsPeak(array, idx) ((array[ (idx) ] > array[ ((idx)+1) ]) && (array[ ((idx)) ] > array[ ((idx)-1) ]))
Functions
void heartRate_Init ()
void heartRate_Deinit ()
void heartRate_Resume ()
void heartRate_Pause ()
void heartRate_Process (void *sampleBuf, uint8_t numAvailSam, void *param)
Detailed Description
this file contains heart-rate functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file heartRate_driver.c.
Macro Definition Documentation
#define heartRate_IsPeak (array, idx) ((array[ (idx) ] > array[ ((idx)+1) ]) && (array[ ((idx)) ] > array[ ((idx)-1) ]))
private defines
Definition at line 57 of file heartRate_driver.c.
Referenced by heartRate_Process().
Function Documentation
void heartRate_Deinit ()
unregister from HR sensor and free used memory
Definition at line 116 of file heartRate_driver.c.
References gui_sensorTag_TurnON(), heartRate_Pause(), and OLED_DestroyDynamicArea().
Referenced by gui_heartRate_DestroyTasks().
void heartRate_Init ()
Public API register heart-rate sensor and FFT
Definition at line 98 of file heartRate_driver.c.
References gui_sensorTag_IsActive(), gui_sensorTag_TurnOFF(), GuiDriver_RegisterMinPollDelay(), heartRate_Pause(), and sensor_RegisterPacketDelay().
Referenced by gui_heartRate_Init().
void heartRate_Pause ()
free used memory and unregister from HR sensor
deallocate data buffers
Definition at line 159 of file heartRate_driver.c.
References sensor_GetPacketTargets(), and sensor_SetPacketTargets().
Referenced by gui_heartRate_QueueMsgPut(), heartRate_Deinit(), and heartRate_Init().
void heartRate_Process (void * sampleBuf, uint8_t numAvailSam, void * param)
process available HR data
Parameters
sampleBuf new data buffer
numAvailSam number of available data values
param optional parameter
place the available samples into buffer
if it's time, update HR
if we reached the end of the buffer, shift data back to make room for new samples
if the value is too small, reset the variables and activate sensor proximity mode again
Definition at line 184 of file heartRate_driver.c.
References arm_cmplx_mag_f32(), arm_rfft_fast_f32(), foo, gui_heartRate_QueueMsgPut(), heartRate_IsPeak, HostInterface_TxQueueMsgPut(), kStatus_OSA_Success, MAXIM_Disable(), MAXIM_Enable(), packetType_heartRate, and watch_CurrentLinkStateGet().
Referenced by sensor_InitAcc().
void heartRate_Resume ()
reallocate the buffers and reset the relevant variables
allocate input and output data buffers
Definition at line 135 of file heartRate_driver.c.
References sensor_GetPacketTargets(), and sensor_SetPacketTargets().
Referenced by gui_heartRate_QueueMsgPut().