HEXIWEAR MK64 Firmware Reference Manual: intf/src/host_mcu_interface_tx.c File Reference
host_mcu_interface_tx.c File Reference
this file contains MCU-to-MCU TX interface functionality
#include <stdint.h>
#include <stddef.h>
#include "board.h"
#include "fsl_uart_driver.h"
#include "fsl_interrupt_manager.h"
#include "HEXIWEAR_info.h"
#include "power_driver.h"
#include "host_mcu_interface.h"
#include "host_mcu_interface_defs.h"
#include "error.h"
#include "error_types.h"
Functions
MSG_QUEUE_DECLARE (hostInterface_txQueue, gHostInterface_msgNum, sizeof(hostInterface_packet_t))
osa_status_t HostInterface_TxInit ()
osa_status_t HostInterface_TxQueueMsgPut (hostInterface_packet_t *pHostInterface_packet, bool confirmationReq)
Detailed Description
this file contains MCU-to-MCU TX interface functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file host_mcu_interface_tx.c.
Function Documentation
osa_status_t HostInterface_TxInit (void)
functions definitions create RTOS structures for sending data via communication interface
Returns
status flag
Definition at line 93 of file host_mcu_interface_tx.c.
References hexiwear_intf_OK_handler, hexiwear_intf_TX_handler, kStatus_OSA_Error, kStatus_OSA_Success, OSA_MsgQCreate(), OSA_MutexCreate(), and OSA_TaskCreate().
Referenced by HostInterface_Init().
osa_status_t HostInterface_TxQueueMsgPut (hostInterface_packet_t * pHostInterface_packet, bool confirmationReq)
This function puts a message to the end of the Tx message queue.
Parameters
pHostInterface_packet Packet that will be placed into Tx message queue.
Returns
kStatus_OSA_Success Message successfully put into the queue. kStatus_OSA_Error Process fail.
Definition at line 164 of file host_mcu_interface_tx.c.
References HostInterface_EventConfirmPacketClear(), HostInterface_EventConfirmPacketWait(), HostInterface_EventSendOkPacketWait(), kStatus_OSA_Error, kStatus_OSA_Success, kStatus_OSA_Timeout, OSA_MsgQGet(), OSA_MutexLock(), OSA_MutexUnlock(), OSA_WAIT_FOREVER, packetType_accel, POWER_CURRENT_MODE_SLEEP_SENSOR_TAG, power_GetCurrentMode(), power_GotoSleep(), power_SetSleepSource(), power_TurnScreenON(), UART_DRV_SendDataBlocking(), and UART_TIMEOUT.
Referenced by bluetooth_SendGetAdvModeReq(), bluetooth_SendToggleAdvModeReq(), bootloader_DestroyTasks(), buttonsGroup_SendGetActiveReq(), buttonsGroup_SendToggleActiveReq(), GuiDriver_NotifyKW40(), heartRate_Process(), HEXIWEAR_SendVersionReq(), pedometer_GetCalories(), power_AlertKW40(), sensor_InitAcc(), and watch_SendGetLinkStateReq().
MSG_QUEUE_DECLARE (hostInterface_txQueue , gHostInterface_msgNum , sizeof(hostInterface_packet_t))
message queues