HEXIWEAR MK64 Firmware Reference Manual: apps/pedometer/inc/pedometer_driver.h File Reference
pedometer_driver.h File Reference
this file contains pedometer app functionality
#include "pedometer_info.h"
#include "pedometer_defs.h"
#include <string.h>
#include "fsl_os_abstraction.h"
#include "host_mcu_interface.h"
Functions
pedometer_status_t pedometer_Reset ()
bool debounce_count (bool dbcntm, bool condition, debounce_count_t *count, debounce_count_t threshold)
void pedometer_Init ()
void pedometer_CreateTask ()
void pedometer_Deinit ()
pedo_process_status_t pedometer_QueueMsgPut (hostInterface_packet_t *packet)
uint16_t pedometer_GetStepCounter ()
void pedometer_Resume ()
void pedometer_Pause ()
Detailed Description
this file contains pedometer app functionality
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file pedometer_driver.h.
Function Documentation
bool debounce_count (bool dbcntm, bool condition, debounce_count_t * count, debounce_count_t threshold)
debounce counter
Parameters
dbcntm [description]
condition [description]
count [description]
threshold [description]
Returns
[description]
debounce the counter
Definition at line 139 of file pedometer_driver.c.
Referenced by pedometer_GetCalories().
void pedometer_CreateTask ()
[pedometer_CreateTask description]
Definition at line 221 of file pedometer_driver.c.
References kStatus_OSA_Success, OSA_TaskCreate(), and pedometer_Pause().
Referenced by gui_pedometer_CreateTasks().
void pedometer_Deinit ()
[pedometer_Deinit description]
deinitialize pedometer objects, free used memory and unregister from acc sensor
Definition at line 246 of file pedometer_driver.c.
References gui_sensorTag_TurnON(), OLED_DestroyDynamicArea(), OSA_MsgQDestroy(), OSA_TaskDestroy(), sensor_GetPacketTargets(), and sensor_SetPacketTargets().
Referenced by gui_pedometer_DestroyTasks().
uint16_t pedometer_GetStepCounter ()
get steps
Definition at line 289 of file pedometer_driver.c.
void pedometer_Init ()
[pedometer_Init description]
initialize pedometer objects, reset relevant variables and register to acc sensor
Definition at line 196 of file pedometer_driver.c.
References gui_sensorTag_IsActive(), gui_sensorTag_TurnOFF(), GuiDriver_RegisterMinPollDelay(), OSA_MsgQCreate(), pedometer_Reset(), and sensor_RegisterPacketDelay().
Referenced by gui_pedometer_Init().
void pedometer_Pause ()
pause the pedometer step detection process
pause the pedometer task
Definition at line 280 of file pedometer_driver.c.
References sensor_GetPacketTargets(), and sensor_SetPacketTargets().
Referenced by gui_pedometer_QueueMsgPut(), and pedometer_CreateTask().
pedo_process_status_t pedometer_QueueMsgPut (hostInterface_packet_t * packet)
[fitness_pedometer_QueueMsgPut description]
Parameters
packet [description]
Returns
[description]
put acc data into the queue for pedometer app
Parameters
packet data to put
Returns
status flag
Definition at line 174 of file pedometer_driver.c.
References OSA_WAIT_FOREVER.
Referenced by sensor_InitAcc().
pedometer_status_t pedometer_Reset ()
reset the handle values to their default
public API reset the handle values to their default values
Definition at line 130 of file pedometer_driver.c.
Referenced by pedometer_Init().
void pedometer_Resume ()
resume the pedometer step detection process
resume the pedometer task
Definition at line 271 of file pedometer_driver.c.
References sensor_GetPacketTargets(), and sensor_SetPacketTargets().
Referenced by gui_pedometer_QueueMsgPut().