HEXIWEAR MK64 Firmware Reference Manual: sensors/inc/sensor_driver.h File Reference
sensor_driver.h File Reference
sensor wrapper routines for manipulating sensor's data-packets, formatting and sending it to different targets (KW40, OLED...)
#include "fsl_os_abstraction.h"
#include "HEXIWEAR.h"
#include "FXAS_driver.h"
#include "FXOS_driver.h"
#include "HTU_driver.h"
#include "MPL_driver.h"
#include "TSL_driver.h"
#include "MAXIM_driver.h"
Functions
osa_status_t sensor_Init ()
void sensor_ResetPacketcounter (packet_t packetToUpdate)
void sensor_SetPacketTargets (packet_t packetToUpdate, packet_pushTarget_t newPushTarget, bool shouldToggleTask)
packet_pushTarget_t sensor_GetPacketTargets (packet_t sensorToUpdate)
void sensor_RegisterPacketDelay (packet_t packetToUpdate, uint32_t delay_ms)
void sensor_SetMinimumDelay (uint32_t delay)
void sensor_SaveTargetsForKW40 ()
void sensor_RestoreTargetsForKW40 ()
void sensor_ResetTargetsForKW40 ()
bool sensor_CheckForKW40Targets ()
void sensor_InitAcc ()
void sensor_ResetLEDIndicator ()
void sensor_ClearLEDIndicator ()
void sensor_StopWait ()
void sensor_Suspend ()
void sensor_Resume ()
Detailed Description
sensor wrapper routines for manipulating sensor's data-packets, formatting and sending it to different targets (KW40, OLED...)
Version
1.0.1
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP Semiconductor, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
support: http://www.mikroe.com/forum and https://community.freescale.com
Project HEXIWEAR, 2015
Definition in file sensor_driver.h.
Function Documentation
bool sensor_CheckForKW40Targets ()
check if there are sensor packets with KW40 as its target
[sensor_CheckTargetsForKW40() description]
Definition at line 2125 of file sensor_driver.c.
void sensor_ClearLEDIndicator ()
turn LED off
[sensor_ClearLEDIndicator description]
Definition at line 1990 of file sensor_driver.c.
packet_pushTarget_t sensor_GetPacketTargets (packet_t oldPushTargets)
retrieve particular sensor's targets
Parameters
sensorToUpdate packet which targets are to be returned
Returns
desired packet targets
[sensor_SetPushTargets description]
Parameters
oldPushTargets [description]
Returns
[description]
Definition at line 355 of file sensor_driver.c.
Referenced by gui_sensorTag_IsActive(), GuiDriver_RegisterForSensors(), GuiDriver_UnregisterFromSensors(), heartRate_Pause(), heartRate_Resume(), HEXIWEAR_startup(), pedometer_Deinit(), pedometer_Pause(), pedometer_Resume(), and power_SensorManagement().
osa_status_t sensor_Init ()
create the sensor task
Definition at line 363 of file sensor_driver.c.
References BATTERY_ADC_ChnConfig, flashlight_isFlashlightOn(), FSL_BATTERY_ADC, FXAS_ReadRawData(), FXAS_SoftReset(), FXOS_CheckForTap(), FXOS_ReadRawData(), FXOS_ReadStatus(), FXOS_RecoverI2C(), FXOS_SoftReset(), gui_sensorTag_IsActive(), HTU_GetHum(), HTU_GetTemp(), HTU_RecoverI2C(), HTU_SoftReset(), kStatus_OSA_Error, kStatus_OSA_Success, MAXIM_ReadRawData(), motionData, MPL_ReadRawData(), MPL_SoftReset(), OSA_MutexCreate(), OSA_MutexLock(), OSA_MutexUnlock(), OSA_TaskCreate(), OSA_TimeDelay(), OSA_WAIT_FOREVER, packetType_accel, packetType_ambiLight, packetType_batteryLevel, packetType_gyro, packetType_heartRate, packetType_humidity, packetType_magnet, packetType_pressure, packetType_temperature, POWER_CURRENT_MODE_SLEEP_SENSOR_TAG, POWER_CURRENT_MODE_SLEEP_SHALLOW, POWER_CURRENT_MODE_SLEEP_TOTAL, power_GetCurrentMode(), power_GotoSleep(), power_IsBatteryLow(), power_SensorManagement(), power_SetSleepSource(), SENSOR_GET_DATA_PRIO, SENSOR_GET_DATA_STACK_SIZE, sensor_Resume(), SENSOR_RETRY_NUM, sensor_Suspend(), START_PACKET, TSL_CalculateLux(), TSL_FormatLux(), TSL_ReadRawData(), and watch_CurrentLinkStateGet().
Referenced by HEXIWEAR_startup().
void sensor_InitAcc ()
initiate the accelerometer
Definition at line 1480 of file sensor_driver.c.
References FXAS_GotoStandby(), FXAS_Init(), FXAS_SetActive(), FXOS_Init(), GPIO_DRV_TogglePinOutput(), GuiDriver_QueueMsgPut(), heartRate_Process(), HostInterface_TxQueueMsgPut(), HTU_Init(), MAXIM_Disable(), MAXIM_Enable(), MAXIM_Init(), MAXIM_InstallCallback(), MPL_GotoStandby(), MPL_Init(), MPL_SetActive(), OSA_TimeDelay(), packetType_batteryLevel, pedometer_QueueMsgPut(), POWER_CURRENT_MODE_SLEEP_SENSOR_TAG, power_GetCurrentMode(), power_IsActive(), power_SetBatteryLow(), power_UnsetBatteryLow(), timer_SetPeriod(), and TSL_Init().
Referenced by HEXIWEAR_startup().
void sensor_RegisterPacketDelay (packet_t packetToUpdate, uint32_t delay_ms)
assign polling delay in [ms] to the particular packet
Parameters
packetToUpdate packet which polling delay is to be updated
delay_ms delay in [ms]
assign delay in [ms] to the particular packet
Definition at line 1883 of file sensor_driver.c.
References kStatus_OSA_Success, OSA_SemaWait(), OSA_WAIT_FOREVER, and sensor_ResetPacketcounter().
Referenced by gui_sensorTag_IsActive(), GuiDriver_RegisterForSensors(), heartRate_Init(), and pedometer_Init().
void sensor_ResetLEDIndicator ()
reset LED counter
[sensor_ResetLedIndicator description]
Definition at line 1982 of file sensor_driver.c.
void sensor_ResetPacketcounter (packet_t packetToUpdate)
reset the packet counter, to trigger reading during the next sensor loop
Parameters
packetToUpdate packet to reset
Public API reset the packet counter, to trigger reading during the next sensor loop
Parameters
packetToUpdate packet to reset
Definition at line 321 of file sensor_driver.c.
Referenced by sensor_RegisterPacketDelay(), sensor_SetPacketTargets(), and watch_SetNotification().
void sensor_ResetTargetsForKW40 ()
flush the backup KW40 list
[sensor_SaveCurrentTargetsForKW40 description]
Definition at line 2141 of file sensor_driver.c.
Referenced by gui_sensorTag_IsActive().
void sensor_RestoreTargetsForKW40 ()
restore all the sensors which have KW40 as its targets
[sensor_RestoreCurrentTargetsForKW40 description]
Definition at line 2106 of file sensor_driver.c.
Referenced by watch_LinkStateUpdate().
void sensor_Resume ()
resume the sensor task
Definition at line 2165 of file sensor_driver.c.
References timer_Start().
Referenced by sensor_Init().
void sensor_SaveTargetsForKW40 ()
backup all the sensors which have KW40 as its targets
[sensor_SaveCurrentTargetsForKW40 description]
no need to pause the sensor task, since it will check for it itself at the beginning of the loop just check for potentially new counter values
Definition at line 2082 of file sensor_driver.c.
Referenced by watch_LinkStateUpdate().
void sensor_SetMinimumDelay (uint32_t delay)
set minimum delay for the sensor loop
Parameters
delay in miliseconds
set minimum delay for the sensor loop
Definition at line 1871 of file sensor_driver.c.
References SENSOR_DEFAULT_MINIMUM_DELAY_MS.
Referenced by gui_sensorTag_IsActive(), and GuiDriver_RegisterMinPollDelay().
void sensor_SetPacketTargets (packet_t packetToUpdate, packet_pushTarget_t newPushTarget, bool shouldToggleTask)
set targets for the particular sensor packet
Parameters
packetToUpdate packet which targets are to be updated
newPushTarget new targets
shouldToggleTask flag to check if sensor task should be triggered, if paused before
Definition at line 332 of file sensor_driver.c.
References sensor_ResetPacketcounter().
Referenced by gui_sensorTag_IsActive(), GuiDriver_RegisterForSensors(), GuiDriver_UnregisterFromSensors(), heartRate_Pause(), heartRate_Resume(), HEXIWEAR_startup(), pedometer_Deinit(), pedometer_Pause(), and pedometer_Resume().
void sensor_StopWait ()
stop waiting for semaphore
stop with waiting
Definition at line 1954 of file sensor_driver.c.
References OSA_SemaPost().
Referenced by timer_Stop().
void sensor_Suspend ()
suspend the sensor task
Definition at line 2152 of file sensor_driver.c.
References timer_Stop().
Referenced by sensor_Init().