HEXIWEAR MK64 Firmware Reference Manual: gui/screens/1. watch/inc/watch_private.h File Reference
watch_private.h File Reference
this file contains watch screen related resources and prototypes
#include "gui_driver.h"
Functions
void watch_Init (void *param)
void watch_CreateTasks (void *param)
void watch_DestroyTasks (void *param)
Variables
guiImage_t watch_imgBattery
guiImage_t watch_imgSms
guiImage_t watch_imgMail
guiImage_t watch_imgCall
guiImage_t watch_imgBluetoothLogo
guiImage_t watch_imgTempUnit
guiLabel_t watch_labelTime
guiLabel_t watch_labelDate
guiLabel_t watch_labelTemp
guiLabel_t watch_labelEnter
Detailed Description
this file contains watch screen related resources and prototypes
Version
1.00 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of NXP, nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
visit: http://www.mikroe.com and http://www.nxp.com
get support at: http://www.mikroe.com/forum and https://community.nxp.com
Project HEXIWEAR, 2015
Definition in file watch_private.h.
Function Documentation
void watch_CreateTasks (void * param)
create tasks in the watch screen
Parameters
param optional parameter
Definition at line 324 of file watch_driver.c.
References kStatus_OSA_Success, OSA_TaskCreate(), and watch_timeUpdate_handler.
void watch_DestroyTasks (void * param)
destroy current running tasks in the watch screen
Parameters
param optional parameter
Definition at line 383 of file watch_driver.c.
References GuiDriver_LabelDestroy(), GuiDriver_UnregisterFromSensors(), kStatus_OSA_Success, OLED_DestroyDynamicArea(), OSA_EventSet(), OSA_TaskDestroy(), OSA_WAIT_FOREVER, RTC_WatchUpdateEventWait(), watch_labelDate, watch_labelTemp, watch_labelTime, and watch_timeUpdate_handler.
void watch_Init (void * param)
initialize the watch screen
Parameters
param optional parameter
check for the notifications
Definition at line 221 of file watch_driver.c.
References gui_sensorTag_IsActive(), GuiDriver_ImageAddToScr(), GuiDriver_LabelAddToScr(), GuiDriver_LabelCreate(), GuiDriver_LabelSetCaption(), GuiDriver_RegisterForSensors(), GuiDriver_RegisterMinPollDelay(), Notification_GetUnreadCounter(), RTC_GetCurrentTime(), watch_imgBattery, watch_imgBluetoothLogo, watch_imgCall, watch_imgMail, watch_imgSms, watch_imgTempUnit, watch_labelDate, watch_labelEnter, watch_labelTemp, and watch_labelTime.
Variable Documentation
guiImage_t watch_imgBattery
definitions of screen objects battery image GUI object
Definition at line 65 of file watch_objects.c.
Referenced by watch_Init(), and watch_SetNotification().
guiImage_t watch_imgBluetoothLogo
bluetooth link GUI object
Definition at line 114 of file watch_objects.c.
Referenced by watch_Init(), and watch_SetNotification().
guiImage_t watch_imgCall
notification call image GUI object
Definition at line 102 of file watch_objects.c.
Referenced by watch_Init(), and watch_SetNotification().
guiImage_t watch_imgMail
notification mail image GUI object
Definition at line 90 of file watch_objects.c.
Referenced by watch_Init(), and watch_SetNotification().
guiImage_t watch_imgSms
notification sms image GUI object
Definition at line 78 of file watch_objects.c.
Referenced by watch_Init(), and watch_SetNotification().
guiImage_t watch_imgTempUnit
temperature unit GUI object
Definition at line 126 of file watch_objects.c.
Referenced by watch_Init().
guiLabel_t watch_labelDate
date GUI object
Definition at line 159 of file watch_objects.c.
Referenced by watch_DestroyTasks(), watch_Init(), and watch_SetNotification().
guiLabel_t watch_labelEnter
Menu label GUI object
Definition at line 201 of file watch_objects.c.
Referenced by watch_Init().
guiLabel_t watch_labelTemp
temperature GUI object
Definition at line 180 of file watch_objects.c.
Referenced by watch_DestroyTasks(), watch_Init(), and watch_SetNotification().
guiLabel_t watch_labelTime
time GUI object
Definition at line 138 of file watch_objects.c.
Referenced by watch_DestroyTasks(), watch_Init(), and watch_SetNotification().