################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
SECONDARY_SIZE := 
C++_DEPS := 
OBJS := 
C_DEPS := 
ASM_DEPS := 
CC_DEPS := 
SECONDARY_FLASH := 
CPP_DEPS := 
CXX_DEPS := 
C_UPPER_DEPS := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Static_Code/System \
Sources/sensors/src \
Sources/menu/src \
Sources \
Sources/intf/src \
Sources/exceptions/src \
Sources/drivers/power/src \
Sources/drivers/TSL/src \
Sources/drivers/SPI/src \
Sources/drivers/OLED/src \
Sources/drivers/MPL/src \
Sources/drivers/MAXIM/src \
Sources/drivers/I2C/src \
Sources/drivers/HTU/src \
Sources/drivers/FXOS/src \
Sources/drivers/FXAS/src \
Sources/drivers/FLASH/src \
Sources/cmsis_dsp/src/TransformFunctions \
Sources/cmsis_dsp/src/SupportFunctions \
Sources/cmsis_dsp/src/StatisticsFunctions \
Sources/cmsis_dsp/src/MatrixFunctions \
Sources/cmsis_dsp/src/FilteringFunctions \
Sources/cmsis_dsp/src/FastMathFunctions \
Sources/cmsis_dsp/src/ControllerFunctions \
Sources/cmsis_dsp/src/ComplexMathFunctions \
Sources/cmsis_dsp/src/CommonTables \
Sources/cmsis_dsp/src/BasicMathFunctions \
Sources/apps/watch/src \
Sources/apps/sensorTag/src \
Sources/apps/common/src \
Sources/HEXIWEAR/src \
SDK/rtos/FreeRTOS/src \
SDK/rtos/FreeRTOS/port/gcc \
SDK/platform/utilities/src \
SDK/platform/system/src/power \
SDK/platform/system/src/interrupt \
SDK/platform/system/src/clock \
SDK/platform/system/src/clock/MK64F12 \
SDK/platform/osa/src \
SDK/platform/hal/src/uart \
SDK/platform/hal/src/smc \
SDK/platform/hal/src/sim/MK64F12 \
SDK/platform/hal/src/rtc \
SDK/platform/hal/src/rcm \
SDK/platform/hal/src/port \
SDK/platform/hal/src/osc \
SDK/platform/hal/src/mcg \
SDK/platform/hal/src/llwu \
SDK/platform/hal/src/i2c \
SDK/platform/hal/src/gpio \
SDK/platform/hal/src/edma \
SDK/platform/hal/src/dspi \
SDK/platform/hal/src/dmamux \
SDK/platform/hal/src/adc16 \
SDK/platform/drivers/src/uart \
SDK/platform/drivers/src/rtc \
SDK/platform/drivers/src/i2c \
SDK/platform/drivers/src/gpio \
SDK/platform/drivers/src/edma \
SDK/platform/drivers/src/dspi \
SDK/platform/drivers/src/adc16 \
SDK/platform/devices \
SDK/platform/devices/MK64F12/startup \
SDK/platform/devices/MK64F12/startup/gcc \
Generated_Code \

