/* ###################################################################
 *      This component module is generated by Processor Expert. Do not modify it.
 *      Filename    : sensor_timer.h
 *      Project     : HEXIWEAR_RTOS
 *      Processor   : MK64FN1M0VDC12
 *      Component   : fsl_lptmr
 *      Version     : Component 1.2.0, Driver 01.00, CPU db: 3.00.000
 *      Repository  : KSDK 1.2.0
 *      Compiler    : GNU C Compiler
 *      Date/Time   : 2016-03-04, 12:30, # CodeGen: 0
 *      Contents    :
 *          LPTMR_DRV_Init                 - lptmr_status_t LPTMR_DRV_Init(uint32_t instance,lptmr_state_t *...
 *          LPTMR_DRV_Deinit               - lptmr_status_t LPTMR_DRV_Deinit(uint32_t instance);
 *          LPTMR_DRV_Start                - lptmr_status_t LPTMR_DRV_Start(uint32_t instance);
 *          LPTMR_DRV_Stop                 - lptmr_status_t LPTMR_DRV_Stop(uint32_t instance);
 *          LPTMR_DRV_SetTimerPeriodUs     - lptmr_status_t LPTMR_DRV_SetTimerPeriodUs(uint32_t instance,uint32_t us);
 *          LPTMR_DRV_GetCurrentTimeUs     - uint32_t LPTMR_DRV_GetCurrentTimeUs(uint32_t instance);
 *          LPTMR_DRV_SetPulsePeriodCount  - lptmr_status_t LPTMR_DRV_SetPulsePeriodCount(uint32_t instance,uint32_t...
 *          LPTMR_DRV_GetCurrentPulseCount - uint32_t LPTMR_DRV_GetCurrentPulseCount(uint32_t instance);
 *          LPTMR_DRV_InstallCallback      - lptmr_status_t LPTMR_DRV_InstallCallback(uint32_t instance,lptmr_callback_t...
 *          LPTMR_DRV_IRQHandler           - void LPTMR_DRV_IRQHandler(uint32_t instance);
 *
 *      Copyright : 1997 - 2015 NXP Semiconductor, Inc.
 *      All Rights Reserved.
 *
 *      Redistribution and use in source and binary forms, with or without modification,
 *      are permitted provided that the following conditions are met:
 *
 *      o Redistributions of source code must retain the above copyright notice, this list
 *        of conditions and the following disclaimer.
 *
 *      o Redistributions in binary form must reproduce the above copyright notice, this
 *        list of conditions and the following disclaimer in the documentation and/or
 *        other materials provided with the distribution.
 *
 *      o Neither the name of NXP Semiconductor, Inc. nor the names of its
 *        contributors may be used to endorse or promote products derived from this
 *        software without specific prior written permission.
 *
 *      THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 *      ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 *      WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 *      DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 *      ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 *      (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *      LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 *      ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *      (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 *      SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *      http: www.nxp.com
 *      mail: support@nxp.com
 *  ###################################################################*/
/*!
 *  @file sensor_timer.h
 *  @version 01.00
 */
/*!
 *   @addtogroup sensor_timer_module sensor_timer module documentation
 *   @{
 */
#ifndef __sensor_timer_H
#define __sensor_timer_H
 /** MODULE sensor_timer. */
 /** Include inherited beans */
#include "CLK_manager.h"
#include "Cpu.h"

/*! @brief Device instance number */
#define FSL_SENSOR_TIMER 0

/*! @brief LPTMR configuration declaration */
extern const lptmr_user_config_t sensor_timer_cfg;

void LPTMR0_IRQHandler(void);

/*! @brief Driver state structure which holds driver runtime data */
extern lptmr_state_t sensor_timer_State;



 /** END sensor_timer. */

#endif
 /** ifndef __sensor_timer_H */
/*!
 *  @}
 */
/*
 *  ###################################################################
 *
 *      This file was created by Processor Expert 10.5 [05.21]
 *      for the NXP Kinetis series of microcontrollers.
 *
 *  ###################################################################
 */
