<?xml version="1.0" encoding="UTF-8"?>

<workspace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="workingsets.xsd">
  <projects>
    <project>
      <name>HEXIWEAR_Nfc_Click_MK64FN1M0VDC12</name>
      <path></path>
      <open>true</open>
      <activeconfig>debug</activeconfig>
      <buildreferences config="debug">false</buildreferences>
      <buildreferences config="release">false</buildreferences>
    </project>
    <project>
      <name>ksdk_platform_lib_MK64FN1M0VDC12</name>
      <path>..\lib\ksdk_platform_lib\kds\K64F12</path>
      <open>true</open>
      <activeconfig>debug</activeconfig>
      <buildreferences config="debug">false</buildreferences>
      <buildreferences config="release">false</buildreferences>
    </project>
  </projects>
  <workingsets>
    <workingSet editPageId="org.eclipse.cdt.ui.CElementWorkingSetPage" id="1474015647753_1" label="HEXIWEAR_Nfc_Click" name="HEXIWEAR_Nfc_Click"> 
      <item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/HEXIWEAR_Nfc_Click_MK64FN1M0VDC12" type="4"/>  
      <item factoryID="org.eclipse.cdt.ui.PersistableCElementFactory" path="/ksdk_platform_lib_MK64FN1M0VDC12" type="4"/> 
    </workingSet>
  </workingsets>
  <cdtconfigurations>
    <workingSet name="HEXIWEAR_Nfc_Click"> 
      <config name="debug"> 
        <project config="ilg.gnuarmeclipse.managedbuild.cross.config.elf.debug.1792027861" name="HEXIWEAR_Nfc_Click_MK64FN1M0VDC12" configName="debug"/>  
        <project config="ilg.gnuarmeclipse.managedbuild.cross.config.lib.debug.660039418" name="ksdk_platform_lib_MK64FN1M0VDC12" configName="debug"/> 
      </config>  
      <config name="release"> 
        <project config="ilg.gnuarmeclipse.managedbuild.cross.config.elf.release.1939339834" name="HEXIWEAR_Nfc_Click_MK64FN1M0VDC12" configName="release"/>  
        <project config="ilg.gnuarmeclipse.managedbuild.cross.config.lib.release.355096884" name="ksdk_platform_lib_MK64FN1M0VDC12" configName="release"/> 
      </config> 
    </workingSet>
  </cdtconfigurations>
</workspace>
